In [2]:
import pandas as pd

# 读取csv文件
chexpert_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-chexpert.csv')
metadata_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-metadata.csv')

# 打印head查看数据结构
chexpert_head = chexpert_df.head()
metadata_head = metadata_df.head()

chexpert_head, metadata_head

(   subject_id  study_id  Atelectasis  Cardiomegaly  Consolidation  Edema  \
 0    10000032  50414267          NaN           NaN            NaN    NaN
 1    10000032  53189527          NaN           NaN            NaN    NaN
 2    10000032  53911762          NaN           NaN            NaN    NaN
 3    10000032  56699142          NaN           NaN            NaN    NaN
 4    10000764  57375967          NaN           NaN            1.0    NaN

    Enlarged Cardiomediastinum  Fracture  Lung Lesion  Lung Opacity  \
 0                         NaN       NaN          NaN           NaN
 1                         NaN       NaN          NaN           NaN
 2                         NaN       NaN          NaN           NaN
 3                         NaN       NaN          NaN           NaN
 4                         NaN       NaN          NaN           NaN

    No Finding  Pleural Effusion  Pleural Other  Pneumonia  Pneumothorax  \
 0         1.0               NaN            NaN        NaN           NaN
 1         1.0               NaN            NaN        NaN           NaN
 2         1.0               NaN            NaN        NaN           NaN
 3         1.0               NaN            NaN        NaN           NaN
 4         NaN               NaN            NaN       -1.0           NaN

    Support Devices
 0              NaN
 1              NaN
 2              NaN
 3              NaN
 4              NaN  ,
                                        dicom_id  subject_id  study_id  \
 0  02aa804e-bde0afdd-112c0b34-7bc16630-4e384014    10000032  50414267
 1  174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962    10000032  50414267
 2  2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab    10000032  53189527
 3  e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c    10000032  53189527
 4  68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714    10000032  53911762

   PerformedProcedureStepDescription ViewPosition  Rows  Columns  StudyDate  \
 0                CHEST (PA AND LAT)           PA  3056     2544   21800506
 1                CHEST (PA AND LAT)      LATERAL  3056     2544   21800506
 2                CHEST (PA AND LAT)           PA  3056     2544   21800626
 3                CHEST (PA AND LAT)      LATERAL  3056     2544   21800626
 4               CHEST (PORTABLE AP)           AP  2705     2539   21800723

     StudyTime ProcedureCodeSequence_CodeMeaning ViewCodeSequence_CodeMeaning  \
 0  213014.531                CHEST (PA AND LAT)             postero-anterior
 1  213014.531                CHEST (PA AND LAT)                      lateral
 2  165500.312                CHEST (PA AND LAT)             postero-anterior
 3  165500.312                CHEST (PA AND LAT)                      lateral
 4   80556.875               CHEST (PORTABLE AP)             antero-posterior

   PatientOrientationCodeSequence_CodeMeaning
 0                                      Erect
 1                                      Erect
 2                                      Erect
 3                                      Erect
 4                                        NaN  )

In [3]:
# 读取第三个表格（mscxr数据集）
mscxr_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_Local_Alignment_v1.0.0.csv')

# 打印前五行数据来查看结构
mscxr_head = mscxr_df.head()

# 打印列名
mscxr_columns = mscxr_df.columns.tolist()

mscxr_head, mscxr_columns

(                                       dicom_id category_name  \
 0  675d792f-a3521e48-5eec8573-1e81d644-e60c34f8     Pneumonia
 1  675d792f-a3521e48-5eec8573-1e81d644-e60c34f8     Pneumonia
 2  5318d353-daae9c3d-2ee8648e-32b65198-aeff801e     Pneumonia
 3  5318d353-daae9c3d-2ee8648e-32b65198-aeff801e     Pneumonia
 4  4decce85-c6ede74e-7a8bc81c-e81edee9-5ec17116  Pneumothorax

                                     label_text  \
 0                          Bibasilar opacities
 1                          Bibasilar opacities
 2  Bilateral multifocal areas of consolidation
 3  Bilateral multifocal areas of consolidation
 4               Large right-sided pneumothorax

                                                 path     x     y    w     h  \
 0  files/p10/p10233088/s54276838/675d792f-a3521e4...   196  1136  532   315
 1  files/p10/p10233088/s54276838/675d792f-a3521e4...  1009  1134  491   350
 2  files/p10/p10123147/s50230934/5318d353-daae9c3...  1510  1268  755   796
 3  files/p10/p10123147/s50230934/5318d353-daae9c3...   454   690  637   670
 4  files/p10/p10500801/s58577720/4decce85-c6ede74...   265    90  880  2198

    image_width  image_height
 0         1767          2021
 1         1767          2021
 2         2539          3050
 3         2539          3050
 4         3056          2544  ,
 ['dicom_id',
  'category_name',
  'label_text',
  'path',
  'x',
  'y',
  'w',
  'h',
  'image_width',
  'image_height'])

In [7]:
import pandas as pd

# 读取第三个表格（mscxr数据集）
mscxr_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_Local_Alignment_v1.0.0.csv')

# 读取前两个表格
chexpert_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-chexpert.csv')
metadata_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-metadata.csv')

# 1. 从 metadata_df 获取 subject_id, study_id, ViewPosition 对应 dicom_id
metadata_info = metadata_df[['dicom_id', 'subject_id', 'study_id', 'ViewPosition']]

# 2. 合并 ms_cxr 数据集和 metadata 信息
mscxr_with_metadata = pd.merge(mscxr_df, metadata_info, how='left', on='dicom_id')

# 3. 从 chexpert_df 获取疾病信息，使用 subject_id 和 study_id 来查找
# 先确保 'subject_id' 和 'study_id' 在 chexpert_df 中存在
chexpert_relevant = chexpert_df[['subject_id', 'study_id'] + chexpert_df.columns.tolist()[2:]]

# 4. 合并数据：将 mscxr_with_metadata 和 chexpert_relevant 进行合并
final_df = pd.merge(mscxr_with_metadata, chexpert_relevant, how='left', on=['subject_id', 'study_id'])

# 打印最终合并表格的前五行
final_df.iloc[1, 3], final_df.columns.tolist()

('files/p10/p10233088/s54276838/675d792f-a3521e48-5eec8573-1e81d644-e60c34f8.jpg',
 ['dicom_id',
  'category_name',
  'label_text',
  'path',
  'x',
  'y',
  'w',
  'h',
  'image_width',
  'image_height',
  'subject_id',
  'study_id',
  'ViewPosition',
  'Atelectasis',
  'Cardiomegaly',
  'Consolidation',
  'Edema',
  'Enlarged Cardiomediastinum',
  'Fracture',
  'Lung Lesion',
  'Lung Opacity',
  'No Finding',
  'Pleural Effusion',
  'Pleural Other',
  'Pneumonia',
  'Pneumothorax',
  'Support Devices'])

In [6]:
# 保存最终合并的表格
final_df.to_csv('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_combined.csv', index=False)

# 统计 ViewPosition 每个值的数量
view_position_counts = final_df['ViewPosition'].value_counts()

view_position_counts

ViewPosition
AP    1125
PA     323
Name: count, dtype: int64

In [12]:
import os
import shutil
import pandas as pd
from multiprocessing import Pool, cpu_count

# 定义拷贝文件的函数
def copy_file(row):
    prefix = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/"
    target_base_dir = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/'

    source_path = prefix + row['path']
    dicom_id = row['dicom_id']

    target_dir = os.path.join(target_base_dir, dicom_id)
    
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
    
    target_path = os.path.join(target_dir, 'original.jpg')

    if os.path.exists(source_path):
        shutil.copy(source_path, target_path)
    else:
        print(f"文件不存在: {source_path}")

# 读取最终合并的表格
final_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_combined.csv')

# 使用 CPU 核心数来决定进程数
num_processes = cpu_count()

# 创建进程池并执行文件拷贝任务
with Pool(processes=num_processes) as pool:
    pool.map(copy_file, [row for index, row in final_df.iterrows()])

print("文件拷贝完成！")

文件拷贝完成！

In [15]:
import pandas as pd

# 读取数据
metadata_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-metadata.csv')
mscxr_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_Local_Alignment_v1.0.0.csv')
chexpert_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-chexpert.csv')

# 1. 获取metadata_df中的dicom_id列
metadata_dicom_ids = set(metadata_df['dicom_id'])

# 2. 获取mscxr_df中的dicom_id列
mscxr_dicom_ids = set(mscxr_df['dicom_id'])

# 3. 得到剩余的dicom_id（即在metadata中但不在mscxr中）
remaining_dicom_ids = metadata_dicom_ids - mscxr_dicom_ids

# 4. 从metadata_df中筛选出这些剩余的dicom_id，并且ViewPosition为"AP"或"PA"
filtered_metadata = metadata_df[metadata_df['dicom_id'].isin(remaining_dicom_ids)]
filtered_metadata = filtered_metadata[filtered_metadata['ViewPosition'].isin(['AP', 'PA'])]

# 5. 从chexpert_df中提取与filtered_metadata中相同subject_id和study_id的记录
merged_data = pd.merge(filtered_metadata, chexpert_df, how='left', on=['subject_id', 'study_id'])

# 6. 保存结果为CXV文件（如果你需要保存为CSV格式，可以修改扩展名为.csv）
merged_data.to_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-remained-data-ap-pa-without-ms-cxr-part.csv', index=False)

print("表格已保存！")

表格已保存！

In [17]:
import pandas as pd

# 读取数据
remained_data = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-remained-data-ap-pa-without-ms-cxr-part.csv')
mscxr_data = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_Local_Alignment_v1.0.0.csv')

# 提取 dicom_id 列
remained_dicom_ids = set(remained_data['dicom_id'])
mscxr_dicom_ids = set(mscxr_data['dicom_id'])

# 检查两个 dicom_id 列是否有交集
intersection = remained_dicom_ids.intersection(mscxr_dicom_ids)

# 打印交集的大小，如果没有交集，则返回空集合
if len(intersection) == 0:
    print("没有交集，测试通过！")
else:
    print(f"有交集，交集大小: {len(intersection)}")
    print("交集的 dicom_id:", intersection)

没有交集，测试通过！

In [19]:
# 读取数据
remained_data = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-remained-data-ap-pa-without-ms-cxr-part.csv')

# 统计 dicom_id 的数量
total_dicom_count = remained_data['dicom_id'].nunique()

total_dicom_count

242287

In [21]:
import pandas as pd
import numpy as np

# 读取数据
remained_data = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-remained-data-ap-pa-without-ms-cxr-part.csv')

# 设置随机种子，以确保结果可复现
np.random.seed(42)

# 计算总数据量
total_data_count = remained_data.shape[0]
print(f"总共有 {total_data_count} 张数据")

# 1. 抽取5个不重合的测试集（5-fold交叉验证）
test_data_folds = []
remaining_data = remained_data.copy()

# 每次从剩余数据中随机抽取20%作为测试集
for fold in range(5):
    test_size = total_data_count // 5
    test_data = remaining_data.sample(n=test_size, random_state=42 + fold)  # 不同fold使用不同的随机种子
    test_data_folds.append(test_data)
    remaining_data = remaining_data.drop(test_data.index)  # 从剩余数据中删除已抽取的测试集

# 保存每个fold的测试集
for fold in range(5):
    test_data_folds[fold].to_csv(f'/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold{fold}_test.csv', index=False)
    print(f"已保存 fold{fold}_test.csv, 包含 {test_data_folds[fold].shape[0]} 张数据")

# 2. 对于每个 fold，从剩余的训练集中抽取不同大小的子集
for fold in range(5):
    # 剩余的训练数据（去除当前 fold 的测试集）
    train_data_remaining = remained_data.drop(test_data_folds[fold].index)

    # 定义不同大小的子集
    subset_sizes = [1000, 5000, 10000, 20000, 50000, 100000]
    start_index = 0

    # 生成子集并保存
    for size in subset_sizes:
        # 从剩余数据中随机抽取指定数量的数据
        subset = train_data_remaining.sample(n=size, random_state=42 + fold + size)  # 每次使用不同的随机种子
        # 将之前的子集合并
        if start_index == 0:
            final_subset = subset
        else:
            final_subset = pd.concat([final_subset, subset], axis=0)
        
        # 更新剩余数据
        train_data_remaining = train_data_remaining.drop(subset.index)
        
        # 保存当前子集
        final_subset.to_csv(f'/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold{fold}_train_subset_{size}.csv', index=False)
        
        print(f"已保存 fold{fold}_train_subset_{size}.csv, 包含 {final_subset.shape[0]} 张数据")

print("所有折的子集已保存完成！")

总共有 242287 张数据
已保存 fold0_test.csv, 包含 48457 张数据
已保存 fold1_test.csv, 包含 48457 张数据
已保存 fold2_test.csv, 包含 48457 张数据
已保存 fold3_test.csv, 包含 48457 张数据
已保存 fold4_test.csv, 包含 48457 张数据
已保存 fold0_train_subset_1000.csv, 包含 1000 张数据
已保存 fold0_train_subset_5000.csv, 包含 5000 张数据
已保存 fold0_train_subset_10000.csv, 包含 10000 张数据
已保存 fold0_train_subset_20000.csv, 包含 20000 张数据
已保存 fold0_train_subset_50000.csv, 包含 50000 张数据
已保存 fold0_train_subset_100000.csv, 包含 100000 张数据
已保存 fold1_train_subset_1000.csv, 包含 1000 张数据
已保存 fold1_train_subset_5000.csv, 包含 5000 张数据
已保存 fold1_train_subset_10000.csv, 包含 10000 张数据
已保存 fold1_train_subset_20000.csv, 包含 20000 张数据
已保存 fold1_train_subset_50000.csv, 包含 50000 张数据
已保存 fold1_train_subset_100000.csv, 包含 100000 张数据
已保存 fold2_train_subset_1000.csv, 包含 1000 张数据
已保存 fold2_train_subset_5000.csv, 包含 5000 张数据
已保存 fold2_train_subset_10000.csv, 包含 10000 张数据
已保存 fold2_train_subset_20000.csv, 包含 20000 张数据
已保存 fold2_train_subset_50000.csv, 包含 50000 张数据
已保存 fold2_train_subset_100000.csv, 包含 100000 张数据
已保存 fold3_train_subset_1000.csv, 包含 1000 张数据
已保存 fold3_train_subset_5000.csv, 包含 5000 张数据
已保存 fold3_train_subset_10000.csv, 包含 10000 张数据
已保存 fold3_train_subset_20000.csv, 包含 20000 张数据
已保存 fold3_train_subset_50000.csv, 包含 50000 张数据
已保存 fold3_train_subset_100000.csv, 包含 100000 张数据
已保存 fold4_train_subset_1000.csv, 包含 1000 张数据
已保存 fold4_train_subset_5000.csv, 包含 5000 张数据
已保存 fold4_train_subset_10000.csv, 包含 10000 张数据
已保存 fold4_train_subset_20000.csv, 包含 20000 张数据
已保存 fold4_train_subset_50000.csv, 包含 50000 张数据
已保存 fold4_train_subset_100000.csv, 包含 100000 张数据
所有折的子集已保存完成！

In [20]:
import os
import pandas as pd
from multiprocessing import Pool, cpu_count

# 假设你的目录结构已经整理好
prefix = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org"
base_directory = "/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold_data"
folds = [0, 1, 2, 3, 4]  # 根据需要处理的fold范围

divs = ["train_subset_1000", "train_subset_5000", "train_subset_10000", "train_subset_20000", "train_subset_50000", "train_subset_100000"]

# 函数来构造路径
def construct_file_path(dicom_id, subject_id, study_id):
    try:
        # 提取 subject_id 前两位，形成 p{subject_id}
        subject_prefix = f"p{str(subject_id)[:2]}"  # 假设 subject_id 的前两位作为目录
        # 构建完整路径
        path = os.path.join(prefix, f"files/{subject_prefix}/p{subject_id}/s{study_id}/{dicom_id}.jpg")
        # print(f"path:{path}")
        if os.path.exists(path):
            return dicom_id, path  # 返回dicom_id和找到的路径
        else:
            raise FileNotFoundError(f"文件不存在: {path}")
    except Exception as e:
        return dicom_id, str(e)  # 返回dicom_id和错误信息

# 多进程处理函数
def process_fold(fold, div):
    print(f"\n正在处理 fold{fold}...")

    # 读取fold的原始数据文件
    fold_file = f'/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold{fold}/fold{fold}_{div}.csv'
    fold_data = pd.read_csv(fold_file)

    # 使用多进程查找每个 dicom_id 的路径
    with Pool(processes=cpu_count()) as pool:
        results = pool.starmap(construct_file_path, 
                               [(row['dicom_id'], row['subject_id'], row['study_id']) for index, row in fold_data.iterrows()])
    
    # 将结果添加到DataFrame中
    paths = {dicom_id: path for dicom_id, path in results}
    fold_data['path'] = fold_data['dicom_id'].map(paths)
    
    # 过滤出找不到路径的记录，输出错误并跳过
    missing_paths = fold_data[fold_data['path'].str.contains('文件不存在')]
    if not missing_paths.empty:
        print(f"警告: 以下记录找不到文件路径，并将被跳过：")
        print(missing_paths[['dicom_id', 'subject_id', 'study_id', 'path']])
        # 从数据中删除找不到路径的行
        fold_data = fold_data[~fold_data['path'].str.contains('文件不存在')]

    # 创建新目录并保存处理后的文件
    new_fold_dir = os.path.join(base_directory, f"fold{fold}")
    os.makedirs(new_fold_dir, exist_ok=True)

    new_file_path = os.path.join(new_fold_dir, f"fold{fold}_{div}.csv")
    fold_data.to_csv(new_file_path, index=False)
    print(f"处理完毕，新的数据已保存至 {new_file_path}")

# 遍历每个fold进行处理
for fold in folds:
    for div in divs:
        process_fold(fold, div)

print("所有fold处理完成！")

正在处理 fold0...

FileNotFoundError: [Errno 2] No such file or directory: '/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold0/fold0_train_subset_1000.csv'

In [29]:
import os
from PIL import Image

# 定义根目录
base_dir = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/'

# 遍历一级子文件夹
for subdir in os.listdir(base_dir):
    subdir_path = os.path.join(base_dir, subdir)
    
    # 确保是文件夹
    if os.path.isdir(subdir_path):
        original_path = os.path.join(subdir_path, 'original.jpg')
        
        # 检查 original.jpg 是否存在
        if os.path.exists(original_path):
            try:
                # 打开原始图像
                with Image.open(original_path) as img:
                    # 调整图像大小到 256x256
                    img_resized = img.resize((256, 256))
                    
                    # 保存调整后的图像
                    resized_path = os.path.join(subdir_path, 'original_256.jpg')
                    img_resized.save(resized_path)
                    print(f"图像已调整并保存: {resized_path}")
            except Exception as e:
                print(f"处理 {original_path} 时发生错误: {e}")
        else:
            print(f"未找到文件: {original_path}")

图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/f7ba6691-53545537-20c8b2dc-79dbd392-36f05d15/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/1d3cf33d-0bcbe0fd-589cde2e-ff4cd9b4-41b8ed96/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0ef420a4-7f73b19a-2b43ee81-f8f3e1ed-d94b9a27/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/f7b69ee3-db7f264c-fca7d1c7-1d372fc0-02b35a47/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/36a8ff8b-be622816-dcc0c794-e85c285d-9fde04b4/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/a5d3aa8b-573aa054-cb848da6-184d98fa-539aecf3/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/1e16b6b4-d5a7ebf8-78fae5b1-fa122b81-cb68fb7c/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/09a6c621-8faee2f2-bd72a98f-ed8bee84-9767b0a9/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/cf57f905-933439a6-c42a1e8d-f2b3a936-de0d1923/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/52f2007d-4835f8c4-eafba189-443dfd0e-20d8603c/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/c6ee0c83-d00283b2-46648090-03f78e74-0b06ecf1/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/1ef030a6-c9efc6a2-1f6a64cd-1a9a7bc4-230a865e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0a13d67a-40ead90f-74cbd9a1-a1133c01-6ce2f064/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/6960e5e8-3c7c8e6a-d951d989-fe3aad0c-cb7407fe/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/44712083-6ebbda14-6e11adaf-578d786c-b736804f/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/8d36f63d-6e725615-3f005c82-5e0213ba-13cc3761/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/32a32fe1-b5d54978-bd949e3a-a3249f06-03094042/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/e3fc5bd6-0ebd345c-dd63d96c-6844627c-1b6cf82b/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/a8e5ebec-d70fa00f-d0fd6e3e-ede9aecf-0f955fd3/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0619df15-9da411e1-9a47d1bf-973bbcf8-97f09ae0/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/1bc70985-bc33bdb8-0f538f84-0c541095-4021ce11/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/cb41183a-0412434c-a3a43ea7-f32081b8-bee045d5/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/c5a5291e-345df52a-8260a936-62410186-4edb49bd/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/956ec432-03e9c40c-ff58e74d-db0b9443-71042da1/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/928e66f1-87ef1b9e-0ce33e37-760d835a-a539e8b9/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/975001f1-aa6ac139-0411a210-a0ef87cc-4956e706/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/c6d9dcd8-49e961d7-227e2c94-92994086-9831113b/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/450afa3a-8338f4f3-c7f038ba-4f51f4de-bbea445b/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/da4bce81-5bb0a836-fc8962ca-ce94c3e3-6ae338cd/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0cc0d181-b0d47230-4802a1c0-07c6a7f9-642cd78a/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0db18f8d-7f096b32-012523d0-af5c8b13-0d44c969/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0fd5056b-d919dc47-134133e9-67967602-741bfe0e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/2468ebd9-40397438-697c7ff8-f86b7085-b34c2c8f/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/a9fb25a4-6b39c48b-03a92249-b0c290ae-f5f44ae2/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/65899cf1-69c8c359-1661d042-03a9a1de-d3cde420/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/331145d6-d982c8c1-772c4dac-f0da5016-52726c05/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/9d32e96f-dcc52f72-a7262f7a-298b9e97-39fc55bb/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/580cfee8-7b30a8d3-15f9fd6b-1905426c-acaa1635/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/ee82e08b-be7f5a74-8f406515-467d9e49-0b63bc0c/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4a83b37a-23203e27-02d50dff-e844997a-a60ee329/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/84dac834-d9f40739-755532a0-1ddab50a-cae07005/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/3d4e6fef-70941314-2926c04f-6a249d1c-77724d90/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/8b71881c-c896b1ec-9e6c08d8-6f61075a-c98e7454/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/7c17f8c6-00e14ab0-5ec77692-208b5095-0f6e09f3/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/043df04d-931d53c9-ae497983-ce79d340-656e2354/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/2804ccb9-1c49e7a2-e0657535-fb11033f-bf5b58af/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/17173530-ecd74be6-e5f43436-4e94adac-0fdc8a69/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/46bdab14-1fa0233c-c0b0841d-4c0869de-6564ff0d/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/79b98067-e378e7bc-4e832f17-3edb1f0a-d3a49dd3/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/3a5d63ba-30ddd666-f1f37606-f53c9f62-439d25a7/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/b993bc76-cddc4026-8da6095d-4948f005-5fd3dddd/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/57826c85-d6defe1e-e0e251cb-90dfcf74-31099bca/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0ae1a7ad-fcc627aa-01e96e50-cb14cf17-23f441ac/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/494aeff6-5d986c6e-d99faba7-5cc88912-a84926e5/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/21e95fbb-5db81e97-4466520c-f60ffcd7-fc39a052/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/ae00ad94-bc780297-f273a669-1fff3fa9-9875f668/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/77986392-2dac3752-b145c42b-2ba010de-d49de562/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/a3d38710-f682ca24-b82bbcc7-5400751d-2fcf8dab/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/68818a69-aa452dad-990777ed-149d3a35-853a56df/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/7e950526-ccc5960e-735b0f76-a80365d9-139f5bff/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/120f452b-65fb787e-b66fc8a3-5214a74e-278158ec/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/42d21848-297127d4-371f5901-168175de-fd3e0b44/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/8afc3991-7ec1912b-b24d9633-3c4b0f57-17c0e8f4/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/63c09ff1-7cae5eeb-a2231e4f-b62e0028-3fb27199/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/696f475c-ed224d78-23d1e42a-98b93bf8-ec57a197/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/10abfd75-dbb0cb76-ba525896-f9a77aa4-d08cc9d7/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/7a28df15-9a9dfa2e-e829e842-81f1f7b3-201b4b4a/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/400381dd-d0d474c7-2b1f51ba-7a91a5ab-e3db5cf1/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/b7c6fdce-f0908c0a-7d9af9cc-c41325ae-72b92805/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/366732ea-66b20dca-ce7c0fcc-f783ca4a-d05fa190/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/aaa3dc03-dd29e871-949084ef-1486b951-e502b225/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/42e4c1ac-413f6bf6-d8f4cf62-10fa476c-5bfaf9e5/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/3c58546c-0dbf3603-a97cbc6f-c4f6379f-46f0775b/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/a6d18cb6-12f2afc5-01623453-d3b4abaf-9fc7c542/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/db56399e-4f04b226-d9773c85-a6d565a6-04fe3904/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/8335a2c5-150c417f-90f20a4f-67283021-a12b2267/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0ac8f355-58fc87a7-70dbe5d1-82d96f7e-d57316a6/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/5e1fc04e-c01733e7-6ce7bc2b-df15975e-66c09955/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/b47aa34a-d4007cb7-a1e0e045-c60d42fc-a66ba91a/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/579aa963-68bf9738-656afe52-4588c247-a4a60642/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/1c712da2-d8760888-e8cac04f-51da4234-a33d806c/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/f0822d85-e737edc5-c4e90e14-22a76bf6-e041499e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/05cfa70c-bae80a26-8b294ba9-86716b29-7b719ea7/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/937bac70-10bf0f5d-e1527c6a-72b06373-b6398027/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/00258b8f-48b301d2-0cdf26b5-240d3e63-5a92e789/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/2db1c70e-42a70b4c-b0f24e2d-e1dceaa3-05cccca4/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/29929685-ae7731db-33f9f7e2-2eed3f1e-51aa9261/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/575a1076-2f828d1e-6cac9045-82ed4378-042a0e97/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/2f8ca5e2-5a1e02ab-e84f7547-069743e9-0f08d9e0/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/235d293b-833b0b81-e451ab61-45f26757-d58f2712/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/3fa1566e-0957c0dd-ef142837-8de55f3e-2ce96431/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/3023bd72-ffc82de2-76338d8b-94646c07-364af619/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/63fdeee3-5aaec360-f0f0ca21-4d4dfd32-eff883b6/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/38a13158-88db56a3-6235c2b5-ba17092a-fbecb615/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/ced4ad92-0b5bdd09-b67b83a8-8f155ad4-de399934/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4053b069-4e043dfb-a51aa130-f6318b90-21719d34/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/7c6edd07-7c4c8c3e-d8b216c7-88d2d002-975f90e3/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/25d70f01-7e7927a3-892438ba-dfc840a3-59fd316e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/30f62b64-c18d5fb6-49e670e0-093c8310-ca5d96b9/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/26cd4845-5c52d871-e5d996d0-a2113787-630c0309/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0d64d01e-719b983e-81dbaadc-087e797b-45daf2ab/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/675d792f-a3521e48-5eec8573-1e81d644-e60c34f8/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/5a9c65bc-9063ed84-7e21d143-1c2d9cf0-23ab0caa/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/1c038d27-c6193e6a-d4588595-a78608bd-565e11fa/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/dfb7d0af-c4934461-1f3e54d3-d13567bc-45021a07/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/c5c859e0-31ad17f1-2cdf1e03-a460a231-437e01cc/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/219c2095-b6f293aa-4d1b7c09-eb0c8425-1fb61f2f/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/c337d8f4-4f4a2ccf-1f03b68f-8ee20146-4f889f3f/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/209e814c-6fd84f44-e881959b-12e210e5-32c61496/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/14ecb713-14c8349e-5544e7b0-a1fbc250-28900dad/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4decce85-c6ede74e-7a8bc81c-e81edee9-5ec17116/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/ef5bcbc8-776e4cc8-7454a3fc-fb242b18-40c22ecc/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/3c1c6ac7-2237a2c6-c72ccbcc-cb075b9f-9c469bae/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/d4c3eb06-68dcce85-81bae663-853a3883-288dc307/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/5d9735fb-282f0b43-3cb54e78-0e785de3-f91d81d1/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/bcc3f4e4-b738eb07-3ec62576-98d963f8-d96610f5/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/68d3b53e-69bd2fe9-d6ae4e66-f65f12a1-2139ab1e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/034afc43-2fad16bb-0c7f7afd-78ac6a4f-b2a8e2e2/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/44d21fe9-7d185d5f-00927b0f-11bf3dce-45b85640/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/46159f52-75e2f0fa-ee4eac2e-f199c524-fe3d4410/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/e146fe5a-8b20498c-b5cd2dfe-bf0d6228-6e74d514/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4778fba4-0c7f0787-2274de15-85e7b73d-eb3a124c/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/021cf26b-cd5779dd-8a839d8a-92ede30b-41c1f997/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/00c33c9a-6378dff6-fc80e90f-169c891c-996dbd2e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4f4ed242-b8dbadb1-8f7e2378-1ecd6192-a2ba3603/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/8fbf70c6-38be49b6-19536bcd-74b5e494-4ed5093f/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/68008d7c-f0c13a3a-b04a2a33-01ca141a-daba8d14/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4f39b894-0f96583c-dbe3186f-466adf72-1f5d6944/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/47424716-029a30a2-741447c7-dfeb69d9-66a4ec94/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/f2ea048e-52ada468-199a5a64-06f14cb3-76e57312/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/63614692-b3e38869-3ea31ecc-ae721b69-7b7cfdad/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0bd6e8c7-8a005ad1-8975bd65-6f25528f-28f4a2c8/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/5840dcb5-d927aa9a-7c1e3474-ce2b18a7-8dbb0075/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/320f9022-bd20ed21-b786e599-db45cfdd-f102a453/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/3e7f3aa2-ca26dae3-c544c6d4-40f9e440-d39b0215/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/8726c74a-245ab051-430f078d-b0c78c3e-7f0d714e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0f9db700-33529f2a-fb3c8a52-ee20bc00-6975d0af/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/24e489d8-affaee96-e41cd0c2-f1099291-3a0c4737/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/43fd797e-a37c21e7-c005cf50-44307d95-66496607/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/0b8054fe-62364893-543b3eb4-bf467b77-9b643fe5/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4a050186-c6320c70-b83046e2-f2c1f2b6-85c0f190/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/2a2698a5-bbd7d59c-b1a5a426-0a711037-b60142f3/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/f9474194-83c01c55-41295dbc-708f66b1-a289b0e3/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/141aef44-70c16b9e-a1b1a01c-04cddd6f-419ddf07/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/07dbb821-ab4f47ba-0b907549-7f7d716f-2c687f5b/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/226d3cc7-a5b83731-b756ef4e-37afd118-cf5ea84e/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4d85d642-5e8316ad-ceed42bd-9bd4615a-20c66bf0/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/e7da986f-69b47a88-1b95356e-8d74bbdf-42853420/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/e8c85149-4c24607d-c1d7d76f-4fa7b60b-b0245eb8/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/8afe8a73-004dc473-b4775f04-0952fd66-39b22b99/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/4ce9e5bc-91147696-d0c4b6cd-fc5ffa18-c485b700/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/f19b9819-95cb024f-8e3be04f-bd51425b-1ce5208f/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/e538135c-ebad1b7e-5f239803-3d6bcf94-7c5fddc4/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/185ef302-c2aa6070-cda98c90-88f59501-a0fc1d33/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/9ed39c33-886e9fb0-03544d77-e20557a9-ca545c0b/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/912bcb92-73828ec5-8dad1cbd-cc3788ef-de788956/original_256.jpg
图像已调整并保存: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_images/2122466d-daff1844-db642157-a9d56c17-bac026e9/original_256.jpg

In [4]:
import pandas as pd
import numpy as np
import os

# 读取 metadata 和 chexpert 数据
metadata_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-metadata.csv')
chexpert_df = pd.read_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-chexpert.csv')

# 1. 合并 metadata 和 chexpert 数据
merged_df = pd.merge(metadata_df, chexpert_df, how='left', on=['subject_id', 'study_id'])

# 打印合并前后的行数
print(f"合并前的行数: {metadata_df.shape[0]}")
print(f"合并后的行数: {merged_df.shape[0]}")

# 2. 只保留指定的疾病记录
disease_columns = ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Lung Opacity', 'Pleural Effusion', 'Pneumonia', 'Pneumothorax']

# 3. 将疾病列中的 1.0 转换为 YES，0.0 转换为 NO，其他值和 nan 忽略
for disease in disease_columns:
    merged_df[disease] = merged_df[disease].apply(lambda x: 'YES' if x == 1.0 else ('NO' if x == 0.0 else np.nan))

# 4. 拆分数据，每个疾病一行，删除 NaN 和 -1
expanded_rows = []

# 定义路径前缀
prefix = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files"
prefix_256 = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256"

def construct_image_paths(dicom_id, subject_id, study_id):
    # 构造原始图像路径
    subject_prefix = f"p{str(subject_id)[:2]}"  # 假设 subject_id 的前两位作为目录
    img_original_path = os.path.join(prefix, f"{subject_prefix}/p{subject_id}/s{study_id}/{dicom_id}.jpg")
    
    # 构造 256 图像路径
    img_256_path = os.path.join(prefix_256, f"{subject_prefix}/p{subject_id}/s{study_id}/{dicom_id}.jpg")
    
    return img_original_path, img_256_path

# 生成唯一的 seed，从 0 开始递增
seed_counter = 0

for index, row in merged_df.iterrows():
    subject_id = row['subject_id']
    study_id = row['study_id']
    dicom_id = row['dicom_id']
    
    # 遍历所有疾病列，判断该疾病是否为 YES
    for disease in disease_columns:
        if row[disease] in ['YES', 'NO']:
            exists = row[disease]
            img_original_path, img_256_path = construct_image_paths(dicom_id, subject_id, study_id)
            
            expanded_rows.append({
                'seed': seed_counter,  # 使用递增的 seed
                'data_source': "cxr_crop",
                'prompt': [{"content": "", "role": "user"}],
                'extra_info': {
                    "env_config": {"parquet_path": "data/cxr_all/full.parquet"},
                    "env_name": "cxr_crop",
                    "seed": index,
                    "split": "train"
                },
                'dicom_id': dicom_id,
                'img_original_path': img_original_path,
                'img_256_path': img_256_path,
                'disease': disease,
                'exists': exists,
            })

            # 增加 seed
            seed_counter += 1

# 将拆分后的数据转换为 DataFrame
expanded_df = pd.DataFrame(expanded_rows)

print(f"final seed: {seed_counter}")

# 5. 保存为 Parquet 文件
expanded_df.to_parquet('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/full_v3.parquet', index=False)

print("数据拆分并格式化成功，已保存为 Parquet 文件！")

合并前的行数: 377110
合并后的行数: 377110
final seed: 606351
数据拆分并格式化成功，已保存为 Parquet 文件！

In [10]:
import pandas as pd

# 加载 CSV 文件
file_path = "/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/mimic-cxr-2.0.0-chexpert.csv"
df = pd.read_csv(file_path)

# 给定的疾病列
disease_columns = ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Lung Opacity', 'Pleural Effusion', 'Pneumonia', 'Pneumothorax']

# 创建一个字典存储结果
disease_counts = {}

# 遍历每个疾病列
for column in disease_columns:
    # 计算1.0和0.0的个数
    count_1 = df[column].apply(lambda x: 1 if x == 1.0 else 0).sum()
    count_0 = df[column].apply(lambda x: 1 if x == 0.0 else 0).sum()
    total = count_1 + count_0
    ratio = count_1 / total if total > 0 else 0
    disease_counts[column] = {
        'count_1': count_1,
        'count_0': count_0,
        'ratio_1': ratio
    }

disease_counts_df = pd.DataFrame(disease_counts).T
disease_counts_df

                  count_1  count_0   ratio_1
Atelectasis       45808.0   1531.0  0.967659
Cardiomegaly      44845.0  15911.0  0.738116
Consolidation     10778.0   7967.0  0.574980
Edema             27018.0  25641.0  0.513075
Lung Opacity      51525.0   3069.0  0.943785
Pleural Effusion  54300.0  27158.0  0.666601
Pneumonia         16556.0  24338.0  0.404852
Pneumothorax      10358.0  42356.0  0.196494

In [11]:

import pandas as pd

# 加载 CSV 文件
file_path = "/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_combined.csv"
df = pd.read_csv(file_path)

# 给定的疾病列
disease_columns = ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Lung Opacity', 'Pleural Effusion', 'Pneumonia', 'Pneumothorax']

# 创建一个字典存储结果
disease_counts = {}

# 遍历每个疾病列
for column in disease_columns:
    # 计算1.0和0.0的个数
    count_1 = df[column].apply(lambda x: 1 if x == 1.0 else 0).sum()
    count_0 = df[column].apply(lambda x: 1 if x == 0.0 else 0).sum()
    total = count_1 + count_0
    ratio = count_1 / total if total > 0 else 0
    disease_counts[column] = {
        'count_1': count_1,
        'count_0': count_0,
        'ratio_1': ratio
    }

disease_counts_df = pd.DataFrame(disease_counts).T
disease_counts_df

                  count_1  count_0   ratio_1
Atelectasis         342.0      3.0  0.991304
Cardiomegaly        379.0     90.0  0.808102
Consolidation       195.0     26.0  0.882353
Edema               326.0     94.0  0.776190
Lung Opacity        542.0      9.0  0.983666
Pleural Effusion    618.0    123.0  0.834008
Pneumonia           324.0     50.0  0.866310
Pneumothorax        323.0    289.0  0.527778

In [5]:
import pandas as pd

def preview_parquet(path, n=10):
    """
    读取指定 parquet 文件并打印前 n 行

    参数:
        path (str): parquet 文件路径
        n (int): 打印的行数，默认 5
    """
    try:
        df = pd.read_parquet(path)
        print("列名：", list(df.columns))
        print("\n前几行记录：")
        print(df.head(n))
        print(f"\n总行数: {len(df)}")
        return df
    except Exception as e:
        print(f"读取 parquet 文件失败: {e}")
        return None

# 使用示例
df = preview_parquet("/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/full_v3.parquet", n=20)
# df_sub1 = df["exists"][:30]
# df_sub2 = df["disease"][:30]
# df_sub1, df_sub2

列名： ['seed', 'data_source', 'prompt', 'extra_info', 'dicom_id', 'img_original_path', 'img_256_path', 'disease', 'exists']

前几行记录：
    seed data_source                             prompt  \
0      0    cxr_crop  [{'content': '', 'role': 'user'}]
1      1    cxr_crop  [{'content': '', 'role': 'user'}]
2      2    cxr_crop  [{'content': '', 'role': 'user'}]
3      3    cxr_crop  [{'content': '', 'role': 'user'}]
4      4    cxr_crop  [{'content': '', 'role': 'user'}]
5      5    cxr_crop  [{'content': '', 'role': 'user'}]
6      6    cxr_crop  [{'content': '', 'role': 'user'}]
7      7    cxr_crop  [{'content': '', 'role': 'user'}]
8      8    cxr_crop  [{'content': '', 'role': 'user'}]
9      9    cxr_crop  [{'content': '', 'role': 'user'}]
10    10    cxr_crop  [{'content': '', 'role': 'user'}]
11    11    cxr_crop  [{'content': '', 'role': 'user'}]
12    12    cxr_crop  [{'content': '', 'role': 'user'}]
13    13    cxr_crop  [{'content': '', 'role': 'user'}]
14    14    cxr_crop  [{'content': '', 'role': 'user'}]
15    15    cxr_crop  [{'content': '', 'role': 'user'}]
16    16    cxr_crop  [{'content': '', 'role': 'user'}]
17    17    cxr_crop  [{'content': '', 'role': 'user'}]
18    18    cxr_crop  [{'content': '', 'role': 'user'}]
19    19    cxr_crop  [{'content': '', 'role': 'user'}]

                                           extra_info  \
0   {'env_config': {'parquet_path': 'data/cxr_all/...
1   {'env_config': {'parquet_path': 'data/cxr_all/...
2   {'env_config': {'parquet_path': 'data/cxr_all/...
3   {'env_config': {'parquet_path': 'data/cxr_all/...
4   {'env_config': {'parquet_path': 'data/cxr_all/...
5   {'env_config': {'parquet_path': 'data/cxr_all/...
6   {'env_config': {'parquet_path': 'data/cxr_all/...
7   {'env_config': {'parquet_path': 'data/cxr_all/...
8   {'env_config': {'parquet_path': 'data/cxr_all/...
9   {'env_config': {'parquet_path': 'data/cxr_all/...
10  {'env_config': {'parquet_path': 'data/cxr_all/...
11  {'env_config': {'parquet_path': 'data/cxr_all/...
12  {'env_config': {'parquet_path': 'data/cxr_all/...
13  {'env_config': {'parquet_path': 'data/cxr_all/...
14  {'env_config': {'parquet_path': 'data/cxr_all/...
15  {'env_config': {'parquet_path': 'data/cxr_all/...
16  {'env_config': {'parquet_path': 'data/cxr_all/...
17  {'env_config': {'parquet_path': 'data/cxr_all/...
18  {'env_config': {'parquet_path': 'data/cxr_all/...
19  {'env_config': {'parquet_path': 'data/cxr_all/...

                                        dicom_id  \
0   096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4
1   b79e55c3-735ce5ac-64412506-cdc9ea79-f1af521f
2   dcfeeac4-1597e318-d0e6736a-8b2c2238-47ac3f1b
3   d0b71acc-b5a62046-bbb5f6b8-7b173b85-65cdf738
4   d0b71acc-b5a62046-bbb5f6b8-7b173b85-65cdf738
5   3be619d1-506a66cf-ff1ab8a1-2efb77bb-fe7d59fc
6   9b314ad7-fbcb0422-6db62dfc-732858d0-a5527d8b
7   8e3f2822-0c1d4b71-2a265bbf-5b96e531-ccf5fa30
8   ad13cf84-62c34a01-a01b9e87-2581a359-83bbc046
9   6fa5997e-b1dfecf8-3c174666-8815c84a-32db59ff
10  f1adcae3-2921c0a8-5d9652f9-4191ecd7-f2a96f35
11  6ad03ed1-97ee17ee-9cf8b320-f7011003-cd93b42d
12  6ad03ed1-97ee17ee-9cf8b320-f7011003-cd93b42d
13  6ad03ed1-97ee17ee-9cf8b320-f7011003-cd93b42d
14  6b360eca-17d2ae1a-19126084-78e9c85d-9800d216
15  6b360eca-17d2ae1a-19126084-78e9c85d-9800d216
16  6b360eca-17d2ae1a-19126084-78e9c85d-9800d216
17  943486a3-b3fa9ff7-50f5a769-7a62fcbb-f39b6da4
18  96f9a77c-59b47dfb-0cac64db-6538421a-a6b135e2
19  cfb03587-782edf6c-1bf392e1-98196cd5-365d69e8

                                    img_original_path  \
0   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
1   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
2   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
3   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
4   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
5   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
6   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
7   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
8   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
9   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
10  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
11  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
12  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
13  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
14  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
15  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
16  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
17  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
18  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...
19  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...

                                         img_256_path           disease exists
0   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...     Consolidation    YES
1   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...     Consolidation    YES
2   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...     Consolidation    YES
3   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...  Pleural Effusion    YES
4   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...         Pneumonia    YES
5   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...      Lung Opacity    YES
6   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...      Lung Opacity    YES
7   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...      Lung Opacity    YES
8   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...      Lung Opacity    YES
9   /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...      Cardiomegaly     NO
10  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...      Cardiomegaly     NO
11  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...             Edema     NO
12  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...  Pleural Effusion     NO
13  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...         Pneumonia     NO
14  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...             Edema     NO
15  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...  Pleural Effusion     NO
16  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...         Pneumonia     NO
17  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...         Pneumonia    YES
18  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...         Pneumonia     NO
19  /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr...         Pneumonia     NO

总行数: 606351

In [35]:
import pandas as pd
import cv2
import time, random

df = pd.read_parquet('/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/full_v3.parquet')
paths = df['img_original_path'].unique().tolist()
sample_paths = random.sample(paths, min(10, len(paths)))

print(sample_paths[:5])

start = time.time()
for p in sample_paths:
    img = cv2.imread(p)
    if img is not None:
        _ = cv2.resize(img, (256, 256))

total_sample_time = time.time() - start
avg_per_image = total_sample_time / len(sample_paths)
total_images = len(paths)
est_single = avg_per_image * total_images
est_96 = est_single / 96

results = {
    'sample_count': len(sample_paths),
    'total_images': total_images,
    'total_time_sample_s': total_sample_time,
    'avg_time_per_image_s': avg_per_image,
    'estimated_time_single_s': est_single,
    'estimated_time_96cores_s': est_96
}
print(pd.DataFrame.from_dict(results, orient='index', columns=['value']))

['/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files/p11/p11063065/s53033221/d6988264-ef9b1993-bc183ebf-38960313-54d10c43.jpg', '/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files/p19/p19998330/s58626532/6c6f0868-10028db0-0270ff74-65210a42-e084c544.jpg', '/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files/p14/p14767213/s54407749/8c83b1d3-37ab9008-4a3a5056-89bac880-95d016c7.jpg', '/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files/p18/p18268875/s52525965/ea78df92-50c0d7b1-d29849e2-2704c06e-89a66f5f.jpg', '/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files/p17/p17477304/s52291282/02974fed-1605f6cb-99757fcd-a573d926-7a858725.jpg']
                                  value
sample_count                  10.000000
total_images              242798.000000
total_time_sample_s            1.220405
avg_time_per_image_s           0.122041
estimated_time_single_s    29631.197579
estimated_time_96cores_s     308.658308

In [23]:
import os
import pandas as pd
import cv2
import multiprocessing
from tqdm import tqdm

# 读取 CSV 文件
csv_file = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_combined.csv'
# csv_file = '/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold_data/fold0/fold0_train_subset_10000.csv'
df = pd.read_csv(csv_file)

# 获取唯一的原始路径列表
unique_paths = df['path'].unique().tolist()

# 替换路径前缀
prefix = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org"
prefix_ori = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files"
prefix_256 = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256"

# prefix = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files"
# prefix_256 = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256"

def process_image_path(original_path):
    original_path = prefix + "/" + original_path
    new_path = original_path.replace(prefix_ori, prefix_256)

    # 创建目标文件夹
    new_dir = os.path.dirname(new_path)
    # if not os.path.exists(new_dir):
    os.makedirs(new_dir, exist_ok=True)

    # 检查原始文件是否存在
    if not os.path.exists(original_path):
        print(f"Warning: 原始文件不存在: {original_path}")
    
    # 读取图像并进行 resize
    img = cv2.imread(original_path)
    if img is not None:
        # Resize 图像为 256x256
        resized_img = cv2.resize(img, (256, 256))

        # 检查新文件是否已存在，如果存在，打印警告
        if os.path.exists(new_path):
            print(f"Warning: 新文件已存在并将被替换: {new_path}")
        
        # 保存 resized 图像
        cv2.imwrite(new_path, resized_img)
    
    return new_path  # 返回新路径以便在进程完成后追踪

def parallel_process(unique_paths, num_processes=96):
    # 使用 tqdm 显示进度条
    with multiprocessing.Pool(processes=num_processes) as pool:
        results = list(tqdm(pool.imap(process_image_path, unique_paths), total=len(unique_paths)))
    return results

# 开始处理并显示进度
new_paths = parallel_process(unique_paths)

print("任务完成，所有图像已保存到新的路径！")

  0%|          | 0/1047 [00:00<?, ?it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s56875184/00258b8f-48b301d2-0cdf26b5-240d3e63-5a92e789.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10446794/s51668285/0bd6e8c7-8a005ad1-8975bd65-6f25528f-28f4a2c8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10233088/s54276838/675d792f-a3521e48-5eec8573-1e81d644-e60c34f8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10123147/s50230934/5318d353-daae9c3d-2ee8648e-32b65198-aeff801e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10500801/s58577720/4decce85-c6ede74e-7a8bc81c-e81edee9-5ec17116.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10103318/s58470002/4b55dc6f-a8f1b418-464a67bb-61e5dcbe-61f64393.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10686970/s50918944/205e63b4-1d7b7bb0-5cb9f421-214c6758-52883243.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10647030/s58488064/33610ebf-e50c479a-c4c63cac-a2456bc0-46789016.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10238167/s54158485/1001d6be-a7245a90-410147da-9723c89f-e2e48a41.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10625523/s54317439/1875f504-2961fe1e-4c0c4d98-256a2e24-892175a3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10415973/s53911366/2f5430f8-c5254c06-93086191-e172e483-890db6c5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10667797/s58923918/52f2007d-4835f8c4-eafba189-443dfd0e-20d8603c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10171967/s52209484/41b86e36-36a1a4f6-bad84a3d-b2f42c69-51b52ca1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s56305820/310807b1-15bd51d8-e4cf7456-395a6a80-94bd89d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10663051/s53718425/0d6c12c9-73c843f7-c4a66b2e-9c976fec-5f8f470b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10267709/s58630233/68008d7c-f0c13a3a-b04a2a33-01ca141a-daba8d14.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10594556/s55320026/1a16cc1a-c411c2ce-5b183fdb-d070d522-8273b7b3.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s57815540/2be80973-78abc991-1a37f74b-f6a9fac4-d21e186f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10517964/s52539103/24e489d8-affaee96-e41cd0c2-f1099291-3a0c4737.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10640977/s52825690/288a7d41-dfc9638d-24b10d18-6dc6eafc-df0208d2.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s59849838/12e44e17-83038e09-ab7e75cb-cff2a30e-6f1e9e14.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10532853/s53292365/4e7f7a09-2203ee9f-ae3c3f07-040ba833-92baef47.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10388470/s51417242/08c206fa-15bc2f42-f8918f67-9efc66b9-c01f6feb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10295447/s54152935/63614692-b3e38869-3ea31ecc-ae721b69-7b7cfdad.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10039272/s50589184/3daa2f39-89cf3e9d-6be38a60-2cd19002-964fed61.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10471577/s56127038/1e16b6b4-d5a7ebf8-78fae5b1-fa122b81-cb68fb7c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10127469/s56582733/37d7e851-822d8e4b-10293051-661810fb-c1ea0501.jpg






Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10280054/s52350255/1a39dbd5-ce57571a-f918d974-842ee233-f58422dc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10699336/s59206518/0d21952b-62e3a06c-7fa98353-46abfc4a-cf0ed8b7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10129119/s52886997/4fe39bd8-3722c28b-0bcaa1a8-eda9ae12-d5797d04.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10022373/s54005410/007722d2-e9cbf1a1-99492060-00ce4657-89a5bab8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s51640314/30fe40e1-ab514475-aa387b0a-e1718b1b-ba680a97.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10039272/s56823182/284eedfa-094242da-bf433cc8-7876765a-f05a0b30.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10116099/s55167428/43755e16-4fa5c359-23433e58-19885fb4-0c775848.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10258162/s58165075/40b07755-2524769b-a050ef41-da33b294-bdc1cfac.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10224976/s55827028/263f4b49-a7acda12-ac09e200-38c1abb6-c8f1a736.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10421218/s51489361/475f1b25-8c659725-53ce9a05-4dcfbf84-648981b9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10056223/s57733074/185ef302-c2aa6070-cda98c90-88f59501-a0fc1d33.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10039272/s56948355/138f8635-f0427bf9-8fd0a81f-7004c876-f913b5fe.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10270108/s59722607/47117427-c114f8b2-16fbe49a-5f2a5cef-6c448297.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10533554/s53552442/5a705387-059dda71-371bf595-040ce15b-e7c01088.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10218191/s58714747/0a028963-43f5001a-1cd86060-a8c69970-6c83a8d4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10115397/s52993418/5161d2a0-8d0f5369-43d36cc7-41a6f37b-d289e44b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10258162/s57074033/111fefd1-4ca65451-85f9a9d6-bc6820a6-06e33e05.jpg






Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10550799/s52602032/268fc4fe-2c537ac3-9d4d8201-77150900-743a2ac8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s58018342/14ecb713-14c8349e-5544e7b0-a1fbc250-28900dad.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10216556/s50981597/018aa67e-edbe363c-b7b7db2a-6cbf31b9-a55e9aae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10199945/s51826643/262628a5-997312e7-1fcc94f1-cc2c2595-59c16d83.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10336412/s52082223/459ca311-6569ed51-6087d76f-ebf1b3ee-205b8ca4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10564151/s59054404/25a60a53-5321dc07-a544a3e8-b9d07f82-579bbfc3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10180419/s56075642/14ed3d4d-14a4b260-38264f20-cd55bb32-cbb5f03b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10313200/s59877766/529152bc-8619ddc6-c5ce80da-7c8bb377-09024aae.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10267084/s59827176/3332cf8c-edba75ae-55b3f8c6-3c649171-e82d4154.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10437175/s51114167/66ad4593-edb8cc5b-c5a58fe0-a2a81cc2-d5b876b5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10598816/s50309067/450afa3a-8338f4f3-c7f038ba-4f51f4de-bbea445b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10438089/s56572458/10742c3a-7a53c874-504c91b3-4edf52b6-63e07a65.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10877472/s57615334/399118d1-15101922-19d14364-5128b5f5-383753e3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530907/s53919204/1d3cf33d-0bcbe0fd-589cde2e-ff4cd9b4-41b8ed96.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10918768/s54785893/5af80b29-6db9e37e-31e0231d-3bab2757-3bf743bc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10123949/s53602454/1958f42f-183b9923-8722fe62-1ba9e7bc-01b678e0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10374990/s53976242/2cc8f7f9-6aa05788-674ed5ea-32ac5cbb-eab9c2c4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10680329/s58474868/559a4998-c29c68df-ec6db2d8-07219b06-55cceff2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s58469946/22d3dbb2-f5d7bdfc-9a600d10-e859adca-17c26435.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10289125/s58560223/088e6230-420045e5-b6cd7fa6-67c4d377-9fffad31.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10677118/s58401435/5c997459-f39f2771-4f541c32-5d525d6e-a366028d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10347064/s58235286/124e3930-bd138fc3-da83d23f-a481bf9c-7bdc3a14.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10404451/s56987955/215f63fa-4589bf7a-a4228654-deb82888-423f0463.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10516278/s58467771/59de830c-85ab88f1-16604bfd-1950e54a-d006459e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10272619/s51729857/0d64d01e-719b983e-81dbaadc-087e797b-45daf2ab.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10328573/s58279180/3565b358-250fc12a-0ccb5f07-64a611ec-d2eadff9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10401098/s55170084/1da6a979-7e85d032-196953b6-4bcaa2aa-fe1cf236.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10667727/s59297548/0b4c1a22-3e135e03-be0016c2-90436561-ec493812.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10320599/s51734262/3c5b4038-4b47ec05-67947b5a-568a8b69-f299b8dc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10544620/s54661943/01daa078-940696aa-44a9a401-30773c80-b36e0098.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10663878/s57703449/06b94da3-5b8f3d81-4e40bb3e-4f7807d2-a621ae8f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10062617/s58048417/57826c85-d6defe1e-e0e251cb-90dfcf74-31099bca.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10136781/s56279036/3023bd72-ffc82de2-76338d8b-94646c07-364af619.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10706664/s58768538/1a117114-891ccfc4-5dc0b7e0-d7998745-38412c46.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10612095/s59551015/21e95fbb-5db81e97-4466520c-f60ffcd7-fc39a052.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10049902/s50339410/232bcc7f-82a2e28d-e6fcb4b2-c6df2736-ecc560b9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10065383/s52292453/5209cbae-fb03f881-a574bc73-1650ad4b-d98ba5d7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10919671/s58656175/14b8fb1e-746a372d-eb1897ff-9c25e7b4-18c3a889.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10569882/s57059623/2804ccb9-1c49e7a2-e0657535-fb11033f-bf5b58af.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10380616/s53925580/310d75dd-30391573-30155c98-d3a221b3-082b68ac.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10003400/s53341253/19b74f79-7ad317b1-887496c3-2645db29-48245a51.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10571299/s56353220/52c1d3b2-6f9c5443-4ced7bd4-b9e524cb-b8d18187.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10390732/s56782281/16ea1d35-a0aea7a3-8ef05378-5d5a20bc-db4004dc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10977201/s59062881/00363400-cee06fa7-8c2ca1f7-2678a170-b3a62a6e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10253803/s55814412/63bb5bfa-88f93af9-b9d2e5d1-836e6797-aa7881af.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10293407/s57055255/4f3dc24f-4a2f2140-3e16dfa6-abcbefc0-b0edb47e.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10481486/s55646022/1eb558d1-9c8f1b8a-5a88ee41-049f74d3-ff0f5f4e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10573359/s53581594/34c05125-69e84337-82aead9b-d66d97c0-1b1b9d25.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10270108/s59326252/3873d55a-7b6fc707-b4202cfc-91115ec6-cc52d8f8.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10324973/s51426486/3b0a6fd4-70c2c75c-aea7a8ba-eb76be2e-894ee5d8.jpg

















Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10624280/s54364577/1b51857f-65e44d4b-8bd4958f-f2cd5bc4-a85296bb.jpg

















Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10626933/s58564541/2d16ba40-9c92f4ea-474678e7-533c71dc-2ed1cb56.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s58444910/5e1fc04e-c01733e7-6ce7bc2b-df15975e-66c09955.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10456463/s58410899/202bc2a9-0c9efe8c-8c7e352e-89630d49-45996c81.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10653589/s54611483/56ae3ba8-a8be69a7-f436acf1-f0e99f59-db42e97e.jpg

  0%|          | 1/1047 [00:00<11:38,  1.50it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10653798/s56634372/30be9385-307211c4-7a5d6748-006698ad-614e1cd9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10670818/s50191454/1176839d-cf4f677f-d597a1ef-548bc32a-c05429f3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10532853/s55156948/0fd5056b-d919dc47-134133e9-67967602-741bfe0e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10242587/s51563295/672613f9-16e23e76-c1ca9370-8cb9e7fa-20021abb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10420013/s51567065/29497ef7-493b55c3-468026b1-f087f5a3-944bb828.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10103318/s51375310/580cfee8-7b30a8d3-15f9fd6b-1905426c-acaa1635.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10532853/s55459306/1d1c08b9-cf3710bb-ea85bb1f-48cc7100-375dbfc3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10196757/s52369058/3929b643-a476a0c0-8a2739cb-ee4e0f95-ff02e65d.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10045929/s52686702/1960c49b-b1f7e842-13c75a39-27686a98-741528ff.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10225793/s52569552/06d8f348-7e843f0c-febb4048-c33861ee-a55a5153.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10320599/s52962720/23277273-1562753f-9e0ef2da-477b3c6c-f8e921dc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10207998/s50917015/640a3532-6a737862-10ad84e6-5327df81-1005d1ec.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10285188/s50768680/2890c03a-d0cd1395-2b4069ce-97a5eea1-1a45ff62.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10653798/s51137289/148e89de-5fba475c-460886d7-f2b48703-52770db5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s59868992/4e972189-3f41fa23-7aa2cc16-a19c2a12-f03cfec2.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s56622871/2bfbb8d4-370e3dd0-fb6e2f6a-68435e4d-32033248.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10058575/s50255541/450dfe58-97a2df21-2631844a-92f2a69a-9b47e278.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10594721/s55136856/6691d379-db55ed81-2ccba30a-8a565a78-3a16096e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10571791/s56615010/2a2698a5-bbd7d59c-b1a5a426-0a711037-b60142f3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10293407/s52060624/0326cd1d-7e9aa882-9fa3c528-e5a68107-db648c54.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10512303/s54101781/1c1af751-bb34ab8b-f87d5d43-6acf3974-f78fb6fc.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10793648/s59992821/4d2261d2-ea35b771-4c444625-ff5ec459-e8630225.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s58113442/3e7f3aa2-ca26dae3-c544c6d4-40f9e440-d39b0215.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10948510/s58893354/4298f9db-3a432187-64b73070-2a2bbd25-89a1e653.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10147617/s57642139/3e4cbe28-cd788d2e-417501bb-560b9489-4ead4037.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10351166/s53373644/0f9db700-33529f2a-fb3c8a52-ee20bc00-6975d0af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s55014952/1a4eebb4-5f14f61d-645d1efa-fea0321c-248b4d2e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10904848/s53913122/07515550-14af81c0-806f3f68-f59c3ffa-114de6b0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10668602/s50285685/32ed5d66-94608a96-b7484c3e-e5e7e1e2-42e9e354.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10417160/s52846151/303611e2-4cf1ca7a-b13c7427-6b74d766-e31234bf.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10866763/s55642969/6252974f-932d03bd-2bf0b9d3-df44540c-5d3f49d0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10441044/s51018961/31c3f743-94c6e881-b1df7101-4cfc0219-748cdba4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10490202/s53207793/36a8ff8b-be622816-dcc0c794-e85c285d-9fde04b4.jpg





Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10466167/s56157336/63c09ff1-7cae5eeb-a2231e4f-b62e0028-3fb27199.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10095982/s52132160/29c358b2-93a017c2-41071274-5ebe0de7-25ab9974.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10554112/s57066627/2c730827-44d342a9-c97365c1-441b894a-a6038f9e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10172240/s55641238/5a3e28b1-42108a17-b7a53d97-c12d68e6-a7152976.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10977414/s54963862/446c9f7c-246424fb-63500a9e-c37d4aeb-07352111.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10577868/s59056356/120f452b-65fb787e-b66fc8a3-5214a74e-278158ec.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10435823/s54756182/457f6ba7-1f5c049f-40df5923-cc6a38d3-54ff80d4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10650522/s53787562/2082f0b0-88d56722-ee120818-9866ed19-de62b4c4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10803114/s53287973/24dcc6bd-268da180-8371ae76-64cd7bcd-550a8701.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10624843/s57969834/51feed6a-d9ff97da-4e106925-d11e2fa6-3c5cf4a4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10328573/s54778414/0ae1a7ad-fcc627aa-01e96e50-cb14cf17-23f441ac.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10275579/s52499441/644fbda5-196983de-2077dcd4-b4f7ecde-174a8a47.jpg

  2%|▏         | 19/1047 [00:00<00:32, 31.97it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10188275/s52911598/10ae218c-cc3f8883-fabc5ac3-6252e96f-41c032b9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10246275/s59914700/4d3d3d2a-53c8ce4c-3940dd57-cb57feba-9beee786.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10318893/s53044529/5f29d6bb-248e1d85-6a3f5a8f-9db5637a-b61f0c65.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s52438407/2ff2bbb8-3bbe2db5-c29ac461-306d90b8-d8bbf319.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10884708/s55751585/29929685-ae7731db-33f9f7e2-2eed3f1e-51aa9261.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10298415/s51668044/2243dcc8-870394ed-f971bc66-4da12c92-2623af89.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10045929/s54575275/1f890421-32642e36-29feffc2-aaf443e0-39fae6f7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10199945/s50033741/22030fdb-741021b2-c55d8f08-afccdc9b-15982c91.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10232271/s52254755/5824d6dc-87272d1b-07553a8c-d5c200bf-2cefb0c6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10441044/s50598066/53f79a03-85a92ab2-ead415a5-66f6be72-09b2b8e5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10605865/s53473566/60fc808c-ccf9e056-6e6a007c-6ef95ec7-efd26b60.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10335293/s56253889/03af0b26-34279b67-2c02a6c2-623a3be7-39804656.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10292574/s52107743/05cfa70c-bae80a26-8b294ba9-86716b29-7b719ea7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10225380/s53143902/5c0eefb4-12eff817-6a508fdf-40a92999-cac2aa61.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10920214/s50898584/1ac55331-81fe8e50-9c962cd1-8b461e56-60474f95.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10335293/s59059360/1ece5595-380cb070-4bad0fcd-8bedb639-c584cc2b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s50535293/4e25d1df-a2939401-d79bfcd9-bc4f0283-43ffc8c5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10546701/s55595129/4fed7c61-7907de34-0de6c2e0-3be4a53b-4d3c94ed.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10065383/s55304894/530aa547-c1da4a37-6ae80cd5-d6f0773b-f7500b76.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10421528/s55558761/55057442-b16448c1-a2c956d2-506032ab-0cae121d.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10136781/s51621886/649af982-e3af4e3a-75013d30-cdc71514-a34738fd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10935371/s55612091/1c9e6619-dd867388-03bc56ee-5262ce09-6fee1070.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s53545970/6960e5e8-3c7c8e6a-d951d989-fe3aad0c-cb7407fe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10877472/s55385722/5e2875ed-5af98374-1b280d32-f5b441c9-75a1ee17.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10804721/s55738096/40be4f75-1c002ae8-afd2c557-b82560ce-c2a73cdb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10580961/s54177976/08af9164-608d1c19-064dad02-e8f32e34-389f49ba.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10476869/s50383756/3aa8113c-4d7c7495-62bd08b7-f5932075-054e1a50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10180419/s50955532/20350a0c-ec8bfc21-78eb4e6d-11a1a159-b8319ebc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10081869/s50580744/23ba64f7-520da4fc-48f5b55c-47b0c7df-c282d8e7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10391104/s58854836/162d2bf5-33cd24de-412fbfa8-b79204a1-ba67892d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10129119/s52861649/236e2059-92473066-56a87bf8-2cd4bb00-e17ff7a8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10678335/s52948435/64bc78a7-c1fce9c4-56048db9-6d3c57cf-8b749525.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10129119/s55184478/1d28593d-114cd53b-8749ea10-63e21680-d211f49c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10610928/s50810427/1784a616-39b6ab34-c303266c-b4218d16-d4049a6f.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10919671/s50881250/25767946-75a7af8b-4d87ff61-b3b5d790-0d6afd5f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10476869/s59527010/15121178-e63e820e-da95905a-6bee3266-9f834ca5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10501066/s53642253/47424716-029a30a2-741447c7-dfeb69d9-66a4ec94.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10790860/s57102448/1aea61ab-276cb4ee-fdf25c7f-2a50a1e2-cb2b5d88.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10224171/s55518255/0dae5d02-693e18cf-b1cb0d3e-f1e766b5-7693cfd6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10557919/s57040996/0ef420a4-7f73b19a-2b43ee81-f8f3e1ed-d94b9a27.jpg





Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10907112/s58594719/2503270c-7043215f-2287ad6a-5eee56de-2c8b53e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10350928/s59854957/2ffb00ee-7e6e8162-ea10e2d6-775a8c0b-2740a4fe.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10799662/s50842144/15a4f2f7-a3735212-45117eeb-1ad9f3e2-e6dfd89c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10421528/s52428780/5f282dc1-be6f49d6-feb54a00-ad6148ae-9092fb5a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10025647/s51297617/4ae3fc58-4d0f0150-48c3e754-998072f8-634033c6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10453519/s52152690/12c002ef-56642f8b-6f1ad349-3da1d7e9-e89e2ba9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10860165/s56095885/48b0e32b-2398c54b-cc497c43-12b34ebc-cd840da6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10830115/s53495917/10ba73b4-c80e414a-427cc607-d87459a2-1014585d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10043139/s51632240/350a19d2-7329f60d-17416b9a-d6eca016-187e6876.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10996599/s55911944/1f93b086-0ee29257-270dff14-0fbac1ab-d5a8edfe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10245082/s55438683/24d2c2c6-e4726d3f-b0dbec5f-e9cc089b-48540d67.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10688315/s55531229/5b7f04a9-93c18f0b-1299899f-7f66f704-52f1b321.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10129119/s56831701/20d79687-37a0f0ad-967a05fa-66731b2d-66975264.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10437175/s54595343/5fc45545-84200c31-e3cac93d-ad677ff2-3f4f30fb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10058575/s53122863/10efde27-48a44d55-7556837b-355abeb1-7ba9ca97.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10643827/s59867585/1f939bd2-3e24d39b-1ec772f3-70dfd2b5-179a8585.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10860165/s58020294/4a79d632-0a0b2a09-1dce8265-ec57e422-2d0a1940.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10147617/s57844401/1cbbc3bb-d73918dc-73c6ee64-27309278-4ddad091.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10238167/s57032261/4a0d8472-88315a59-85ec7269-c8bd123e-94d8c085.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10258162/s51216700/692b4033-d2503bbd-71f263e7-f8834773-32baddb3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10065383/s53295124/331145d6-d982c8c1-772c4dac-f0da5016-52726c05.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10773739/s56346242/1ded0fc6-dc59870e-c054eea2-5b6cceee-6151983d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10286475/s52005402/43fd797e-a37c21e7-c005cf50-44307d95-66496607.jpg

  9%|▉         | 98/1047 [00:01<00:06, 141.01it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10336114/s56658784/26c9b77f-358d12ca-c2aa6c5b-b46bc57c-94385d14.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10685081/s52802097/1872851a-b65e1420-c46fa051-83f339e6-5d5d5ed4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10695678/s51393152/1f954a79-711f4d6c-40e7cf54-7ffb2c71-a12fdc8c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10410641/s59980986/380fda55-d2283afd-511dcad7-803d3b6a-ed8c6b64.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10175711/s58594275/2140c6bf-91e0254a-280ea10f-0586ccbe-dc259661.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10207354/s50800227/19852806-2ceda70c-5a28d2ba-91d0166c-c9650251.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10269246/s51588704/303d478d-52ca0cc7-3c7bd3b6-18ac0372-98de794e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10533554/s53071657/4fc4e2e7-12cc2732-82a80d7e-87e98697-8cb6bb06.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10209431/s50872013/078257e1-ad7b92c9-ed39606b-6f8c7787-d6e77290.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10803114/s50512608/49910657-1f377f22-5cc20631-adab4e1a-1debb4b0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10860165/s51185175/5fce7dfc-f199a154-a9e2f420-6507ffce-80fc3960.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10270108/s50073778/235d293b-833b0b81-e451ab61-45f26757-d58f2712.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10129815/s52901287/33091813-ce951c7b-f1814061-b9779882-29096a0d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10293407/s54999484/30ccaeb3-f5749560-4d7e8db0-2d79915e-25ef7358.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10012261/s58270659/2f5e274a-749f1c06-1c8be147-4fabf575-e333e808.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10268877/s57765703/2f8ca5e2-5a1e02ab-e84f7547-069743e9-0f08d9e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10287750/s52768515/23b6b813-151e8257-4a9c8ee6-09ec3aa6-c4deb247.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10421528/s52206344/14780823-690f850c-df8d355d-d88cfbb4-07f45e4f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10425960/s57092941/2b53929a-a2b4dae5-c4a9e18b-684545c2-adee4022.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10671457/s55068814/11d4409a-7dac36e0-30dacbd0-f4347e17-ca7e55c7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10109555/s56241563/36c7d1d7-51b0b4fc-35315f26-b521e8ce-27aba583.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10617964/s57356945/003eb04a-a4c5a1b6-06dba045-c2fa72ed-2cfa45ad.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10043321/s59164130/24576d55-4cdc4874-729ddeaa-15966dc3-5ba0789b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10920214/s53822561/295007ec-7a1a53bf-5d7aa346-98ef226f-bcf8a5ef.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10922531/s57274865/01d34b98-eb9d27cc-7326a6dc-859ab94f-ccbd7f18.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s54587510/0318ea6e-c09b62d8-69f2142e-7d741614-7b4a5eb0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10688315/s50712523/4b4f6f09-28feab4f-05449b0c-661cf45a-1fd7ef5a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10580148/s54430109/1238700b-a474fdc8-45cbc4ed-645be4c6-37e5c7fc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s54569056/167bfa4f-ff65ca7b-83a2e6dd-73ed4d62-c091ad56.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10157674/s50660715/20f1cd1b-36133a90-d2cdd6bb-943610a8-bfb869cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10490439/s54474986/2923c931-9c084586-7402cb34-f8cdc68f-5656980b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10180419/s57292133/2b8b41e5-e23c44db-d8030f96-d8fb5c37-6ea47431.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10382575/s58727188/29fcd58c-3c7ed878-848c95c8-1e5f90e3-eac9e22e.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s59780252/4f4ed242-b8dbadb1-8f7e2378-1ecd6192-a2ba3603.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10103318/s57408307/64fd2721-0a573e13-a92988c5-45f65441-4096aeeb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s55614336/4e0bbb78-42ff83bb-e50691e3-f16f9524-7def2cbb.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10336423/s55039102/177efe74-1a8ce0f7-cf2ef3d9-e58955ab-a12850b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10330990/s56307141/0c759487-e5ff61e5-a92e73d3-08506c5b-8ff2b085.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10277852/s53356197/33dc9098-a2de042b-9e5d3472-98ce0af2-f0a8147a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10336114/s51313454/2c1575a0-23e91a91-eb5e883a-0cea63f7-ff5df5ca.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s56366597/0bb30f28-4a6a569c-f5ff5797-7bc2ff00-6c182658.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10111325/s52572230/0e6912e6-00cf6c4d-9f61c4b7-673fb9af-764b3432.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10650522/s50046711/69518d6a-a5a0954a-1b4366f2-26e264a8-a290b5fc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10537484/s59103871/42b55c55-d0d4e2c8-20df90f2-2f95a755-666da300.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10048451/s53489305/4b7f7a4c-18c39245-53724c25-06878595-7e41bb94.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s54369732/3f8495f1-89e8493b-e2157051-21745438-72ccf6e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10070928/s56508815/0b95db03-1a1d16a5-4d99e880-495f11f2-c9e0ba94.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10815532/s59884101/2159c0b5-6e08ed9c-9c77a410-f34aa8e4-108bfc2d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10301609/s53426639/6569beb9-0ac9ec46-a2882534-82d685a4-2711a668.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10594556/s56138591/431f8d29-813a8b48-aad9f667-f2edaf0e-10c26e3b.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10573359/s58767157/1b22bc9c-9ae19bec-36382456-f896e9d1-8ddb865c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10441044/s50287757/44aa97f1-0ef2d266-8c0f3c7d-c3d33c38-36619b2f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10204908/s56849267/4238c9c4-9ef05408-3d52fed8-de18991d-591f12ad.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10065383/s54059506/0dca7720-300a8209-f74117f4-6df513ec-df54b630.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10469621/s56786891/04e10148-c36f7afb-d0aaf964-152d8a5d-a02ab550.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10146602/s51154665/3d4e6fef-70941314-2926c04f-6a249d1c-77724d90.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10099869/s57908246/30134f6b-0b9cb4a2-aa18e5e3-ff619ccb-169b8d6b.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10395166/s59367648/146df8f2-587b432d-3151e370-fcba82ce-23b7e6ff.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10440642/s56383128/39c96b9b-db2e0a13-fca40210-d9b92472-4ec034c0.jpg

 16%|█▋        | 171/1047 [00:01<00:04, 213.81it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10471469/s56327935/07f42b6a-5bd971d0-ba230fee-4149bfd3-c9d2a718.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10204908/s51791511/5d9735fb-282f0b43-3cb54e78-0e785de3-f91d81d1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10122589/s59846275/38024539-fc96a132-ae469f40-dc9b4ce3-d21ccf05.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10965904/s57884330/46bbdecb-073e5261-a12500c8-5a4d0fcd-d6cf0f7f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10667727/s52481976/2f22b153-f24ed6db-360ecabd-dcae4df5-7abbaeb9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10157256/s54754996/51dc3706-f3a2e0b2-942e9cdb-d8504713-c9c77a55.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10518021/s57680832/1df86c06-9d82c50d-cabd4706-272b077e-6883c9aa.jpg





Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s58928697/02b34cf1-7523ff12-277d2754-55c0c774-65c5bf50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10227823/s58583372/070f9a48-638b423f-463500a2-5163d22e-0095c10b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10204908/s58622528/1f05a882-412f2ce1-0943e8a2-b1ca475f-e2e8fe0e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10161112/s53763289/584f18ec-1c6605a8-5ea3aa51-0db860d3-1bd8d908.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10014729/s52359357/5f090a4b-dc8a796d-726db5a0-62f19c9f-58cccd6f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10113898/s57086922/3fd03b1f-425d6961-6418b831-04057265-2ce261b2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10026255/s55384601/238ce890-bbec475f-c82ec6bb-7080bd2f-c4b471f1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10402135/s58230532/226d3cc7-a5b83731-b756ef4e-37afd118-cf5ea84e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s53255026/42832aef-62f47609-8de1ffd4-8b89b0b2-2da8cae2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10191980/s59883063/35f2baec-b8d54f53-a532d8d6-726ce8aa-cacc7bbf.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10907112/s50676962/5629f932-8b989b64-96313648-ebe91d69-2eac94d1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10141364/s50909732/518c2f56-2744cbbd-fc63b56f-d29bf82c-f169b7ec.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10045929/s58067291/159c845f-1a6c33f4-ccaf0c51-eaf492a6-d43f603b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s50106781/57334e76-0fad3701-e04c6411-aed6e95e-1ec79017.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10677118/s53811610/1a97ff9b-a334ac83-ed07814e-bcab8363-9b1d04bd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10432862/s50608079/3eb2c7f8-1c178075-437d2500-02dbf9a2-c8d83b59.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10251714/s51280690/2468ebd9-40397438-697c7ff8-f86b7085-b34c2c8f.jpg





Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10483304/s50076705/4a050186-c6320c70-b83046e2-f2c1f2b6-85c0f190.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10176514/s52975359/41328d79-ea626b7b-06cd5825-0c074389-484b2eb6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10589569/s50985069/1119a0b0-a09b1fbc-6720882c-976e6ad7-31bb4a75.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10019777/s57883142/44712083-6ebbda14-6e11adaf-578d786c-b736804f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10167784/s51240614/51d2a2d2-6ae66ee2-c1633291-05a5a8e4-823dd257.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10115397/s58152455/04225687-dc6f69d1-8ff76315-e34a93af-7b125604.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10432862/s51891483/0d28a215-5938c04a-e905e500-5444641b-2979a8ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10103318/s57848443/006078e7-ccc78819-247245df-4cb6d404-2c081561.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s59607416/35f060f6-ed5f5989-f3b6f309-d0d8dd67-f5e05049.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10286521/s53966149/4a2355ca-1d9306c3-77a15170-90474ce4-4c0968e1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10270108/s55506142/209e814c-6fd84f44-e881959b-12e210e5-32c61496.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10438089/s53822965/64681b59-6717affc-71292c17-3d5f1699-314e8f75.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10157256/s51815028/052bc196-c7b17e16-16916681-2f8bad23-d272e534.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10272120/s54794754/28d73927-950fecef-37125e29-63cf1e59-b588f442.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10532853/s55408365/597d55a7-61254943-ee8dfb3b-263896c0-dafec889.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10231735/s59167452/136cf649-269df46d-ad22528f-14c635cd-c4c9fb04.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10395166/s58677395/5faeaad3-f5a85682-089e4f9c-2804eaff-1495c607.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10263569/s59599838/2fb46fda-1f6dcd64-c0ec9e27-8fad388d-6c4b6d31.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10803114/s56530218/2bbed805-9edabe38-d0476a90-21720847-53aa7ab7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10533970/s55986309/366732ea-66b20dca-ce7c0fcc-f783ca4a-d05fa190.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10421528/s53391789/58703df1-05a250a8-7a4e7433-e796b0fc-87339d8c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10992229/s52029682/28f399a4-3fa364c7-9dcc6590-7bd05025-7b042086.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10441044/s53779858/09c15a78-ba10e444-d4031895-3c392b15-80e84c47.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10314749/s56062486/141aef44-70c16b9e-a1b1a01c-04cddd6f-419ddf07.jpg

 22%|██▏       | 226/1047 [00:01<00:03, 260.94it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10781581/s55504777/34358051-90d3b204-0a1ae11d-82dc2233-35bfb041.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10216556/s58133454/2f1c35dd-87dba75e-8e130c33-fa4599a2-b2e62843.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10296472/s55541245/3eeae468-58573d18-cfbc19d6-dfa2a900-7504dd2a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10150465/s51024959/00bdf373-5448ddab-2f092dd1-387d629c-0f800bfb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10163947/s59905689/1d0b2e6b-f196d62b-1a0aaf92-522983bf-a7d909a8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10161682/s57893492/6941cfe3-b31106cd-b5a9f1af-7871ab45-41254812.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10627407/s52677954/5ab9fa8d-e7935ba0-bc4b24d3-7d43c53e-429746b9.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10550799/s51294166/021cf26b-cd5779dd-8a839d8a-92ede30b-41c1f997.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10922531/s58251965/49ae9014-9f93c2ce-4800343e-612fea9e-d2f20449.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s51730342/59addcc6-ab62b0a4-1f395fe1-9217e431-06c3ab63.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10314359/s57592795/07dbb821-ab4f47ba-0b907549-7f7d716f-2c687f5b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10920214/s52101493/1ddb9d27-17bd3d10-8a9c9e8f-a34c870a-7a0f3f91.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10597833/s52755775/4420f8fc-f70a40c0-42809676-72040d55-6f3d7c67.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10014729/s52149569/0f768188-ace0476b-e815f596-4bcca8f6-f6614985.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10919671/s57354094/3886bc27-33aaf43f-0c2dcec3-3942bb09-3b7cc150.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10388009/s58203625/579aa963-68bf9738-656afe52-4588c247-a4a60642.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10623425/s51875181/5da15491-389464db-4c8172ca-55a0b1b2-2459a2be.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10286521/s52316121/0cc0d181-b0d47230-4802a1c0-07c6a7f9-642cd78a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10065383/s53525291/66803d25-8cd70ad7-5c433c69-ed2f0f5b-f136a8e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10432862/s55597223/0627c853-011ae393-e68b5a95-13bf75f5-17b5cefd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10659469/s59291632/4a9bea1f-2f8bbfe5-baf3b3eb-a4509768-72dd18d8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10361930/s59928548/3aa9ee81-08355b5d-713a3a03-6cd20281-6222326c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10263098/s56588602/65d29dde-c462d971-ff0bd2e0-22fd4583-57b9987b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10385501/s58104387/56b367b6-4fa4db91-244562ae-56f8c64e-4324d3e0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10108709/s57571205/67564162-2ee01995-9407f467-9e3b22b4-b2afe785.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10045929/s59828529/179be083-f2a68e52-e3880292-9233815b-9d68c738.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10507647/s56026633/63bf26b3-1ee8df77-08eef46f-d7514a82-905448a8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10216556/s52221900/64f19f01-c2b1f96f-b032366d-3c9b3e21-6a7ea5cc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10388400/s51883602/0dcec620-f207f178-08fc674e-f7355c5a-c462af37.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10922531/s50760076/007d334a-04a690df-57c10e6b-cc5fabb7-6bb04064.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11005736/s52195959/f18e6c73-1fb3d2e5-5ed214ad-3ddd23e9-afd310a5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10002428/s55758034/3bea0373-0d10dd77-1cac5b90-651be924-d343b184.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10688397/s59570530/e4205ed1-41507ca5-83414da4-595ab008-f7fb085f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10918768/s53306579/5a9fd3c3-74d161f2-20df15e4-d8413b35-b7f4afab.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10099869/s53490649/51b87aea-067e060a-6bd1abed-1eac7ee7-e030a9bb.jpg

 25%|██▍       | 259/1047 [00:01<00:03, 258.29it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12176298/s52954842/eeedc8ef-a2ac3f2b-db1cd3f4-6ab2922e-ae93a7f8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11569093/s56084617/68a9dec9-436c84d0-572f0df9-18929544-6b237d3b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13011941/s59136181/ce87b712-09821ad7-7428454c-ea4bad5d-39bde641.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14151932/s57101194/5a07536a-1f270441-c2c2c379-95579922-dc92991e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11208075/s51644616/c77dfa1d-d518e62b-677c25b1-0e3eebf5-e21cad79.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10268877/s54137212/e279d10a-22b3d14a-0527c87a-bbd31c9b-de232422.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10051043/s52582060/6e0ed7cc-d3b1ee12-2f391e3b-52e3fb69-e45d0cf1.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10501511/s56192491/9b398dc4-d359553d-6d17aeed-08b6e93a-50240bc3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12051412/s58962528/ab81cb15-8a50ec62-52d9f51b-5c39c81d-76de7931.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13871390/s54956630/5be69cb1-f4316166-04046b14-d56dd3e8-c74a8110.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13130441/s51064714/816988b6-f2c33f81-3e6f44f0-8ad131a8-c1749797.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11022245/s58274962/f7ba6691-53545537-20c8b2dc-79dbd392-36f05d15.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10454455/s54038361/9a0503f8-52f28e1f-f008b6dc-8ec7af69-6b931726.jpg

 28%|██▊       | 290/1047 [00:01<00:03, 199.98it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11062918/s53899404/37c4b068-a75c3e99-66c18395-6696e401-092c6ac5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14214357/s52823880/ee630a1e-5e278957-508042dc-0a344ee2-f43b2838.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14065514/s50052981/8726c74a-245ab051-430f078d-b0c78c3e-7f0d714e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10762976/s52676311/f82e5b39-72418607-0cbe5bbe-0a9f5a97-523be460.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10717732/s51379169/230523a5-da6cc3d3-c905304a-66c3430a-a7e9cbce.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15928453/s52328145/c436cddb-4126f15e-59c0733c-34b5a4b5-bbda7ffd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16410756/s55123722/96f8655a-86e19a19-aa7e5622-f65b7fea-a2fa8bbe.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16576751/s59287191/ee4c2cb9-e878526b-3c9125f5-30b36301-497e0e4f.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18696483/s55431902/12d6a4d7-d595e0b8-c2e2318b-a17d87d4-aae230d9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14387068/s56469870/92666ac1-70ccc2f3-66bc3d47-ed08bd0e-d444a359.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14387068/s51664945/9196cf10-d7be030b-9eb57d37-e9f760c5-b583cca5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15617050/s54109745/47a183a1-dbf096f1-46578cdf-ba8952e9-3da89a61.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14387068/s54023727/d395c594-96025cff-7e6af4ad-ca08ac10-032bd500.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16043240/s53861171/a0c83599-da2ea7b7-03944f49-45a6b253-31fa3b34.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16784759/s51956495/d5b2f589-804a20cc-021baf24-799275f2-c39b6255.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17114146/s55670691/c5a5291e-345df52a-8260a936-62410186-4edb49bd.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16744975/s57554599/fae374ab-af787a3c-743533fd-d86dc18f-9369e8bd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18699864/s52598516/70545b3d-8a18050a-bc68b563-5dd2538f-cb601e79.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18727840/s56183111/3c1c6ac7-2237a2c6-c72ccbcc-cb075b9f-9c469bae.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17343613/s50130312/887776b5-5bba279e-cf6a5f4a-7388d4e9-ea0858bd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17927113/s59181430/8c267545-97e8e070-9f9a831b-ab6890ca-6b3162da.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18036188/s52385577/937bac70-10bf0f5d-e1527c6a-72b06373-b6398027.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17032041/s59517245/de9e5878-3ced9712-89ddc2da-fcc92482-502d7fb4.jpg

 33%|███▎      | 350/1047 [00:01<00:02, 250.74it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12532356/s54218174/a5d3aa8b-573aa054-cb848da6-184d98fa-539aecf3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11733904/s57047836/c56f72b9-e424764c-c6dad295-7304e057-95835ab8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11665626/s58718017/c75d44a3-9721af75-c6c723d7-54bc997d-65b06f50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12493668/s56343563/ac31142c-465c4d4f-acef8287-aa0b5b9c-2f42b25f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11937809/s50791204/c470905d-211ebc24-980a3992-97a56218-ccfff459.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14048212/s55313405/28908e09-dd70a21f-7fe23a32-9c66030b-076cf12b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19743788/s59738058/a3e91cd3-dbcbe6bc-085ce21d-77743afd-f2671a51.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11226141/s54346060/bcc3f4e4-b738eb07-3ec62576-98d963f8-d96610f5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18867724/s51055214/9a16c5f7-7ba13838-cb2108b1-8447237f-9a2aba45.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19607507/s56576576/cf1789f0-bf1fd4fe-50020b83-e4fd4719-965afa7a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13559413/s54604413/5f0f3578-07a15ffd-fc4acfcb-c5cf77c1-3250e9c6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13964474/s56999137/171e85cb-282b0f3f-e2cb30e8-b7aaa1ca-3e4422d5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16508811/s58890549/ee316aaf-4836b322-7a19300e-e45cd9fd-b0399146.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14527555/s59928268/a258c428-7cdc757d-54a99005-96796826-bb3199e3.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13964474/s50909414/22f15611-56e81b77-6ec98f91-5d740640-14d8260c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13684752/s55703639/7ed70855-df0444dd-a76a7e37-489b2b4c-6ac4004e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13648483/s53691511/60148dd1-1dfa9c94-4aca88eb-4fac3fe3-8019413b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14886080/s52774958/86edb3cf-4bc2fe40-3f2ac1d4-a5aa44f9-89f0f343.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15680945/s55742152/ca9c4c3e-f88fdfef-3f1be3e9-713980e8-c4286d4c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19991135/s54910031/d04bbcbd-5143439e-50ebe9a8-71380f67-44f8d127.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11625962/s50010465/9bc8e859-6b4a06ac-13b45157-af7847ca-db49eaa1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18574585/s50486781/ae91431f-db70a388-3f5f2a99-3de56e9b-ae0f2119.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19257413/s50052884/8ddcee53-7657a1a5-5926e9f8-58c57835-aeb610b4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13964474/s55513654/634557d1-cf60366d-474c0152-9a7b5559-72f0bc1e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13593993/s53855796/d472582e-b387a6f0-2792667a-4941f665-ca52eb2f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16143265/s52661177/8e4cf852-0d3c4827-7c70edfa-962066fc-e24914a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12593920/s57495887/543ddf75-b40274a0-27806ef2-e0231e20-9a290d39.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16490541/s55862467/19ad291e-2093eaaa-b0881d58-f7359e05-6961e3e8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14756130/s59343343/d47c83a1-7edbe949-34368e0c-b6614f10-3e10f368.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11390883/s55418524/a031c2fa-fd3b348b-d7c45dab-96ec2f33-d607a7bf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13964474/s52510673/4d85d642-5e8316ad-ceed42bd-9bd4615a-20c66bf0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13263843/s54651626/b87403e9-8463e40a-a104367f-cb96ab7e-b13e08a2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16180572/s54524068/25d70f01-7e7927a3-892438ba-dfc840a3-59fd316e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15773840/s50665023/4cf8d6a1-c5fe806c-06d3ab76-e2616288-45ecf24e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14851532/s55167068/8137d98b-e8a60482-a158cc07-096a8d02-978fa0cc.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15455844/s57630926/5e60b8d3-cc5b0d12-5ab64da0-69b1b020-832beda0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13875890/s53047820/7652ec4d-d7c950cb-be26e33f-7b5768d4-933eaa97.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15606311/s56119310/d9713fc1-d6c8fba0-06e285a9-ee681ef1-498ddf13.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12423759/s53349935/b8c7a778-2f7f712d-5c598645-6aeebbb3-66ffbcc7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15811456/s56371125/a377960e-1665d336-c57bc69a-423714c7-14a9bc28.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12870544/s50074708/4037e95b-93ffbb99-fd878e5e-a54e0f1a-9d890e74.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12411448/s59084308/e5b223bb-a292aa14-d74cb307-545550bf-05bd073d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16662316/s50074184/49d47140-69d47642-b0184b0e-7faf527c-d9edb9ef.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13150311/s59191122/f717a475-b500ef37-d179a27e-ad501557-08129dc5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16855430/s55801123/6de51358-d77c44f7-19d5cd49-0d32b6fa-15f71ae5.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16735911/s50138272/60438f8f-f9c8e51d-67711019-cbaaad27-b9a5f299.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14387068/s58601585/027ed427-b023757e-7391ee80-7a5da2fb-b3ae0b4e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13251286/s59318787/8350f725-7918f8aa-abc95fec-a3d62a15-a47db0d9.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14443991/s57369379/53588137-69f5216f-022b1177-b7ed05ef-9a670fd8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15419510/s51288835/5ae25c72-34cb9d49-a4da40d2-b675e012-73e45602.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16544722/s59467020/e146fe5a-8b20498c-b5cd2dfe-bf0d6228-6e74d514.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16751749/s59245308/bcf2cc18-3401053b-113ae6db-daa24d50-08934ad9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17453200/s55480559/e1a1e5b6-0dad0754-37c2ece5-f8692ab5-36767700.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17326223/s57811038/fb84939c-f1c2d08f-d036fecc-b02bb05f-d696334b.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17520318/s52984010/0ac8f355-58fc87a7-70dbe5d1-82d96f7e-d57316a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17640354/s58068780/93fd0d8c-16753965-aa889bef-8b7b90f4-63dea004.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17770657/s53231312/e21e6bf0-7434a403-cec6f190-febf1e0a-d1b58336.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16270775/s56277157/1d43a894-5ef3cf1c-ebf3bc9d-5291db2e-40307726.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15185305/s52381727/2b387f17-5b587878-eab57bc7-959a3a13-68001f85.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17735780/s51828437/86824ae8-47aca95a-11895fbb-657cbb87-6876fbee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16751749/s57787040/3d1d93b1-6b91fadd-c1b40a43-382aef3b-639c3488.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18070827/s55818479/31787733-0d0c11e6-80b6fc88-7243ef83-56f58a97.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18096934/s57896500/f7254b7d-1a32be23-2b58d468-1d80dc7e-736286d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17991372/s53324431/f8b5a751-a6bf778f-e266405d-f51fe5e0-45a0b8a5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17112351/s58374430/9da0108c-13514e2c-3899c199-d1b3424f-3eaf754a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18307935/s51175521/1d54e0fa-5dfb8edf-f8b67f0a-c29e017c-f5e2ff6f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17206933/s57571408/42ca3426-3c2dc573-7e2d42fe-aa2b9627-d888b47b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17509177/s55209403/bba8ed6b-66f78a53-425c5109-51456d04-09ceff4f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18341991/s56421788/2c84c825-2889fd51-2e46959d-586c6113-74033204.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18508091/s58480659/145b4dc1-8dbb973b-9e23119e-a8c272c8-962f2c4a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10310992/s59119274/45c08046-13fc49a5-baabf910-c74237e4-9d4c3a54.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19016834/s53124891/cd63e875-f4edd5c0-6b3cb2eb-aa774713-24cec640.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18596190/s52057436/effcab7d-e2f9a960-9d614f9f-a38f2e7b-c2b3a23c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18939639/s54297784/0803ec93-3826d0a6-2a1d0987-d9dea835-1c556749.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10920105/s55281558/267cc457-a4573bd8-2f401d19-1257fb65-04115df7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10620406/s50208060/f7216f70-ea0d379f-f2d9028e-817459ef-f8357a3e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10500792/s52823815/2e0e4c28-77275236-9695b5f1-bedff2d6-f816e6f7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10348831/s54040054/412226a0-fe97f725-576b21f8-3d8d4fd3-ea7cfa4a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10950205/s59076233/68818a69-aa452dad-990777ed-149d3a35-853a56df.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19033014/s57288740/c36b30f4-1d299116-9356da7b-9322febc-e879f28d.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11022245/s57732352/7c113cab-8f9bee61-2b8ef272-d3fb769c-21b9dd1c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10975446/s50572011/d25f054a-e8199cdc-c669cb2e-ebcfb082-54c205b7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11122975/s51433149/320f9022-bd20ed21-b786e599-db45cfdd-f102a453.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17735940/s52020286/c34dfe2b-d14c687c-630f5559-64f62309-7c1a41f6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19185965/s58878711/4e488ff8-f2a8fd4d-8b1eea83-9b8be0b1-8efce8ba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19542943/s53647422/949fb11c-506def51-4806af01-24d8693f-2f90ea60.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19757720/s59572378/13255e1f-91b7b172-02baaeee-340ec493-0e531681.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18567979/s52363317/8bfe0461-6d1010d0-01f5cc7b-9a74c4a7-a2bd6efb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19990821/s58744660/5719f0b1-60d0c52a-3b0adefc-05403503-323fe972.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19016834/s53515169/af20fb83-3a400800-9bd658e7-a793f80f-3762604f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19061282/s51863042/1c038d27-c6193e6a-d4588595-a78608bd-565e11fa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11413236/s52541396/46bdab14-1fa0233c-c0b0841d-4c0869de-6564ff0d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11666315/s55846009/ad6ca061-cd4f43aa-05bb1be0-ba7c2fbb-63ded903.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11594544/s55024513/08e51cae-edca79cd-73712013-7f37b98e-5563104d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11495809/s52705409/0295a5c7-982330bd-2203b511-4d052b0f-a43a5e17.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12927172/s59768980/fe873c2e-ce9b63c6-d57fd8b6-ae72aca2-79481b3c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11607453/s52606790/5335699d-de67abb4-a2143b68-30ca5a5d-f5410238.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12952223/s50551136/2ff42829-e2419fdc-267d447a-f0ece038-e2161c61.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12967247/s59159822/8dfd7437-485b1d7b-acb13339-631636e6-75711fe1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19680091/s59526794/a6f62f68-51689aa3-2c49f059-d1f61a23-b84def59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13045537/s59637018/f61542f6-7f179382-2536eaa6-7268d08d-e859cb95.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13415410/s55345925/c8186025-4c5d3f4c-6b055ff6-866156db-5498778d.jpg

 36%|███▋      | 380/1047 [00:02<00:07, 92.92it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14782385/s54491476/59b48569-10f6fc80-500fe094-39887309-bf64db95.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14443106/s56836380/78e763db-b5ee86ae-bc0ef22c-da34a3cb-80b76884.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14718365/s59269152/5024f775-51ab5259-a943877e-ebaa6afd-2ed9fe6d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14744884/s52630162/0619df15-9da411e1-9a47d1bf-973bbcf8-97f09ae0.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14841168/s56921440/d47b1887-47d16d76-fc1df56f-5a5cd514-a9f91c9e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14838068/s52155075/f566dd0d-3c17e49b-303a542d-2da83f87-8ed2062d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14809018/s52210037/678e6b7a-4d5e6c4e-317a9d16-b2822e94-b675e6e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14851532/s53685384/d3033719-9b507af8-6e6975ac-c32ea556-6f68613d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14939898/s58625661/d4f0d97c-72567146-ee0487ff-a3d1cc6f-78099694.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14916430/s52063498/e2338833-727a4d6b-814d43a1-4fefd674-4402c655.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14851532/s51078371/66e86adc-70548bf4-9981e744-42d0da07-838b4d2a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15110016/s55789161/3fa1566e-0957c0dd-ef142837-8de55f3e-2ce96431.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15131736/s54867671/6cd580d7-5ec74248-17b89c75-a4a99d48-97e58fe4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15131736/s51479309/879a6090-bc908584-faa34013-2ab152cc-c80f9feb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15144601/s51244891/ce4d53fc-3f17c875-c053c0b1-43ce1358-096e6002.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15317980/s59582472/c44360f0-77884b1c-2953cce6-ca29c90b-117fd1f1.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15259244/s58685714/ecc315d7-39f7e590-405c1a1f-5a8f026d-560ba339.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15189156/s54936089/3d6b3d6e-a5ba71ab-e5728380-ea398775-63f45adf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15192197/s54132210/26299e75-4c5376b5-b5de5201-d3167dfd-7d6ce8de.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15287015/s54608802/5298031f-ae73f5c0-09834d5b-f6443ec8-37177e92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15310905/s54903096/d0effd84-2747ab0a-d72f4900-db0f5ef7-8fd355ef.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15385925/s52283504/621226d3-8bd2caf6-946500a6-6fb80ebe-7bf7dc3e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15207316/s52767831/425d59af-b3a07390-48699ce4-edd9cf7d-3b4faafe.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15419510/s52189004/1b6cfbee-901f801d-651c11f8-2c84bb31-91883814.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15573773/s58181880/e54f3f70-6d5adcac-31b6316a-9db61d03-b0a58333.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15573773/s51172881/eed11bf1-ac4c5180-203633e7-392d562c-124e8c2d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15411028/s56053760/e9358a67-7aa99ec1-44e98efc-a9f02c43-f6aea5cf.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15657457/s58148344/30f62b64-c18d5fb6-49e670e0-093c8310-ca5d96b9.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15574754/s53673703/9ffd4904-fc2df6b7-4482f6d4-de063c6f-f7b28ad7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15612622/s53964812/77986392-2dac3752-b145c42b-2ba010de-d49de562.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15578020/s58632562/18077403-5c40e1b1-446ed621-e9aee033-8723348a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15656571/s52668819/8c33fa3a-721b673e-292363c6-9bef84d5-76b10d32.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15862493/s59398497/c337d8f4-4f4a2ccf-1f03b68f-8ee20146-4f889f3f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15881535/s56093476/210f9c01-9e0728bf-4b8ec9bf-34d1564e-16cf509c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16063753/s58544788/1457d199-0dc5bbec-d54aab5d-6a56be2d-b28f3920.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16151467/s57403629/6b968168-2b475025-5520f2c5-a374e929-1d037395.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15809646/s52573647/554fad67-08d3ea82-687b0b92-4825e624-b17ef914.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15840907/s57339166/38b3b47d-6984aed6-acb1ea60-2c93049b-1ccdfc91.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15857729/s52552967/9ce5a44f-66532667-66a23383-cbbb4b96-4a927036.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16086306/s56124209/7c6edd07-7c4c8c3e-d8b216c7-88d2d002-975f90e3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15765403/s56720361/7a28df15-9a9dfa2e-e829e842-81f1f7b3-201b4b4a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16280215/s54131365/bc1fa6bc-ab42145c-8b254fa4-7f57c637-2322310f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16290812/s58483917/05ba3e85-875eda0d-e635ab65-721ad62a-2ab3e9d5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16473192/s58917847/2658f70c-c9854394-3cd45c23-40826b83-e6bc3108.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16446532/s56927296/828be9ac-e28f0cb6-5f44466e-79e91ae4-c12158a2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16454913/s54486409/03eb61b2-a370310d-6620ac24-e2c25319-8300ef0a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16339049/s57550343/4d4f608f-c64ebef6-baf62802-b4ab4659-d427aef8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13475033/s56512741/f0efdf99-db7193c1-b47f4ffa-dd90a48e-2071134d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16486158/s50537653/2008aed3-8c01149b-4fa7b2eb-0af9445f-5d4cb6c6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16508811/s59842151/430e6100-bae3aa34-d72132a7-2c61b505-8d2056bb.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16690146/s56314674/cc48765d-c7afdd60-37cafc86-b2cc3c5d-f1b3e09b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16704490/s53727489/5aa5a6fb-d698ed8f-52192990-47e8d34a-55d2448d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16711795/s58768499/915c7be4-25562cef-46ee2f69-986e6f00-0054b400.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16863257/s53714723/937bc2b8-84f85471-4a0ba680-16f2c77f-112dc5c8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16826047/s51777321/8b71881c-c896b1ec-9e6c08d8-6f61075a-c98e7454.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16855430/s58324748/c8591b84-dfb9bd0c-54f0a9f4-e5258ccd-4fec4b57.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16901671/s58643678/219c2095-b6f293aa-4d1b7c09-eb0c8425-1fb61f2f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16855430/s58141048/f1b89b54-27c193cd-47878997-195a1a2f-9d7bbffb.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16948236/s56425788/c07c3ca3-b89aa91e-2c71f7ec-ec6ef208-a8a99d86.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16921793/s59886743/0af26892-361a6f8b-3291710f-436a475d-67a25beb.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17080143/s57007763/0256325b-599d7e3f-315c0911-45a20707-4921326c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16973455/s51434888/a7b1168b-df66b0ac-4483df51-735d9ef8-0eb00093.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17029854/s57547451/91b2414b-1efc64b6-d472d4bb-bf5700e8-1be0b8de.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17189198/s54003688/2247b067-ee0f755a-9ea52034-1cc6095d-1d4ea3df.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17532555/s51973242/a8caa425-eec0fc90-7a713f4c-e0019cab-b45a3a56.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13896515/s55597572/1f96d075-e46aa57f-d3aa1e67-42ce2b69-83381327.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17533213/s50508699/2c3ab1b6-b9c74b7f-d05aeeb6-13bcba65-2c7fe8b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13896515/s58678573/020b5099-d3d7ffdf-de17c3ce-3474f286-010786e6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17719188/s57480702/5fd33713-52cdbfd3-ee36fa8d-078d15f4-632780e8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17749188/s51478722/88bba186-6012ae56-6ca9ec6f-e2efcba1-c946757d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17782789/s50963331/aaa3dc03-dd29e871-949084ef-1486b951-e502b225.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17629294/s55492413/ac0ed4aa-2b6e53af-fa5703a4-fb959f5d-1df8dbcc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17536853/s53250619/fc110613-d25b1a1f-83965887-2a4807db-acae76fb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17261065/s56321064/7a1165df-fc1f2e7a-f901fa11-d73f3ee4-91abd6ae.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17582273/s53640940/7c3f6d1a-0447b992-51522bc2-3b65cadb-802823a5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17470135/s53934868/4f0479a8-03185ce7-14b86109-fce527ce-37acea35.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17478604/s55974954/034afc43-2fad16bb-0c7f7afd-78ac6a4f-b2a8e2e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17910612/s56566624/ff26aec5-d410ca6d-dfe531ed-91de766f-2b19efb9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17890530/s55291849/696f475c-ed224d78-23d1e42a-98b93bf8-ec57a197.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18101124/s57525714/01ac3a9c-cdd8e92f-0e80f3ee-327bb3c5-cce84554.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17973546/s53030097/0b033e50-32c12a92-a7d06e1e-65f6423f-fbb5f3cd.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17978572/s54678947/3faf82c7-6dbfeda0-5f59ab15-7cb775ad-a20533ac.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18230098/s53441079/1c9521c3-3d5127ce-f0c81526-2fa17a47-f49a967d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18224196/s52946760/c2bb8990-9789045a-070071f0-a817d725-cfb2472c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17978664/s52794641/1f6ff6ad-999c1585-cd4c316a-722dacb0-36e76651.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18087960/s59570639/8afc3991-7ec1912b-b24d9633-3c4b0f57-17c0e8f4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18316256/s57102827/14110629-6cb50b9f-35184b2f-efa91de3-49c0d97c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18222244/s50325750/494aeff6-5d986c6e-d99faba7-5cc88912-a84926e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18275181/s58008723/708d1a10-1fcc7686-542e01fd-a0bb7a55-171df99f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18278449/s50913025/1695b913-a4849cad-9bd590f7-3f67dde9-01379ee2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18454110/s54339247/c9638d78-27c2c0c8-24a4fe00-641be672-8eb21232.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18426683/s59612243/95423e8e-45dff550-563d3eba-b8bc94be-a87f5a1d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18659631/s59284918/af8f292e-eecbb702-9aeef1d2-46861e97-709d3307.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18460817/s51161819/bb2e444e-0ab44b4c-4e79e82f-58800395-9e8ed1bc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18641560/s59183641/fb00404b-3f5d94c3-93e725ea-0418bc53-39a4b259.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18568013/s52444162/e796eece-2ce49000-50b52602-70ff45e1-fce5325c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18487334/s57881979/ff8b2af5-e8c313a0-9caec8e9-f6a90929-3b53792a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18460230/s53225676/250bb626-f805c9f6-d82488e1-019d8362-ddb9eae6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18499001/s51275763/91d154a3-f3cd26fc-a7a22401-819876c1-e83f417e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18708770/s52379941/1390b0ae-1d811d95-96849a8b-78266070-9e4d752c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18512911/s58891549/4a07ec47-07219c0a-f144f691-b0625175-f58f47d0.jpg


 46%|████▌     | 481/1047 [00:03<00:05, 110.53it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19220379/s50172287/5840dcb5-d927aa9a-7c1e3474-ce2b18a7-8dbb0075.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19231238/s56136629/a70fe0f7-a3e8ba24-e3a2dd24-6e33352c-d63184f5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19255812/s54109373/8eb7739a-2b34e357-7ac2163c-9849dc45-dd79419f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10258162/s50234584/d828d1ad-eefdcfb9-4b91350b-0d8be73f-c6bbb750.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19291186/s53599304/5fc634bf-aa7f4234-ee9fa3e6-92b056ba-eb49cbff.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10267709/s55427191/31c7145a-bc952ff0-ad9037a8-6b884fbe-bc918022.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s59514256/7b8067b0-f458a483-41f10754-fbd5d3fd-63005b7a.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10402372/s50879902/09bcae55-47d8afaa-5cd21ca4-2cc83c46-d432bd6d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11045360/s51261011/8dff0bc3-9d11d2ac-bea0584a-24fda778-04114f6f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19302735/s51301706/db04dca1-062f1601-d3c19739-19c38abe-1e6936ec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10599327/s58488643/747fd9e0-d9b0eead-cd180cda-c544d95e-aae7bab7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10843678/s57146887/5abdb6a4-39bd107a-485108fe-e3e5ee96-46b0dcf7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16957952/s59610928/b5d3da06-fd20e016-8b1924e1-3ff9ceed-fb365036.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19396070/s50534773/37f7c8e5-528b11ed-1d10f5e2-121a7ec5-8ba2536f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19431075/s59836649/39de51da-c8f37b7b-20d63c0f-30144823-67e6acb7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19431075/s54223401/6d7c4296-157fc904-b6d6c70d-f3c54944-61ba51e2.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19508874/s55173947/61fa8614-aa1251bb-bdd10c50-dfc1aed8-3c0c580d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19731864/s57876331/a1e78eb5-72f569fd-f5c8c795-887b8a35-97d007e1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19753900/s52466746/3ed05664-05fce550-de490277-244f5eee-aac9f449.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19736038/s55236880/f15fa920-164dc599-6c373498-63bfe100-47e15f3d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19830694/s57272251/1c712da2-d8760888-e8cac04f-51da4234-a33d806c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19997367/s58801152/1bdf3180-0209f001-967acab6-0b811ea2-3c2e13eb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19879454/s52698197/41ad325a-6d408609-7c59fc9e-b3cda836-8c530739.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19845120/s54088476/6662f562-874d668a-17c5ece4-426fc021-d889ed61.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19975898/s58781773/3a5d63ba-30ddd666-f1f37606-f53c9f62-439d25a7.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11617451/s52355043/17173530-ecd74be6-e5f43436-4e94adac-0fdc8a69.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11638384/s59182998/ef1d261d-a4002d49-6ae5a6d7-f32f3ea8-8cbde6e8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11996533/s53687112/6d4b2436-1413b0ff-f9d646f0-e4f8c4cb-a333afcb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11771778/s55562243/8afe8a73-004dc473-b4775f04-0952fd66-39b22b99.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11840556/s57583652/63fdeee3-5aaec360-f0f0ca21-4d4dfd32-eff883b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12484308/s56655161/7c17f8c6-00e14ab0-5ec77692-208b5095-0f6e09f3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13205882/s52878743/b2861128-44f16a19-3b643243-d9c4e8b8-10aa2bc7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13231528/s58431224/1681ec86-c494eeb5-a3a0d50c-fe88b0ac-4d59d022.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13751863/s51365925/975001f1-aa6ac139-0411a210-a0ef87cc-4956e706.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14470386/s56879846/6d0c2dc0-2b387e77-6540826f-5ce156d9-65baaf5a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13837158/s55086740/10abfd75-dbb0cb76-ba525896-f9a77aa4-d08cc9d7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14558952/s54331133/a3f707d5-83218a88-f7a40366-dca1e135-2e927a80.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13964474/s58308524/4c6b5299-3ebba16c-f51ce5aa-b087e79c-2ac29f2d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15128282/s50643827/f19b9819-95cb024f-8e3be04f-bd51425b-1ce5208f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15020653/s55819643/c53efe0f-fc0ec359-ccfa3122-dfef8c35-38d97baa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11002115/s52793213/5952d7f5-0fe85217-57d72072-c87673d8-319f555b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15245907/s54604346/8519a22b-0dc68370-3563a433-e77760d5-6fd32541.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15857729/s56216565/de9e7463-d51a6b2a-2601990d-3ca399d2-0f7a8df4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10050755/s59226213/b9a2f699-c72f1411-04649240-170bde26-1fd058ee.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10938464/s55539124/6be5d23c-ff350429-7011bfdc-2ef55dae-465b2763.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16139035/s55403763/0a13d67a-40ead90f-74cbd9a1-a1133c01-6ce2f064.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16732638/s51703305/805a8950-23cbb6d4-e782fa05-4f383d52-095f442d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16311268/s54831478/39cc8525-959e9b7d-94468591-dc9f50b8-b8738497.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16610791/s54470386/f40f60d2-b94c2f83-1011e078-66ee9bc7-1c81a14b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18910060/s54976912/4aff4e09-0a9a3659-30bd8a5a-f8c582bb-99fa4c27.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16252824/s58999060/d7f3371a-d34ec230-59beb696-fd345311-84d58524.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16553329/s56936171/8ad111d7-bd7f226a-d10f242f-59b1df46-5defb013.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18517718/s56047116/26cd4845-5c52d871-e5d996d0-a2113787-630c0309.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10678335/s53343765/600b88e8-cdeb206f-24980db9-a88d5336-a9ab05ba.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19206480/s52594758/d1935e38-bf72f688-646772e8-395c6a5f-1cdfc7a6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18043576/s59470333/7a6ac94e-6741600e-3913ae75-86a46dd3-21126bda.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19016834/s53078046/f0b2495b-1f5bba25-28b2aff5-41d9fd3a-a364895f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11312170/s58824834/9ed39c33-886e9fb0-03544d77-e20557a9-ca545c0b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10074323/s57695149/f85db56c-b08924cc-6776b39b-2765f379-13e29682.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17550028/s54718865/ebb0c6fb-a7b3a17d-9c63a423-98f15af8-25e5836d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19453522/s59237858/85a031dc-8b89a005-3dd45e42-12780038-96f28b75.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14130631/s53751278/50128e0f-c1577db7-d7282723-d18af7ff-beea4f86.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18975498/s56704744/c1f65874-3634f16f-702108f6-32fb8da4-216d64a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17909761/s54447687/32a32fe1-b5d54978-bd949e3a-a3249f06-03094042.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16592995/s50135789/cb41183a-0412434c-a3a43ea7-f32081b8-bee045d5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17896062/s55043805/912bcb92-73828ec5-8dad1cbd-cc3788ef-de788956.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17900872/s56021427/a9fb25a4-6b39c48b-03a92249-b0c290ae-f5f44ae2.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17838301/s51924942/ce5b980a-39d861d4-c9184dee-08626cce-313eb439.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17838301/s57255382/e5382fdb-74985bc4-2fb7ed30-c1708f5c-3f136ee4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12557964/s58099140/8a0e38a6-512f2f0e-7e5d404a-2275169a-54d34bea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19771110/s50972502/6da8b3f1-863ce5cc-b0339d9f-55152f50-9fc3c9da.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10452634/s58837458/ad9809f3-0e1a7d8d-b573a7f4-2c15c11e-7008fcad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14691641/s56778059/f8a82b97-4fed7408-de542e58-e97a181d-f2da93ce.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15625104/s54781953/483592e7-b3f195db-66d52f55-43a510b5-16643707.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12156923/s57198299/45e28ac2-888938f8-bdfdc38c-0acdf76b-9538530b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15311843/s50155900/335179fd-39a2ec5e-c854b903-797c0f99-55054c02.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12959538/s55567406/ef5bcbc8-776e4cc8-7454a3fc-fb242b18-40c22ecc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19650702/s51719757/80251f0b-24b564db-d714b5cf-1fe0d83f-47a3be66.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15805011/s55366215/4e6ec8a9-95db0911-20870772-6484aa31-ee3aff92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10552974/s58811823/3a039e86-1a6331e3-c4c35498-9303cb24-26827344.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11267564/s58082115/62d7d6b7-b3bcb6c1-e0f43f0e-54ca2ad4-9153aca2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17520318/s53387439/7cc4f749-16ae8c41-f7db9f19-3bb5bc06-a968c35e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14316200/s58221620/187a2bc9-22bf5772-be7fc95b-265e6ffc-27610f9a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19075045/s54025444/a2082ebd-e2e4d325-ba2534ae-474619f3-c8f5ba9e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13919405/s53335715/43d3d7e5-51d7b668-0c5f9716-d11df728-ffaee25f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16796158/s53728843/8e23cdbc-85f7ddcc-0097ac18-46bf2c55-4e1d3a55.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15510911/s57274497/c4aa2f33-b91fbec1-971f13fd-81f94e33-e8312181.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16787268/s52099770/7487924e-03fbb530-b7b17507-2b1e94f1-b314b8a8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15662081/s55470878/0710b151-dfa61e7a-eb10eed4-13decfa4-8273e261.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13442218/s51253582/680ac98c-69d483ec-a7be5d29-f3b61b45-f46ff7b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19759491/s52749045/897059e3-92ae214b-1458e44d-75eb5510-5098e1f8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19700882/s59846923/09a6c621-8faee2f2-bd72a98f-ed8bee84-9767b0a9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15486932/s52967497/5039e35b-87c10539-951c799b-c0f0996e-566040f4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13598803/s51332346/a0cf505c-0d0135ae-4106dd58-a0139675-95d7c6a5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14553780/s52679899/cd42a7fe-14d64cce-faa9d2fd-b1de6250-5961591c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10950843/s58186479/062ef786-947c4176-86b62a54-348600b0-14d47230.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12338003/s58901531/add69b28-5d1de563-74d9629a-7c9acb1a-622efbee.jpg





Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19759491/s58459168/8fbf70c6-38be49b6-19536bcd-74b5e494-4ed5093f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18230428/s51900068/1bc70985-bc33bdb8-0f538f84-0c541095-4021ce11.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12431768/s50467666/223b7554-79124b13-95fae213-c90e5979-56e15031.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19938391/s55313618/6364a269-81a5e3b8-98ec1697-7719569f-71254236.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10968669/s50445102/16d4240e-453c3fab-75913781-14422f9b-5cff0c73.jpg

 57%|█████▋    | 598/1047 [00:04<00:03, 139.93it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16052230/s52501106/1ad2ef88-52d312dc-98ea0159-8f4a5670-b4912f9f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18919193/s57393148/e074b975-a29f177b-43042508-779a6259-5568481b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10624280/s50678355/1e9dcb75-73a83383-c7743b8b-bc289a0d-dbf5b362.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15906662/s52348460/dc56ff3e-b5074c00-5dbb2327-b6a2250d-8db5a157.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15881002/s59658268/ed730ed6-e391f6a6-55e52913-a66b2844-da028e10.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14634306/s51903133/bb3ccaab-8adc2fdc-31478294-9c85ee8a-4b84f2ca.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18164811/s59809664/f0822d85-e737edc5-c4e90e14-22a76bf6-e041499e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15290079/s59403202/fd80977a-06be7821-ec0adce0-7d8ade57-c989189f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16932330/s59893695/ce9b3d04-da636dd2-46521543-a77ea8aa-04e60c18.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11230804/s58107238/861170d7-48ad8670-573b7e81-99a7eb78-ebaee3bd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15614063/s52983837/d0b50a99-ae808cea-c678ca94-dbbb2401-09f7194e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12558196/s54892743/215acc39-a9e0859b-b6002905-915384f6-1cb49131.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18096934/s58719806/b2d93146-ca4bf8a5-57d1c6e1-ab3adb78-c21ba362.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14997223/s53647617/81ec392d-d7d7b085-57108530-40a1ba37-91cce411.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15753424/s50569248/7f920625-025c2064-91d6ef6d-85da9c3f-d9dc4e04.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12481952/s53637784/40d2c925-8e88625c-e897ded2-2951a757-87849505.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12611156/s50678707/64d9f580-61011f08-2a9748a6-15df13d9-c0df40c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18477696/s58025089/da4bce81-5bb0a836-fc8962ca-ce94c3e3-6ae338cd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17058654/s58211137/19fca09c-7e20a765-dd60de42-a14e9d3b-cb7f761f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18955018/s54944872/c777abc3-202e1496-ab814fb7-1451e728-001d915d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19385219/s50720936/10a99391-935979a4-5bb5dd0d-0b46a553-e0cffd4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13208073/s59359700/1ef030a6-c9efc6a2-1f6a64cd-1a9a7bc4-230a865e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19674514/s55927608/9f1cbc0e-42b604af-21c70f7f-46a75356-5a4cee85.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11714491/s52600755/4d01571e-5ee47fa4-f6a37130-b9ba04bd-c27a7fc9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10903792/s58614235/24bec92e-63b01207-fd74aa66-2a8b208f-27224dd0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11508828/s56551712/26737002-631059a7-f531f9fe-94a38d2a-b889cbb0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10990840/s52299234/9ba14adf-0bf914f3-04376785-67134700-c55e7237.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12131616/s50623336/37d10d11-a745010f-2ab0ccd1-f5d9146a-93252fde.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11862995/s55652995/5167bcab-33126367-151217e9-c187bfc6-e429f253.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10648046/s54836145/c341c37b-13cde0da-786cf878-d38e9a93-db24da5f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13985881/s50698039/16f91d47-250658f0-1fc41e13-ebfb59d6-74f8b5a7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11600106/s52452382/04c2e395-06a6e4d0-0e6b9e03-374558f2-14c96a8f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13251065/s56702676/4d6f6d92-07528749-46f0ad7e-6905ade4-6f2e7409.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14399274/s51015564/68d3b53e-69bd2fe9-d6ae4e66-f65f12a1-2139ab1e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13762124/s59503392/e8752fea-a518ba9f-bfce012f-fa070e37-11f34da8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10476869/s52231166/95c32485-da7e26a7-53e671b5-6a7687d4-0347ee81.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13423238/s50319341/baea0e85-ab995dbe-cd930d81-e64f337b-8d905a49.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12325327/s54220360/6d8de594-2b240b26-c2743f1d-5eaca3dd-04d31abf.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18823905/s51819397/f43ae8f3-b48bca30-8a308c6d-8d22e88c-50074371.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17987679/s50635222/19ea3cc2-45049cf4-8f04b5c8-34262d5d-c9d5eb2d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15738526/s56342210/ccf9a248-2b125294-ad0e77f9-dfc17f5b-60e0fd6e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17517983/s52159721/0da5aced-8f5dd5f8-bf93b1d6-5dd7dc98-8f767dad.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18936722/s55477078/20be69d3-0a98b71f-94b4059d-422cc93e-d46878f7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17411825/s54223967/a8e5ebec-d70fa00f-d0fd6e3e-ede9aecf-0f955fd3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18143542/s53724527/1dbed3b6-1b0d8907-5a82a60d-8baeffa7-7ff9fa35.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17872769/s52769981/2f7f85ab-77aaad94-9b5aad39-4751bbd3-697097b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10018328/s51710812/7ff4e7c7-59ffae35-f3e8c04c-b3e5efc7-ba128f43.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17237709/s50933738/f2d417d9-b71eba65-cdf1a277-8404d1a8-62a21b90.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17121948/s53241550/42c44543-7136acd1-83b0901d-7e5d08b3-24327533.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13645282/s57801214/cfd760d3-5cc9f896-e8ef0254-d0551e21-58dbc9be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18220139/s51199109/bf1833b1-481d6eb0-a54c28ff-62c7d6af-daa560c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16152603/s56051886/8431e7ed-374194fe-fefded76-46f69e25-63c1e199.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19608147/s57640970/4053b069-4e043dfb-a51aa130-f6318b90-21719d34.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11437366/s58458228/cebb7c90-0f1d4a5d-771e07ad-daceb941-2d998ac9.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19291199/s51110455/f3b0df7e-eeaab2a9-83ae03bf-cb1706bf-20665666.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11732026/s54539002/50c252e7-34c01886-00e87977-8d7154ee-b39634cd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19341743/s56948595/2a33eb95-9f77d300-265d7062-2c6c65c1-5d5924bf.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15009233/s57256545/be39a244-3124c478-f202e009-29c3ea27-ce5a3256.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13843083/s57474405/72f8465e-e6efdc49-76ff5266-11d2f8e7-692d9234.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12394964/s54648531/da6c6b05-162e8dd1-9a823494-f285a278-0ef9771a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11717909/s52127446/65ef31a2-e080f853-c5c75be5-2246e4e8-105fffb1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18429092/s54680974/18c0a036-1d85d501-b5d206f0-b1525e93-ae549e47.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19822698/s58272428/58223abe-b8f64f41-22f1a80b-b3e70da7-86eb0011.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19810100/s50979209/4778fba4-0c7f0787-2274de15-85e7b73d-eb3a124c.jpg

 69%|██████▉   | 726/1047 [00:04<00:01, 188.73it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16967621/s51884353/0c1f1112-0ecc1faf-12de3b69-bf92873b-939f2ba6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15445857/s50967054/18e1246d-a9c790ca-6b40ea18-81b9ccc8-3469c113.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12394964/s59007262/59ddf46d-bccfc0ba-15ef4185-6581b093-864220d3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16359994/s58908246/404810f0-c911dc41-d7564ec2-b846f224-531a6f45.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12493668/s53822725/03b28c93-8573431e-720d6a4a-b51b9f2e-0963de24.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16830390/s58157716/885b7197-35ef7a5f-54aa161f-58faf728-ae027441.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16182400/s53094096/1c9de17e-cf986487-c81fb07f-0d1e33da-d8bbd1b5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17112432/s56998267/be319f71-2b1ab302-55580f5d-ffc6e9e0-9e90689a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16650418/s52087631/ec006d9a-70bc5abe-2709118f-2d47e657-6a728c09.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17556194/s59274236/87d2a3c1-90872963-8db3f814-d6ad982f-6c21bc54.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16601683/s51529993/6ea82e84-aa9cd50a-becdc0b2-5810acc3-b217d535.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16679893/s55232384/8335a2c5-150c417f-90f20a4f-67283021-a12b2267.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16431831/s50066633/6b7eea34-85cbf22f-b5f190dd-e66aae9a-bdcebc99.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16490354/s55448089/65899cf1-69c8c359-1661d042-03a9a1de-d3cde420.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16009326/s56053878/1f0ac635-c831201e-e561bf78-f71d6aaa-5895d9fc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18618203/s56265275/dbb71182-0081bef5-cba5a036-c71c0f59-925942e4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16203142/s52691854/bbdf69ff-2f414870-44f957f0-d1290dc3-4575f2ec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13859188/s52811469/0677ec27-61328435-0dfee3b9-356bfc03-8cbd3353.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11849511/s57160921/aaaf94b9-37d0427f-4d8c0285-e70028b4-e0b67870.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16799095/s58806478/5298c5ce-2c1f3efb-7ababa4f-b1b934ca-8be48e33.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12133670/s51759637/01c47909-29055dd7-7ccfb97f-a38194de-11a8c26d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12668169/s54438962/f7e3f8a3-7299389e-84a7eb76-0cb81c79-06875895.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17865089/s59717631/e47abb05-dec27a0e-e5af4d59-1fd1d5a0-1c34655e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18208545/s51034438/adb67a2b-a1473b01-b1004ae8-e612d0c9-1c2b5e3b.jpg

100%|██████████| 1047/1047 [00:05<00:00, 190.83it/s]

任务完成，所有图像已保存到新的路径！

In [9]:
import os
import pandas as pd
import cv2
import multiprocessing
from tqdm import tqdm

# 读取 CSV 文件
# csv_file = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_combined.csv'
csv_file = '/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold_data/fold0/fold0_train_subset_5000.csv'
df = pd.read_csv(csv_file)

# 获取唯一的原始路径列表
unique_paths = df['path'].unique().tolist()

# 替换路径前缀
# prefix = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org"
prefix_ori = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files"
prefix_256 = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256"

# prefix = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files"
# prefix_256 = "/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256"

def process_image_path(original_path):
    # original_path = prefix + "/" + original_path
    new_path = original_path.replace(prefix_ori, prefix_256)

    # 创建目标文件夹
    new_dir = os.path.dirname(new_path)
    # if not os.path.exists(new_dir):
    os.makedirs(new_dir, exist_ok=True)

    # 检查原始文件是否存在
    if not os.path.exists(original_path):
        print(f"Warning: 原始文件不存在: {original_path}")
    
    # 读取图像并进行 resize
    img = cv2.imread(original_path)
    if img is not None:
        # Resize 图像为 256x256
        resized_img = cv2.resize(img, (256, 256))

        # 检查新文件是否已存在，如果存在，打印警告
        if os.path.exists(new_path):
            print(f"Warning: 新文件已存在并将被替换: {new_path}")
        
        # 保存 resized 图像
        cv2.imwrite(new_path, resized_img)
    
    return new_path  # 返回新路径以便在进程完成后追踪

def parallel_process(unique_paths, num_processes=96):
    # 使用 tqdm 显示进度条
    with multiprocessing.Pool(processes=num_processes) as pool:
        results = list(tqdm(pool.imap(process_image_path, unique_paths), total=len(unique_paths)))
    return results

# 开始处理并显示进度
new_paths = parallel_process(unique_paths)

print("任务完成，所有图像已保存到新的路径！")

  0%|          | 0/5000 [00:00<?, ?it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10320090/s53562356/d3ebce45-84e704cb-5dd6020d-0afb0b3e-9fa32222.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10435691/s55006072/849d71b8-14c37ba2-82d8ca3c-1bf84195-8bff3039.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17574863/s55426811/ab6f1f23-3784f50c-ee260cac-99a38c1a-13a1c795.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10265482/s51582361/a8230243-5cba33f6-3529e6da-1e0d15f5-47f4e7f1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12358841/s55120343/f73c42d6-6bad3529-fc44b386-8cf29fb4-43fa4400.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10535715/s59613325/24b33ac5-c1ca69b1-2de94cb7-5ea4e090-b3ea1ac9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10024982/s55121733/83a31644-8a9e73a1-0e092921-3de1a867-23397545.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10743265/s53683327/0b0a82b8-28b89b58-023e81c8-f1f25232-d17e5c12.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19690769/s59256511/5f4e71d0-fe2cf87e-32422067-c9c3e74d-fd64b436.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14588689/s55910653/398c7437-988230c7-d8f91f6c-449a9062-de852c62.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18569605/s58070736/b7fa8faf-691219fa-1b3eb431-9f6c83ee-83fa54e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12881468/s56358713/001888e6-f9d643f9-9120ca72-a0f10ecc-3095912f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14981068/s52933489/c7ad3b45-4de576cb-232bf86a-5f1d6295-df52e975.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16796985/s54464435/662a8731-1195505d-0e5d7083-5d215ad0-8227c90e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14671013/s57836629/b35dbb9f-062b56dc-97d3002e-a4bd1559-ef33eee5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14033331/s58523360/cb9fb36d-afc07da6-1f153318-5e6ef16b-9b8dadbc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18975498/s50178926/c97a3994-70142aa4-738650f9-c396fd9e-de05a90e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10076958/s59180098/66c6405c-b1bb1e2d-6537a336-ad5723ef-5fc758c5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12996303/s59604933/60939443-0f96dd55-9c7b461d-4e827472-d8cdd967.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16809525/s52988376/a3121b5d-c26717ca-43cb7b8a-465c9cb9-83ffb778.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17986383/s51422291/1d2e1a1c-dcecf624-5283bde9-0f1852b7-49c01683.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10653013/s59625680/6ebd2c65-d947b4d9-52faf826-fc895524-bcd931fb.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11693603/s53085165/19118520-e5e3cdac-ecc36d03-3dd5740b-ae85fd3b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12051380/s57994889/f90868dc-9c28b822-1eefaad0-b0e4b393-cc69bb89.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11315282/s51082051/fab3a0d6-df9932ee-7be67c44-9eecbb16-1cb6bee0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14405281/s56105529/0c5cdeb1-e0801d21-82f918ba-96eca48d-8d158c23.jpg




Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11115375/s51078311/11b06999-819f882a-97f3cb41-03827745-94bf52aa.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10924565/s50819653/9a1d1aad-081d4460-77bc5fac-8b28e0be-912c4998.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16181355/s58856345/5bf3d07f-b85a7a68-ed149ccb-97f7c919-18559b63.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15290079/s50171018/7da0bcb4-4266b282-1a0f9852-250000a7-d30219cc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11966699/s50631849/392dafca-6ca54ab8-43b8977e-eb5b16f6-d99eadce.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17237928/s56644705/9ad7e90d-01688956-5522068b-136c07e2-b19e87a0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18153920/s50341258/7e16d404-b3892f49-70c4db26-54171ce8-9db73087.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11241014/s54585153/e9bfa50c-9758bde3-4534ee66-c39b3114-f86de2d1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15605860/s54709400/99981157-30388ff8-11530d88-9298b889-d3a90583.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18201772/s57098797/1bcc996a-409090b2-7d798202-c5084e0d-eb922ef2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15195362/s50658726/5704bb68-7d54bf67-c07706d7-e786a0e0-99de2855.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17340686/s58040849/9cf8e1b3-4a4ea8dd-33fc8814-862d81e5-34c105d1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13163471/s55498362/635e82e0-3639084a-cdf4646d-4e59c8cc-6e2eda35.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17370967/s56605044/2b5a7e3a-be552c3d-9da23d7d-0cc0d299-0f531d15.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15070812/s54680418/c1b6de64-d2317807-387d59cb-34da067c-655e3563.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19197066/s55779661/7ee4bc2d-c04653e2-c8120a00-5135acc8-491048ec.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17945610/s54490035/ab618eee-2a493884-a478b561-100f5f42-562e5657.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11597207/s59569195/545f6680-a02b3bc3-5af53442-f1e7be6b-6799cfab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16668660/s58221045/1d33d55f-1bba9265-33b261aa-ed4afebc-5b9b55ad.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19010275/s59172363/985415fd-eabd15ae-726e4b25-7decb6a0-8c110375.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19783898/s55655942/a4fd73f8-0428f0e7-65938b7f-1fd366d7-5c05d59a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19661325/s52962867/48da1ebb-b8e1f502-cb81dc6b-8edeeb6a-e8dfa8ec.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16565695/s52659747/021f4abf-f0660e22-da7f1d76-06f2fa73-5c475ec2.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11537949/s51499957/7871ed3e-062f360f-8c74bf5d-6c53ac37-78ea3228.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19585869/s51409180/08d6c90a-9fe8ef17-f414896d-9ca21c6a-cf093ae3.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19616613/s54465952/2693bbff-d23b647e-f46f116a-2ecbc21a-c450ebef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13941091/s53110531/c3bcf2ec-d204b33c-12a9888f-70ae2f4d-54306bc1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16698321/s59008712/bb68f729-3111423c-0ef3ec41-4f68da88-24fd89fa.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13273624/s51455913/21cd5b0d-53817892-c452ff42-adf960f6-c0bd0adf.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13672788/s56031932/397ce514-306052c1-42a8b150-582fc9c1-9c52996d.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10997073/s50423961/7558a0f5-822c7d0c-33dde2e9-d132cd32-181ca2b9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12924518/s55166339/98a707d2-4169e4a0-705f32be-edc522bd-62123a90.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14338016/s59516975/4c979129-256b13f6-5721f674-021adb3d-9b93e122.jpg

  0%|          | 1/5000 [00:00<1:17:15,  1.08it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10314749/s51931288/1f8f290d-367636d3-41f6ac97-7e4cb787-3cba53c8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18862842/s53141494/ada29eba-df4621c7-7d7d50f6-1ee21fc0-24829100.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15936063/s54642228/dd3a7bb8-26d4405f-0bdaaa5b-29d67a83-46adc337.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13808136/s50911395/b86f5158-57ccae20-7eb26421-ed563d95-743f28f0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10386562/s59672745/5de404bc-bee62b6f-07455884-eaf31726-346cd34b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17643850/s50218905/1b86cb8c-417c7144-ec5def4c-37a71eea-04ab986c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12058674/s51825551/4cd7b303-af052ad1-ab3f0035-151238df-5565ee67.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12227507/s56979640/2139b949-c88b10d0-c962d81e-1ce7a9db-e6c3b4ef.jpg

  0%|          | 3/5000 [00:01<23:57,  3.48it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16283494/s50875279/d01c2c55-d69eeb56-161ac1d0-e6c5fac7-43559f2d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12008763/s55998665/9a8f28ae-ef51332f-252c89ff-a80f252a-c68178c5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11341217/s59948284/85750a27-ecc2842a-ae8f7339-a6d8dfef-695012b0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11803001/s58427150/1abfa115-7f73e547-594dd032-e6fe5953-5e7fba5d.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19736371/s55333862/09d3b894-4d819a9f-e2446a18-d904dabe-3d5677b5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18044722/s50478289/2bebac04-e7c2d675-4d043f05-750d5418-c43c2568.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15851682/s53853838/f9081799-38ee97fa-b8e3b5ea-102c0d4e-9438daa1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16962956/s51219630/fea39ad5-68c3095c-c83e2251-84b01bc2-dc6fd577.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10982917/s51637236/8b47adc5-98b8d2bd-4e93ca91-8e3d47d0-de402ea8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18871604/s59494686/e99e6bbf-56330dc0-2eb24b65-3c3ca116-1b1525c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17172316/s51272682/0865f898-f64d6a04-9e449e0b-e437b806-04d2d636.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18620666/s55819240/6cdec08f-9d750ca1-a5ea7699-8fac7aa9-3974bd35.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17402093/s51304422/2ca14a48-781d6784-575129ef-cc1358da-b2f4fc4c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18939639/s53884150/3d42437c-db3c1f76-fc74e089-d1820944-8e11acc0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19533730/s58568566/59f7be0d-0affdfed-751942d2-d8691aed-c02be7a1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15233042/s51401129/598d604c-41c0bbe4-839811cd-e7a37b45-502e5f3f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17561108/s52548135/19b2319d-3d44459b-9dc5d15a-de38da22-6fd5fc4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12847817/s59739662/33ccb602-aba645d8-4359cbd7-39568ada-b906f1d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12237851/s58729109/bcc85e1c-3bece256-2a46729e-2487abc9-802a0844.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12112476/s59852380/4f222996-7f7bd165-553aef9b-4a4f374c-be930683.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17041931/s58431430/fa5d1f6a-dfd244a4-1e740484-5514d31a-a9d122d3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17132597/s55006497/0afcad69-3b7d18d7-edf589ee-79eebb70-8e633950.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17284612/s59217031/9830bf3f-a14b9ea4-c009090c-102a91b4-fa23d455.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10535715/s57903313/0da6a9c4-319df0c7-8dbcb91f-1fe7a315-bef56e0b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15690435/s55318530/c0b4a444-9ac2bb4a-97a4cc18-d45646ab-d23c9f01.jpg

  0%|          | 4/5000 [00:02<46:18,  1.80it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14143731/s53003166/589aa887-7594b6ce-e8067d7b-09cb313b-7a5354c2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16893353/s52621660/62c0e76b-2bc89c9e-eb12a013-1aa9ceda-ee874395.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13859181/s54336811/6f7d566b-e0aa8334-2ca7756c-ca9c5d9c-66752a3e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16307595/s57123799/4dba51fa-462d1b34-a2dc645f-beace74e-5c2470ab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14235272/s54940700/6b7b9d86-d7a1b063-ee3fe33c-659f16fa-f41d5033.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16362604/s51755551/408f0036-d4f5c6b0-f0a89ed2-e9dc8c14-adf484ad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17257279/s59975819/b2d2a719-f426438f-7e6d7f1c-a169ff25-4a53210c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14886080/s52092932/d0c50535-ebe22655-76699791-5c9dbe4d-f2622c55.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12213423/s55464048/dde1c3d9-fde0241e-b8d345b3-63119e11-e9d0e6a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16920636/s51956836/2bc47567-e4e78a9b-2d777886-9f1f4d43-67abeb2c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13717854/s54507864/5555de45-8c3bbb43-b8f5d5fc-5dea7175-6933316d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13198693/s51559908/e488c5b3-d0446dd4-56536360-6d42001c-58e505cd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10245890/s59928668/1b791f51-3b259d8d-6a04439b-9bdeeaed-066ccd38.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16126373/s56784795/e04746db-68c79c74-d16fbc0d-489249c6-aa7df779.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10755736/s50939160/a53e75bb-14b87d03-d03ad191-2f01324e-bec13b48.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10970092/s59135513/f4c7f36e-c7a5fa31-05ec3531-b104bc90-103ea7b7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16346972/s59963892/197aa54f-e1b98846-b8620ce4-ecbffdb6-69b93d9b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10145374/s53602703/6c15333c-3a223cc4-551e3906-fc2c6a00-f8a80cc3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14395025/s51066768/f258b299-9d590556-32b51db7-1de8e431-10b51e5b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14358732/s58201497/02f1f38d-509af280-ca736b00-d1a58bf1-8bddd94e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14675727/s55400633/900858c3-588c851d-52e0927c-8981fe65-ab6c95b6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10021487/s53109949/ee7287c9-969bff42-1519469b-1e4372f7-f8f86cfe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19509694/s55675964/94b4daac-2accd785-9c7c3c19-0ed43f71-192cdb5f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13126641/s56598273/8dc935bd-110d31ba-d8590c29-a3864783-f817372e.jpg

  0%|          | 5/5000 [00:02<46:19,  1.80it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16753086/s55784211/af0d110a-9f3441bc-84ff6d87-4d3fbf35-5cccf779.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17439857/s52813257/9ff166da-87b108a4-3e1fbef0-b0affa86-558b512a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18056245/s53376596/ce0af749-08c8e400-a7ef66bb-c5c6f08c-fac9a38b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12668169/s57528671/1869f021-95e9cad4-c7cafb46-f5fcbfcd-d16dde9e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18486555/s52570733/b6f4ca77-7fc669b4-d9c53b76-00c604c6-eb06b6ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14357860/s54370059/17296e5e-f6046611-f2a7dcaf-5f8124ba-49f83651.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10157508/s53992660/c8a84fbe-2a349cda-337c02df-320b91ef-93f61283.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10908761/s52126283/986e23af-ed1c1c14-00eb8e59-3844cb36-ada8bcca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10795168/s54713296/d0ad3dd8-a32dfc31-df5b6635-f6f2259e-6e6998ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11533536/s53536218/6964c061-b0875312-8372c9e9-d84f5a32-28f1a0fb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19288645/s57002925/f9983a00-5ff93fc8-0d58a555-7d0b3dba-fabeda54.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10964049/s52973052/5d3ae0a1-77341dc9-af55acfd-6f32e976-ff0bf2f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19893304/s52771884/96c8f34c-6f3f715c-35ca78eb-c404308c-1167e8bb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10481162/s50101371/f5a1c97e-f3b9ecda-744ed4f7-fdf11b28-3d6eb180.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19877239/s56669336/e901777c-eb5741e3-ae831f6a-1cb5e4af-c5bf34e3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16796985/s56661156/5561bbc3-545ad5fa-f30d8a23-3fe26c0b-62b2cb8f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18347490/s53658836/9cf9495c-439fd916-c752631e-d5b33d41-306b978e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12727378/s51263612/ee9e5de7-573ae4d7-19037d48-0f28f7e3-7bdc7689.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17971334/s58829443/ea360a16-de60dbd3-d4a732ed-e64ce03c-527cd75d.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12643806/s58751405/d6396a9c-8ea98a48-fa3c14c8-b39578d5-6f84af92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17168033/s50910695/43542fc7-e598ff19-2ab2908c-2cee9e95-4cdc3806.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15925803/s55158777/6271c728-73d76932-d92a7a3b-b5487ca6-1b1ecfd0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10255799/s57086295/8a3a8b94-8789aa06-72275d84-7244d19c-dc910488.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13261938/s53218858/f370fb54-6997e3ba-f9d798cd-00284eee-71adb283.jpg

  0%|          | 6/5000 [00:03<41:30,  2.01it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12796898/s53538666/faf1991c-1c804a15-bc2c3e53-f869e3e5-651e8733.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12190999/s57287527/d75df80d-8e44eee8-27252116-64bd6d3c-bc7c3191.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15146814/s58144310/4d18c339-fdc8dee5-37c34f90-b64518a4-50b4b8df.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13775508/s51042111/acf1ed8c-3b9ecbe8-7b3ca12f-cb659f32-cf812bfb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12653342/s57024948/6534e0fd-213b7a65-f285a88d-631240f9-f574888a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17336284/s53507367/b9bfa1b1-4a53df5c-c131d627-cf5e39ac-f516de69.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18396526/s52278355/16359ad1-4b2219b1-99875381-67488116-81be8ff1.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17925184/s54217409/b6d20dc0-7ca25dbd-b9b9c242-641cd3b7-13118b53.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17892707/s55639041/71713481-76a0a4a1-150158dd-d9fb6dda-72ba1b94.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16317237/s56821926/ea0dab6a-0a88083c-ffa96d8d-59a8b9b2-4120791e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19277667/s52393624/fac6cc5f-c53b15cb-1df370ee-9284596e-c309b475.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10003502/s53836463/371aaea8-195e21b2-ba5a2856-54803ecf-1b72d88b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18425098/s56997745/f6766f28-a8a04e13-c3dbf21f-24f6140b-63cacd2f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18624957/s56774137/3e49dbe3-db9bd06c-29011098-d5ca9698-acd9cecd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16939345/s54373251/0a031921-7f67e9ca-e5e90725-298b2abb-b03b29b3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16867899/s55029870/b224cac8-2d10561e-f82f140c-6791a17d-f4ceca66.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14282911/s56701986/d74807d3-53b88a2d-1ce6f7fc-1cf94295-1ac12d14.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18408877/s56380086/97eb5a62-57e89c80-ad17a343-78f22e24-d4a20f05.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17401392/s57924292/8306418d-0da72d83-175b9e6f-ab2a0b89-bf66c678.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15107347/s50851310/774f2736-58f6d8a1-d769260c-9d5771c2-9bd7c26d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15052507/s52249302/4cf0fc0d-1b32f59b-0a68732a-939863ba-2863c867.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14931360/s52837742/8b396aa6-ab0112f5-e5966b3a-27e3544b-72d76e83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14498294/s57750655/fa4404f3-2b06cecf-1f561250-5513a699-6d12dcdb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16117248/s58999351/73d1e5f8-44e4e835-4d551ef7-748adcb0-ca453cb7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12061180/s58895288/fc5a2c11-5616154b-034f0951-35b4bccc-272ce51c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12192195/s59395070/8d9afaa5-479722d5-ead77de6-6a98acf3-c93ecdbf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19700047/s56346486/4a68ddf3-3c5d2937-bae43986-3ae30a2a-b6e8cc9f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13117065/s57955630/8efd0404-a942f8c7-7929d559-3f2aaf19-a0ac1250.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13508515/s57826279/e488558a-30cc3177-06825bec-9a7ef844-43b50fa9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13662179/s57336199/d8269fc3-828f20b0-01a8aec3-3dacddd4-11eebe53.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13723320/s59610243/e46db339-3f645db5-2d732c7c-4bf5558e-4c725829.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15868448/s57232596/692ba57d-340a02a1-c7191350-436db6d0-70cf280b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17425647/s52468274/06029927-134c4f60-4199944e-73ac523a-e26554e7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17124656/s50494176/f8f9e1d3-a221510f-806516f7-61043509-6ed83678.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17211008/s53054999/c0ab613c-69b675ea-c3192f32-3dd9b171-a1cc0d82.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17361558/s55952813/f91fa566-3727c33a-d71070d3-0e6f6c05-3e3efeef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16574411/s56447425/a7365a77-99be6804-c84302f6-212715a1-cc5649ca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18609163/s56989187/9725ae23-8d746405-7717fc68-0ef93962-f0f370ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15269527/s55374834/a4bf06a2-67e4d7fb-39942f6b-918c35d8-22858032.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12399776/s50517215/cd280dca-9ef7a8bf-c35f0130-1ea7fb49-dae86269.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13669110/s51438537/67aa16e0-b991bd51-68c2efb3-a4435d9d-ca445f5a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13135946/s52546073/1ec07497-ec6f4ace-baa95464-3ff6c941-6418e970.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18092465/s52709368/35e0e88d-397ec66f-9f808ab1-22d82340-465271a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18637097/s56407446/a24df645-7e8e719e-af2ade16-faa2b404-f738761a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16020842/s53911282/c86037db-084c9c7a-55f8760d-fd488b9d-cee73ce5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19336651/s52820891/05e11806-18018319-c19b745c-33109e20-618b6bf4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16345504/s54426331/505d26e4-66aa320f-47de94c2-527b0013-6f9cc687.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13881772/s51265927/4d91911d-7ed6ea7f-18ae148c-fb6fdc45-798771a7.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13658672/s57998234/b1af6459-c0d7fb0b-906035e3-70087b83-7040803d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15942634/s59275918/ea14c407-522f4086-28c854d4-3b17a9ae-e171d964.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12191200/s56350966/b4686959-7cf7255d-39d4af66-4ac5d6df-40d43323.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12429546/s54509386/5931ffe3-c2c5c815-51076f68-2b14fcb5-93a337cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12117907/s58863134/8606e522-c1f6b6c7-bccfccea-a98f219b-8b81176e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14919634/s50461229/2ceaeced-c497214f-9a5e9326-63065473-ab01a0a4.jpg

  1%|          | 44/5000 [00:04<04:47, 17.23it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13010793/s54237552/35dffc9a-da951ccc-84902f28-b8367a21-7d992e6a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14851532/s50686747/6da80776-b8a61cbe-7898eaa5-29b7ca8f-c0ea57e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17354160/s50868740/54e6202a-f6a7469a-e441eeaf-650ef335-431b0cc9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10657705/s56681729/399e39d6-0a2a1fb5-a095a49d-eaa16b28-5754717d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19394614/s57263642/be204814-ff5eb505-e37dec95-b2094590-f9d658fa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11486363/s50407540/f29f3684-3f7c074d-24daa7ce-ee06d4b6-f19a6a5a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18194653/s56798732/cff3637f-936b1c2b-f66d3b61-249d2608-ef6c83e9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11116370/s57969817/e5b52e8c-32f91891-d5cf819d-a1a91dc9-2a8a675e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11577761/s55358877/a0df41d1-29b856c7-d510da09-f0501d14-1d4954ba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10354217/s56434512/e0db8a50-89a67b12-6fc0a9b8-5f30f497-29c7cf30.jpg

  2%|▏         | 112/5000 [00:04<01:39, 49.37it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14246614/s52672561/43c56ff9-25921395-2bcde14e-77ebbb12-c70d2a6d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14833492/s57132020/ee92154c-254612fc-9e7276b7-a4d7af64-fbf9b3dc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14480391/s55540056/b066a073-515fbad6-c383ae28-2d4b1562-35da0844.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15566609/s53018075/32fcab16-f93a7d6c-857d7e0d-22509645-9fd18331.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11411992/s55949145/1f66a8bf-9f51988e-4ccfeeb9-5adc68ad-275ed476.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10280054/s55737655/27215d79-75424784-95b82434-10f57ca3-657fda33.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13242005/s55604697/7ad6e862-7c812250-41834dfa-816a2555-9f752725.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13356179/s50621911/2a853254-920bb79d-1d8abc2c-d1c45954-627d8953.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13690559/s57792988/059c7138-cdacf845-f1603248-d3f5a4b1-0cf42a0f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17190208/s50117828/fae40ced-c8913217-2fc1529b-e60b575f-d7d09ff8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10956924/s57666341/346f97b1-5c55a61e-c6ce3713-4e94eb05-9be3e41e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16987914/s51602641/c2b938ae-9e5d6cad-630c8b20-a9cd3fc1-bd45b154.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17968028/s51038154/314e84cd-f4aca674-ac514e90-d7471964-6cdfdc75.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17704056/s56587210/08dbd040-74d66982-b6a614c0-1ac6afa9-49006b27.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17304513/s55937870/19a86854-bffcf93f-84656f6e-84cd0b5c-6dc1a5fd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16346361/s52691485/cd4f39cf-ae14b7f3-7c63979a-93c6e8cb-b6c103f0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11057136/s56312058/e9d63760-0feb72ec-08da3155-5f86c8bd-d95730d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10712217/s59112567/a7f0eb21-7098933d-1fc340d9-282912fa-7df107b2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10667727/s51672295/55f81aea-42be9ebb-7b8f65b4-b7344218-98591ee6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10380149/s55144390/a466e45f-f647dde3-fbf291e7-19533975-cae0a74b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11057136/s56312058/c45acc32-3e147b8f-6a1cf064-d2d0309e-6d9fd57f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11020337/s58896668/68ca1ac9-58d26c35-4359418a-6a0ee79b-09ef8d82.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11922572/s52425958/42b437d3-bf7771c2-59da0ec2-51aa379e-6a9545db.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11044484/s57757249/dba745e9-063d32ae-e9863933-139e4866-4ed909c4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18049523/s56159509/0477653a-a54786dc-f30238df-b0f60d13-49f564a0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18805037/s50222977/c7edabef-91e5d31a-67c5e63b-93470902-5f2a198d.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15750321/s54945893/79ba0d8c-a0994568-b44cfc3a-a379b516-5c3bce78.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18550032/s54779802/693a9005-7745d0ae-65f0894e-a84d4436-71ea086e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13158770/s53785312/3c52621d-df5a77d2-26287eee-fe8f7359-4357eeef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14657829/s59312818/b761c9a5-3620edfc-091720fe-1212361d-cd7ec144.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12018288/s51088587/4a13f6b7-84e3e21e-48aa2462-b5fd69d7-0033d91d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15288761/s51250866/187d33e3-7c75d677-29355fd6-6dd4d855-e351db7b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19227394/s55687472/869e7f14-7f88917b-923efb43-4a8b5a41-10a5ca6c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19717260/s51660977/16080ab8-647ffb95-c53c20a2-6c3d874f-6c38e007.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17820613/s55866939/0edbe84a-c16b84c1-69367843-1bbfb3d4-f12b1a95.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17409226/s59219758/a6bfcdd0-8a0e22bf-3d7b921c-798a763d-305f40a9.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19179198/s59712741/e4820759-ea5b80fd-69544d36-c69db137-ae55c5d0.jpg



Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19390187/s50026489/40e97e62-2063a33c-3fae4e75-18ce7717-be560b49.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17313753/s53040306/12a0013b-b202f954-0743db5a-d495ae1c-1be59fc8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18070899/s57921417/58cb31f8-44f5efe4-20bb0af9-b7ac7c75-3ae734b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11922120/s50551044/94a1b870-4f456c33-7a6c51b9-c0640ec4-67eb86c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17782126/s52630595/196fb39b-99939999-7ae1e22f-7d7f7a7a-fd9b13c3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13570524/s53927177/3448a09e-f83ba81e-41533351-0a90114a-0777fa09.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13871811/s56143480/3da00655-af7a4e9a-91f745dc-a6156040-a8c26222.jpg

  3%|▎         | 134/5000 [00:05<02:06, 38.56it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19533730/s54944201/9a8a4076-42c3af4b-e2f792d5-d7282915-eabf2741.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14067009/s52336795/87579955-d780b8cd-fedd80d4-610b740a-678b3040.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13117944/s52991369/198e4191-748f9986-391cec83-ac50a806-9f932b38.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13016422/s50946365/aa1b0d1b-b47fa207-a56ef59c-9a153c65-22ba732b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13855600/s55118234/656c9ee2-6bb450f5-3eac2286-53148fa7-cd103325.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16174942/s59737347/2dbec58c-d9b24fd0-f14537fb-3c4d7eb5-29b09151.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13192224/s50275287/3a3b992a-81d79634-c899b5e1-ec36d458-7d0449f4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16341421/s57802476/a93b7caf-4848980b-64988819-345662e2-68e0e09b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13331522/s58944974/ea5e9c6c-9529018c-534de391-6738536b-ecf6b738.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13209752/s55585072/43c32be5-b94de8a0-1de4057e-0c074edb-4b39d314.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10439374/s52630441/9bd22380-be7c0325-b5a5cbc5-1aeffe40-7b188bb3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17071904/s59995791/80ae3334-3581b020-910940b6-28e7c19c-af9a1ba1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14222873/s58820889/b330f984-0ec5cdc2-aa513a9c-662ada4d-4e22a459.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18274981/s55308874/f2595ea0-1a7b0238-8e9b4d05-b1c2abea-27dcaa16.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15913953/s56351171/1ec66490-a216afcd-0074b806-b64a21c7-661535d8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15435415/s51451963/eb4b359b-29d211dd-21d920a9-6dca450e-d31e1d81.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13965528/s59414683/b514af04-502a9dcb-9cd85e59-6fae87fa-a4b705a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10192748/s50526893/e8f727f8-5dbb62d7-3164336e-55870a8a-70654576.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19353810/s51383997/0e6de1e6-e0453b58-a4563c4c-f3dda168-ffdf0a12.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19798578/s56262849/0964804a-dcb9daa0-437428d1-c772ffaa-387b1b92.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18551091/s52198095/a1290677-c6478825-434b98eb-e41adf1d-fa11dfd4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11184688/s53009845/6da6a115-7364a0fa-6add9f57-402f7874-318c4e80.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17908507/s59114005/096a52a0-3ee82c44-cdf164dc-d586684c-bd6e7364.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16359120/s56386236/49f81c8d-70daed58-e2cc933a-066f6c8b-e610327c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12375699/s52149418/78511d2e-2e29abbb-91ccfe9f-4b61aef3-f3e3e0c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13134704/s52513034/b9a845a4-32ca1e5b-bd87a171-58c83f6d-8e1f869e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18785670/s58541181/c9bbf92d-7b6e8429-8608e05f-fc02fbfd-ed2c38f7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18022558/s53384995/bef1fa99-b3211347-5c32b387-35b98820-c720b599.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18939572/s54548598/8089639b-52435bb6-a0018345-24593737-fe2d36db.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18449910/s52536602/57518937-b7f5726b-a7258dbf-95101c99-9f8cdd7c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18110461/s50190062/5991bf30-d798ffbd-a27c797d-abb55e8b-5d43cda6.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17244595/s53830688/4a3f78d2-9e5baa3f-21000819-49f794b4-4e01a820.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19826828/s50692000/b8c72b77-1822d8f6-c06571f7-07e7a394-b5af81ad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19864406/s52661474/9345d015-4fa7d8a2-9e488607-1509bc28-a3553469.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17006856/s58424825/a7a3cea5-3326b9de-3b5d9402-70f8ef8b-99c14e16.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14405281/s58093405/8b57c4d6-25c28ad2-dbbf8a01-961e0f46-faca42fd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16201645/s56467323/a17deef5-fd297e99-9d276d3e-d85d9450-80a08bca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11934114/s52152296/67653b61-d4cdc144-670c5d2f-1d19f3a2-480d85a1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17339765/s51751674/43e297cc-b3ad2a42-9492f29c-041df3e0-5834389e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13655106/s50326036/d8e9a724-ba5fe94a-adafbceb-a8a2f73c-f52b5c51.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18769510/s59137528/30f0f433-8064d2f2-146d3645-3c98d559-971b7fbe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11687219/s56588162/0b2e6873-571518ad-ed82a243-8eeb99f8-1c42747d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18232511/s59002707/0cc13b4b-6eb6eda7-c6d4528a-53523364-3a3374b1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11763439/s56673936/b88c4335-78914a8f-fb9a492f-4c3b7df5-35f234d6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11541551/s55997343/25672ec7-0d50dc13-d14068a3-75c8f5cd-84c176d6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11439122/s57272352/b29df036-af92a19f-2e9e3269-b4dd15f9-784bb5ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11227287/s51553669/9c840bf3-4faa7476-f564e368-cba48850-df19c3b3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11213912/s56675995/693a3995-847a17e9-2be651ba-151c998f-46faf1b2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11966699/s59263162/2910a888-e2914a6b-b599da1a-eb784cc6-ab7583da.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10775892/s57036378/3f33c1fb-c3f491b9-a407c925-c1fd389a-e6c34426.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13365915/s50048338/e6bbb448-ba0d10b2-d97950c6-6d017a55-0c4d2a79.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13496539/s58531151/4befcb29-9ad6b0d7-054dfff8-7c4cd988-08331a53.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16934687/s53150248/c84aa847-eb59f21a-44ecd3a8-342e858e-7a51507e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16521833/s55475885/ee0de60e-00b9808f-2d085c77-124c2b24-439bdf00.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15379667/s54351091/394105a5-53ef28a8-6e5abb91-2fca6df7-f2df076d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16426000/s58488145/a7c3687a-e49fce26-20530af1-7cd8c507-e6590e40.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16314334/s55549507/b3de9ee9-b6a27d3b-8da9824e-8b1205b8-091808f8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16200045/s54461412/99549426-b2acda78-2e960eb3-277141d1-440ec750.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11353982/s57764336/63db5920-6b30fec5-2f9b124e-730c5cc5-385a6232.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16223763/s59590851/427dfeca-45745fe5-ccdd5643-826da1c6-e6fa78a1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16470044/s53797987/04d2d75a-3afd79bf-e880b240-70c8fa1f-a1e0f700.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15426182/s53009077/b44fc29d-580d3622-a578cdb6-7c006778-b7c3a735.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15696146/s56912684/63e2aedb-c226240d-418fbf19-6e820611-1c6d9810.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10901772/s57056764/8afac5ae-faf50d08-cb1e14bc-b41d9d08-fa7b7c81.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10408562/s58850566/7a56eaa1-bc210036-0097c9a4-267cf5ac-44ac5a1e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15137973/s57760510/afdb3364-fb64c72b-549c8d51-a4906cc8-a875c3d0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16003661/s57346250/47fa4a86-4839d813-d85ff2b4-d35e0263-5a6e577c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19259478/s54141341/02c510a8-1a4d8806-fe0b38aa-908133ac-7c260266.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11648537/s51613207/638d0044-94b7180c-688eccfb-4659f52b-78f8c954.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15424569/s59849324/b8fb2f00-23a4028e-d68f0ff4-20261e29-dac69037.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16800364/s58374973/11fdba62-e2995119-7717556e-714f18c9-99235366.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13941266/s52776392/fe582f55-babd4900-2de0982b-d6b42a75-7ca31bc3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13766608/s55583684/bfc7eb7f-80a7eebb-4783f198-bf7dfd6c-9daee9d3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13694589/s57976843/1a6d7d91-1fd0758a-4e857706-f962ca9f-b253038d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17598360/s51478232/7cff9c4a-78f0f3a4-bbff3278-73bd44a6-86651b2e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17336353/s52506705/3330748b-2e2bd1fe-cd319890-e98087eb-cfe72c38.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14692345/s52788473/01109c0c-9e655546-edce1305-4798efa0-b474f615.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14949831/s56587538/58d313c4-3c00ed0e-196b3123-dea149fe-860e62c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17763551/s50725955/bb0728f0-fa909774-54ee583f-76d35b89-2735c56d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17612000/s58767084/2acdf618-b9951694-444df536-dcb8ff43-f10e5804.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13684752/s53638482/02b881b2-5e83190e-0417e475-079c4f8f-1a947279.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18402151/s57455117/1b23152e-5f1fa3ce-139ac4e7-99d9d9d0-851a3d3d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12702546/s53933800/c727b13a-16cbf320-6b0a18dd-4ec5fa92-2cca2b6c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12025572/s59307809/e3c3dd9d-f1261088-5c218bc2-5fd92d61-fae05b2e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11797247/s55973982/20aa5ef5-4cd808ca-0a7de914-ca7ee0c0-7703d706.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18161880/s56194685/36be1d78-90903ef2-0d98b482-0d585f08-570ded1b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18761260/s59780236/462f83ac-32dc406a-dd9819a8-d6884664-4795c9f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17277688/s55379449/c58359cb-c1d046c1-167279f5-64bd6223-13e0a131.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17098669/s56948930/7d77ec69-0453b4bf-8240b1d3-6c7103bc-607b624e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12677246/s58946272/56cda957-4f4c3aab-581040c7-edcd938e-f50275ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16543497/s55121630/849044cd-085f68c1-7652dd70-eae02545-a4109705.jpg

  4%|▎         | 186/5000 [00:07<02:34, 31.22it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14786549/s59253534/8961d412-5bffb3a5-4d7bd01d-3612b22b-dda56206.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14821269/s52495144/f3112969-9e0228f2-91f2f459-b3bf5c52-5442a516.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15965724/s53977085/d0f56076-0754688a-a4e9b83c-b3e8cee5-b43a8d97.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15024955/s56099256/991c1166-6e3f8d11-789fe8da-694798ed-6f3bbc55.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13977251/s53809408/9bcc8f90-554e1d54-436d87c4-0cda0a1e-9514fb59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13831190/s56074498/fbe5f841-3c9623de-fc77f5da-5b990f92-8e060b50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18049473/s56895688/c650e504-3bba9738-d29190cd-3fb3b9ad-9d0e1bb0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17002995/s53093135/68061713-5fff1c59-90ebb853-44566d77-ae9fe3c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16600921/s52897000/08eb3cd7-5a513f97-708880b8-5abfe265-bd1fdf1e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12106204/s58027451/94775276-1858f3a9-ff2923a7-a67c072f-382d2489.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19035431/s50745697/896534c4-be815aba-b2134032-6e15c69e-80275709.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19793246/s50712271/ec894491-d10ead13-c624b86c-1965d8ca-0babd060.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14398566/s59460454/b3db4b5b-2749f445-10482b3a-b679ada9-0eea6994.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16057607/s58454518/00fe1d9e-2c035ed9-258548d3-c48bd2f1-ab80c6e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11532890/s55943713/e085ad9a-e8bab575-39cde12e-64e6d84c-1dbb9570.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12504826/s50922066/5908ccbc-e6bad231-ee8386b6-ef6042bd-cff76a13.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10329745/s59872860/9e2797ed-bf279cb4-2b6e5da9-dded3f6a-9774226f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10242353/s56006933/018f8a97-d89e897b-639170d3-a39830b0-f6bd9c06.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17400716/s52396788/01327194-6af8e959-c4d85434-cf576e3e-7fb06dce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16232950/s55273730/1f4e2a9b-d53bc6b9-775bd734-6ff8b27c-bca35f91.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16889059/s51058521/e61ee4a6-005c33dc-5a251328-3478d79d-da36dbc2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12408654/s52542261/d68f37c4-6e2bc11d-a2230756-5684f883-750d1f1d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19068326/s56650217/170204f2-9d207855-4f220c79-046f4a82-8fa06801.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11984647/s55603341/23ef2140-316437ad-93785fa4-b9677f03-d0433d00.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17451560/s54190514/5f58256a-ad413113-6a9ceff2-2454e55d-0d2930dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10233088/s57596981/3904cd9c-c585a00b-b6d978a8-11e38ba4-dab20bd5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18399938/s54332667/48a2e9c6-ea5b2bcd-83f482cb-59b974ee-f75fc83e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18143490/s53028392/8b73ec29-f7f2a3cc-4340703a-b4d46c41-1f9475c0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17559288/s54970629/d295710b-13067198-5224086c-19034f1a-cec8b94f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10116310/s56996062/f6ff4430-9ae1d3cd-762827c6-f11b52ae-3e851a51.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19373022/s54951299/93919cac-b2ca07fe-2ad38c72-64cac866-4b0d2748.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12423759/s57315725/d05b3f68-f93d4f58-160a7d65-e77c15bd-69be6f2c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16462861/s59845003/afbd4eb6-9fb0d0f6-fb8e2603-cd56a9e4-36608b9f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10135376/s55854950/cff65f9c-5080b576-aaa6660b-0d89b2f0-0f8243b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10958772/s57415152/74fb60a1-88aae256-f1401e6b-ac4931f1-d1178254.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19938391/s52371525/bd659536-42ab5d8f-6514e8a1-655bf07e-4d8849f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11648170/s58990687/f959a6b7-7343da11-8aa667bf-e196adf5-3db4ca6a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10191971/s56265061/cce7a2a0-e5764b49-4bb6e9ab-a5a7a7cb-c145a405.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16203314/s51525682/4655b373-ce3f8ae7-5d82cd7b-a2e13336-b061e8da.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12064183/s54806887/2f30902f-4c555209-4e4765e4-4931d289-7c5a1751.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12513827/s50042273/48ad03dc-f72f3968-0420258e-bda8f45f-44d8ab35.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17288844/s54644366/adcf4325-aa59cd31-be329869-32fd0147-d3cd1387.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12691278/s59305940/ea3cb846-5799e493-6ffad7ae-411ba398-c6344176.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18037800/s55015899/6d19b8a4-c39483a6-58263239-65d860c5-5de62ba5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13844441/s57425946/abc14153-ca4676e5-7f71c9ce-f9028086-874891ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11086705/s51320238/0df005d7-9829e9af-0d4943f2-0f284174-626c707d.jpg

  5%|▌         | 258/5000 [00:08<01:55, 41.14it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17172702/s51602203/0aca425b-e536d0bd-31d57470-c028d6e1-d2f60e7e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10374990/s51016241/1301886a-2fab7184-0a541d4e-82376509-f457cd2d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12416498/s51241208/85295f68-72931f60-8c2551e5-c17c9c03-4258aa1e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19238215/s56047393/f4aea41d-69f9943d-71124cad-649627ab-54f4450e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12237086/s54870010/7e5b7a7c-dcf91696-1595301f-45120918-0a426d0e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10197227/s58924079/b5ad21ed-a4ee40d7-f4a21f0a-b53bf456-8fe3faa1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11135350/s53772313/cd3281a8-6fdf014d-d38263aa-913e7ac6-50920fae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15586921/s53588559/c82c2cdc-e3d34619-9d61fdad-9c4d5df5-ed943dbe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15459844/s59685814/a692ff1a-cf5ec0ac-b956ae45-655657a8-29585646.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13945603/s55683869/1cc3fe25-19cfcc9a-c87b5f7f-9b66b6b9-36575421.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18852055/s52219226/372d9777-a02424f6-f9767d5b-b7246e64-71ae38b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12819615/s56219903/9085f84d-e49c00a5-31734d75-b1472777-af3c87c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16287302/s55197593/0d13e0f5-021f7df1-4a1f02bc-e82bb985-6512cc2c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16092597/s59093707/5f0c9e57-8410a1cd-a6c0b465-05f86928-27f5e34f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14921553/s59844401/0942a151-910e9a9e-afe3ff83-5737affc-43ee6df2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14464018/s55732657/898cd8e7-602febf2-869be902-45d73bcb-75e4743b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14415891/s54246247/1140282f-ff8a1cb5-1e33ab6a-d32d86c7-6193cfbb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14473881/s57978135/9e6117fd-68c53f52-842dba3d-54561a47-51ca1d9b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11449055/s59812126/5e652bfa-61d793cc-cf40b44d-b50430aa-7b8675c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14270780/s51787459/11ee6033-634a8de3-79ae221b-a1bc2f9f-c022d9c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14234821/s54277296/76944675-f8aa7a97-3885fecd-e9eea927-d9eada8e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11958726/s54018098/1487e216-537b4d23-09a68a55-982da6fa-551c13a2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16704300/s53399056/a81cd232-4b937dd8-2696f4f2-ac8e4ce8-8b0a7b1e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11601553/s55613348/5b701e32-d8f60fbf-e8beb54f-0108ec3c-fcc7b61b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13733102/s51206796/7f4c2b09-ad5aff2b-e0e66edf-6d25fe30-60a02ce2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13174810/s52301265/52818119-4e871e7a-87a66cdc-8c62ee63-6ff8fe95.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14527555/s55108756/447e8aaa-e7655053-e5602dad-a2ed2c30-13ee4952.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12393609/s52799177/bd4da310-d5815816-4cd5771e-c341e4a4-53c03fb3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16839550/s59674063/fe973523-399311ab-30eb14d6-af12928c-02b1359a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10610928/s51190007/3750bbf6-eae3c76f-2ad1a500-9da0b50a-16586b5d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10434791/s51223891/894a0aad-00338d9c-e6f648f8-ae123c7c-a223c055.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16861844/s59736900/ae4d3585-df11b38e-866e4b13-099ce34d-4ff9d7ae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18321272/s58516191/118faeeb-8e37a955-7492599a-202c8a3c-48ecd3fc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10717732/s57045572/1f227320-8f00ccf8-5588a2a8-ecdfdf04-62b615a3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15225349/s50164921/9097dc1f-f6817715-479f4403-08353215-4be9ece4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15689523/s51196985/1f4ceb62-5da50e67-46f5a161-aba184bc-3fbe993b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16934764/s53400108/c2d8f027-9729d576-85c227f1-44983e81-0d94eb5e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13896515/s53789660/ebb4833f-b98cb523-ee32fa0a-90c24211-81d147e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16485876/s53227388/3749b3c8-3dd6e803-b76dec66-48c71d17-827a7ca8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15121841/s52351687/9f5a143a-98f22c47-0073d18a-82f666b2-be5cce3a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10755736/s57119111/76a51e41-2a76d449-bbc3e083-798951a6-a9d3fc9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19667420/s56067609/663f79ac-a7e3df55-f9f340dc-49d66327-43a47baa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16365899/s56889009/111de997-f454773c-9cd9daa4-4d2a82dd-ef2ad266.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18477696/s53009254/ab7f8cee-11fb54e7-4d874019-5b9df410-ec7ec43e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11848123/s54043593/235653dd-4b12c400-87a86e7a-b8a3050d-1e492643.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17195991/s56500894/06980cc1-94b37c18-8297f246-90ffe664-bc51fd35.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19249586/s54223468/678abec1-1cd8aaab-0d71b478-7dcdb158-576b1249.jpg

  9%|▊         | 427/5000 [00:09<00:54, 84.12it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18066099/s50909178/2513447e-b03cf408-81f2bd79-8112e007-f6c33a6b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10145417/s56206403/3398c6bd-5849d745-0208a74b-27de6ec0-d8a27eb0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11539240/s56039062/0da5464f-fa78e9c5-8fc7aa28-c687f195-97e857e7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18500562/s52547941/8ddafcc8-c8a5d481-ada7bca8-1ec9d046-afeb0212.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17963938/s52129351/b1e085a8-6a09a9cf-bccf2f79-e4416995-3f0a837b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15268828/s50288695/82d70232-cf01d666-06daeccf-e394ca56-eee51f33.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15637323/s53569368/a227dcaa-9d6dec91-5472b6d9-e67b3ba6-90c63847.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11879241/s53616612/0256f5da-c33da064-f4d9d96f-7b11c9a4-6db0ab58.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11041878/s55633032/80dadd38-64709aec-8d6b22d3-cfec467e-743a5cbe.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10457976/s50329143/9c1888da-fcc51340-7ac4a691-dfebb3ec-c2cc707a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13088713/s52779841/d2d67562-f540dfa7-db36cedd-1167b381-f1e9f922.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13712284/s55541199/b5f7fcdb-9b33060d-65d90c56-727cfc82-6ea54baa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13446842/s55880396/98f1002d-cbcc5814-be27b4bd-01abfe10-327f1c4a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15796335/s56152882/d2510d91-3f2ad513-d43c3fef-f2eb41eb-fef3d3cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19413444/s58083583/d59117df-63759428-c24f928f-cded9cc1-abff7123.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19713198/s50553732/6cd90c15-232eddc2-d91f6f95-f1101640-27eb7cad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19173988/s56740219/15042f0d-6f8331d5-3d5024cd-58c50c13-d53683fd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10224976/s51003818/d571c0ed-ef4a176c-84f1bbc0-b6e48cc6-e9bb5965.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17597298/s54771306/8eab62a0-5882a64a-bbee9866-edb6424e-d936569a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19631559/s52345693/4f8ac76c-9d14e937-39fb71b7-e89cd8fa-76b946dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17612000/s51260148/d89bb779-1ca568ef-9590f33f-80c03cc8-6b7459ad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15970241/s54089430/2484decb-d0d15ecc-12b0c318-470abe94-0da30a04.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12019930/s54406761/deed11c6-cebef128-ecacfb52-58dd441f-bd52bc72.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17690327/s56855906/425deb7a-d1e00a28-9c9f7167-29566ed4-f161acd1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16330662/s58863432/3465d598-25e41f96-dade2221-ee4ca3b5-22705b5d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14706167/s52905791/49f14ef7-5a5d5840-09032bf4-7219db8d-850a6d6d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16086306/s51296893/9c9f4a77-61aa0bd9-893aa97b-6a1742e9-0d492646.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18298823/s52434315/f341d9fe-b7498335-0d5a19ac-1db1dbf4-a8cad3d9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15574754/s50332835/b4261333-4203aa9a-5c9c5375-4923d12f-635bc03b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10398981/s58934860/e5d6588f-ec5d5b4b-c3727805-167a1b52-90e446ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18315077/s57692961/11d29ea7-69874a9d-faa2bea1-20bcc9ab-109275aa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18898820/s57599899/1a16907b-13f41cb2-7781ff34-03ae7f06-642b551b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12621822/s59433547/b4eb6c2d-5b2a37dc-06f61103-1cf7d9a1-0c8e7d4a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11441519/s59285773/c00039b5-9f930469-80107e75-0da8ebbf-cc40c979.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14310616/s58836737/4c111027-71da91c1-16a616f0-4bcec01a-88f7bdc8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12119271/s52439844/d5a1ccd8-5e34cf27-605912fa-e6af645c-189be47b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11482582/s56078591/b60a87b7-3dde787f-92f47284-c9ac71eb-432381d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18450747/s52406577/ce530667-e5a149de-da22fef7-86790de4-bdcd7cc6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19205606/s56321609/9d7b6ea0-869579e9-f524d4e1-9a4623c9-55117f9c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10382575/s52224959/fa42e310-5c6bcc42-9e0fa5ec-51668e1e-791000e8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15811456/s56499621/6ff5a532-248b2eb3-a695798e-58566a4f-71e633f2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10109398/s57416957/b5f4b672-358fd4e5-1f44c626-268c8c87-0b438ab1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19928728/s54779532/7377c600-b5a82b96-a9289684-675c7af2-ef12db9f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18156009/s59834260/e4f4d559-a4b015b9-6011de84-184ec1d5-5628854e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18727840/s58478181/a9872063-894582c6-11098791-f6d915d3-b416f32c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18742611/s57694873/ec2a7016-7abb5e6f-ec277f81-650a99c3-2d109b4e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13491843/s54831447/b103b3ae-50832a85-ae8b9e1c-47c8fc99-13951fa0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10591859/s55633642/3bc32216-bfca952b-b37059c1-16214d1a-5186bf34.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14368217/s54719665/7c014908-451cf713-84a95618-78c4562a-fb396b89.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16276490/s52174522/8b4a71ac-2efaf09b-ad228999-9c157dec-04b88dc5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18258847/s52077595/2f2c1938-9ee87657-b9f40849-81a898c4-959d3a5c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11658675/s55310365/807c83cd-c7e0a3a3-7074ac47-e37361b1-e7fac003.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11548636/s52750051/ba82d57c-e2b7172f-4886d2de-2be04550-622b064a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13119476/s57467669/9ffa3eff-c30d6758-b905985c-7e130eee-bd2bb02a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13430229/s52263098/61b669d2-615bb348-3dbd15d9-82401db9-188a15ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13332932/s57045388/f86793e4-6c9245eb-755fb5fb-d76f90b2-759164ae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15426827/s50018729/d329b1d9-aa6de532-6bead763-135e0509-832dc449.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14921725/s51208163/c20d6f7b-3224a9ff-193b0812-f103571d-72ac4fb3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12598850/s50799036/627dd5ea-772b45d5-9a35678a-24f9b7c2-e4dfe1c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11677206/s55967245/43407e2e-094eb5dd-40c5c035-db1996d8-a99aecc8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17875794/s59691586/59d012bf-1d11c7b5-513384b2-04857565-d3d05a28.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14892655/s57210428/61107159-0ade720c-34a75441-ff48295d-d6fb10c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15425725/s56731744/3fc796e4-b338d57d-ec2d0f2b-54797878-c55f1d80.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14014950/s57361332/2221c253-69f46f06-a2ab3709-9fd639c2-1a6d8aba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16905933/s53951212/ea3d98a0-5eb32126-66b0ed51-8b36c839-88002739.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17583585/s53895842/dadbf04e-2f60a1ac-9048ca27-9ac1d15f-fea44393.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16381668/s58310654/0fb73595-23b81c8d-4ea5787d-39e972a2-ac72f365.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16521799/s53590982/66aa1ea8-3545580a-519f658d-8736b35e-0c726005.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10622292/s54047557/b892bd3d-9b6fb1e2-3c14b477-29a0aa0d-3b136660.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17517983/s52490734/90277366-d95a7fa6-02e4412f-b274ff8c-e3787fd8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19388659/s59956625/dd1a32ad-0577fe4d-1d8dabea-7e6e0a71-f1c7d25a.jpg

  9%|▉         | 457/5000 [00:12<01:35, 47.41it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17083848/s54430409/e1c84b0e-140814a7-5a18dd95-f478a5b4-c639cade.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11722313/s58116567/ce54ac64-ee096f94-0ccb5d54-80ae3ba7-31712d05.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19759432/s55749468/e272c2e5-ba734f33-71b51db5-e2a02e29-3bf81970.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16086306/s58895160/98af472a-f312386b-e321a029-1fe0165d-e5e1a89d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19270543/s52288744/df4f0b56-3bb1e86d-d6c5b071-c06404eb-5490629c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13956197/s56117746/1d094933-4701bd16-5141dbc9-2410b8cf-2794f75f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18804278/s54927412/d6b2acc0-e8945ec7-534a32c9-2283214a-10603536.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19881376/s50522805/1e777b2c-8592f169-cbed8d99-fdb1e5db-bc01d606.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19025237/s56223452/5333f41b-85e19e0b-8f629d33-6c32123b-88e641db.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10023117/s52880779/89af216a-df43c172-f22dd4e8-7e4d1721-3061d169.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15175193/s51689629/c8ecc6dd-47fa2e18-cb1057e0-4d006a79-d3727241.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16297706/s51705156/2a385f1f-d260c971-9c1c23a7-4c9e948d-4b1fdabb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15245907/s57696984/fb116493-cf04a9f5-d6dc56d4-5dca9646-09850a60.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17872759/s55228988/b651bdad-1f8f2d7f-4e4c5d98-e875f473-ed755f47.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13481133/s54735631/5b9cab7b-e84fd0e1-a2a2f568-879ee2be-acb569ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19509250/s51715658/dd1fbce4-a19b6be0-bcfca829-000e7519-5495a132.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18746141/s55657217/7825133d-23ce8513-b3870c3e-c86bf58f-3c836fe4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18033939/s55870675/7221467f-a1234a88-79870234-e16ce3a3-aff05561.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15712636/s50459009/ef03dfa8-25642c12-658a7076-81b0afa1-f308b82d.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10178145/s51470432/70092b13-0246054a-8991e708-85c38bfd-52759e37.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13467916/s55996630/307b935b-a64db1d4-da57cb7b-d874d306-edfa9be5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10180652/s53458894/85bc09e3-cb263f3d-212e5d1c-ac58a845-7495bc55.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18962500/s55067168/7bd804a4-a4e1578c-9d52b98a-8f5fc53a-52448578.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11422357/s53347515/15838071-a0ba5a81-72355779-939ce614-5f19f673.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15077572/s52866309/afde0155-7319edcd-088c15c2-8280df0d-44092423.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11607177/s51720015/877ba610-eddf6174-7d465f3a-64af7ed7-cefbb567.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12531206/s53469305/882ee660-514fade6-00077e64-09352438-8a889456.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12006266/s53894773/153f34f8-a0656ec2-be7dfdb4-39ead012-e25581de.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12573085/s53157910/32c108e3-92ea7a51-3dbfc4cb-f2793843-5fdb6578.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10245082/s56831888/1835187e-0883e736-54fce785-3a1a9968-9ca5ccdc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14786549/s56327856/54b45e28-93ba38aa-0b589c65-98d4a3e9-9ea75fc5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11002435/s59259042/81cd654d-43f3ccd9-44709fb9-3df85612-6dc5cd1a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11132868/s59945611/ae5d53d1-43b9fa35-15189ced-d834ae10-af40ead3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13974990/s50980783/8e0be205-c1e93cd9-426e8cc8-c38a1c2d-a9a27d3f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12724975/s58157825/db677b43-a7636e1e-d48b1ae8-7397795a-02cb1192.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18995174/s57261740/954c721f-41abb036-82d11539-0f1e4134-c1e2f70c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13860785/s58561900/143cdf42-c1e4358f-1f1c74c9-0f3d0f63-965ff813.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12027769/s53192803/036ccc6a-d741c0f8-2c342af6-63d75ebe-12aa4737.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12993146/s51889609/972bd32d-e70a7d57-3c22dda1-b86083b0-832a2eb4.jpg

 11%|█▏        | 574/5000 [00:13<01:13, 60.46it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16560125/s55354277/c8f9dabc-fab233f7-ca60d29c-5ad67a18-38fc91a2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13527938/s52158548/81172d71-7c2e7241-40590278-c5759b5e-5dfdc469.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13027405/s52219547/d8427d6b-1ff4c07b-a276431b-8e780a23-f73c06ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18128235/s56276296/d69cd2b7-98acd028-053e6688-80f5962f-fa2be62b.jpg

 14%|█▍        | 709/5000 [00:13<00:41, 102.52it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10046679/s57782654/1b6354ef-49bf6da0-9f681397-5d1fa44e-b8b324be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18307935/s54873121/0c8237c7-82cadab9-10e9fa5d-f1d5b61e-3ff9f9a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11315261/s59737161/d8e44355-afa5345c-eda6f522-6291e9ce-74a8984c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15033599/s57036467/2c19db34-673299d5-a443151e-2d8b1988-5196c5cc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16617031/s57452155/e59efb80-f235c3c7-ad5f4870-05da4ac2-fae128dc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19368870/s55154247/6beb5f82-5c4eda89-a670f171-b83e37b5-ab5931e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13343224/s51025864/1822a7cb-bdbac7f7-cdba0143-1515e5a9-17c1da7d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11527001/s51438255/ec9ac7f7-ce1cd70b-ccf71fc4-37f07716-c248074d.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12601251/s53595724/28bb1a43-a8cb9104-0c42bed4-47b38faf-14704037.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15119590/s53019195/0cac2df7-dfe86f9b-c8114b8b-55fd0664-1fdf1552.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17340686/s55921730/fcefff91-22ab7055-235f085c-ea9ac8ad-bbdaa83c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15816613/s55665409/a12e4e54-4a8cf9a9-ac9c7087-d189199d-e2685edf.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12620045/s52854198/786ee4ff-3fd0ace1-f6b1fdff-ee0e40d7-6f916aeb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12263568/s55433592/ec49fa3c-81286852-03afb1f8-8aeb302e-48ab404c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12788432/s56832620/a53a44fd-f150f026-d16289f0-ed3652cc-d3d36d75.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12726753/s50294295/35a4bdde-3f018751-3d2c6b51-15983e31-7b7e4de4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17697134/s59857129/1e6de43e-fa5bb671-c3497a0e-7593fe8a-88149382.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17140082/s54636584/57e1cefa-1f267a7d-22a84a9b-81603a36-478ead4d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17850184/s51664302/d37ee52d-8938b225-ee6395bd-cd2e575f-ca5f36e4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18995174/s50818159/86da85f4-13684538-5591e53c-1a18c965-cdcff6c0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19635953/s52340518/5bcf13b2-6935250c-e6fc836f-b15d8afd-e0d2a52f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16113543/s50812822/a14323e5-f4fe35fd-aa9ff12d-3c90ab04-c03704e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12911944/s54506624/d350a26f-ff65c7ae-218fc783-5994fed3-f31d588d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11297219/s55368200/03c931f8-d19eb1f1-0ad115cd-144cc27c-46f55be9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19338519/s58922068/205553c5-243be494-961e2c1c-0a6eaa89-8ab50e98.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19335948/s56604728/7e4bff4f-8e214eab-1a044bf6-7d0dc834-12353087.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19843082/s54775728/83ac2cc9-b87ceda5-3d5b643f-d75c8c67-aec42a65.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10197716/s59796322/e0ee3ee9-8f366e71-8a7ff407-80560a08-56fd392a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10476869/s58477944/6e690949-2670a76a-8c8acf51-749562e8-b72968c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16681170/s50461458/9f6d5b23-9fae1d65-6c37b381-7e77e9fb-6642bcbf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12159404/s57886086/a5d1dc3c-7cc95685-929ff13a-11992eb6-12ef4ece.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13648633/s56210371/eaae9122-31f79963-30bf5106-0d545178-db951a15.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16243656/s50669293/2a2df0c7-65b8d06c-a73c3bd5-bf721aa3-92321708.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11532890/s52365750/e2e4635d-f71e8334-440d098b-c3333d63-c1c53c8d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10361825/s57490524/9df86ab8-de467454-82c93d96-ba9dda45-7c86bfbc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11439927/s56834910/5558286e-cc44dbfb-0b996811-a511f118-7c3d4756.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10669695/s58812773/ae89d3b9-b5c3cca5-3b41579f-33cdc5fb-7770f9d7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10151556/s59864083/2f8a0775-62cf7270-136e2c35-0c8a1238-331e3a23.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10117273/s53559076/370cc9e7-a6060cfa-95fd09d0-dd6910d5-ee94028f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10471469/s57251432/b344ace9-f6d12b46-ad3c9377-aa61b285-d6bddb57.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18994929/s50658183/f9d48de6-15469e76-dfa67bf1-52be65c0-b352cf5c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17457354/s56595572/53d6e716-25481dcf-566fb86c-205f90c0-d5bfafb9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11249512/s50284811/11045257-abfa7c4c-51f8759c-0860dbaa-585fbb38.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19650283/s53959568/2406eec4-b47fcd97-dadc0b32-baef4228-a6251563.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18418572/s50294680/6cde32d3-52597273-e93bdd1d-2a37cfbf-b1326283.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18065565/s55345852/2a382998-0907ee0b-62815676-688ecb08-11f1af51.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18662708/s54610289/ba4e25c4-c2702015-5157576f-ab9d7940-2c0e320b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12406522/s59111673/807809ac-b9c479ba-c9b2e978-62509571-554200b8.jpg

 15%|█▌        | 753/5000 [00:14<00:49, 86.20it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18879223/s50514500/71ab6467-740dd792-5ee6b9bf-ed55e99a-6cbe94b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15147932/s50944756/f0a28fc8-7e914777-bf9e004e-1c45ce62-5e0cc44c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10320090/s59169604/72274138-7ce66b73-e2efdbbb-d256f0ce-90ca234e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13203329/s56944806/65534b52-7aad2c9e-31130bd2-f3b71b64-29920bd6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14634306/s51443611/56af05a2-d521be5b-5ec8a763-0304da18-a5b5d82d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19655295/s59611454/607083d9-1b236773-2612d4c6-0d3861ce-1892bd77.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17763551/s54856086/92a0b949-cd8e20f5-0ec5a9d2-3d722a31-9e1de50a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11152718/s58404043/c9dbb31f-6fea912c-ebf28ffd-6dc2f158-7bbfd85f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10327156/s56155924/4f774645-5b515ba7-54a4b882-b8e8a6ce-0300760d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10149722/s59687570/0a316503-e72d1ef3-aa73a7d2-975e8089-6dd0aacd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11981987/s51955011/77c63414-3867f9ce-53918b11-996fb7f8-89cba4fe.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10226496/s59509337/bff3986a-3c2c122f-c13c416e-f710cb3c-97d0069e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16635089/s54881025/675a9cc4-68d98c2b-f5997bc0-633111fe-933e9a01.jpg

 16%|█▌        | 785/5000 [00:14<00:50, 84.27it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15353701/s55788114/d7de7767-13e301af-5bdd565f-ca94a020-affacdb6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13098601/s56877296/727f56f3-d839c9ec-c04086d6-34f089b3-dec98dd2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18632932/s51244040/8868220b-ac06594b-5830af57-bc03055c-b8aa9cf9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18513641/s54278441/c5a14f2e-e38a1ec3-a5d1cd2d-77fee3ee-9d10e264.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19797689/s51614740/a58d9cb9-4e866b3d-ca912797-6134e560-6aa3b825.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13481227/s59859349/da75be87-223d1d64-94ad7921-76292cee-5243c012.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17823921/s57342213/6acc91c7-b5dc88c8-04ad1e37-d8ea2e71-c0937ad4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17370807/s59311619/d7bc3924-81fc4f4f-23ecd4cc-f28d24d4-bbdbb8af.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17814954/s50328324/3df830c1-6bcc023c-667f9eb6-57a10165-432fdb14.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14967359/s51325149/80d94d9b-4c558a4d-66fce5a1-e270cc3c-fd2e072c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11725800/s51427279/5e7963cd-e1c5a399-3d99d3f3-7a5ec3cb-cf1792cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10394897/s58175830/811e29d3-2fbf9cde-45dbed22-61763312-581629ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15952397/s57629401/500ccb45-747f7726-d338a293-1d80f10d-ecddc7e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11548266/s50338856/e0128a52-47759b51-d379086e-dee5fd4e-cc17ae21.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16840682/s50121976/6524f323-21a0acd7-d2253054-6063e5ed-d20fafc8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16773796/s58084420/7494cb49-099d351b-0e03726b-10674f3a-b482faaa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16701608/s56016395/8dcaa148-9b420fca-c9da0725-30ffd9c1-f5705fe9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10930322/s52078313/9884c40c-75f1cb21-10ffa8e0-ed5e9969-f92483fd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14102384/s53992940/35e534cb-99ddc932-01ef7d0c-3f37028b-0a7a19ac.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14517807/s56493170/89946f7c-4a833748-49595e40-72822a71-ae687d94.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10021487/s51955860/9d05efbe-b474c031-b94c3bac-081b238e-f816a7e0.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11583269/s59815336/3b6a5b99-ed2ab1f1-ce32b5a3-a7668f59-3f61ced2.jpg

 16%|█▌        | 810/5000 [00:15<00:55, 76.13it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12553538/s56260929/7f9d790f-5edf1ee8-1e2ba362-c2c0ace4-c2c6f840.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12444275/s56191073/56c83867-02e5fe51-d43433b3-1beb8c24-fe2c8149.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12183714/s54436727/22b1076e-10a4f0c0-08f43417-01ec74a9-e856ec18.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14486034/s58685970/312ce161-6ecd20d3-aeef3e10-8f7d1e70-9add23a1.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12863592/s53278455/5afd6876-25169645-3e901601-4fbcf9e5-ec1d244e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12404412/s57940267/deee1edf-9751511f-7227b9bb-5287152d-e0ca6020.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12135022/s50537556/d2b5c63d-bfe3a65e-efcedd03-3ddd80bc-d9c5c9af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12447402/s59361689/64cd2fb1-2a4b75fc-3c186de1-e1bd11c6-2d2ed2a4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12476587/s53882176/1255a090-dad8c341-80659b05-ca09f18a-8c3d067c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11966397/s55574170/ddbd3cc1-52708e98-09d769a6-cb711f85-6a2f7349.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10520145/s58204628/43634189-095e2512-ebfccfbc-cb380fa9-f280351d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16428221/s56325349/4306315f-83b99062-7e15b165-291a1e92-95a30322.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11769254/s59671319/7238f578-1e8af66d-f6429106-6ff96175-bd4d88fc.jpg

 17%|█▋        | 829/5000 [00:15<00:53, 77.92it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17800278/s52266983/297f5751-ff8054c8-869ae362-45a9ed06-3579cd7a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17147966/s53295710/ab5805c7-05bb30ed-64d6c386-23f7cb9d-2e2917f5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17978114/s50763076/3f6327e3-7c53f90c-51207988-c98e2ddb-8ab096e6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17049363/s50191763/48970a4e-35cb8719-1e2cdf9a-e7b1e913-fde17a01.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17286356/s57054667/121632a4-679e7a4f-65ad7b5d-5317b7a2-2c37c26f.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19533730/s59507190/6ed757b4-39995a2b-d6d084fe-c5ffe086-bbf0ec7c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10195979/s54815277/5ba2a8d0-49238a42-0173571d-d353c3ea-36d92038.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11928692/s54164323/405e6cc1-70b9d9b3-1c752677-010c4ee9-b217b783.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10489424/s54073228/277d6eac-5c7a3640-f1b696cb-a751817f-d06d19df.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14984395/s54834940/07771d97-c57e1fce-6564bfc0-b6c54cdc-0898b3ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14531257/s51643234/2a2b1015-794d1bed-827c3132-3d0488e1-68178566.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14372025/s50815613/4f5b7482-45cfda22-5a0aaf43-c03762b2-2609a606.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15682814/s55913488/de6d98ed-59eb77e1-78a06a11-a1813566-4a801da3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10886389/s57245909/1dd3f677-7b9e2db2-eb425a6d-bafb791d-ff507821.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19777120/s51748483/f8ef0ef4-5cc1e4c9-bf9ff26d-a410f8ad-1df94e57.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16030116/s57668483/652155ca-cf055a80-e075315f-53731fdb-dccc71f0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19427719/s55083904/1ea5f9bd-3c1bac7e-8ddda37c-85b8f926-bb1f539a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19535344/s57187984/3f8b847b-e0b76f40-8df4f4c3-091e9b2d-41884f96.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19488061/s59343302/25a70420-4879c018-26a563bc-b915e699-cd01a0aa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11894825/s57629787/9047a7c7-c6d52772-b285f631-f7a1c406-4e65da22.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11873032/s56025418/564ad1e0-0d4f2faf-8ec900b6-19467a8b-8a0034ec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12051958/s54592502/edde1526-daab8805-6af34a75-8f2617a3-50ebddab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16325273/s51101893/238a2df6-89e4903d-9c1b3959-262d9f43-2e828826.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16449190/s50871420/54cda78f-02b2b91f-3bb88971-ca816ad2-67865508.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10335293/s57299722/d84d4e5e-06d16d87-cfde158e-cefdab60-ac17bd34.jpg

 17%|█▋        | 873/5000 [00:15<00:47, 86.37it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19773753/s58060880/ddc8ca5c-cad75f0e-eccdcacd-77377915-69874d4a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11881853/s52002780/947fbcf6-a59c5f02-a139ecae-2a7631b1-ad9f816e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11970980/s55459010/4090bf58-91aacf6a-6156a197-784191fa-ef451f68.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18369032/s55791686/7a4419c6-95c3e41e-1bb3de64-2c9279fa-71caa683.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16426580/s51029639/cdbbc28e-4bf65121-d41a0805-8db5a769-6049c5b7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16367950/s50149006/d75a59a0-70356f38-6b9b738a-1415a9fc-22c941be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10989760/s59412231/ffe74dc0-21c3a18b-60e117be-0e0835aa-8c8d6a37.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15796335/s54679714/85605b36-5a081456-e479014e-e6bd0174-5d28e099.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10838161/s54425585/a42617d3-9830110a-f18bacbf-9030d35a-c310b860.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16053405/s59346435/0853126c-fded6d33-97200dd5-a500ef93-67d1c74a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12698729/s50186150/63cbb7c3-1736928e-5615820c-5926188d-6867e696.jpg

 18%|█▊        | 888/5000 [00:16<00:49, 83.68it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12128253/s52673013/084ce60a-eae75390-712fc462-b2dd34a6-161c4d8f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19943755/s55058866/b41db189-81d57559-41b04ee3-45cf8969-fd88cfea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17767787/s55517212/dee868e2-c0a1b8dc-8fd18431-fb1ef21f-b6cd3421.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13840639/s59277971/da98e186-fcf3beea-c73a329f-7c237370-6e4255d3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11990968/s54314565/d0e5d4e6-0bfc934c-e3968b70-fa2f999f-6e75c9ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14065959/s53360314/087c8ed5-e062e972-de53867a-1a9deb48-1f16147e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15506615/s59532036/a202ce38-ad2a7b0c-643fb1d3-e8780ddf-14cb5072.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15793456/s53694115/5100714a-7795bb79-6d9a8ab9-2ec22e74-610e28ef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18023511/s55232155/0520b33e-8b9fa5d2-2d1a0e1e-1db9237d-7b7074f3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18358319/s59701436/656a0ed5-94e2b62f-3116829b-785e87f2-aead6091.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10898945/s58494512/d82827dd-a16b3946-53bacf48-5fa8bff1-050b80c8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16324879/s50493609/4afcb710-203a05ae-0db156d4-b08d9446-04bdccb8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17548718/s56006443/ac01eec8-a6680052-b9e38726-2159be47-dcd25c51.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17028437/s55357971/3f3c0af1-158a57d0-08baee05-3867ee65-071bc34b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10580148/s56365712/34859384-b3cf1fc1-dd89177f-1f396255-61659c0b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17948573/s53719140/283c7b52-7f7bbe47-c1ed772a-dc725ad1-c3955f5f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10354450/s59676639/6f399203-04ad1d64-b99f52b5-f54906a0-982ba720.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16006840/s50955214/ba0a6d41-cceeb08b-4cb67f99-ac3635c0-ab95d4ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15951258/s56205645/1efa888a-b2dedb24-e193ca00-115b5e8a-cb75fcbf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16751749/s57123927/9119a930-f6f4b42c-7a484c12-258d4a4a-b033a356.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17374465/s59594333/a7598935-229ead0c-0cd8c842-aba3fe83-5538e235.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17800953/s52142152/9805b6c6-dcb617ec-6d82c62b-7d1cce2b-99f13b45.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10375986/s52644701/38aeef25-aecbf7d7-8f4f0700-6653dc4d-4b6ad2bc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18705722/s59088504/99fbe478-c67be6fc-c572511c-cca4a45b-a04ccfec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10224976/s53517305/eabff76b-fee7e6e7-043b7103-923dd7e9-e08b950d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14180468/s57849546/1bf81123-94b3a594-7b75bc04-dc5ab487-6b145d52.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14203508/s56090577/e70d0130-48072f5d-af286245-f17977f9-0f69798b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15421455/s54083427/7bf3eec3-bad189a3-38534aec-c91b94f3-2f332f6a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18346402/s56975286/89a439c1-60bb901d-4cc7aac3-377a19a2-0d96fa7c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17521365/s53027704/17b332ee-6dc74082-bcc8b1e0-0fab09b5-d19004fd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11268579/s51730355/6a60a208-90f427c5-136e4fe4-7d05070c-ca710edc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18299196/s52719379/b716057e-1a0a2e93-7111a5af-09115e19-f30b80f3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14848660/s53268228/ba1e9983-bfab776f-0fc3c1bb-a9516095-e5f79501.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18975498/s51819837/60ecb35b-3d142aa6-22991269-9896cf4a-baf68218.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14252822/s50223899/208ce220-33c6c5d3-9fcc3a36-4c8fc33f-150fff5a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16820620/s57246923/65dc4cd8-bdb63dc6-26bb0bf8-4eb3c210-aef32949.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11306899/s58522677/0c01ef90-20f6be1a-f8fcbf07-8d5d8f88-593fd90e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19025237/s51258801/42296911-3ec7c82e-12d867db-b3dab099-d764024c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17675016/s50113680/1d18665a-c7fce968-860d7a5b-b1dc4c56-8dd0ff83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16092597/s59894902/602856a3-142d104e-ff3e7c75-6671e489-079d6e7d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19793246/s51413943/1e56d08d-34251a76-45131101-ff55813b-5080cc72.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16842228/s56903191/d044d7fb-126a1358-d854ff6b-d3c148d8-f1b98bda.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10320090/s51027981/b6d974ed-80a13ccf-cde759e5-b98acea5-2ae99995.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19845120/s56477711/19d66878-15dc18ad-59dd99d6-7e953943-8dcbd838.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11442840/s57985247/fffca9b8-7caab0cb-4449d872-a04568f6-98bc4b94.jpg

 18%|█▊        | 904/5000 [00:17<01:26, 47.22it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18624005/s58316556/f211669d-ffc2f056-8bb7cc81-c58a18e9-2fef3ef7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19431252/s52703454/50978c6b-a7fcbd50-1f190a55-2fa4de00-20ff36b2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11861017/s54256011/b1519cc9-98c7d816-cdfae9eb-fa4fb685-4e0ba504.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16434143/s55322181/85d3f72a-7c01e7df-bbc82fc7-1feba955-57ff2876.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14628457/s56031352/6f4b6f79-93c903eb-175f4e89-bbc75c8d-b43c2e86.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13129491/s56009963/78dcc21c-5d07d988-7cd8c952-8cdff310-8656d559.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13272752/s50758560/a58cd324-a4938ddd-70d94730-5d7ad824-f656e586.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13880645/s57495992/9b0da55f-2f554326-61cfe6dc-35e7e1e2-f4cb3dda.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17562503/s58410198/e70ec274-a46f1b76-562fc490-39726b52-4ac57105.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10989799/s56002857/85a483f0-8fd6c744-4dc4d693-25d314e8-c3114b72.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19807716/s59234738/347d9154-ef34355e-34789398-2c08ac1c-0d7f35a2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19805942/s51934751/498bc8b2-d8876903-d867f28f-f0798bb0-720cf925.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16264442/s52292967/8043ee42-c2ad9721-459c61a5-3331afc2-cb162ab8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15180359/s58428939/0b7a9cb9-543f84e5-7800246e-ede18d64-05c2de12.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15517908/s58600590/350ec702-a9519159-fc6667c9-9f49dc1e-a6ea2330.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10557857/s52132789/f2f90a98-242625f0-8f44580b-8415dc9d-e09b7fec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11648387/s51991190/4011cd40-73f2eae1-5401da8e-999a7168-c91134ce.jpg

 18%|█▊        | 917/5000 [00:17<01:34, 42.99it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17391510/s51388524/19a205f1-0718e800-b19a9bbb-2010f435-2ed4c1ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18052788/s50775920/0ae70b67-aab7641a-c3ca5c75-de73bb64-bfb46d9a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13616762/s57512115/9389cc3d-4a92ec35-e50fb541-81e6a51d-aea4c43a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12338362/s50863207/78bf1ef3-bb3a427f-969bfc85-0c97c099-a748fda3.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12251689/s52948637/a7f7371f-d826c10f-f30f14a3-299b4328-6029ad5e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12293804/s55255338/effd11e7-22e570b3-123ea140-33fa0e50-a983a7ca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12268481/s56345944/96d25247-6097a924-11c7332e-12abc3c6-f1aadcdb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19303239/s51416134/29d42410-e0a1ca71-73164352-c5e3aad4-ae88f6b5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19149321/s52417732/56152f95-a92c30d5-116b8b27-1a9eff13-8969f4a4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18116982/s54400262/72a91083-0608df46-5cb4c584-18ef162f-38ffdb9f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19813574/s51692672/8d665c0a-ca40daf7-d5b0fb2a-6c7d2f13-57ea4475.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13090641/s50375287/803a9128-2a0f68be-f1fe32ef-38bfef60-55c26d17.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15854157/s58176997/81702c0a-afd1ed12-5a52cd3f-31c70742-392d5611.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15589086/s59866429/83f5a031-0ec4d5f2-cc880a1d-b4313d00-1f161d61.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13721591/s53438190/5642a08c-071bc3fb-a8035aee-0d70227b-3de4121c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13470788/s50261017/2bcad39b-7cbb610f-0834fee9-6bc42171-b37c4bad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10193372/s58856096/3d90098e-c30b1f7a-afa8a328-1cb95c56-6cbbb32b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18828209/s55583818/00a4dded-331890a1-cb1c5181-b6927bd2-3ac3c603.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10026255/s57824622/c29320a7-dc1b4175-ea373549-5304bb54-54587c85.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15062911/s56884109/2545eddb-dc74dc79-5391a876-9dde419e-255585b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19955994/s54535614/4c0867d3-605e214e-8934d3af-24c2996b-b4f085fc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13349201/s57157593/c8e72940-bcdddfcd-0584dcb0-b7eebb0a-d9f37ebe.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12323119/s55472138/0f61cac4-5273bcf6-f011bbf7-2a24ff1b-9c03737a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11984647/s50912149/67e3ef72-5983e585-658966d1-add5281f-23d4e2df.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13525805/s52925518/c743fe4c-38bbf6e3-bd99e2c9-1c1c41a7-4878a542.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16954290/s59020913/10427ebb-d7a815f8-3e2c7727-7cc0839a-07084b6c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18322589/s58349137/f59791dd-2e8e1e7a-607b2f6e-18b713c7-aed09023.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10368327/s54755729/fbc38e8e-386006f0-26899427-267959c0-61357843.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10989760/s58541791/2510f6ec-5948a4f1-5b3e3336-e6ffad83-51202ae0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18190489/s59639560/f6620aea-048e07bc-688b3583-208cf36a-a27de491.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12589336/s56269373/4c4af9ef-4093f79b-c459b6c3-bf6d3ea0-9fcbf02e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15902186/s59756362/21d84ce1-7774c9a9-d9b893f8-bdb4e59e-d4bf325d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17278932/s59504404/7a104033-758c7f59-a1c9da8a-448edee5-a0e78d8f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10057005/s56057364/86d872e8-00b86ec3-29cc71d6-aaca7905-1999e9e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17182700/s57667637/793d28e6-f04b0975-395c03bc-6ded951a-ac743b3f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13844441/s58191194/51f9d0e9-ee91ca44-cc089881-6ef5ac75-054662d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10781156/s52401852/c643d02f-2e12beab-4fa61221-e17d70b6-75a52d9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12698729/s55243696/6f0551c3-8e338dff-cb09d1a8-be2b4fca-26cd07ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14000990/s59704054/99f8501b-b7a0e074-050a4baf-e1b06a70-c5834ba4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10667797/s50692384/bb670410-d0f4fd4b-5deae0cc-c4204316-2948130f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11725800/s50213561/79ba1d2b-bfe4a0da-84859a19-fe6c90b2-4ef25fab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11625962/s52668617/9b65d20a-0680c831-798fc9ea-3b625b33-d690a549.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13046313/s54886944/69b77582-02d94498-8d8c479f-986a568c-16096bdf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16113201/s58107178/39cdc855-fcec783c-3f89b74e-532c2b9a-4aeac042.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15771239/s53749605/51e22fed-52cd498c-667510b0-737a9e93-1be6d479.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17309553/s54364664/dec6c009-a929061e-ff93c5d5-172449c5-2d74df32.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19918971/s53647572/7d34370a-133ad888-da87ec6e-76b8fb59-c904aec5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19123301/s58609337/5bc84afb-939ddcb3-31d06f8e-d2a293aa-42f40303.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15403852/s50859676/c71e5cc2-96792e00-1d050b6f-96ad753b-5dad8f5e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17715939/s57794590/ce36cbb2-edbf6a35-dfc6a5ca-b17a6348-c1e2710e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15682570/s52853669/3801821a-c5c0c9e9-5b3ac40f-a9e637dd-6b86b349.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17595401/s55570493/a5974f6b-58bb696a-49ddd383-d5148fbc-7986bba5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14166603/s50883680/2aeb51ba-04800f43-60307676-dc9a2111-35696c04.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18207287/s59039911/8132c84e-08c40cd8-db21f086-8d1bec11-49856d86.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15308966/s55787748/14d3f3a0-fbf26a0a-0d134466-6f699ca5-dcd3aa41.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15130765/s54349163/4ba3424c-bd3eedd2-4afe4b37-a0be8376-96b71dad.jpg

 20%|██        | 1020/5000 [00:19<01:13, 53.83it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11273854/s50364985/e9bdbc10-02f85361-7dfd5a36-24935c85-6e8286e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13186108/s51051097/210a3764-d3c6126e-53f8f64c-9467a867-a909693c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19774071/s50968346/a845aff6-4fad6b8b-efeb96d7-2fe6d736-3302db1a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19116514/s51976072/7cccb45e-6437c3d3-0baf669c-b209f38e-f1259b22.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19385130/s51370385/11cade08-f3599874-91df70b3-22b93f09-be148302.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13441375/s56485111/e24de1f1-5a8a1169-eccfec9f-cd13d6f2-46d49213.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17172702/s52719943/f8b59525-14dc58fe-dd82e715-f97b9558-7f7f969a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11209060/s57831075/fcd81c43-c53f5d33-2786fbf4-e2155645-413777be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12805811/s59342188/8de97ae3-dc947690-ec32fcdf-0880ac63-703d0704.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16103537/s53503405/42de91b5-0a29a507-072e47b9-bead3bbf-28c0d94e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16865608/s58030663/258c5521-ec5820c6-2ab122a2-bc34d0f1-2aed9cab.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19437821/s57375542/79bd43ec-e8015aad-2c598b44-d7cb5b85-eae63e3e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19164039/s51053330/6f0a238d-cfb78cc0-589a974a-fe27524c-136275e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10545740/s51509540/3e978d26-25694cc3-d71c7f8e-05d3b85b-d1bbb9b3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17520318/s54474339/dfc5c6b9-faecdb04-3c2516c4-48a8c688-4188b289.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14519466/s53103839/b7fc32d2-2263d03a-ba3b7a8f-84853546-e344e198.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14697497/s51392505/71f2da96-c283a79c-ba0e7798-b27f65cb-12ca7a83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17058654/s59177431/a0c125fe-cbfba945-ec1b33c7-e8d602c0-827ad2f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15355222/s50019013/020c090d-ec45a115-6ab5417c-467086f0-24d4e65f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10790860/s55542575/bb3c5c5d-25183e5f-2fa36ab2-5df75026-02508bb0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12848856/s59342966/1136a06f-f6efbcbf-6bfacc35-446c4e72-6dbd149f.jpg

 21%|██▏       | 1065/5000 [00:19<01:05, 59.93it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13012861/s50892774/254106cb-972c1e21-3d917a78-3426c75c-8daf742a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18186439/s52368019/e27e9d95-7660d673-cc290a34-e507752a-22e23905.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18694024/s54553378/60080a55-0fd8a60b-640dd3df-86f45ad6-208e94ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17775768/s51248636/aed7ca87-07c92aac-ccb412b4-4463afdf-9e73f0ca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10904848/s57034262/53abe81e-e68cd3ab-82dafca5-2b167594-ceadb588.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18958108/s50895277/0155a440-1d4d4c25-c9e28a05-dcd1a1ec-ce4ef1d3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18264198/s55309695/4184115d-1b0e6de2-66e56468-d90c8a87-bc3b7403.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18940596/s59895491/a7a0bf5f-73953cf6-d790a1f3-e0fae7f4-30d643d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18253547/s54165124/afaed89b-1390f009-52aab09a-bfa95b27-e97b9c19.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18919271/s51013310/ef9d96e1-c8f42c8e-b39ab4d1-1e2cf940-882900c7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16662316/s50893918/733b71d0-592479c4-0a5d1385-4b3ba447-23f8ab21.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10692459/s52058371/1a5326fd-24be9dc0-c40900df-df8cea4c-45a72e7a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13825137/s53238909/65fbb09d-c5735d73-e085414b-222d7fe5-2f3ff47a.jpg

 23%|██▎       | 1140/5000 [00:20<00:45, 84.58it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14928790/s54727588/fdceaf1d-745e32c4-a15ffeaa-bdf8ceab-7318c7e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10884125/s54869758/c0278020-8f7e30f9-a825321a-84257279-cfa91007.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13515629/s54955533/b62f39da-73254c55-2286ed57-f8cf1d84-0e910cfc.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13894879/s58694946/5d8cd44b-4822d51d-f4c93d54-13c97480-f62a4176.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13183778/s53004183/df85061f-3d0cb422-0feadc6d-b5b07532-4c358565.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13379857/s51173108/ffc5e81b-5d618a73-76a06d73-811285d2-f0148992.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13999026/s50875344/8653cce3-c016cb8a-1b9cedec-6d148d79-0a3b6dbd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18845894/s55401563/34dfa162-53dcca8b-e370fe31-6a01c5f0-93f8e88b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10790860/s58425672/cb7755e8-e9fa7b3c-dbffc508-133627ab-21e2908f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18148412/s51268116/f7935532-8540faf2-a26fa00e-cf34f54a-59918603.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18247129/s56042179/cc3f5c22-6286fb0e-be330dbb-bc564cbd-73d3b75c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11782912/s50311414/0104629f-11f7eae6-d488c504-831a209b-ac904389.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10634160/s51116050/af009d85-82f89b1b-ee330548-f8515158-91967ee7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14280430/s59634987/0434db49-05ae7a07-9252e4ca-7a7dcfa0-53384f09.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14352573/s56894019/43832918-8bdc55ee-ddbad181-1642262b-4a9fde50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16281901/s53789839/2e4d61b3-bfdbc05b-61e7bb6d-de1da011-56045d42.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12939877/s53697862/78bee4e3-46c839b9-c4054946-f95cb11f-939d21c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11087917/s51023876/21486a90-66f89ba3-38256c3a-92b59a40-452bed44.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14358566/s51494910/dd1eeff4-5a87b4f7-c939441a-65c6af70-02f65076.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13339704/s50985680/8cc37962-31d98d00-c8b90a19-bfa63f09-78761280.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18232511/s53488998/b773ecf3-557bb927-042d8841-22e33f6a-0002cf94.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10580148/s53671771/c2c1c431-8114d651-40a0f3a1-4000e24a-b196b811.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12351810/s57550468/45ffadb8-d3fd7ee7-8f1e4465-42bceb13-1fe5c1d9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19615440/s59887041/8175e72f-a367a359-ffdb79f5-793d3c1f-f18ada86.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14782843/s52408391/0b185b01-a149e44e-adbf88e5-259b58b2-c5ca920a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18426683/s51660082/c3ccb444-0b133a32-1bfbbcac-87b04842-16468c86.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11607177/s52947138/988054b3-2f284682-ecf635a2-70843d67-87f06449.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13588195/s52585398/45a81d80-11ca834e-437d28c9-710e9481-44c79368.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13193330/s59154909/8c4d5914-05a6a31d-5b0dfeb4-09b27329-d2a20cc6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13399504/s52663907/27ccd219-74250114-6482da97-efd51baa-26db25a5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15488912/s50769064/73c36bea-9c34a16f-ec726892-eced48b9-e67da6e1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15752845/s53039720/bb43d19e-99c7ccd9-c49a9863-c77abf54-26952f84.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17710466/s52391713/e13a4d0f-4d11844a-f77de615-adecf3b3-2fa39965.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12256822/s54411868/1a31aead-ad0425a9-b42cb3fc-f801d577-fe0416b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17202838/s55857512/b4458fe0-a6b1dbb6-92fe321e-071a3235-2210748c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11203123/s58108841/f6233109-00ced46a-67dea6a9-4a66434d-914b5c9c.jpg

 25%|██▍       | 1227/5000 [00:21<00:43, 86.86it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17172316/s56347147/5c6aacf6-7e8f252f-52c0b28c-e2f0d42a-97d2ea25.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10763729/s59635751/350e4b09-5a2cdcbb-c94f3847-b2edc90d-92b8cdb7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14405232/s57146437/c00476b3-2bd45c40-5347c5d1-823b2e30-d2f62551.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15571243/s51009089/e17ea68b-faf8a71d-cf8609bd-4f8115c1-1e271ffa.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12440965/s53071585/51ed74b0-875bc677-f205e89a-414d426e-ea627305.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18055482/s50816346/1324c240-db22ce25-fbd88469-4278bdc5-7b761c37.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15944183/s55536744/ad5275d4-fbaa415d-4a2a9e68-5fae4f5b-7b06f40d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13159904/s56826921/8855a02d-62da6ad5-b1e47fd5-fc30d4ad-f2cbb526.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17066802/s56517802/00636a9e-1cf570af-91ef624e-fb50c73f-ced2bf92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13184933/s51905928/651c4169-94a729d0-c106e57b-c9c4864f-da822a8c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17362900/s53820175/2412cb8e-e6704e9f-d83c4280-f6e0a5fc-139d6b54.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17718978/s55103957/1ff7dfec-fdbb04ff-cdee4eee-1bef66d6-278eb2ac.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15326204/s54628199/e745faad-dc14829c-d0f0fd03-cea4c202-c15ee194.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11152474/s51959639/cdc9d1ed-44e560b9-567db13f-747df18c-6d763971.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18207623/s52243781/2bb228a4-3c18a673-ecf60a29-514cab15-d4fc3be1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18891052/s54298759/6615d6f0-69469dfd-05502d47-0ada13a8-6dbad348.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12379467/s55611740/a16acd68-5c14f343-23eb5bc1-a7093d85-bb57d87a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19837636/s59762400/2f5dc5a9-2750c463-e8a3b4c5-4bea6716-0ec8c6b7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11032631/s53685231/d6b0d992-82881162-c877228a-9297c117-39fb3e62.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10208568/s55173564/72331721-b68b280e-bdb1e777-12f73365-260e01fa.jpg

 25%|██▍       | 1238/5000 [00:21<00:49, 75.42it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12537194/s58627988/867531e3-1dc887b7-008cddd5-97ae22b4-1d1691a3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16771388/s50050321/6c810e73-35c714e3-32798a35-92520ad0-bf155538.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10670818/s51426266/90717d6b-5ce04686-5fe2bf61-544f10d4-cac7ec0c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11648170/s57650593/6ad03bb7-03139cfc-82d578a3-315f4d0b-0c095db1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15143229/s50423014/cab99f0e-942b1723-ef2c1ebd-4405a736-7b42fb7d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15868868/s58212673/c79762ce-eac62e5c-d041a281-9a3dfdd6-0878d8b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12106911/s54893917/73e09d71-126496fc-7c872e03-f48c2176-7d0c1bdf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16243656/s51524512/b0d06767-f4ed5f90-b023482c-25bfe4f1-2b7459a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14038277/s55122505/ac982c7d-5690b0e9-248c39eb-5ecadb81-dacdee82.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14196702/s58659402/ff02bf78-f84b6d87-a4615946-e4343a28-7b93593b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14150037/s58194660/05f75001-fac7437b-5faf6c2a-0dcfec74-491968c3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15348823/s55952309/51e244c2-f6950066-cba8dbc3-ef0f789e-e8ade06f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12838333/s53507347/bca2aca0-88cfc345-73a0c605-97a06787-fea22e2f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11700849/s55781258/525df14d-5a0b40dc-39a52879-12d1b5bc-19b7d8c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13131638/s51535994/509e4620-4f411d01-6b03e9b9-987d9e06-4d6b74d6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15634731/s59794344/7726f9b1-a75d0a87-9638ef68-7691209a-28290485.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14496696/s58652363/c39cfd07-0cd20471-4febfdfc-c4200ce7-2ea619ed.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14161165/s54578233/37f81de5-92cdef92-debf4bfe-7ca56f2d-b12b6b1a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14498233/s58069723/20ce1ef0-4c64762b-38d8bf12-58e2ec30-aa8fd999.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19934880/s53513172/8d821d18-ef6593b4-dff05645-466b8d75-79894729.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12669967/s54719855/0ab72f0d-51143a9a-26a3c216-bb1865dc-72fd6885.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15689523/s53270910/f764793a-f262fa0f-0f20f88f-8e9e8ecb-0ea65518.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17405329/s55291678/f30e7101-803edf2a-4181f462-53b4c3cc-3019efad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10171967/s50676702/f5e198e3-ac260039-910d47f5-de82b345-cbaaa7d0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10908761/s51517997/d6e47879-b72dcfef-05755074-89b94895-2a48086c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10476869/s57858155/06d0887e-d1594839-946e938f-32b8711c-35bf246d.jpg

 25%|██▍       | 1247/5000 [00:22<01:02, 60.40it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10772636/s58080171/7fdd8580-6d009d8a-a8836c24-73e3a119-c210c571.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14045846/s51998474/669f4394-bd85f14d-1d5db6ac-38a1bfe9-c1a17067.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17179037/s50728369/6530f637-44fcab01-90cad7b8-a65dcb0b-b22dad6d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11523241/s54851215/c033bdb0-f82850f5-165f5026-b6e6edcc-db50abed.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12967352/s57412257/be881430-51009e0f-d06b4a90-ff3845f2-f8d3323f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18663902/s55339624/26b977b7-1178a4f5-e4867a5b-0f0a8d05-e11a712f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11928036/s52805285/0cf5e3fa-bb8619f3-810cd1cb-ba6b672d-aa3d67c3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11896917/s54662960/10c2939d-383cc7c0-5f2b7bf2-88d6d73b-6ff0c133.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19344453/s52076613/779393a1-3fd06054-43aace70-58570776-b6b112e4.jpg

 25%|██▌       | 1267/5000 [00:22<01:01, 60.83it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11399232/s55094661/cb524928-fd4d35d8-835b18f3-43c8ebde-4a32020f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19229277/s53992488/f16df012-7b0f9d0b-f5808bb7-b540f1d7-a70fdb33.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10302201/s52585100/bec800a6-75022025-be53526b-0530bef5-3a917240.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16437473/s58460633/8769fb92-1a1219f0-0773d59f-7d46db4d-68f79d6d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10476869/s55161244/af42d034-71ef58c9-c400c0bf-bdd01ecd-c809ae56.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17763551/s59918328/e211efa8-d8216c0e-09f97857-f0861041-080304d9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13155939/s57797634/405ae891-a2123a98-93fca5b6-203f30e2-4cc38ddc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13950510/s55155002/34304659-19b99404-48dec969-5f268150-c7d97717.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13186935/s57803819/d0fcdfc1-b0c87cf2-510abc6f-3fc18352-047cb968.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10624280/s58160849/df105feb-4c93d1e1-0e6e3f92-9ef36a01-3de921ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13603228/s53658552/77fb9117-e9a9a642-d5fcd710-504ddd11-7c0b84fe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17402692/s51029215/568e7b57-31c3e408-64260309-e23d70e5-1a2b3661.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17487379/s51181780/7bf55751-fdf198e3-2ec1c42b-02817a3e-b1df721d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19546724/s53891677/0210cca6-16d471ea-7e494d52-51027846-17cdc883.jpg

 26%|██▌       | 1309/5000 [00:22<00:54, 68.16it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19361390/s54088613/8c2792d9-fc620d69-e2f7c086-05476d18-69e3ac42.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17195628/s55060997/7fe63849-33ba36d0-7cce77c1-76218ed8-924690de.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17186187/s52176312/24491bdf-73f43b94-ad1f80f7-ef618d4c-d640f75c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13570028/s51990399/82d1c776-607c8365-571dad56-2c1db205-6d864f90.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17301684/s55365119/5019e8ca-0142b14a-047b7035-0c035c24-ca0e2120.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18033939/s53472532/6ea07b6c-7e8d30e9-f909adfc-59dc0825-c7cc88cb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12395029/s58011076/8532e0d1-2c6c7020-8d606f57-dabdec12-00525c0a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18695674/s52888566/b4e3e2ef-57748e7d-31fe95f9-f1689051-f76efcb3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17111103/s52139463/feddf9c6-040b7172-f7cca225-8f5ee6e4-76c98971.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15386471/s57052625/b5e64c5e-b1ea676f-35e199bd-a3fb1195-27bc2028.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19355136/s52363294/3d930a0b-5563369c-d2a6eb01-08669a55-928b696b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18877812/s54503854/5bbcd77e-601896cc-af8b0b29-ff013fb3-f4a81d28.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16356118/s56763193/6968ea2b-99030957-5256b4bd-5037a91e-3f23110e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16582220/s59686795/edcd630b-fb2feff4-8925c0e0-1be20d1d-1a912c1c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18565269/s57499373/41411477-781bcc48-8b8fba85-ab6ca3f8-f11b9b92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19656748/s56095669/bacac0bf-eb90ac1d-818f3bb5-ee274f19-2752d106.jpg

 26%|██▋       | 1320/5000 [00:23<01:05, 56.08it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18783149/s54841781/191599cd-5dbc98f2-9fcafe8e-5f583b30-bded4273.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18415857/s50271089/e6ef1771-55cf5e61-455c2f60-30cfd83f-3ff1371c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18882650/s50484186/7012e5d7-c55de59e-06d5ac5a-6caf6584-3177e778.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14851532/s59364971/39922ca1-cb122a2e-5f5f5b94-65973906-45a1b814.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17114771/s51822903/66eb1604-af144a8d-7f1e6241-c893d73c-d3a58216.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16455067/s51635912/5689e6ab-dcf08e55-f7c2551b-45eba845-2c0655b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15592981/s54403766/fc9b9fe6-8e428238-e357384c-5ec385b6-a27d6652.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12110838/s52363625/e15f0559-75b925c8-2a300c71-9c049b99-bc64088b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17504528/s54986906/f1045f09-ab338624-b539a025-795bb3bc-73143579.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11485828/s57777817/b8ab06dd-bf7b4f4b-e328c7b9-99403118-979c7b89.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13741891/s56649230/72bd0542-a7a0708b-57ca0df0-e28cce87-72e9e0ec.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19683695/s57143744/225449b7-a077f445-6329be5a-eb3b5c65-0656c32b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13120648/s55161745/c7417c00-0336e789-ff110796-d806a42c-31cd0366.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14065959/s54007894/9c5b05bd-66c78c42-b6e78e92-930a15c7-509038d8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16454913/s52130931/773a8d27-d035a2bb-f0acc65b-14e47fe8-0f81a38f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16670578/s50404601/709d0ab9-f1250dd3-7bfb290c-0ba59aad-e809238b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10247690/s58955257/8e33b270-d67fbd1d-193ef19b-63977e9e-23dbd48f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10308375/s52139824/53f5b331-b246e0f1-f7e1d461-eb3139a0-caf707e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11585206/s58371110/3b50b5a0-bd5c1dbe-729ced5e-b08ec457-6f706e72.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13375208/s53081134/e2f972e0-14fdb67a-a63af68d-1a123c58-bb9777bc.jpg

 27%|██▋       | 1340/5000 [00:23<01:12, 50.57it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11422357/s57060345/9f5925c7-5cfdad61-0af8ecf1-c90b1abe-e47e0181.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16736889/s53642996/a710451b-1d66ae40-0a3bba70-80eb7e59-84c039a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11844664/s51129858/e4984b81-6805af45-9878a0e4-d25f618f-3dca2e9e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10624517/s53054919/24e98dd6-da23fa29-b3fbc33d-cb624b7b-b84bbbb1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16620451/s55240825/beb7d5b8-068c0af1-40cc3ae4-33895fd6-d0f2961e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16476559/s52810262/9c3d5eed-93ab86af-e1ec6ecf-3c699147-faefc60d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12027869/s58472636/76a21e43-6429a34f-9fcf8f25-782863e3-285b52e6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10138124/s50525058/935898f2-37003a64-e8b904f5-9ad745f4-426978d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13581561/s57401588/5115f7e6-f08a01ca-25892cf5-aec3faf2-fe12bb7b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19929294/s52315941/198047d6-212a9bc6-977799b4-10ce9cc9-3591120e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11630519/s51099891/b9ddd08e-339f7f98-5368edba-25a054b2-c82334bb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11778436/s51432698/9262b47c-f737c863-35d5016a-7f595a26-e56cd68a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10975446/s55185117/0d768fcf-0bb1bca1-eb1fe1d6-686b876b-675a2e95.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17341475/s54725751/45c58cd8-d8fdf071-9081fed1-e0b34f56-2ef71464.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17251067/s59466378/e6793fa8-1fbcde36-22b20a05-10cdfbc5-dc081aa1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19509298/s58590245/cab1e399-d2b4c008-6d88a326-862d770d-fd4e6b07.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16059753/s59825575/8d33d700-f0ef1dc5-88023837-fd9c84ec-1259bbca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15748140/s58008611/d30b856c-29c9e8fc-cbe42479-012571ad-4d6abe33.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15670628/s55412409/56d3959f-29b38a56-fdb82844-5b5a00d5-8228024d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17445819/s51156353/0598afaa-39c4a06d-2a071024-5ac0f5bd-2d7b9ae4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11404203/s52320841/c3c70144-63b8445e-cc720f00-4ae3fdc9-e9e81f20.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18769460/s54277068/9cfbe4a5-d693b1be-8027a1c1-463e1d04-576cb9b6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18597372/s51502434/94f07bab-8aae1542-24e8bd2a-a492d9d6-941fb033.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18688735/s57407067/835a5f85-151b015a-975afd90-5e5b4299-4f0929b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10215159/s50306786/c87713f9-e922dab8-5872e953-ee8eabb9-c3ba0159.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10948510/s58847052/fbd381a8-74c7a983-efe4dc65-c5e87829-52ce2263.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19774387/s52917434/32fca9e9-dc6272da-26a8078f-484561d5-af50a8a5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11948471/s52856158/38525e4d-08d3c52c-23433b4e-3a7d8beb-db022b95.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18512386/s50784959/2e834030-39a1824a-23d391bb-d72820e3-949f4289.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16107458/s58928914/327aacd4-85251761-c643ea9c-3ca7f485-b13769a0.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13689440/s53401714/0aab7129-c6ddbd14-4b14cad7-0e13634c-c0a1d820.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13948093/s51042474/d11b716e-927b579f-2e04e0bf-510563e5-f07bd85a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13813244/s53799927/cac9e446-addb7fb2-86b7fce7-6dca9b9b-28a3e32a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13812710/s58207863/ed5c7bf6-2b213724-4c736001-3582a2e3-9ccbab89.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13165778/s54566654/c9a92f12-cab84ef6-1a1676a5-386f93b3-5b5845a6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13831972/s56446495/c4b44448-c0545116-3246a396-5b70dc51-f9643b4f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11187131/s52116011/00d24e93-df389d00-b6e5f10c-d99618b5-15010ce8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13445415/s50756748/f0a39404-8edcef25-8d37f149-e1c34ba0-be24cf30.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10461707/s53527169/724ce2d6-623cee46-25b76d44-e7aba727-bb096a32.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16735911/s57889791/d5fdf235-7553cd31-870f7b70-1cfb677b-a16e21d8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14522065/s50830064/1ac32f6e-ece2e888-72315955-ff53d0b9-3eb5ead8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14485204/s51334383/20f60768-54b7a519-71aafeed-8cf5a91d-dda9d48f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14117743/s50555546/3eabd589-8091df8f-797ddba5-61876c41-3ceb39e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13639031/s58870696/a28ef018-6bb9ff28-423b31a7-3f50e3b7-d277f558.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13046589/s54290597/0d534e5c-4c907e07-2c746e4d-a6caeb2c-ca38b40a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16560053/s54871655/f2123d7c-6e9288e9-36df005b-b714b058-e272491c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15318793/s53587962/23f68b31-0957873d-ce503c1d-9dd93504-ee261474.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15411028/s58198603/0af624f2-c173f973-e3edbd7f-d3af5712-4cc2e2f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16537076/s53070593/8c936def-0c5a7c22-e579b229-50daccdd-cf44efda.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10267084/s51899004/61481acd-96c396c5-9feeae92-d7a5aa9f-fad74aad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11862995/s51925787/fc8c7b57-24804f68-518f8fa5-6aada417-6bcfe49e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14957820/s57410929/353a6832-785b3bed-c2007050-f32867c3-a80e300e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15831124/s51292171/64827cd2-dc83cd9d-369e9ca8-cb7cf12a-8b33516e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10214395/s59590946/f26fcd00-830e22b8-59cd3f3b-f3a06dfb-9896f611.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16052230/s54714668/bedfb9a2-3d2da06f-db23b0e9-cecadbcf-119e59ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11550134/s50882360/d318e5a2-0bcde8ab-5005800a-47aae55f-e7487108.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15650202/s51357105/079053d1-b5384e99-23239716-ca506003-1dab2f8f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15357560/s51821812/98420b64-158ba4b5-e46d48ee-6231a45c-a05e8d03.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10412483/s55975707/ab214042-e9c951ba-d24bffc6-2bf3e383-02b503a1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18586980/s57356446/d7e38d36-28f15383-c0691c52-f3fa7207-0c0439b1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18946719/s59519146/eed1451c-9a5639bb-f4fd34b2-53e6134e-f5d06a39.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16334516/s53602937/4e978740-b97d9a2c-f97c4610-4dd52d72-5cb121ef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10933609/s54853227/c3994ff3-e8774cd2-b7a4c40c-959819fa-d8d942b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10314749/s51718228/537fb8c2-2ff9eb2f-84984388-93d3e42c-96e511f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15281216/s54054044/9fbf8650-029188e8-80b8a100-41bad5f5-b98fa6d2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12661994/s55725376/45b6fe7e-95d4d978-26f55b2a-9814d130-79380709.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11759824/s51698352/df487a80-90adcb04-08b32cde-2875919c-5b2b9cf9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16346361/s54426811/f1e77bcb-ef49c5ac-0971e523-24e75151-860fec71.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14718365/s52262137/fc9a8408-d6748db8-03a23319-097e8687-af3c5a76.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13291712/s59537122/ea674832-496529cc-61929fd7-cf38583b-8781c3a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10386562/s50762650/c62576e4-9c4f3e26-eb71c8db-f0efb8fc-f05d4196.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13078497/s54020063/fa1a0e84-a634126f-abeb0c16-873ec16b-221c189a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18891030/s53546744/56f0a63b-e24226ed-d3140cf9-0601b9b5-d014ee57.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14274713/s54556027/5cb3b071-82ed070e-a512e286-ab4b6e89-6b972d63.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10082014/s50194136/9d44ce7e-0ce1b816-4544d792-4b56a090-9c235f36.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11684236/s56702434/b5188dc3-a357e4a4-93a3f8bb-378634a9-88169dbd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16798209/s51063629/9fd1ae00-1923d808-70fa7f96-4d181de6-505699cd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18042405/s50497877/7a5f6b38-961228cb-a0ee82f2-0aec5bdc-aeb0b609.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16956482/s56344861/2e4b7a3a-3b2cedf3-a6e5e874-3f41a2a2-fc905dca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19902080/s55278470/f73cf160-4cc4ccda-b21e70cc-0e52a504-73f273e7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11658675/s54795944/48469c28-c0488416-b6943367-3a1c1285-991f69c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18691393/s56760870/a6698e16-f7a79eac-4fcf0ed1-88e88142-3abc8371.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17224335/s53689613/7d59f4ec-04acc294-ebe586b2-10c28c57-a6e76314.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14682921/s58709742/98485c95-a74cb98a-825dd616-ace764be-d5e86f1a.jpg

 28%|██▊       | 1403/5000 [00:26<01:41, 35.58it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18777408/s59526923/58d32a1d-e7516052-41c81021-01cdfb44-31592b13.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18995174/s59857455/09e7825d-b962cf1f-3224ff59-fa136e0d-bd461f2f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17592232/s56938290/8a4e73b6-579d0dbc-a3757230-3d5861e8-19b4fe6f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17106724/s56897221/8b7267e9-09058f59-cb5e35cf-0cdf2e5c-cd80c580.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17612547/s52582759/b71c8667-6e622d07-2fc9cd55-e95e8459-c87196ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13306856/s51338116/25394fd4-fdbd289e-8cda3a2d-cfbaf7a6-75f910f6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12351481/s55446650/73a6999f-22a5c358-164245bf-0943d8b7-c2d0a0de.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16911520/s51615460/b682f30d-878ed466-a84d17cf-c992c8e5-26a9a852.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14477516/s52159640/ae6da400-63cb7664-94e65630-c4e77462-ecc1993c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14072816/s53170993/10cd0b61-346d327d-e754635d-3c90bb8e-211344b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14864363/s57313282/b44e89df-8fc15219-9d352950-dfa2c487-cf0a84d5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18718424/s51942379/7aa0af47-ce40f184-1aac68c9-b6eb1463-31db7d6e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18722792/s59527478/6872d3a9-8b701437-03360a4f-2d729504-68ab9325.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17991372/s53987207/07410e97-f46e10b5-797d4b3f-0098df48-e9a7c8d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10877472/s55088814/fbe69997-284d1ea9-2187c805-4744d106-01a8df72.jpg

 28%|██▊       | 1413/5000 [00:26<01:44, 34.22it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11484862/s56998657/979f390c-fe9451cc-62c7d3b1-1b9c647a-e21d20e1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11208075/s50417525/47e44dea-7fa10227-c16b627d-4288443b-4c0424e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12513239/s58667270/75f9cb5e-576d6f4d-55e1deaa-c9a775b1-8555d65f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12932366/s59934875/2c191226-c338baaf-e97f03e4-92493864-7c71e0bd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12652268/s51927381/2b88f883-03eb1748-4abce23f-f9a3ff86-8ab414a8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12620320/s57295094/75fce999-79424506-012acd3e-b67ac809-c7e301b1.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11508828/s55749682/7eca05f0-36b18306-3af94797-040efbd9-dfe0f4c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17267800/s56152416/08dec683-2081f1c1-25e5aa7d-ad7cded7-b0d5afe1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19358609/s53579425/960a353d-a835332d-fb31336b-b05f1fbf-749acc88.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13478618/s55599898/b41d9d10-14ed34e8-ac602cb1-f63b3589-f2b2306b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10803114/s56530218/4e706237-7bfcb1f1-73ed2f42-d39a58df-de79389a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19596777/s56803078/bf913b58-c609d1f1-d56ce017-c37db642-9a54bc33.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19122984/s56463629/c8f9518c-c96e2373-9606b2a3-8582da68-e8c04ddb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19560960/s56238873/0af977ed-6e3e7f85-1d76b65f-f371f7ee-77ddbc4b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19122984/s50241695/c6f593f7-1054b520-47142047-b3e3483f-43aa69e0.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11415430/s58388445/d2386567-641cddaf-79ec538a-cb280854-199b84ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14477097/s52326970/c9d5739f-c65a8c42-209c574c-b7da98b4-9b23dcbb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10546701/s50506856/75a75994-a91f2740-1b47c031-21a68bbf-97408c18.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12793919/s53432584/cf98f919-76a88752-b46a4437-427af8ab-43a01034.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15094150/s50349663/1c7b2d77-98f29076-bafeaf03-0e13abe4-b5301700.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18642217/s52007934/54d8a244-fe27a2b4-c549546d-2266b64e-257c1d4d.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11707694/s55738549/da0bc26f-c9385e58-57dc5290-8066ad3c-1dad5e23.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15160486/s56286020/ba3826d8-4351c008-7520b8aa-a02f5aea-0aa56e7f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10594290/s58891700/2177decb-0865f965-f1496891-31fb5fdc-f53ed9cc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16439884/s55376562/7cc062d8-4dd85494-90a58c1d-dec638e5-4d72df65.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14080329/s56057164/a233ce68-064cd938-1a04aacb-41bf9307-1f04f0d8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15386577/s56944118/6aff280c-0758feee-d3dab7af-8f45d982-00e76aed.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12831242/s56099075/8231ada0-c687927d-8b0cffb7-b9004d1e-e60575ce.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13748151/s59000018/17b014f2-d2f99d7f-a4cc5f04-cbde51e4-012eca6b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11863733/s54203712/4716b0fa-a82df329-5397858c-78a58a0b-e928b94f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16656904/s50885314/f090783f-744b35b9-f3a48853-d30c1515-a98628b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15694968/s57776674/519397cd-0687d56a-442318d6-b5202976-69370ee9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16032226/s55959060/b4b96874-15ada7aa-964dc7f7-53c494e9-ad3edde3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16457378/s51182107/37dcb04f-d0335e7a-ffadff0d-56fee360-e3fb57c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16897596/s53339106/091d7e6f-99636e13-b9ee957c-9750fcc4-49ca3ddc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16223084/s56383682/26bc24a7-61d91e5f-f503dc25-8e8ca3ad-b067e56c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12338003/s51466149/e1dade06-c993ea14-c2b77196-17989b17-e8c03c1b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14987986/s50359479/1c20745f-fce00fe2-feeefd35-516bcb50-5879ef13.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12620320/s50824087/b5d438eb-4b190dd2-9c6c75d1-a67532af-80c2425c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11100454/s52983444/4af710a8-1fd9589a-9d905df5-9ade611a-f0f74321.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11682251/s56484364/ea76599a-8cac79c1-dbe98293-c3ed83e5-cddc4cc1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15456778/s55755092/d816b326-6cf47cee-b05db246-c57ad29c-d82753ab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10225380/s52624118/e143df9d-37d3fe4d-b7984bb7-5c9b08f1-30dc05fc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11329142/s52314866/689328f5-9205d2f9-b3042b04-d34fa42a-34300b93.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13921670/s59486720/11d9b47a-27da52ef-78747f6c-153ce191-ad3deb40.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13325402/s50692823/57f13b38-500f9f17-4db2cb36-84c94d7b-f5f3f3be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10520715/s50734223/e0e1c908-ea899c6f-a0044434-1f17d649-f6ae4b59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19655295/s53197950/dde6b6a5-d713848b-b871601d-a0000562-923d938e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11864776/s55977180/60542e04-7738085c-90c5e5fe-79da5f66-7bc1688e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18056245/s59344479/ead9c51e-274d0cd1-7dafd161-e6320d7e-fd2abf12.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14081532/s51846274/d642ccc1-4f683c67-2ae983c6-98b53d74-1b0db372.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14513082/s55490591/c95bfd12-c7254f3b-1bb81960-f82d8410-dda8dc63.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18190098/s52846638/c458d43d-f4a7eb7d-a51b95a8-f4aa2c82-52d243ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15639504/s53703677/566ad7e0-c0327508-af80cc02-d5eb6531-1bc8dabd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16560053/s53743922/0cf6e89b-8261611f-bf8c6570-8285928d-9915dbe6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15691899/s51862832/5f1bb5f7-596f8052-cab78e0f-2de8017f-6a904464.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17694075/s52630351/7f812ea0-22db45e3-6f522abc-40c546f7-601d549d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11274342/s52850376/c3e87200-1e004fc5-5dfccaba-0122ff8a-1f07d72b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18377113/s53925701/77aa0461-6d26af44-e06d6930-3e6b0bac-6422dc09.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17056572/s58887183/5cbf9144-a77330c4-019e1e85-7a77657f-5bda3f01.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17302284/s51094419/c3f7c574-e444e425-c1b440b6-f8ba7739-4ade730c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10821892/s59894473/b0469b69-8ed109a6-665ccdc1-afdc8f9e-45a7698b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13135020/s59607809/025c240a-d6d7487e-b667360b-16f2ed65-331ed514.jpg

 31%|███▏      | 1572/5000 [00:27<00:48, 70.46it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11119242/s53455616/6c443fea-343389ef-d356aa38-c1c8dc7e-81e91161.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19509298/s57082396/fa2875f4-b213a7e1-1d49dd22-45d953d2-a3e26809.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17439964/s53439383/c1e08691-e2984937-e6ed7a89-4d83e06e-5f24b512.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19151600/s51222960/84856900-ed326afb-b8e05aaf-3c7cbcab-5d33168c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19356325/s56395812/033f9605-e38386bc-51a8593c-d7e6b792-02724c3c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11595868/s55885763/8eb2e54d-09c4770d-ec8a7423-15f040c8-9ffe9018.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18066099/s52939934/6cc75957-c6a54270-b60f2be9-c5b5ad95-eb8bf4d3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13325402/s54276228/1761884f-82a54821-112bebe3-db444863-d54aed1e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10850326/s53787341/542d2400-7c0a2fff-b08eba2a-b9d441ef-321a1a3a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10024331/s52186169/500badcf-c7faa505-cf17cbc8-4ede32f5-84de626e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11506052/s58998399/9afb1ae8-7de9e7e0-4cbb6c09-7b48dd7a-db2a265a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15619921/s56042987/a871e82c-88275a72-5c9eff0a-f5855ee5-adebe5ab.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14593165/s59159826/9518f903-ce80fc96-3b6b225a-48844087-5c92bfea.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13761048/s57392562/256e7410-584f71a8-06c0aa9b-2b2093b6-a6a431f4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14033331/s55086693/67de5091-c6f3a0a4-328d2b3e-9a567597-8fc94c50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10911403/s53162291/ab75682c-dee796a9-982e4c32-1219806b-0e13f142.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10194314/s53544531/c026cd9e-fc960b96-bef869e6-dbda5d97-98993590.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10225882/s59794385/98874f53-71abbab1-8c1949af-a445535c-4525fa14.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16816455/s56987795/ebe32647-171d4eaa-cf993973-55632b19-7a5ba9ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10516213/s56626810/82543a53-80472837-9055718f-bd3cc888-129b9eb7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18559699/s53669979/2b83ed41-fd6ded3a-1dbb5b57-265eebe4-b3f71a96.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14280430/s59843686/6b8b8242-e6e78651-054eef89-c633530d-e498bfba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16724979/s51010790/07288bf5-1ab40877-6447e9d3-53922970-8738c5f2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19640899/s56076038/6f07892a-d554ebc3-6a296780-adbfea09-b2ebf73a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11040709/s52448714/2c8ed744-27ecb772-0b52f401-ff4e2a2b-02c930fb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14479847/s56346033/59b3910a-ab493a4a-97e62104-625a9f45-b793cfd7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13191788/s59332795/1253879b-c6602a2b-c7b8ae3a-c38bb697-bd17fecf.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13338612/s54110978/91eca819-62dfb32d-a6c06dd0-1f79530b-8affe04e.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14189406/s56723874/6672acdb-bca0a0ed-dbcbb5fc-4e5b160a-62fb41d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16473254/s58297921/31a7cb9f-4f2c6188-829cbeae-c3253d00-7e3650e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14765058/s51103597/357e75c3-5bad8b65-2f50bfac-743ab831-a168a37b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13918272/s57556100/a5d440db-90db2145-09574fd1-4c7f5ce7-743e12a3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16203356/s51084123/f68e523c-cad0e33b-21bca272-472d33f5-43d843a3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19762081/s53426615/0eb6b3b8-81654226-e1a3a85e-e68ecc88-6fa0228f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10516213/s57075807/22648352-4d2fb0d5-818a47de-24ae0293-fbda4f13.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17058070/s58381689/9e822224-4f0f911b-820c9731-8d713f87-36ae0546.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13475033/s52240207/c5f6b48e-5ca7ae46-4fab692c-24718944-688b465f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18755913/s55388473/81cd33ec-a8d0300f-b1471887-bf4a9e69-0818b915.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15380734/s51191114/1fcd995b-1ec680c3-bba45110-e0430c14-bc44fbde.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15015358/s59377423/0a2b52bc-15e34775-95ebbb2a-9d5981de-fd6836ab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16697275/s57519896/6e1e4058-5cdc03ce-c64c9936-1e4bd287-d3a76352.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10432951/s58812506/5daff5cc-c57378ad-be7603dc-ef5c935b-319ecf67.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11235666/s54224363/ee7bd203-dfd22756-eac4f949-f30896a9-60b4b2a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13421733/s51721990/7a071b79-86029400-5823e1e8-14a306fa-ab69a376.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15683514/s51161417/68857420-b75db076-e917434a-cb858447-4e2106c4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13118416/s52427901/4206bcc1-61cf0cbf-213cc458-5c2849f6-ffe753a2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13017716/s51087639/e0ce3db4-b59d9f36-6bcbae83-5605cb15-d09fbbe9.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11055094/s51013748/ccb79875-371d0fcc-dbd4082f-e9f708b8-4ab6f5a3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14037995/s57246468/d34340c2-acdda1df-6d11f7c5-a60746da-36d70e5b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11638660/s56291824/c4efa1c7-a7860e2a-bab7d17e-75570b82-ae1d3dfb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11900070/s55665252/ba38de73-d02a98e3-2c522d2f-cefad4cf-03d04cf8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15295888/s53269208/ac859aa5-f007974f-7163e048-0397f229-cca37a7c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13940544/s58705334/a54c59a5-d4e272ec-163713ba-6dd86be6-0e0b199d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10123147/s59653233/928603db-e75b9ab0-2cbcca9a-c7a11e4b-40a43945.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15540412/s58326300/03fc3ead-55d1c220-8a0d801e-548247cb-8b28b79f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10391104/s51592833/54188774-97beeba3-1bfaf8bd-306febd2-d5b5e8d6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17346220/s54289352/4765af40-0c7f6dcb-2e8fa306-515d6447-86f182a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14397721/s53269152/d7e8f198-1a8a2544-197414d9-701c02db-fccf4b40.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15682570/s51552543/5971f28c-0f160dca-e364235b-b0cc0f5f-50142214.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12185775/s56614076/45e31ec5-029d54e9-1acec167-663a1397-bccb2493.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15319814/s52273359/376de051-84c5e145-50492106-914ccb16-c9911a24.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18595899/s59797209/fe990ec0-5d97d4dd-4cef5a9f-b130dfc0-335ff880.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14018231/s57362399/7511618f-97c0f8a1-204c052f-799096c9-1320e82f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17989329/s55113109/2c76ee8c-423849c6-fb953220-a6370858-75deae6e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15928453/s50775606/6c032071-53f71fc6-423a4d34-5a794c4f-e2213431.jpg

 32%|███▏      | 1584/5000 [00:29<01:17, 44.18it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11826496/s58807632/90d3bb70-02166008-3c69a263-64486f11-7c532121.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19705230/s58394543/210c69c4-149a1bf5-818472ec-fd48f415-153f3df4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12889151/s58589050/ee2dec04-b5a27acb-64ca45ae-ce609e59-a622972e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12764579/s51316959/31abc686-1acb3a8b-c06cd468-44e9f07b-3122caa0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11778436/s55780594/fc29559a-0a51949e-4fb3a572-0e266f85-946f835a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10778867/s54985035/129eaabe-0986dbd7-77bfc895-d828dfc8-196fb491.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14851532/s58103833/445b99e9-01f5072d-77cc64c9-359902d0-e84c80c3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11861017/s54540129/ec731aa4-b780ed90-a9f2d0fa-93517bdc-9febf371.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18508209/s53290551/58da731b-bc9c38cc-51548488-ece505fd-dbc77a35.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18904293/s51199832/c70e83ce-b3ef3be5-a536cae7-ba563687-ad0808db.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10095286/s56888033/147a4538-954b0f7f-750f5af1-2dfd8607-a7550567.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10912090/s51845523/97c1eebe-278d49b0-654bddca-07f399b4-f465e90d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15512088/s53365208/173b3150-dd6c19af-c2d5a90a-4f2876e5-1ed52629.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12721132/s55962889/ce93ffcd-72e181a0-d45c33d4-bcb24f0c-cc038773.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12442793/s59841056/ef2d7cdb-29bef88e-43e8fc6e-9c09f039-33ead57b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12565441/s54591299/2ce886fd-a4dad168-f63f90c3-9a04b650-e7d70057.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10892301/s53879559/327f6f99-3902a176-e388c3cd-3568e059-af824364.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14933845/s54152258/72b4c962-017beaf7-70dafb7b-2939eccf-3a675890.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10302979/s53857774/2cde2a7b-ef799689-5fb384f5-41a3debe-b8b3086d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13138475/s50021580/dda47ec2-9be75c07-c2a039f0-8a2977f3-48385b9b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11863733/s56333360/abc190c6-747a5b38-9fe153a2-6a967dcf-858ebc5f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10640623/s59874024/67ecda99-7ab0410f-3b449aa5-06651a93-d9558169.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19533730/s53141109/78ef1dfa-4a8186b5-a1c73cd3-6dfdb8bc-2796fcc2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17243592/s51437282/ac577eda-de1affa0-5ac1a05a-ab6aa0e2-27ed457d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18429092/s52928787/5b8bd07d-504b0c95-34061e46-ceef96d2-67ef4984.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11855597/s54430572/11f980ea-681c647d-792fd631-935d9a07-4c7ed618.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15456456/s54312981/25fbfa6a-2785616b-ef7a0743-3ee8fa3e-cacefdcd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14365923/s55023827/ec5596d5-5738099a-f5b655cb-c1b024f5-c99fe344.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10274866/s55661736/c4d7ce75-9444ec69-b4e38f1f-e8894df2-bc207d44.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19477853/s56361879/c0e1def3-5da329ed-4e0f9f1f-3f300746-db69149c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11733600/s57200338/ab59f2ab-5f92a19b-4d726d2d-349eeb19-1e3455c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16007214/s58487951/421346fb-f56b164c-baf1b2db-cd46e532-bf059b52.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15684929/s56430581/bca62c68-3c2422eb-bdcdbd2e-94eee48c-dd40484b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17625935/s54466019/f1e3b7e6-b0b76972-e0a77a89-42b7789f-a883d276.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12292383/s53456056/0ef250a4-5ea5edff-1b1ee569-b9012656-3a403d9c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16718650/s57613114/ea80e0fb-006b25b5-939a382a-f533e656-1e71ab8a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19778971/s59890897/6c32002e-1996cc27-26a7d94e-939888a0-bb20e4c0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11005736/s55777145/1ebf79b0-538224ef-3e7aba5d-e9e7992e-70983e49.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17439447/s51826816/78d75d24-0ec0a3bb-1541ed11-8d87b606-7c3a6dde.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10896351/s58096231/5840f836-943bc203-ceeb3de9-7db760d7-18b277d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18005279/s57376132/ff53aede-137585de-68b24326-a74cce27-16df03cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11388716/s51958726/4286aeb4-8deee0e3-749d4b5a-061ab257-2968dd48.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11766333/s55817214/f741fbf1-9e44d58b-db0a24e2-06a7b19a-acefcc66.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17741087/s54064837/8bcd141d-66acbb76-0dddccb0-4eab3b08-044c5ea4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13872997/s57208270/1d030457-1d0456e0-95a3ad86-99d57294-3f1cd198.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12447402/s58923926/6ace317e-25f9f94b-c631a6e0-7f9c7007-264a89a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19048920/s58977656/f85d64c0-a257c31f-d67eddb8-9134b277-9dc32f96.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16497039/s56426172/b6a93827-35fbc88c-e0c9b4be-ca7be860-2c6df4a8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13602608/s50927603/b4c5b67d-7f535c69-afb1b3de-61e2147d-dd49bf8d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17460568/s53566955/15e8564b-b00c181a-68f99068-2c5eec80-480ef3dc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17080143/s57757119/8515e5d7-677c8b41-0d033aee-daebeff7-3d9a20a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10842061/s51480367/384c6126-07ccaa96-22cc0695-87e2e85e-34928e6b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12934243/s50172947/213bc53c-b0bd7433-a673b22f-1b5d15fa-39565dd8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10228633/s58171827/5a9e67d5-ef41f515-a36e14dd-ebf8d554-ca974cea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10220448/s59926270/9bfd1fae-5466e70e-90af99ff-a3087631-679e49d2.jpg

 32%|███▏      | 1589/5000 [00:31<02:02, 27.86it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16987914/s59292815/99dfb411-d4cf5d38-527fde77-653ab794-2ae5045c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18624957/s54843868/eeee3146-82b5507e-9fb5df34-87e82a35-260f1aee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15189222/s57531134/6f41e5ad-300f5c74-0d7a02d9-ff5a667c-ba5974d2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17038041/s53209610/c555dc1a-2f944452-1188c217-89afa56b-30658b6d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10281385/s50750396/a1877853-72688a50-746fb0bf-3018617e-1fee158f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13983096/s51777207/89e31d4d-4f0807b2-959839f9-7aea345d-f3ea6b92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13160874/s58280416/ab6dcfd1-7f816f10-2546b38d-331d0371-51fe515d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14581489/s56266870/5c54b923-013ed68e-776971a4-8c354a26-4b223a06.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13869522/s51595360/39bfab95-ccbaaea5-3b2d7a68-35550f5a-7dbc219b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11766333/s50237796/42e76162-bbcbc0ea-9b22c19f-4782121f-bba1bf4d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19773940/s56112358/4c16fa5e-b26ba84e-ad97c24e-abdca90f-b027394d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19914680/s57309227/5db5408c-ecacce5a-b5381a70-6d40dd8e-4a9f106b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19139733/s51350442/add24a5c-48445caa-a1ff0292-d555b47a-767d41f4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14586885/s55589371/567c6bff-77efd5ea-f0af8ff2-c38e8e2c-111310ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13131924/s52897540/a6c8e75e-0e235575-0583bceb-ad9f25be-921702e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19022436/s57809380/7a94d6d1-4996a69a-bc02aa54-596f2f53-33307b73.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12881887/s53923867/af6b034d-11efac9e-6bffe0d5-eb38df22-d4b98c35.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10287060/s56069905/ced18bfa-2419bc2b-ec41b545-f3edbd9e-39fc95c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12476587/s54410070/9c9c440a-a0f8fbea-b80c20e9-0666e3f1-342f935d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16735911/s50572062/3410e72e-a13655f5-97a2cee8-a711f4c3-1911ee2c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15928453/s51085794/bc637beb-9a9fcba7-4c67ee59-604a9f21-151cc47c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16515555/s59349654/551938ff-579d4d57-69291c87-6f96ab06-b95dc83a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14995538/s52630069/e389ee53-1bbaafbf-091607be-fa3d4a06-6b2aae8c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18325837/s56675187/0deb5930-1a6a2f6e-d40b674b-8e74f649-b4f90c76.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11228186/s54883225/2307c96e-ef7160d8-47c25adf-84321244-b82578ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13892051/s57988649/bee845f7-70994233-48b5bb6b-8b559d61-facc3393.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12717101/s51935178/13050852-5a0d1b6d-e2bf8559-6c59b58f-ef8706cf.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11882188/s58841081/f8b28f16-1af0a2cc-dc5e91ec-dd2d9ab5-2d330230.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14546527/s58993262/81b604fd-c182953d-844b4076-0b553efa-0cafc69a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18524648/s59639304/f6db4f7d-25efb560-898c3810-a38a7b60-444e4fe2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18551874/s57469882/b48a6c9a-dd39f475-f6e7bdde-3c8c4ad8-f6bfa9c0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19064289/s58122805/86c83b75-1debb4e8-ca7a9ff2-d82e5244-79a14fef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16704300/s55462376/5dbefe1f-11f63d64-de91906d-18b8991e-e5a12d4d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11522912/s53230252/35c2549b-f5abaaa9-d95882ad-b49fd205-dff92a59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16751019/s50514899/8ef02976-88bd5186-90631d46-97986c21-a9a0ea60.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19618308/s50404165/47a8ad67-8ffeb9b6-37109ab0-9e3f24b0-38dc3ce7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10516278/s52185060/f6d608f2-2833e692-c5a0883d-431cb7f2-48004a30.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19463318/s54404161/3ee4ed9a-8eac92c8-7d43b792-ca96cf30-3487dc1e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19325025/s54080082/31f631a3-06b3a73f-cbc45ead-a80c55b8-c0622d9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11651571/s50168718/93ecb1f4-015368a9-075d0c33-0707c352-cb60e1a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16936322/s51629884/d80af1e0-18e517b3-540ce321-013ed3f8-28880334.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15597433/s55179080/792c0b57-cb526b6a-d0e9d7b5-19a1a84f-881ff022.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15113309/s52929626/bea34b34-de3ce5d6-72e1ae9d-37f3eb1a-6c59b3be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13528093/s52235463/c3fb199e-5a593eff-b624ba14-1303bab0-ff964b71.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13922987/s51149204/ff5fbdc8-31df7fe6-e5b67d20-27baf8b6-4eaed8ad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13868052/s56651487/7d139b8c-2014d0b2-2c89c82d-465e1967-b5330605.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13642689/s53862424/833ebc32-4451cbb3-86b31a98-50ded099-d00fe177.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15114531/s50027153/4347b81b-2a702858-6a330ca4-e115c0ac-f1017427.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10364180/s58182875/eb6d8761-345d3090-8dc23fe6-f0260da2-da1dc6ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17374306/s56387591/2c156392-ac341fc0-f2643c0c-c1720339-78f555e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17725106/s58933808/43400c3f-948eec12-65ffb73d-465854e5-ea170e22.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16603653/s55522730/76778ab1-0724a699-a36bb0bf-409e904c-5d9b9ed2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14269495/s59199264/b1aff186-0eca55a2-50756b65-64aa8e4e-6281e877.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15426827/s51963038/b0c061a5-98ac3728-ac681c8d-6a710215-951d82f5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15844687/s53092019/df0ff63a-80fdaada-74f40669-fa705f79-ee2fa606.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16429696/s56951040/79bb732d-2667c9c7-22840ff4-105d4aa9-b7d4813a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14773318/s53110999/e92c0306-7db562f6-cbb9be2e-9c9bf6a2-e4460e88.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10633199/s52205472/bdc04258-5be4c158-3f1eecf1-4c19ca82-aa905eaf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10292371/s56502123/a833ac30-cbd252e6-76962ba4-f268fc3c-bf7fc62c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15424569/s51736005/65843fd9-26d6e944-e7066033-8c441616-1ae78ae2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10141364/s54003357/2a028ed1-9b28bfbb-73e4f638-9bf82265-4b2391e4.jpg

 32%|███▏      | 1604/5000 [00:32<02:29, 22.75it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19299811/s52703059/36e54ac9-0df72b37-5097e367-938fe531-f54d9c0c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15761111/s56011866/90cfe5cb-db0573a8-e53ea866-fd513b76-40be528f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14501760/s54515405/313af90a-b7fea433-67fbe1ee-a6999fb6-0a38dd84.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17172139/s58218678/1194edea-7dc32dba-9388ff4b-bd0311fc-774a096b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14102384/s51173866/34ff5124-563c63ab-d9e97e2e-79dd5614-065e713e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17449903/s55735283/d0ad5adb-3e074ba7-a74d4da9-6d3a56ee-2b642897.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19692222/s53947728/cade4663-b5be984d-1cb21879-baa785fa-6f358f0d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10679708/s59741721/a92f643b-a40e116e-bdf1b200-f23a2575-3efdf753.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18739705/s55346376/1dd4c744-42eed69f-6dbc527d-44088e11-12d2d4d7.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15675092/s57253749/e8b04cc2-4d68f1d3-10801686-c9cb3555-3d5ebb43.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15150433/s52077975/ef1f463d-9c4b6fde-d02918db-992660c9-d33d3445.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15273409/s57388176/192d0bd0-18a25ef6-cbca3a0e-9de2ee8d-274a7ab1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15647805/s50488019/217d29ee-1b22b498-518e7be2-b21f4bd9-ef6f0d9f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16194267/s59494565/5bdd974f-8d49e632-ddb465a7-6a394985-f655d59e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15032392/s57788546/eac966d5-8abbe8af-e82fb70d-09d87cf7-ffd78f4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12450697/s56853659/1251dbff-715989a3-7c882ff6-3b5c0b0d-a6395f6b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10765748/s50879964/762dcc36-d677c29a-5e51e346-eb66d876-e8f04993.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16142940/s51625976/ce7d144a-a25d1ffe-15d7e41a-43d29356-d22d4ebc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18220139/s55063257/8b8648d2-4981ec0c-d370a547-57727528-2ea3d57e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14901863/s50170118/23c86f22-7bcab69d-ea7c9669-4cc57f28-e009b1b1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15131736/s59800551/426bad34-c84321a7-37a7e076-e0395dc2-f2a3123a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14324214/s56391924/cf28a25e-39f5ac26-1144b194-3fbbe5cb-c6a6e3b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18687658/s52207405/7c8b453c-b1bbe232-3397826b-889f8aa2-276f6280.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15894036/s53564922/1e9e33a0-b656b054-cb0ae811-6700552c-3904384e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15577719/s50837004/f22a2334-d05c06b4-283d801c-97da31d1-3c446204.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18708770/s50616198/980feb2c-213ed1b0-092896f0-447953fd-b2061d90.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15499581/s52960684/06546902-b3869b74-267b6302-f6490fe2-2228abc1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18259094/s51868646/246bb1db-298ceb79-2292d71b-02320873-caa08ad3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18701564/s50050051/9e0f43ce-e271210d-7c523831-4e0f048f-d24c9791.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14013080/s59507979/85df6d0a-b7b0812c-6f1b008e-448bf8d4-4c757412.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14930522/s58607574/1d18e8f3-a85771e7-9e0a6517-ab6a89b2-7ace34f7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17646651/s51720680/ed88e0a8-9453464b-69f2acc2-6f2ee836-c25f8f0c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10395166/s56991719/4303a963-d318c73b-449177f4-5d94c47c-6b9dc076.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12629934/s56581804/43561e69-26d86071-1d92a3dd-f759bf99-dde47a87.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13948093/s56356078/4b750cdf-c4a3f2a2-ae8c7830-1ab7e31d-bcd8ae5c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19437821/s56733960/02f64e09-3a12e06f-14104b7b-a312a7bf-ed3690ae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16268396/s52916607/35d9bf21-2024eba2-1e42252f-bcf7f4d1-3df8c524.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16366110/s59165540/0b5c451f-e0f0e8b6-be31e889-b228f45e-7d272ff2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17885958/s52445925/bdd55ba0-8537b4a2-50b49ff6-3742f345-69e11033.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16414344/s51527134/5d44f626-24583d1c-12ae3537-2da4af73-2bc61ca9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14775722/s52180408/d57afc23-5ccc7796-a8cb534d-c1fee029-4ddb4245.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18156009/s52028303/1e84781a-3f2eca76-01624baf-054b9855-50541953.jpg

 35%|███▌      | 1764/5000 [00:33<01:00, 53.36it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12102463/s58767590/071055ab-6cae164d-7d2d4b47-2f165b64-2848289d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15735160/s58204554/3466c356-d9f92f66-6298d119-f9f7e3a2-838bb16a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15214632/s58386632/8b37e2ac-5bc97dfd-5588dade-cf2e6546-cd7a48ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15617297/s56109183/5c2e1a31-f36b2c94-2c6337b1-e8f8c1a5-2f00e04e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10304258/s58875276/8c7dcc56-fb23de47-93b1f009-ae96ed06-69ff10a7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10838161/s57788080/85e31d7d-26e78c52-159f15fe-52747fe8-d5e0761b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12759378/s53493598/fbdf3148-d7efd67f-9a3e1693-78d837d5-ad518d2f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18055482/s55422097/79942c89-5907283f-1fbfb3d0-cdcda04e-26e7d342.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15094687/s58351989/6c76a706-b91d1f34-31878b34-5317bb36-4cdba272.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14754762/s58682241/6b3eada8-54eddd08-89042dd5-efe864d3-ce4ae865.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11151938/s53020796/68cc5bf8-949df1d8-2a5b656a-f51cd304-29e7359d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11936013/s59990145/517c6db4-8f57a7a4-3af7c12d-e8efe35c-71a500aa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14338016/s53216565/09d7524c-99c0e2ce-11174550-600c35e4-cf9c0092.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12396999/s52831138/f8cca216-c091464e-d4010bb5-ff2cc36b-bd674392.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13040755/s54165033/f3c0f17d-0d758997-8946f2d5-6e1efed8-151b3c6d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14525215/s54756795/999a9ae4-79c4fc3f-ee082dc9-f4028c6c-d099a602.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14719866/s52233655/af89f05c-ab7bff29-ba31a9bd-b0259018-2994e510.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14028368/s50042549/e0f10952-5f7377ab-50802503-01708bc4-9197b0bc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12469804/s56104166/98e3ab09-c27fcead-d8e1a53b-6577f669-619547f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10215159/s55399002/4089df56-aa5d2c00-5386c4be-1b39949c-fdf666f4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11209039/s50322382/a82a6fde-f3e6b472-df5f3869-9ddbd024-58008e78.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16398746/s57558603/1120941d-f323d001-d0c133d6-a598dde4-16160beb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17167982/s51835112/889dcc9e-6eeb5343-acc7f927-d8d8b959-d81b02c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12997284/s58867188/4e5c764c-b73ce52e-bf4c0445-b62ee836-6c127853.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12679321/s51335906/0e7899eb-4a6643c1-14e1d83d-80889a76-ca61fd82.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12138575/s59674875/d4e3e010-cc83654e-b6b4e073-515fce0a-913b9b58.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18505898/s53222442/eadc7441-d89954dc-bd8e00c1-54d5f51c-8c40eec3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18753725/s52650223/ac3f7b20-5b97eab9-caac7690-eb991307-6cf37de4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15358488/s51858896/b29745f5-1be6a6ab-3f6663d0-74e7556f-e7a4dc06.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12275484/s54607434/0a3ebb1d-dd17b688-e07707b3-157725a1-1b45e9e0.jpg

 36%|███▋      | 1825/5000 [00:34<00:52, 60.66it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15158950/s51527487/746ab8dd-194cd9f6-286cc3f2-2b8dfab5-1190c9dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14258993/s53147406/82a7a5c6-372e3bdd-bd6df05c-c8efb462-6ae43ebe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10455424/s50470393/66de89d8-f7343f03-d4764176-5fc72fe5-effe351d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11676964/s51026200/32dec165-76811457-221f7f0b-5e7c20bc-a8c2b883.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12405540/s57164255/0b8ed805-118d9141-c2a9df1d-13c5112f-56b38b7c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18295542/s58685522/1f20d47e-75d60e36-0143b9e1-ea384555-e564d9fe.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17924864/s57174804/6fcc2afe-e36cf12b-bc34184e-8e8ea613-41361eb7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11170345/s56690651/cc42f642-815d7055-6d4b206a-cde7241d-95c0408e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15075859/s55016944/bcbaf8d4-870b134e-ebcc6a7c-b1717cef-02f22850.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11185907/s54260647/11a52b1a-42632138-3c07dae2-51d5fe7c-9af46b42.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11070329/s58212324/97b21769-fc496d70-d63d4cdd-57e905b7-4148317b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11287042/s56969632/a19d711b-6c29af26-11883860-c9e6a00a-dd8b349c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11494804/s50477897/3cbb6127-7957178a-d30446f0-33e1af0f-f186a298.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11917530/s50393766/8dbcaa2a-66002147-7f680be9-3c4185a8-fc484e28.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16033728/s56111698/6c6315bb-0cc3a317-0edad4e9-56a45fc0-898d64eb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10298228/s53475248/72a7b737-84213eed-15886afe-d9c65d66-b0c41d30.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13439409/s53787065/486b8f05-451c7ce7-ef0e32f6-26a63f29-b98627c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15051397/s53600267/ef4973e7-73c5a06b-1eeec86a-76bd0fa9-abd2ae9c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10598199/s57995808/315cc543-b7d2b9ca-f53bd5b1-ffc05f1e-3bc90b54.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19607985/s59860455/6afd6370-7c2f1aa8-e1efdaa2-c09e30bc-49c1fcf4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15808774/s57619836/d4eb2db0-b287fe1d-d60e6f93-457dacc4-078ae371.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18388859/s59056348/c51b0e6f-2460f75c-5f29731d-fb2fb73e-9d933881.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14755254/s52541155/40501dd2-88ebb5de-9116b3fe-fbba7c11-1399a76b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16024669/s51176291/660dd9a3-99a94aa3-9e662316-64f24827-e67ee644.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17162389/s55019996/618fe4e7-bba3d4bb-d552c376-0e25a1bd-0bf2b081.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14887253/s53179115/2c98e4d9-17850541-313ec0f2-7bcd89ce-8f9c08c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16087436/s52204443/c15ffd01-d4c677f0-2ef06b3e-6f08949e-1b5fb1b8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12728628/s51628022/d18e1135-31631f13-7317294e-3e2b64f8-8e3075eb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10799304/s52686299/666cbe74-20fa87dc-a66e1a34-ba080d7f-74b6514a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10064390/s53483779/2bc1faf8-e986c1c3-da21cf21-08d61b1e-47bd61a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19375263/s58855935/d6b85b07-07d13ca4-01dbaf8b-6bc884c3-1816d99d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12614981/s57459597/1f13aaa2-9e9b7ab4-37981cd6-60b39fb3-c36600e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12371096/s50558176/874bc4be-f68b6179-d694fed0-63cf718d-c4302b1b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13125781/s50748383/2e6cf090-a7bf4cb3-d9965c7e-0f69ad71-d64d671c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13292409/s50584469/8ddd53ad-5562865c-8a3f9248-cddb0466-adc2dbbb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14487388/s54371002/afd18430-f7ee87e1-90a53e85-175f470c-60a355af.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14698539/s56219501/19895a0f-0d7312e4-310b3772-73a3478e-1903f3a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12631015/s55111341/2be1f6e5-70b6b188-3e500a48-e65f6a45-39a0316b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18974737/s54366365/673998b2-13daa461-7638cdcb-39441bc3-b5eb4b25.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19027367/s50008217/ae293037-1e42503f-139281e0-7b3b4e50-0cebb978.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19966568/s53135744/7a4ff021-185f48f6-74ba95e4-af358437-20df6c53.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19300381/s55000640/d8c6d6c1-c73bee53-8b1b5997-4d30a68d-88a04aa4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19515421/s50360196/b045d2e4-fc6b7ba2-e554acc2-7571bdb5-b5f07e27.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14873669/s58770603/b635856a-d6411c5c-cc93528a-75eea59d-bde56534.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17463554/s58095002/8ef5bd37-d3bb8c5e-24cd0186-cc986085-5f4d667b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11697323/s57288013/029e55e9-7372c040-3cc20d53-59f2fb17-828ab697.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16167811/s56845184/7fab23ea-26c542de-7cabe5e9-8c6ae07c-5dc07907.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12878814/s56467448/f6a8e6e4-c4b93150-a5199778-6724f401-ccbaa390.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13520909/s51578820/b8ba93d0-b12d9433-f4d2d554-f954442e-76944b6a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15403852/s55991451/f8a2d92d-1a8bf6f0-40b43079-39947085-a3fcbfb8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14691391/s50159184/62739588-e8b5df70-79679ff5-1e477285-202c91f2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10804721/s56311807/3c28c39e-df986b1b-cc682488-9543a2de-4efa84ba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18599567/s50269495/dd045735-e121f8df-de64560b-017b6181-809beea0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18860477/s56439228/24204276-bcda3a4c-3d31ba76-0fde73cc-02d1bd30.jpg

 37%|███▋      | 1855/5000 [00:35<01:05, 48.23it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13200877/s51036798/05197ea3-d3be2ce5-33c84ff3-588abd36-4ca718bd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18877812/s51331626/2e0eed2b-998e75f8-49a6308e-575b82f5-ef833166.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13224377/s56665830/fa5c6c55-23da4cb6-f54ec1b1-96f46186-1d6ae158.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18230098/s56477168/519d9d09-fa7046ad-3d6e924d-94f05f91-070aeb13.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18902344/s54908509/565fb49d-4524b79a-1b847c01-24b9f2a1-6001556d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19758044/s51503974/0e090464-b8b6bba0-eebf7be8-2089519c-7539e753.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10521666/s50653988/aedd71c9-e148a5fa-dfd4da8f-bd79e61a-f4ab1e10.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15617050/s55032603/13e041b0-16d105dd-b84d203e-a67afd53-ffe621c2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16465613/s51992362/86f588a9-5bf33e03-d44be5c7-9b4016e8-b78a13ac.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19375263/s56804518/4fe0504d-627cecf3-1e769cac-fe7d2a6f-f1ebf0a4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17266039/s50365408/42653789-3b41a3ef-17431389-141793a2-481970f5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14954046/s57975760/a10146f7-ac95b614-c9e9b600-6385e6a2-07e65995.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17698363/s53147181/78f3f7a3-1c8d482c-7db08029-7dedbaea-0ae69111.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17282935/s50662927/6845d952-925332ae-b8538572-9021f8d2-c8b7af7b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19855099/s57100919/9cd1a0fd-59ea00be-e00ff31d-9c1ca4b4-9c1e52ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19333044/s57773110/b265cf2c-1c1a3d54-89da4b8c-8948d496-79b2aece.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10678335/s56809349/758b5b5f-840bca9f-5c90bf2f-64c04f04-65133b4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19788382/s50093647/5340ca72-217bf602-c6e353c5-a217ed39-45d77e12.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10699336/s51739703/122f959d-4f8b329e-a8f7bdf1-e04d2293-346c4333.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16517161/s53689640/8ef1d50d-bca15a86-148a1969-23d655b4-9fd3c908.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16316457/s58596796/3639ddee-c635f546-03d1c088-f61d677e-590d2342.jpg

 38%|███▊      | 1911/5000 [00:35<00:49, 61.82it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15124686/s56673947/b942033a-3805ffb7-90997a2d-725e615d-a77a67fc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15724177/s51276585/ba163a42-900bc9cf-2316ce97-d2c35e66-bfcb8627.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15862403/s50838230/5ececaf1-8dd22815-06bcd827-06f8bdd9-57b0d3c3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16949275/s52915264/34f16ea5-b646ac2a-2e89d1a2-de200728-c4001c06.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13990946/s54731020/04171408-d45d07ef-22484441-565c3521-c0a4720f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19373873/s50225897/e0ccef99-d8dba812-8d6c2525-973cf1fa-118dc201.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19398915/s58893396/2ebb0fc9-12dfc78d-d7353287-a79196b5-cd75c55d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12380407/s56873486/0660d820-fd0fb904-8cee171b-d8ca4a9f-24efba68.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18573712/s58748089/8ca3d3e6-c72f1be6-a8cc8a0b-8af04612-87e62d3a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19344311/s59251896/4fbe1c7f-dd7f7764-efd4610b-c9ea23ed-f55c9db6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19998843/s56350227/23ba9adb-5344e3bc-0a9e5a61-80f56ec1-df4c0a97.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11892979/s53258352/d0f1b754-3900edde-60a50ccb-5ecd34dd-4caf625b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10365197/s58918212/5f5eab7e-f6a7a455-21d0160a-ad15b35c-10b0a4e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14799868/s57441627/ea34cab3-a5a7cbe9-20219d6a-7639544f-021afb92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13230656/s59200203/577771c0-b5912e05-306f5858-40636bec-1e225022.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17026123/s55625836/2c8c8269-24115181-e93d0c81-11b77151-c9e8970b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18055482/s54336106/6cf0410f-d20ec0a4-14c2fa05-cc5b3f96-2abc90bb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19864406/s53579171/200eb03f-41e6584b-11f8a435-edf5cbec-aedc3566.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10597655/s51870716/b6c24885-a5ae1e07-b71fd8c4-a1250df5-0cf86adb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10724174/s50634429/55168258-893b1cba-fcf79db2-f7c9852b-d8aa703f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14432490/s57950124/85bf1190-79027be0-562f0b59-2054f19f-df13bd15.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11115152/s52701590/24107da7-961a1501-49149a41-5f114605-0af9c3fb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14280192/s59344797/b875efdb-22ce2414-e974a955-85bbd6bb-05d86364.jpg

 39%|███▊      | 1936/5000 [00:36<00:51, 59.12it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19830694/s52889779/ccb1acfc-a9f09b4b-1a4ca6a9-3b913beb-374486b2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13877262/s55654953/80318130-db039afa-a30d6a1d-a278fff5-330f64cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17333919/s54089496/2afa3f11-117ce110-80182547-ad7cd086-569bb900.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13110963/s58949064/20e6d7e5-95dbe5ce-dc5e7723-0999596b-e073bdd1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13187486/s59359037/174b5a67-765c8335-badb5b0e-8c0ff3f3-c505f3ad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13364239/s59326439/58c55ab9-44717fef-3775da88-0b64b0f3-877533df.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13675896/s50066306/79a93685-a136417e-c33905f9-d8f4598d-ffd738b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13512648/s51475080/361a3ef4-33fa9592-c86effd6-46d031f9-e9442ab2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10144569/s54816756/af27eb7f-ca54661c-72b05e4c-fed2a9cd-0327dfc2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12903663/s59978339/642c11e1-1702ab2a-8bb23b5a-2f78911f-6ab45b9d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13649911/s59017438/f0b01279-3afbac65-e9cfcbc3-46efb49a-73505b29.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13373868/s55827029/3ae096f0-8d0cd62e-0f3a605a-01ca8861-dfc83312.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13272142/s51538518/5cde9ecb-315a94af-5fcafa65-d5a599b6-090f7268.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15787214/s57153575/c710e145-280390c3-5b9ddcf7-faa611b8-b39e60c8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17978570/s50134954/76918f0c-ca3f6d36-ebfa3d08-8f192c8f-84212d6f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17804391/s50631298/a4ec7f0d-e1fa67c1-5761f4c4-4ddd7332-c1a98678.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12213423/s50084112/3b5faadd-8115c334-cee45173-18f3a01f-a5ec2505.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17872769/s59159158/6f62e377-17e625a8-400d11fc-6051062a-40438b81.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18623182/s54881631/5e199376-6bae5536-0250809f-c1c180a1-62e6b53f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17066802/s51732532/e27335cb-165c0449-e6ebccb6-65db7f9c-b17ee1e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13748842/s58648583/c1d46b89-3e4302aa-e2b280a5-3c91b734-ed542ebf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10471192/s56382206/2b6685c3-e0104bec-0bfef00c-808f62b1-d9e47889.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19330158/s58299126/a4c45fde-3071c725-7b125b4b-e8d49a65-6a60e95f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11658675/s50176659/025cfae7-a0123ccf-2f7939e5-2fdc94fc-d32890b3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16356118/s51548136/d4a0c7be-5b16c150-f36f5f27-908de30c-70fd8986.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19249586/s54951892/0d853313-9c796c03-90a5ef79-192f2555-c81eb422.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16522757/s57104616/df3e801b-e7a2a583-48a4268c-95ae757e-fc8c1172.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16117323/s58992942/e740101f-4537b16d-94a4f3b6-6666b44c-20d516e8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13235049/s55232479/48def754-2cad05db-d856cc9f-8f952c95-7d6445b8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19123001/s57290885/56ae0947-35fdf678-7950b62e-95695c55-c5fb5646.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15586571/s55927008/e4b7e56f-f8ccbe55-d8f166b3-ae511975-6ca3a49d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14729496/s52476573/75449e0b-6c831106-7cb06e83-785fe691-b2141fb7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11851243/s51748539/b94ef3f8-26374e25-97a6df53-069afe71-4a539a27.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19765968/s50775929/b4e5e6d9-372dda3f-636a7faa-cac88b07-a21496fe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15634195/s56861319/7d6f58df-a5a37d63-61e03de8-9b9becb7-68f44b32.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19048920/s54335663/816ec95a-3835bad2-ffd1234d-895b8946-8fe42f0a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10559377/s54833677/61d5520c-efaf2ba0-17384e0a-1aa02f5f-51a78600.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10819468/s58019262/73265e77-dde93141-d8d93056-68988322-9fd4c44e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15319814/s56268474/daf633ef-203693c7-d649b467-156b71d9-06143368.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14789176/s59710127/0df3fbcc-1b3283da-22571db1-a6066184-f4daab83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15457916/s50345300/60517497-065eb442-bd2e0b5f-3ad5abca-7b639430.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15508006/s57476455/155293ae-67c10a66-511e45b1-bfaeb78a-82a6886d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10771274/s57636595/e3b348f6-d8be8c5b-f4d8bf31-b53a45e1-45eaed1e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10536742/s57557952/f4f48f5f-b7c35205-31309ef9-4cf78935-5a6aace0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14498233/s50244171/cd3c5033-80263ba4-07d9cd39-09468ab9-f864f9bf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17079101/s52544664/1ad714a9-437bbce6-a694ad02-05512130-333e99af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10481162/s58541326/bba21ef2-ce23a91e-898f7c3c-bfec6f6f-46339dda.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10123147/s53504320/4356f829-678fd0ba-3713702e-bfd468a1-0b1fb892.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17079941/s52136309/acf000ae-662e087a-96e6c4b7-729b1bd8-064307cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12622624/s51046480/d3ab65ba-0e4933b3-329f47ff-3304bf93-898e53c0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10999395/s50594575/92460b69-6a98f69c-1d66e16e-b6690aa2-12738a1b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17197713/s54262120/252de756-e79993cd-31c83d14-2088412e-71dcf922.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19635953/s58748595/a7863844-ee104e38-abef8d07-8262cc09-2d6983ff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14316200/s58869167/11345917-1dafe3e9-972faf79-692a1f56-0b94ca02.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16289299/s56576834/44b0bed5-5a030272-505267bd-1684ea37-031669b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16246903/s53626698/75eaf49c-49ec8d58-782cf5a4-5415218a-49342e83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14927583/s50748921/605041ce-bb028b9d-05f72d5e-204bd77b-d75b0600.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19743788/s51631516/36034610-66d3acc7-ead51ad9-507dd33b-2c969e33.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18826099/s53279429/2e3cfe57-83b406b1-954deb30-c3cbb489-c7f983c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13040755/s52995557/92686b72-5503a4e3-af4cadb9-ebb838ed-167c310a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18588825/s53747604/c9a52433-a0a27e56-9f3b12a3-ecd69b32-1d3438ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12577020/s54397259/56ba6b72-02673d91-a6e01ae8-9df5757c-a836959a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12759077/s58567514/446d95d5-64fb6f66-907a1e54-928e31c3-98c37833.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12694726/s52163581/e49485eb-18dc28e4-d23acc2d-c2e4723c-4812a89c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12385109/s53691560/3f6a32ea-ada21fd1-c6032088-b648a2ab-30a5bd84.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12118431/s59886424/7829612b-4f168c31-fc7a182d-085d0e85-9962d727.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13502902/s58003645/e485454d-1c4171e9-af2f67d2-2f8090d5-f1ac4992.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18732946/s56637337/17c4dbf8-42230838-83ff7c7d-4b7d2c43-411b5f8c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18052788/s53511384/e24208f6-9b86dfb1-f48de9b9-1136247e-0b8006c1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17030279/s56020403/11130e14-aa8be1b8-c5826a90-d98fdc6c-0799212f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17417511/s54218686/f2e1a463-5b13d8a8-8cb9f5af-87766522-52210a83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12579469/s53888483/ef2c8966-6de151ad-4599f485-418dd5c0-eb68fdac.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12579469/s52221011/408983bb-4cfaa36c-e394626d-403c92fe-bd200c4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12272771/s51062351/5fe2b6be-462ffb37-c0150f86-4ca699fd-61cf61be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10928511/s51362863/bead1c9b-c17666dd-8a0a9b7c-bb6e17ae-aa9ab121.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13438658/s59841238/ed6ebc7e-0863e191-606cd84f-9347e9df-04a61a06.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16736889/s54226595/649469d4-1c4d96db-243a1d85-6682bf4b-3fc09a74.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17646651/s50442208/fc75e61c-ee134385-a5d0e01b-695f8125-2ed13ad2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12041762/s50955042/50a38032-76896955-3aab02fa-e326edc5-f5ddc5fc.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10667727/s56070341/18b007bf-3dcc9cb8-12f7edd7-5dafa3e5-7a492d99.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17095377/s55015542/afb2fee0-0409bf01-a0ec4758-97435693-13a3866f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17347760/s53643435/82fce21a-aae7b1f7-16c57eab-3ee45596-d4870bfb.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15000393/s52929930/8a2da5f5-09ea301d-768e059c-5f053a34-2d3b3057.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16301937/s56474006/62a1d5b7-b68305eb-0c07a4df-8b232378-58275268.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17288685/s52479929/153e2584-7a808a39-413c8af1-3796f314-f2a2e114.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10215159/s55250786/1fb39448-ea8ca910-7f85e3c9-628e9f72-c9ad63a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16477367/s51514816/622fb8a0-23f141d9-73de5584-6c99d435-1a33100b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11304959/s52048498/86585197-cbc7081a-397c8c70-b74fe19b-bf1e8e49.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10004457/s55439624/ad41d9ed-37ff140e-afe872af-224a8477-f98ac392.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18264374/s53137587/eb85cb7d-1dfa95fa-5a2eefe8-44d26b61-79c01940.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18003419/s51071133/5e25a8dc-c8f7bedd-faf68dd7-d05b68d3-cd7b525d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15420371/s57284558/b7176b8b-285104b9-421b75ba-14929b9b-61b5f016.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10749008/s59080389/83272fd7-ad733426-13aeb1fc-d663420f-0c286965.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15260041/s58614091/d20e3551-fc73763f-1f227275-a22a2d27-5a58489d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10795434/s54462061/b0c92d40-4cf473e6-0946a09b-ca0b0ddf-b106c285.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10954764/s50695788/670b75eb-678bfa50-8ee3c134-747a69f7-ded72c9e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15545849/s56557433/12b2190d-e5039653-34e873e5-0cb926cd-15174041.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17195321/s53963746/65d23b19-9302af6a-76c18ebc-167f432b-414b35d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11164502/s56943674/4f57f9b5-6ec1bac6-b5283f8c-fe89207d-d10a4013.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11951880/s56746319/cb63f128-1ee4ad55-efb51f68-c1c94178-56058160.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11008656/s51496853/540b42b4-9973d603-654c5767-ce6b63cd-db025da1.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14235312/s54356881/03db1e13-5c230041-3e78c2f8-fee109c8-677b8c65.jpg

 41%|████▏     | 2069/5000 [00:38<00:49, 59.81it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11347765/s56394090/25da6a94-18299cb2-80ba7112-75ee5de7-ce792651.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11937809/s58784930/d19dc40d-84b13b17-8fcca360-f8dfdc15-fd858596.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17980434/s56097883/6c1df4ad-939af6ac-e1f47f65-119dea01-524688e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18143542/s51665180/17749986-4c259510-45784e73-a7695e8b-25bb4859.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14687773/s54247352/1ed681b1-aca40082-61de8bed-a15bd7b3-98ec2ff3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14998376/s54546516/b9c58693-493ea8be-2a1f76e5-67a5aa76-91540044.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14317948/s55501876/c747c9f9-4624cc6c-04b17884-038ec677-1ec25214.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14195976/s58854561/245b0507-b9382e80-5eb94bd1-e981435a-fa30392a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12052446/s59815442/ab708c9d-bcd745c2-76bf2f1b-985fae1b-6add2c44.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16860825/s58244256/f9c281cd-d689af30-5bf9f0eb-8e45e2ed-090b7d52.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15223781/s50685580/25f9666c-995b1131-59e255e2-4b3ed6b5-b0e1ebba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15343196/s53891354/3dd7a9a8-d6a1014b-f07f73a0-6dc3e6d5-c9f45f9f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17708877/s53133170/f89f52b4-8374094f-94ef01e8-cd46fcdd-41b665b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12613157/s53244659/d351da55-3740dd76-da1d572c-e4ebacd5-513e3161.jpg

 43%|████▎     | 2161/5000 [00:39<00:34, 82.49it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10337061/s59165166/b4e2a4ef-13185b04-6ce118ae-79b57979-486153eb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12408912/s56822115/bdee9015-f1de52a7-04070943-eaf0b6ff-452dcf5d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18022328/s50489243/9d8c6915-2170ddcc-106a2c17-8e7fb385-99fd4aa4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18794764/s52214834/0f63535f-9aee66db-ac79f8e8-9152a4b2-9403bf83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13381209/s54910552/bd262f8b-7480e035-0520ef42-d1a25b38-4fe0cc1f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10320599/s57140965/b50967b7-67ca3fa9-43bc48cd-e59faa02-3e00ac46.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17353183/s59867028/d42a9d0c-39b627cb-1af850a1-ad0477cd-d9b92c76.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15426827/s51260271/ecce4aac-f3b0ac6d-35112b5d-d3d969a6-08f9853c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18976063/s54561816/80f21436-7e171cb5-c6492e6e-1a4a3bc5-ce3f42c3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16697206/s54718745/d836cff2-a0924af8-0c98f877-a8716936-f0202f78.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16302059/s57484760/49e1a76b-06249946-d8e572a2-8a2dac41-9644a223.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12921573/s51540258/782a7151-6fdea076-582bec8f-3b5ef9cf-d807e391.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11069015/s51847085/1c1d288e-bbc58211-2048011e-af8a3904-bfbe9916.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19692222/s54534919/543bc0d5-37b98ede-707211ee-d9f50475-d0608a34.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10304606/s54409712/8049a7f8-fc171b43-71357457-bcea1355-469437d7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15078112/s58703686/83f879e2-4b41e8c4-1e479613-bd239a65-7363ac00.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10188275/s58439563/105455d9-1ba3e937-3dbf97d6-5c8f52d9-71029c56.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17559288/s54614197/7e6df081-ae0880f5-c5c3aba7-77eaa2c1-d46f09a8.jpg

 45%|████▍     | 2234/5000 [00:39<00:28, 96.23it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19827390/s58082343/01662070-ac2c6561-47e0aed9-375768cd-088b1acd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19765086/s53873724/62daa0ec-9ccd0135-68950aef-5cd9d565-1025f857.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13018979/s51686833/a594bedf-1eeb8df9-13c0ada4-091a8bac-cbb81ebc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19467162/s50554227/fc77869c-28f636da-18ad2064-81cc8b6f-320a4a4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18917209/s55386001/b1c78824-a9f138ec-f6c8975d-6ff79069-c2206be5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15612808/s55679082/c2045135-fd094217-a865d416-d9e3b674-1a7203c6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10188275/s57260832/bae5237a-19e72819-b16d3b6f-725351a5-0cdfb38d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17277688/s57941477/41ca4407-6f4593e7-70ba11d6-0fd5801d-634d3a68.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10245082/s58074309/098651d9-cb25803b-84561402-a618afd2-891cd449.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19963140/s56828395/792e6626-609fe86e-268804b2-c57c6b64-ed4c392c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10610599/s54184981/d14b857b-868ba815-2f9b7eef-fe8f8974-bf942b7f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18698549/s54874115/19ab759c-c5982880-62543ecc-3863584e-24ddbd9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12106204/s57386348/c5b2b9a8-aa8fb615-a7dc61e2-fea1dd29-d8269eca.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18997544/s55138097/7ae60a12-8274821a-282689fe-257ba0c6-71525b2b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14174018/s54285091/4c10f64c-4aa3ebdc-f74ceafd-c1d41df9-93f00788.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14113035/s51752848/3b060cf2-d8e1509b-b70ddd66-a8c54260-bef67438.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10088198/s56156638/d0656966-f0296636-d53d22de-9cbc8a7b-7418d5d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10670818/s51830074/b52e79b1-27394648-bf8d04f3-12ced4e1-d9de30ca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13478462/s53684858/2ef1b9a2-486953ba-d7e61d89-6859c550-608e99b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15911529/s52646931/6e3a9cd5-91eb5828-ac10bc10-24dfa7c0-0e536576.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10896351/s58008147/7983d382-1a652649-11ec79eb-0fd9778a-78b6a839.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19859251/s51121748/4ffea934-0e24b448-7068a747-2f017537-a63f0cc0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10337761/s52982082/0374a4ed-6c473ef2-0fdbcab1-ae0266f6-74dd6da4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11044215/s59054628/aa9e4a2b-8bc0a181-980d75a0-25762b8d-3f71442f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10546701/s50330902/a3290450-a4841160-d326cf66-2feae17a-5ecbf212.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12620320/s50340530/7df86a56-7e3f4980-e819ea78-6da9d5a8-90fb21fe.jpg

 45%|████▍     | 2249/5000 [00:39<00:32, 83.45it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13801250/s57654280/943eeaf9-dc8075c4-65df724a-fd895361-76ea49ac.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13831349/s56554579/e45de464-102cbae2-df3c1b1f-38d8abba-8be989d3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13598803/s51261465/ce3c5973-ede7066d-67ec7b44-6a0f7bed-80915475.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14014948/s54073689/25117a23-a7c79c65-b81ba60c-10388c78-bea0fecf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14375008/s56848635/488d16db-9104c67c-75c9a1a1-3b58a183-e466951b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15134995/s58880931/d5528747-9ef67df8-a86605c3-a5e1c1ab-43500a39.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14965197/s51176095/b6ec56cc-8db7d703-81c85ec0-264d1127-59306a06.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12914859/s52760846/b6f23283-cfb7d700-b42fe7eb-db75f59e-853075f7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14405281/s50424411/4d8a169c-f2eb9f6d-1e1208a2-d1aa880c-852e01f8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19647041/s58126413/89eca405-8947ded0-00eddb65-d6673455-2ba4cfd3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15818607/s52125387/101a0133-b52eddd0-cdb91dd0-2329159b-4a701b79.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10290812/s53877743/f4a457c9-5734c67a-9c12133d-12dd5e3c-219e5fa2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11184688/s57431441/221c9504-b927c95c-0514b0c3-dfd58938-91788f68.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19759491/s53350789/3480ade8-6825b33b-dc07898d-97d83f8a-c743b07b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10072167/s55283974/250a78d4-af5baabd-28ba3b84-13941316-dc3f1d7d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17805601/s53093914/085b6c7f-6d9f32d7-3f3a05b6-30766070-60e077af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17553392/s53886555/a46246ed-2176424f-b7d65d78-41a85603-b614bde7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17648869/s58816751/41fc39d1-8ccf2339-6a964947-f1a826f0-dce0c02a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15488402/s55773892/96a8ae02-1c9910b1-36fabc8e-ece85eee-fdc408ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11585755/s54561046/2a978190-6bd73eff-b579e6d4-1d95a2cd-9ed27b78.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15034985/s54956414/584d5176-eabab024-495d3339-c2766f6f-69485449.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12256309/s54468229/42845f29-9f301cc1-376f336a-23b5bf3f-9dba6057.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12533087/s54514918/abecaa63-bbfde02b-1fd966b5-a7ecbcf6-419f7863.jpg

 48%|████▊     | 2417/5000 [00:40<00:17, 146.98it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14941305/s50456523/5c174950-1b852e7b-b2f05850-dbe3b058-296b464c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18826698/s58930478/b7194dc9-4a14b8fb-299e9108-d9054e5f-a29893c2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15101598/s50698894/a3877cb6-dd061886-b61a0cd5-6ace2bda-19c72e60.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17856695/s59247798/5f9c8720-d261d608-4eac4250-acbd430e-c84cbcce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10532853/s52292676/729b5748-eaa3fff6-23e47a9a-c9b313ff-3a4105a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16500918/s50707674/e503d2d4-1e93a24f-c37b2315-06805ef3-5d9ff03f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17201534/s50932752/ea7fc278-92056b77-75da2484-d330fead-4116a6a4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16671659/s57525874/b869bf40-1042554e-0e7c8cee-5fb96281-e94929b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17934671/s59497020/92356472-65899ee1-8c369f5c-1632c7c9-679efc4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10078115/s58319102/0226e07a-fa9df123-dc0ac293-1fc1361a-6c332c74.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10764840/s53962616/3ff729d2-135d98dd-bcba0821-634dcd42-86f1b18d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10600115/s56290887/fa2c90aa-ef6ccd10-785010e9-c399175e-1506ec03.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17771423/s56346203/85004d93-29624f8f-fb6a703a-5ea33370-bb82392d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16313531/s58455247/00c7d4e9-802b89b1-4bd840b3-e5fd2fc9-5d38566e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18981283/s53205059/dd8ae64b-4b97c0d9-75f9e21a-39ef33a8-ca479abb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17567845/s51699794/78d0d735-418e4c5e-96fb7cad-f939d6b0-aa577a9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10913472/s54337759/c1e60467-404d3c40-e729204f-678a3626-e5251678.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15882528/s56370018/3ee34fd3-da976fbd-39e3fe64-9460bcbb-a07100df.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15288300/s57406322/0dd26ff1-3c69c476-3a7dc3d6-aada6f5e-dee29d7f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11787832/s51624844/91384d2e-bf1be807-f4b34dd2-76b7ed6c-e999016d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11206626/s54641290/d0e904ef-73df08ab-3f864ddd-f0c91278-93d41cf1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11511458/s54965069/d47075a3-87051b24-ffbba1cc-14465e9e-370f327b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15526304/s53225594/98c9f96f-60e148f4-40100ae8-0b738886-f2879b02.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10073646/s52430157/989187e4-e88b4477-fda12c36-68ced994-cda88a83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18835879/s54104761/b5bb8236-0a690d89-2d4ce952-ce7214b6-755439f5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18969221/s51576451/51c03481-7e9a5e4d-eddbed85-eec37bb5-1225b3f6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15456778/s57844824/05bb4ad2-889edb1a-2a194982-f80b715e-0057045d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18396526/s57350400/f6320599-38836425-161ef3f9-3a8748ab-9c123ec3.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12043836/s58006558/da396be3-dcb64c27-8d3302de-11f07510-fc37d4c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12713061/s50741428/4ba6d2b2-409e0e67-4149de00-00a8a1a5-6ee31bac.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19398915/s58361945/775c85c5-621d1f8e-b3e04c5c-4392c35a-ee6e359b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14413144/s52549919/aa9c62d9-d127147e-01cd57d9-c9fbd932-d4ac1538.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14459723/s55170153/b217d96c-a6aa1295-735f1f0c-b8cb0952-6012bc1c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19827113/s51878276/3f8a51bb-08263889-80713e6f-4e42a696-a53b5d32.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16490541/s57997917/b1ceae04-fcb1cd4d-ceab273d-0cbf8895-734edfea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19621207/s54780702/9f08c9de-06164a88-e6c79d73-6b71e45a-c0fc1f23.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19212448/s55376400/86b66201-31ec0a22-3ca0e9ca-5eeea7bf-8c1c7889.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19797046/s56840309/8c364633-f31b7627-d82ffec9-90dd7e14-e89d7037.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17269743/s56954813/fd1176b4-e8155e19-be700dd4-ba8e507d-263b4aab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18755468/s54305187/9baa6a5d-902e940b-9c3e70df-b7657109-251845a5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11495809/s51281727/2b3d96a9-5c2d9feb-cbb54e69-17e06db6-83477377.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10870373/s52118049/ce636c1f-2dadaf39-3f7383a8-d8016f1b-e1dc2b25.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13571392/s53274758/791b940f-9ee4ca59-dc04ee23-9b1adfc8-4efee27b.jpg

 49%|████▊     | 2437/5000 [00:41<00:31, 82.19it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13897094/s59600638/df06cbba-2acb9e33-2710d185-86914e24-37899d73.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19349785/s54669491/041d9b3d-a21d8249-e41aed0b-b95bdcaa-ae9ff863.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15721773/s52591378/9536d495-7733c58c-665e061b-072565cf-8e7860f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15138171/s59894752/b3faeb74-b7f77934-c826d6ba-11b11872-244fea8f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17198431/s52342764/65b97fed-402cb3a5-2ab37700-06c98d8e-cafda5b3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13486720/s55652549/50cdc821-2d120311-0114a8f1-0188cba1-eafaf740.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12881887/s51091574/609e344a-21257f7d-03bca989-fbeec9cf-cf932846.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13613806/s53006455/6a3dddbb-be2fae6a-b9c42448-8e4c8fbc-65d7e0d8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12057844/s55596943/004fc013-89cd05df-e53d1c3b-7a82b0c2-87348252.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13088314/s52527082/bfa90ade-5145353f-8e2c23e7-b71a1151-5d5d5e3f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12341449/s51374016/5ae1dc16-291ff570-9a77b74f-e8476dfe-5aef5a43.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10471192/s50381631/e50a430c-83894bbd-c8f17ee5-9201a3d2-a2783b92.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16014068/s51100137/8c60c955-3f6c9855-a84518db-910ed47b-c0de71a1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11028216/s51088501/27ec182b-13e9f513-2ae7a97a-e26a8a24-7e95e1c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14658826/s58070611/9810c3bf-6e33db46-0e1e51be-7890ce72-2f0f753f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18009599/s58432818/4f41e3ee-435f1389-270ae7d2-705c28b9-4cdd4c62.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17902737/s51846393/aa70b095-c03b7e35-335fd9a3-1a0cfe56-2d2c3f25.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18705566/s50449230/c89d2124-31612a3b-55c7ac2e-0f15d89a-aadd3cbb.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12821625/s59557114/1de32446-d91157c3-0b2445b5-f44f4b77-6aaa126b.jpg

 50%|████▉     | 2485/5000 [00:42<00:29, 86.30it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10398981/s55727793/5f4221fa-5f528de5-78401294-c751a1b2-4496b23b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11566800/s53151689/e5b1f976-c1ed6a3b-9ffa4bd2-07a11d3b-534a5fcb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13580005/s55949697/6f5f4133-2693d569-31e94c85-63e6469c-716ce7ec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13063188/s58350581/396d3bff-33864229-f8648de1-e625d02a-fea65319.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15656571/s55624026/c8e9a661-64aba3ab-77e5695e-d0ebd5ea-2641dd78.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14317948/s56995558/b35cd0ca-229c64cc-c53df2c7-31379cdb-e960bc34.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16524597/s56904391/c0ff5f51-d988a50f-4f16f8e2-ea680ad4-81728c29.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11977245/s50427231/7f980189-a3ebbad4-8af1ba6d-caa7e198-e6d27fb5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15372656/s56886654/6408b3b8-899ea930-97969ce6-4096b7e8-f77d053e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13017215/s59266627/77ddaf00-c7323c94-dce63fbe-3ba90606-9f87d3e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13849733/s54538310/a1ab8f5f-581bbc83-95dcba8d-3f8da9e4-4df624e8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11442840/s54781353/cf345392-fbde6d36-734c3169-0c78ad5d-68bbfe35.jpg

 51%|█████     | 2538/5000 [00:42<00:26, 94.10it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13975008/s53663691/4b6cd383-b022d943-2249944c-94b40bb7-fba0dbfc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15831207/s51068781/75ffea27-25af225b-3f2302fb-3f18eeed-57389bfe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10464640/s54409823/93fd4423-26b72c3e-77585d40-ee372cc3-64f90fe5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17890887/s52638816/dd6844b0-ca0a4c9c-0db66bd1-d6f7b859-15393079.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17077867/s58477401/6cb95bfc-1757ed2d-0c8477ee-2e6eec23-38de7602.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18528723/s59936393/21d7c3bb-a9d9ae6b-3457764a-479074dd-2e897c84.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10296921/s58365690/5201f3b7-ca30c987-c188abbb-3fdd45ec-b9a0ec67.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16906565/s58305267/b99cec15-95649f8b-e3d7725e-e3763807-53a42eae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10440642/s54884491/7141e1cd-a50341d3-5479259b-e491e56a-e4d9e17e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17265914/s54229212/7bdeb0d6-12971639-0f8d3340-f5ab6819-a2925795.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12329981/s50436589/0e467d72-c9e507b0-8c392f39-61331113-5dbe0119.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17868461/s55726583/af90f62e-4f151147-a6510c33-f18e4785-dc72e246.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19674244/s54850208/a158688a-5a658ff2-ab70ce22-e9998f5c-f6bbb1e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19078190/s58094185/1f680419-c91252bd-6637c7aa-fa88e65c-03c331e8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13919405/s53335715/b78ea8e0-1aa9e9a8-de6b694e-4c66b9c5-e766fc55.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13051530/s58056909/4b453b41-3529d0c8-cc61211d-a421800c-d76c2de0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18563023/s59851785/c87209d1-db964e87-903f33fc-0ff3d75e-9975cdcd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18762260/s57940363/cff49a43-13b61d4d-345a726d-86c989d2-a89ecbc2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18122852/s56089676/ae0260a8-c7c68ec4-6e0318f8-c6af92f9-d0f79a4a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17591410/s51299011/93b90921-712b16bd-280f4adb-271b43af-abc90436.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13146404/s52949131/126891a5-06af358b-4dc99b28-f3849783-95ad0602.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19538400/s54854170/a83301dc-0e782c67-3edea489-b312266d-0e2832fa.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14155070/s56700002/3646b489-9844bd73-488b8a0e-4bc7f57d-b2ca510c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14741847/s53769296/c1a8806b-bfa33d3d-7abeaba9-2f2c5a1e-da0e758a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18486265/s51148381/a25f9d0a-2bf35699-40168318-2b79fd22-7828b584.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13198542/s53608368/a5422504-c5298c5e-2e8ae0d3-55ae7302-f630b099.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10407582/s54453540/82c892bb-f1f15125-2893421f-62443af1-c5913616.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11967908/s50680568/152a6883-e34d6fb8-4070b88f-c55e08b5-45e909dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13784236/s50534375/7d36174c-7806d255-45f3540c-22c1b682-c6c65028.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10854695/s50209909/bcab42f4-23887534-62f4ee07-e8b75a40-5d40ca36.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18965721/s56025543/3569be09-b5cf8d8b-2a6653b4-c2fd8d2c-37d52009.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19299811/s50001349/909557aa-0df0baed-8d1c8999-28825f3d-171aebc6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10290354/s52033869/4155ce0c-7415a725-3a39c796-493b23b1-a3592aaf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13984508/s52503673/200a662c-0d39662b-f5a27f22-1ab0e472-39ce3d60.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15116019/s53044988/176b3239-4609f419-3b4622b0-9f45bce6-c12c715d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17250375/s55574566/5ff1149b-d81e4009-2a61a18d-d95a7bdc-f453d19d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19297337/s55591524/b7bcba1c-49aaab0f-fd4743da-75a3c871-6db6c440.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10355745/s53466692/26df92d0-96c3f541-e32c2fba-aa1ce3be-c74372d0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10490155/s53118094/8349159b-eec0d528-2cb62441-7d1b3ede-2e7b1e8d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15189156/s50260638/e4713dcb-f37fbd9d-881883e2-424279c9-26563fc0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13609406/s57253053/07c2e675-3e5d4ede-74d6f453-ddcb6f51-c7d1571b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13332955/s53004519/dd723fcb-68d019d3-2496fdeb-9e771783-6dacbb13.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14295224/s51689739/0096fc1d-7c100751-e1c8cb03-c461efb4-1c6b0f8e.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14274422/s51275138/4fc00ad9-6aaac0b8-8dee6fc8-92e2261c-8a5915de.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10257550/s59305168/2eb41c49-1198a4e4-3ed8d4a0-2809e89c-cd64d65e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16839550/s58970395/2eb504a9-27bf00fc-3825167b-ef4bdf53-75077f52.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15258890/s59048332/f6eee164-4eb783e4-7ea83f13-72b01112-6bf4be1e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17533213/s58882315/7b4b417f-093ce69f-8d5855c2-e6db33c1-477262b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18853538/s50262547/8f1880bc-b0294425-cdd635b8-53be4112-85e39276.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18580594/s54419841/c5c3a5a3-5e5063e6-7ebc4940-55888e2a-27a9bf62.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11923146/s52543627/e5f18871-7b92b552-0a9ee700-38fa45e5-e6beab16.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10856002/s57408877/1a1d261f-c9a7c088-bc434406-ab31b563-7ca0e807.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16720509/s54891481/14dd9bc4-9b065049-d9aa2533-876fa9a7-697b22b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11912842/s50145111/508f4a16-ede7fc44-974a5b8d-6ec1cf50-d7016561.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12070454/s50752117/afe77613-258dc10c-9209ec10-be58ff86-2115db12.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10469200/s52752414/ecfbca50-e32a7a4a-b0821d2d-081ee783-b7885fce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17982586/s56168095/bdf54417-984905e5-5d4453b5-f580b45c-bcd6d4cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10439484/s51311845/7399fd45-11cefb5f-f3efb200-638bd7f4-1acb343a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12106204/s56797900/8e42a8fd-f790e96b-ee77be2a-7651aab6-da4c5769.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13919890/s52653380/2b279038-0cc3fe7d-add6ae8e-b4853116-23ca2026.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12245451/s54906606/16805133-6b4c3ec0-e1137ae3-35ceac24-f22ba443.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15485853/s58747390/19c82179-78942e48-e82fd442-75bc5770-56733408.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14739356/s56057495/e8512f8f-a6c5117c-49ce760d-764e6eb7-f3a0a795.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16701027/s50581264/78d58c6c-923be9b0-8604a5a3-37e46e05-4f33e4d5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11687219/s55710549/70d81e60-7c76b0be-a54b55fd-53ee8f57-e51419d9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14691065/s59489351/2177f536-849b4fdb-5de5c962-c54f5424-9033d20e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15906963/s51089786/7282a959-cf598f72-a07727dc-4c82e8d0-eb24385d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13889025/s52208703/50eba064-e53a91d6-8bb7e5da-edc6cdbe-f7f85d68.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16177747/s55793652/bf1cc658-301ec34d-8a82b193-2440ce0d-41f4c58a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17182924/s54373682/10943788-c81e208d-1aac9cb7-d03b6955-c0286910.jpg

 53%|█████▎    | 2668/5000 [00:44<00:27, 84.59it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15558165/s58643049/6c653974-1e8b13b9-68fe49e8-16d8fad2-28045598.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11792719/s51156968/22bb041f-01e1aed3-ec842bf3-cf6f03fe-22ca0aca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16431831/s54408659/aadf81b5-85c0f69c-6bd6b5b5-65d08f43-32c088f2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18687658/s51993231/bbbaddea-af0f242c-a8e04914-882400c8-d9eb4e99.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12265028/s58373023/312d9eab-45f1edb6-29ed0c81-fbad947f-8ee018f0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10723086/s56546550/b3bbc97d-790b738b-9210ac5d-366320fe-c5deaf0e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18935324/s50597900/0687e0e4-7d483a01-0eca259a-91270ee5-b9a17105.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10839265/s52252056/07e60146-fae489ca-063ad791-c3e4444b-1dbc1b39.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17595027/s51802160/2a4a867a-eae0b7ad-71acde9f-27714798-0e6fcb8a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13405183/s52994252/1a1a88d1-0840e845-4627a663-ae3e608c-b7144509.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14331729/s59416495/e2ae0be8-a17a72bd-5dd16d75-7e11a73e-e2c1ceb7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19597426/s53496861/6a3b236b-a29e8f9d-d6505137-940a71b7-9e5c219a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10867202/s57513198/a4d62fc4-613c998d-9a906778-5703a1a3-21507e30.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10805461/s51258788/9918b88a-73179bff-fc6bab75-5cac0d61-9a36b8fb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16826047/s52520063/88c6c717-a8632896-fd029484-3dee5f36-331a78dc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19763129/s58018446/6b558d09-76bd068c-9fa74e24-191d60ad-7959d726.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12532356/s55771126/dd6e8cd3-e85cecc7-caafb713-ea05c90f-e6850515.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19017438/s50099971/e2f430f6-ad259edf-f8882959-aeb3e034-656ace24.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17978664/s50344932/bdbf42a8-0eb2b44f-334772d8-d22e0a1f-a9a3ca34.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17230481/s57122941/1bd205c3-b687d687-378930fb-d010e904-32a34826.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17583434/s50585587/1bb9cad3-1bea32b5-16ad754a-e9289aa5-d30010e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14494263/s52404296/e20a1297-e487adb4-9d216236-58f3987d-845aaf53.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12051412/s57069061/43390f52-013d31bd-783a5f2b-4cbb7906-a948695e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18563244/s55343579/17096c71-4a07bfc5-89c7438c-63bd019c-63d7040a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18061894/s50792167/3e0c0320-bb71f818-8f4ca1c4-856acb0a-798d66f8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14368163/s58278309/6d55e64b-23341f94-69216015-b6ee52c8-9ca5b6c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19792891/s57548918/0f37b602-ac1b619c-78f78946-82bbceb3-0fa34266.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11512695/s55171875/1ff7bceb-18edf1be-56d532d5-d9b755ba-a5f304c4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14052692/s57491707/c5820225-4b6e9e9e-5a985365-26ee2333-7183fd65.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14344271/s52469580/c95cab50-c3161d19-326207d0-5a2d6a78-2f730e76.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10270108/s53580789/81588559-46b6a865-7e0c8887-df02ebbe-1b964197.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12589336/s58996183/c0d59f41-0cda7b93-591b2b22-684e6d72-15f120ac.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16439884/s58279222/e322ecb2-be96c0a6-9b7bc5b6-5e3a9fd2-2c69ae5c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19577720/s52945976/45fe78d4-6a5b43a3-0627cd80-946b6f27-3df736e4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19781816/s56972415/49aa55f3-23a694ee-bb9c4f8c-13569b65-3735f895.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15393401/s57869215/ae1cb3e4-7807870b-ebd61015-6285477f-253c9637.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17820613/s57446979/0e10eaaf-a7fa9144-8391a61c-f71b908a-b09b43a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15944183/s52695111/580ddf21-242e678f-a3a6ef8c-4b1cf7f7-9f1e8106.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14281951/s50158308/f760703d-bca62980-c87fc27d-1b42be3a-d9d2217e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19061282/s54993114/7cbc9371-93ae74a8-4d6234b9-a496d3e4-8812a350.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19721801/s57245713/42e3ec0b-0113e141-8734cbba-b6c11f78-e495db91.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12808803/s55276321/a1810e3e-afc23612-b2a72ebc-07eb86e9-a2812e9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17201789/s59751094/a79ecaca-ed45210d-53081329-fbb6da11-86125188.jpg

 55%|█████▍    | 2747/5000 [00:45<00:29, 75.15it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13158454/s52939553/d381065f-dca36ce6-1eb54501-62a63690-a0e422ad.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15244957/s53313128/2b35f58c-51b75930-94f111b9-f035ff03-63a418e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15634524/s52065978/aa99ab36-dfd45776-fb83e698-01282621-a002381d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16934687/s54004337/bedd165d-c02ea05d-f64bcf2c-ae5df9fe-0034a748.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13684752/s53638482/7d1b4085-f7bbc735-0945c464-29e9b7c6-2c38efb4.jpg

 59%|█████▉    | 2964/5000 [00:45<00:13, 147.18it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14256965/s57329500/b87e7208-d4ae338f-11fac6aa-b729fad3-ce8de98c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17533771/s56679657/135f75db-12a94b0c-6c6aab28-36eee09d-648f5827.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18622852/s51520762/84317dc9-98698780-f178c4ff-a5850590-2fc796c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13487797/s58389931/a4a6c510-0e388cc4-86156e07-ddbb55b9-d69ec1e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12043836/s55874186/ad99e187-9c276397-bb1d646e-93bc4bf9-e446c847.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10500801/s59547910/7028bfb7-c09d280e-60717577-be72adee-3e80d7b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10291303/s55224008/a6d0d922-7679f119-4c07494d-82b56e1a-9c7cb444.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14376085/s53621502/81d5ce60-a27f07c8-39889fd5-ed092b5e-62f53416.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10980069/s59529095/9aa2d2ef-75757f20-1b280572-ecf550bd-20a6e9a6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16131554/s57479841/3c5d9a06-d730fde2-58ea4cb0-4ca28026-467f45ed.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15767035/s50995690/e947c017-959f82aa-e51d5ae9-e6852cab-1ce0ae09.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17094218/s50637341/ec79bf64-cfef71c3-5908042e-3c9955e9-aa4b73e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12351713/s59164434/53f4dd85-d7442836-92cd5e0e-6f2a2a0b-e5c77419.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12503324/s58282740/92e868ad-3a330f8f-32b1a264-e20bc470-ff52a79f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16177747/s55062691/5869b501-26ca6235-4ab10f4a-b689620d-394060bf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16054505/s57313798/6acdc0af-944b5d89-2d443f39-ea40f2d6-afc4c1b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16010718/s51080571/fccc2525-ce18fac0-9393b788-3e20963b-d545cb67.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16319601/s53409681/f5ffe72f-2177cc32-4bf7c5fa-c241b35c-447b2120.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14748547/s50460116/0f99dc74-f57ce5af-baf17db2-54751823-388ffe47.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15650043/s59723683/75de3c79-9cc526c6-b8e9ffe6-720d7de1-a06e2ef8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15543664/s50508267/eba80ddf-0ae8b782-f8c384ec-3712e8ca-15f8a306.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10038999/s54562872/b731eac3-7eb0b300-94dd4628-a56a3840-e6719380.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16036071/s59585425/3494ff3c-f45ccf00-9544bdd0-4831f411-645446d5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10108435/s54207716/26cf4111-bb686be5-37ffe58f-1a8c7fa7-4ac81dcb.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18108905/s58791315/5cd082da-fdc0466a-071bb9e3-b67084d0-ac2878f5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18663902/s59411169/fad4f48a-d98f3f98-af9fd5ea-24ca9084-a99b9a93.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17222468/s55475780/9eb2959c-104f453f-9e2b62a0-0c7d6eb7-978ee9ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18111896/s51402466/4e85ea12-2896ade9-cdbb29a2-d2a48996-bba1a5bd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15894036/s58572367/9922db3d-443e4122-57ca8359-12882a69-dd06b692.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19930554/s57550757/b178171b-ef32833c-70425330-870eb637-eb16be83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19530208/s50445559/21d8b45a-306ab3a9-62965909-254cd155-ea0a51d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17563347/s52126014/8a7a8bb9-ff655167-38a8b845-33193bc3-81c50921.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18772912/s55565487/be46735c-adde2dba-13917d6e-0174a770-813c20e6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17256683/s52950001/cdafbcf5-0c1fe71c-646b928d-d0f18726-be4a43c8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13102939/s50343790/76f346f6-be5e1c25-6470b5c9-79c877c1-1ea73d4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10502984/s58618294/aa7bad2f-336f7cbc-c3d3d0ad-bacad33d-ff59d188.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14988347/s52186171/492ccc9a-f97a1f2f-e12b549f-ddd1acf7-b21c2720.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19650702/s54806810/8db33252-bd8704ff-bbfaa313-4b0a6017-cdb10259.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16006175/s59747924/e6eef070-c4d0ab28-b6cce930-d2f2d0c5-1314925c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14461528/s55798831/7862ab84-e5c67881-e15e906b-2ca4a020-b3c61150.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13193330/s58821570/09ffb05a-b53c56f1-0dd90646-5ef1b914-0bee2937.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17991372/s56467070/93566517-0bcf7582-ab5b83e2-2a968399-68ec755c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10539937/s58283764/f06ef65b-5afb0bf9-2d8445f0-9953decb-b0345885.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13722018/s52158640/01e72f85-cfae1d53-0cd849f4-b3f5323e-ba89781a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13451992/s51931197/ad7aecb6-6e720a86-4993bb23-a87b960f-77b0678d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10915432/s55366171/70a94e5c-19f218c9-31cc903f-0960e427-c9d061ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13415723/s50894104/be1ceb3b-46ab8bd7-d90cdc2f-32cd13d6-e05badf0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17241424/s52468763/850fcee4-342a8d7c-b8abb6ca-48888c8f-0742d2bb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16833001/s51949053/9a8d96dd-9ffe3666-7d407be0-bb58985e-22443267.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18049473/s55762639/7c51a285-e0154ff3-a0edf803-770662fd-7729ccb5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11731325/s58712832/29fa35fb-7c6685a7-d8ae80ca-29e12062-f470b3a1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11210454/s59203939/8f3b7f05-c2713dcd-b750b3e2-e83e1e43-ce811be4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11247575/s59160851/0a57966b-e724bd7e-69c50ea9-166cff0e-68d769a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15209552/s50901251/daec927e-d7661bd3-cdd75aa4-2be1b524-b8280b6f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18460817/s50427302/5a380d9d-8006b45d-aa3e50d2-fcdc0856-a30fb95b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15794450/s55951652/205f99b5-079e0579-a702e1f1-bde661e8-1ad48d16.jpg

 60%|█████▉    | 2997/5000 [00:47<00:20, 99.95it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18532425/s50067668/f6f0283b-03a7db71-e1228fa1-e9a92601-b634b864.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16295064/s59569683/0ba4310b-79731347-af7524f1-9c1f3559-6dc25139.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16853834/s55210807/769b7a66-c7825d2f-e649be8f-7742e6a2-59e2d3ec.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11803638/s55973042/17afe2f2-b00fa780-55670243-12a2ed74-b2ae8613.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14090353/s52528334/d4ccb25d-693114be-45cf305b-a8ba7c24-35a59d26.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11793360/s50111288/53a2a949-d524d1ea-a8d48b47-b2658c7d-f0782452.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11961264/s52857490/c4322b75-582c89c0-ba090655-80ccc32f-eba9e7ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12702546/s51827713/70a1bf48-b6dc97a1-ee469991-b44882d6-d132314a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17608795/s51974922/d2785b29-11d33003-aee5e026-3852744d-cca47211.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17589503/s54835056/016ef184-980aa245-94275e69-8e845827-ca8c6dd2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17578234/s56668255/7fd6d3f0-b4762930-260803da-3bfe47e1-a3f956cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18298823/s53505187/5505f4db-1632a691-56efc7fd-7d80556c-0ac714e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11296936/s53461257/af323b93-4245d7a7-2dd4d94c-d64c03cf-1c855d80.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10554112/s54773914/d55c2bb5-b375017c-0ea43b38-852acbc4-629011e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18164965/s57224047/7f75ac5c-97aa49bb-eef50342-17b42f0c-ee01b12b.jpg

 61%|██████    | 3040/5000 [00:47<00:20, 95.63it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12736592/s57146595/d7203332-f3c8731e-27d35dc0-3cacfa03-24d07da7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16490533/s59269488/616b3014-37df606a-1dc8442e-c3f9e37e-1d8639f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10807564/s54379705/82389efd-ef6db674-5cebc535-a8003549-17c11549.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19223814/s54962667/5c167177-16f6e0ce-cd492bb7-72094762-534afa10.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19524641/s51351919/8cf8f588-c6e3dd88-a29ff031-54cd91ea-95f7b1e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12408912/s55062102/e9864d8a-7c642bd9-d9e057e6-f16ecd20-0d884411.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19593675/s52357956/c144a3bc-1254fc01-1243d129-51a06174-8eeb3aa8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19761977/s50967467/85373b54-91aae9e2-36acf42c-4da24d55-cd2f75de.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18079777/s53326933/3e943e25-202bd97a-e93469d8-8938dffa-2b74dba4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15281216/s52858632/538b72c9-5fb9c9df-4159a0dc-538d3301-e27283d4.jpg

 62%|██████▏   | 3075/5000 [00:48<00:20, 96.10it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19991579/s58108038/616f89d5-17159eb2-1053225e-73c91a6a-9e7731c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19497735/s57766879/8ffb60fb-e167334d-838430de-f74dcd1e-a5903385.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12370269/s58252802/f2430b43-3fd40832-3361cd26-52cb7807-c3257200.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10803114/s56915281/d4eb74b1-f44ac0fc-aaaa580a-ebd12892-d8aef5e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10304846/s59605154/4ada6f1f-e06a60fc-a1a9f191-02459f81-1de9dc08.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12698729/s58984555/b60a4b3c-e4ccad05-61eefd8c-ce82e297-8c43137d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10903446/s53149332/692329cc-3a466525-00244065-dcd3361e-60a98074.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19935359/s57511898/9c2e43cf-d2df05b5-2f8a7cfc-2f63e26c-c25b084e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19624947/s58293918/6bc610c0-d4cbfc41-f7772abc-6e7df2f2-3ff2797f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13261572/s51103958/0f348ad2-0e62d5df-911ffa21-271c5c49-a91b7214.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11532890/s59091838/ea19eff9-52e0c9e0-15f7305f-a16ecaa1-a00b9e0c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12482930/s58538744/834d11a0-6da5c1ae-e4ef8a52-930fbdac-9b64e1d2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12727273/s57737821/cdc87e5f-baf41e3d-35c55f63-627d6379-585c04fc.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15456778/s58385360/555f03b6-2b0961e7-8d73919a-4bbab0f7-0440a057.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11002268/s58299091/03cdebdd-aa193e73-640acbc2-56be5af3-48e1128b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11042406/s50436511/8698982a-6ea451e0-32286c79-f00daae8-5dd9db46.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19346228/s54100364/30ea0dcf-3173854a-fd22f3c5-dea153b8-aff23105.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13505755/s59688123/a28a5262-c4a1b7c8-dff8b413-839ca820-7c9944dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12802235/s58772007/57484058-b5f0df87-f4382f83-8ee44fe4-533d5a00.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11783844/s59455026/bcd6d168-1b79876c-c0589dcc-65a0b3a6-eca72422.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11051753/s59757456/76bb7a31-d39e0059-ea4c9ed7-e175d708-5fb89bf4.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18009599/s56809024/ec658c90-ef42c88f-fb7f63ce-361ffaa4-c135c712.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11904895/s57464164/ea044344-dca1cc04-38873b68-990e0488-7307eef4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18050451/s52057978/7bb8631b-d7ad3744-c505f6b9-9a0348c3-8051db5c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11252741/s55542969/f4b61a6a-3197ec2a-e5d04a2a-7758c39e-4246f144.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12513827/s53088753/46c60af5-3a34711d-e1974a8e-467663e5-fadfb4bf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11907554/s52724815/c65c420f-fde01204-8a987658-0685747b-5d0daf4a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17167982/s51312201/b8def798-64515aa7-963ba9e4-7bb94478-7eb19a8a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10762976/s55531643/e618f0ba-ece480c0-bd32d4c0-ff2c65b0-e3bd963d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15270331/s50177244/9651075e-e3196631-d8a81a65-40c422fd-827746a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11545313/s58501850/a5cac391-e16543e1-f586d735-cb477334-2e3cbb7d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14720260/s56594020/d54ea07d-8f47c087-679e6c3b-defc48d6-ad21b2cc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14877338/s58167874/d3504a65-a9d863a9-5009393c-7bd72a10-74d668c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12578742/s54543213/e8633f83-74d14df1-c9521097-913c5e5d-3a8d13c1.jpg

 62%|██████▏   | 3110/5000 [00:49<00:25, 74.36it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10745635/s55797364/21ea3202-f2425aba-7583911b-10b73587-3b3979b8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10950952/s57938666/b7d00725-0caf1001-3aacd972-4e96499d-1ccadb30.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17169478/s56920919/1cf1928b-ffeba1a6-b18145b5-e7706772-2cbbe868.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18577366/s54820855/e890bc13-f6a0da3c-5a1de915-f769d76f-f22e9203.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16939016/s53466741/ace753f8-c66b6ec2-e0d6b702-7e9ad5b8-c604a4de.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10407730/s57669115/42bb2c98-b915b39f-efdf4a6e-6dc5ae51-79679cc6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15821345/s57078807/a5223208-a473a93b-5bd6e9cf-e1a06851-fecd6a13.jpg

 63%|██████▎   | 3174/5000 [00:49<00:18, 96.54it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12317110/s51233447/39530d4d-56c36001-067f0c6d-72430763-d250feca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17117948/s58483322/721c516f-362f0000-efa791fb-5d57d55a-98ac2a1a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15928338/s57458246/dd381e02-5878b119-4984a293-c31c6ea0-1549ccf4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13483571/s59166383/104487cb-d08ca993-cba98865-c80d8d61-6d5b157f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16089469/s53658806/39f3c0be-62a41051-d14041a3-da1100f7-7d353395.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14657829/s50444119/d155d1b5-e0c38ef7-5a3b557f-e490d540-6348b544.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18916144/s53277476/bdd85db3-dd3a55ab-6801e4fc-f74b9db4-17c80f96.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18726783/s54132939/3984db26-80b52620-5db2b7e8-17c69328-4b50a3ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14067967/s58787882/4b2b05a2-87617cf3-b2b2777c-4573803e-57d818d3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14172608/s58864560/c15db9f9-2ae80598-46bfb3be-70bb0e4c-f3953c08.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14053933/s57955945/a13e833f-b5ccc1f8-02e3023a-7f4f5d9e-067150b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11044484/s50215123/367e2c0e-37dd771b-e0748ca2-964973bd-019d3aae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15455450/s56680237/ea316823-52035ac1-96c453b4-c3cd8c49-0a4e7fa7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10421218/s51203043/0bda0479-c6d6c442-2657e9ae-003df0fa-29627846.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17503320/s51701657/d66779c1-a92c5199-358c37ac-a791ac59-918e8b18.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16446527/s58343769/dfee2fb5-471ccee8-4705ffaa-3aa354fe-0ae2ec50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15803381/s53274712/94e8bb16-341c5600-964226f4-cd358d19-4a4a72f2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13011941/s59750164/1157127b-b1d397c0-aa6052fb-2380e66a-0f97b1c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12934024/s56544780/d9b55839-054d2872-bc54858d-bac48758-3697332f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14774414/s52310959/3478d64c-60475696-60937275-d9d5c837-311add16.jpg

 65%|██████▌   | 3259/5000 [00:50<00:16, 103.12it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11576109/s55356455/fb091300-005f382e-1fe1d229-6732d072-4699035a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18761820/s57457291/6258b087-227bf16b-dd28d24a-65a30ba7-7c85c52f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12328460/s51260158/1b387c70-52e0f1ce-2600b4ee-cc1b07e7-7e875270.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13656987/s55146085/b2716b14-a54e8b95-881f3646-de38c835-f38be5d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13230293/s51054044/ec907a1c-622d9b5d-f65f02c5-7cc45dd5-2892b9e8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13877204/s53999010/654c5073-b2aa071d-3ad07144-70877e9f-835c6340.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17336353/s59232518/d6ffacb5-84b01bfa-657c2ae4-7de39f63-3cdeb924.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11785297/s53935284/0d7fb1de-4c65fd8b-0b407b6c-1731052e-1ddfb9ec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10326773/s56971723/9b172aba-19309b08-bfbcb9f3-174ca501-f4db7375.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16462650/s55256343/01cacc3f-899210a2-4ff467d2-551c6c45-ea946908.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12637733/s58291313/5d1300d0-e90cc9f3-814b3b3a-90aa8777-14b63537.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13017215/s57857397/6068f4be-0b92fe9f-535fac2e-170e59ab-d732a385.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14350300/s59279215/6e8a0e92-1f7b75fc-52217f6d-b48d9c73-6184814b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12770117/s57882136/f55a5fe2-395fc452-4e6b63d9-3341534a-ebb882d5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10901462/s59554766/34cea193-098ce319-82b49dea-a8760e50-def2eb60.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10298415/s54940499/b18409fe-7b3e56d1-5c4070f5-616735e4-f712cd2e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15314618/s50370500/28a656f3-f59f341d-c27b12a4-70b34e1f-b99080e4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10037598/s57183468/9660a22d-c7205491-7e14e486-17a71603-95610c63.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18144033/s58913767/75cfd641-57460399-f408a761-9b424ff7-4a80a894.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10192748/s50060083/620e9c3d-129ccf2f-a4ea2892-cecef36e-82b6c75e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11677206/s59716697/752ff260-1370b4fa-46cd3c9d-8303303b-90cb0761.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18002691/s53305998/dd21aa73-06598e56-e1a64eb1-16f59abf-4f0e5b47.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12892033/s55267017/45947434-be1321ac-07624e84-cf1d6be1-18d5d59b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17336743/s52768710/b54d4124-0914a0aa-1ab02bab-fdb3e97a-7e1c08f2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17506723/s51601410/2a50f81f-a6c0ec20-47d8f528-81b99174-488ce4fc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16292028/s51764127/408f3209-dd99727a-f49ecd4f-c48aa705-6c8c269d.jpg

 65%|██████▌   | 3274/5000 [00:50<00:23, 74.59it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14992009/s54830093/94e2ae7e-56b78fde-8d6ab125-1f4fae46-39c31fcd.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18513641/s50890002/b5fe0794-11840a45-e1a62d96-10b4bf4a-cc3e09d4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15831207/s55747346/89f95561-df627482-6b4f41e9-a654e22f-214bef99.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18117341/s54299088/b257a192-f9b05b96-6b7727a1-898c5819-e239a0cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13687936/s52182849/b451477e-895788ef-215fa375-939ee85e-edb66dca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11658675/s57692436/215fccbc-5bfee4c8-790f1086-731af35f-d01f08af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15917895/s56818605/d37428e9-a5cc0698-13a63c93-6fccd107-82456659.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14285126/s58061193/d4894eeb-d13a6f53-ba5026e1-9d0a291b-2b4b9f80.jpg

 66%|██████▌   | 3288/5000 [00:50<00:21, 78.22it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10039708/s51842243/6a0ea45b-69f5189b-71c6a8d2-7cbf39ee-5c6cb04b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12331840/s56651214/b015ffcd-ca928980-85e3a015-a689b4e4-7554e841.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13579668/s56104254/6b51dc85-dbed0429-65cae046-b9ce2b21-29fec5c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15653585/s58889400/3eec8c32-2c916e8a-6ece82a7-1ed5e719-c3b06eab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15659181/s56790426/493ad888-c9901b7c-919b136e-9d112af5-69cb1ae2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18262854/s58549592/094f091e-5af135ee-d5fb3c29-a51137c4-bb319a7b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11143932/s50921429/c7c8b7cf-ca735495-8ec07538-aef189a0-3715e8af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18097664/s50972828/a452c25e-0c51eaba-44ec122e-cc7aa22b-d9afd255.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13973055/s58433522/aa854211-7a9e86af-7841911c-a3aa4d95-08d54618.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12965924/s58015080/a29d04d6-c6dc0455-47c82df9-49501629-e1ce3015.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12116250/s55339875/1ffd6035-f146ad75-d7885b13-9642b80f-c60f452d.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18976991/s58359515/dc5056ce-00392914-66808f3e-7b2d2419-5a125dce.jpg

 67%|██████▋   | 3341/5000 [00:51<00:16, 99.19it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19132022/s53862372/9bf80f08-2ce4c5d4-e3636349-caccc6db-45af9013.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13693499/s54184260/f77d468f-9706b8f5-865443b2-667b203c-36f3080d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19069125/s53043768/aa1c9802-aff941ec-7325e4ba-cfc3d574-0488aa6c.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19131119/s53443188/b01096c5-8c7597bb-66a8cacd-cd383e3a-c0abfb34.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18112598/s51696830/17fff41b-c4ffb23b-65bbf55e-9944c0f3-6a1469a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16805260/s52658007/17d1a5be-66ca8381-9daec884-87439844-47a4290b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18551874/s53125742/18574898-c8b0cfda-b3508979-a43bed93-805bc214.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19924849/s52354324/1c155578-785254eb-306b1f7e-dfc17d9b-70cbd7f5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17768098/s51296643/f5e64afd-25b45a7d-ca18c235-2fd4b9a3-9eb78a87.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17710225/s56541205/65246274-6e9f2394-b8b00de4-189757e9-44a5b76e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12684253/s58742479/e066b7f4-037819f2-0effcd11-b6196316-0b4e799d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10517964/s55081582/6c7dd410-5945a2a2-dfd5e02b-ab6a4b69-3bd35522.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14969629/s56466863/a24a838f-cf7791b2-39b4430a-254751d6-a8d182e5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10501557/s52176984/b011d8cc-dc7132b2-88dbf1ce-25edfe98-e7f91d64.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12990718/s53947511/fd942154-306b0626-5fa3ee54-cebdb613-b8fd51cc.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14969719/s50950402/9b81caad-45950b63-68fae78a-caa9bc51-74483a78.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12097762/s50274164/e17ad6a3-7a848db1-89213853-94d729c5-6b0f24ba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19547030/s59756969/a2ceae4b-d379e7bf-9d8b8991-937654d5-c7d5f0e0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10680329/s56572927/f4eaa4a1-cf4c2ac9-fe3cd55e-543c9879-d7cd7268.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11443554/s57808761/dac6be0b-32e1f8b8-75989e3a-f43b3899-de14126b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15564494/s59098052/e2ab21bf-35755baa-01f23ecd-fb02e69e-be4b77b5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15863098/s55799932/ea71f846-ba9ecf7a-79079ec7-ad793b34-32d1d4d4.jpg

 67%|██████▋   | 3357/5000 [00:51<00:20, 78.77it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18920727/s55853536/dea65f37-a3e281fd-deb137e0-86c482dc-1e87c072.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10251081/s57839197/97465425-29dedc45-5c202b66-0274ad4f-f7eb4961.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10108709/s59448359/ba54deca-d7609bae-c46358b2-e99ead86-d3f9b238.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16544053/s56240273/5a9c86be-545c8820-8075e68e-f256bef9-3add2975.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16879600/s55655233/f4c6a5c8-9ef81750-1716952b-19cd0dc0-975e5936.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12054012/s54277948/14fef0ae-639e9b53-21609197-a7740f43-9f782199.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13830137/s56365930/d4599a4f-219e5e9a-94659c48-c32c0249-ab0c9363.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12790400/s57782055/7540f588-8ef3e690-b553ade4-29211f96-7204f310.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10380149/s59674519/c568b066-173568fd-3cef9a99-07341e9d-5b114bdc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10148417/s59773136/ba545f57-fcaff07c-4845a289-e7fea078-03eb630d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16582727/s51864737/33e7612a-b3cb61d6-17455a31-b3009fe9-f4a35aa2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12185775/s56143620/b529320a-394d7b79-a3e8c3da-c28c6b94-7ec08b51.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10068304/s52523257/9fc7bc30-6d7d4d2e-24ef7273-151fe42a-99f87a28.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12373976/s54629537/93098af5-94da8fcc-b7faa8d5-f45c77a7-74f033e5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12868821/s50382399/71608fe7-2b77a388-c8f46e58-46741513-e537415f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11586698/s52120140/08a1fdb9-ac6b9401-0c3b35b8-ee4e47a0-abf0ae30.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13467921/s57687686/b70d7fca-fecdd9e3-41435ff6-e465b24b-78971af1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18070899/s58477749/9d860b75-2673abd4-5509e65e-c1c0949f-6cf6e91a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19655295/s52087351/87f8c185-8b3f42cf-479b913d-d35401b0-bdb138e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19398915/s51510968/41f60ae7-ed61a92f-f49ec334-73373594-aed8f832.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19800337/s53459280/be1ddefb-9327567f-aef38bd8-e918043d-91c40219.jpg

 68%|██████▊   | 3425/5000 [00:52<00:15, 99.60it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13430469/s53350848/83adbd92-93037aef-6610c03c-9e8f5311-0c79589d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10870373/s53022981/99949ae3-8c01a514-959f28fb-5d0dca8c-d3c5c455.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16691753/s51680432/a27f4a96-5803cd1d-bcdb1acb-a1f41563-c4277c83.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19033560/s52631784/268f3523-4c1cb728-abfcb369-bb6de2ae-1632cb94.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19922204/s57608142/aba414a3-12dbd151-947fffd8-f4a59322-d49c660b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15641930/s53690240/d411910d-50bbf568-62f98b12-19f94e62-7fb18072.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15455844/s55897015/680a1c96-84e022af-11f79d69-54fbcf51-72e34b4d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18549459/s51237507/fc9104d5-1eef938b-3bd80823-7f06414b-79920948.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17615451/s51434105/772e7c87-54a7b9f5-40f8968f-324f6daa-1e95cad6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16104236/s58451216/9632b3bb-551c72e2-f1df1522-ca7bc24d-fdbac414.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18877812/s57300873/b46c1fd9-2f57b49b-a5fdf44a-ba513345-75145ee6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11404878/s57050740/fd378745-890fc2ae-da63f3df-c4f6c8a8-f1bd6a10.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13199702/s57399448/4dd3bc76-085761a3-30151bdf-92f7427c-194d5bc1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13098601/s53849471/f26e5e47-5c5e3a2b-1694e814-f47773e8-03a6372a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13058887/s56035224/1478e9e2-bcb787de-6ddea825-1e51f235-9bc58911.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16338268/s57972152/74b2ef73-1156ecec-0ae1f730-3e12ab80-d3bc7e14.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16330662/s54431129/aaae2683-0d8e968e-1f6cdf60-893c6239-42c9974f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17724824/s52806464/b4edfeb0-c0e7fa33-adb9da31-b5e7362d-18ec402d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13120648/s52924179/295144e4-d49dc23c-b70fc009-8a921db3-2cf51ee0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18678399/s53284819/02f34fec-90006473-04d79284-2ca64952-63324661.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18697563/s56205821/722cd1d4-15711845-de35365c-9dda3d1f-a4e6695c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12736960/s59550276/fdd599e7-468b89d2-18d67b6b-8c667472-7ca0cf70.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16622129/s51595139/81166e4f-245a1156-0070734d-ae35e36a-dbb9a639.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17197713/s54832929/2b1295e2-fec8c438-b73c816f-88558227-14cf2123.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10283054/s53642473/752ce9b5-59330dab-94db0dd3-b1b6b79d-e3dd49d5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10764758/s58272725/1ec0c29e-b231e5ab-ded91c7f-00f9bcfe-ec4d536c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14702885/s56757825/2dc1b572-ef03e4c9-34c79821-b2711faf-74f0a803.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14989606/s54863678/a093df92-c3f5b1cd-2cfc5bcd-4532542a-15bcbac5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16679893/s55641550/c370e3bd-bbbfabba-9adb1d81-5471aae3-aaab51b7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13606683/s57242265/af6c2c8b-de4ab155-e59a3a03-1f473d61-d357be8d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16293344/s55303610/9c69dfde-3812768e-4cf00ed9-5e785b3d-a0d31f03.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16773288/s58492382/172ba5b0-18b09f2e-313a970d-54cff10e-17058fb1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10401318/s56447172/bba4a86a-f254597e-b0d7f384-073aa395-78131e2e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18504241/s53979691/6b3806ef-fe221e02-2c9f42da-b401a2a1-6da7e715.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16557374/s54843135/bb19d23d-af4da508-14ea3aa2-8e0ed8fc-2bf87ea7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14729536/s56712049/7e648bdc-3eac6f43-da6cc86a-1a5716db-c1c3fad9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18995174/s57132459/415e2b34-24f91bfc-59a19192-21743ddb-94785a19.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17635175/s56564481/ca5f765d-9ba6bed3-4b43598d-29604d6f-6ff06a8f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13590929/s50589606/e92f262d-49e448ca-33c1cf24-450fd401-c0298b79.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11293517/s57001251/bba7f682-33b9288a-712a4870-190d5eb1-2045568c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14388229/s52835199/22c10d18-9df15d18-57906a38-d2fc0858-cac6e6fd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11926661/s59646492/55713af9-6f47e653-933e3e6d-b56f2931-c7167daa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15412344/s57724509/cfdcdb45-ede2db81-4bfa3f5c-ea87bf98-026b6f7b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11416560/s52370726/8b08eec9-dae17f48-b42c644d-88d4cd92-de62987b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16807878/s50554604/0d39b2cf-394043b8-b57b559c-02c38167-487234b4.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11744037/s52818272/f3384aad-37881153-414d68d9-2bda7c33-859fce76.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15634195/s54256857/62f52754-64282226-85257bdf-0579dd4c-386798cc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10667849/s52145213/3d4de85a-50d1a059-b7c7382b-5e821fa0-9175ee6f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15766903/s56113416/ae8583cc-930742cc-9efa0bdd-98cd32cc-77a85aaf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15697115/s53723395/8e6061c7-3078ec5b-3b54118d-835defbc-3e5e1aca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15214825/s52383757/a499b73f-5435549c-c00ad9c9-ffb748b7-f0d270f1.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19344311/s51569812/a15ac528-1fc761d2-77905e4d-2c82fd82-7548797f.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13800450/s57216928/b3c763f8-6c9aa43a-cc7a46d3-0391a576-cba58ebb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12405140/s58516376/9fcc5266-d32f267c-2a6f6e42-e2d6be4a-880d9bd3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18666022/s54147469/8d9cd23b-191f825c-72a995cf-bfbd9b34-7edf2dab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13297093/s55727059/ae5d365b-23feb748-11cda8f4-b4a7bbad-a4bd3b7c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12542274/s54329610/feec8a3e-2a3ddcde-56693da7-4b9b4ef1-e7a69ab5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12070314/s53275213/b16a781f-265bc0f2-295517a6-b80b93dd-c436c3c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11063065/s50570483/dc3de637-5c5ce8d3-b876e647-427c4fb4-2fead81a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11964706/s54230905/4faa4abe-37c38a51-a5c2454b-a3e224ad-20afdc0a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11507392/s53797697/04fb1d10-46decc75-4d16a716-bdf7a349-a33fffa2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11669237/s56036676/8bfbc1e3-381bc1ef-d03134f3-994d806a-713767a3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10884125/s51981221/bb12a59c-55507a76-ca3eb38c-42f02312-7084f3c4.jpg

 69%|██████▉   | 3456/5000 [00:54<00:34, 44.70it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10663051/s53718425/89b51aec-cb1aab33-97eda27a-b8b1fe88-0372f447.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16442524/s57983940/cfd902f7-2cd399e3-e107ba6b-4ca4da8f-ee25a4c3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19415089/s57628176/c1e10217-922833df-81cf7da8-44914508-052f7fd2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10481162/s56477602/efb7c5f9-8b02d42e-b1d21770-a6259495-3cb7d912.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17767787/s53425333/35fc33e5-d4fbf7a6-68d77c16-835dc098-35019e02.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14579724/s56120700/f33b672e-9a8c12a0-dacdd9c8-30dc3e2b-28aa2e18.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18763864/s57111811/d8486875-b809d9e3-37e383c1-c5fc35f3-cc164e01.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15310905/s57329242/7dea1d68-4b01f068-12b84492-fd2031ff-4564e5c5.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10391104/s53949945/3a3f5f08-e0497321-505fff32-8be3ca97-350d34c6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14095990/s54420580/1a06d600-1253b9ab-d13500a6-3aa12816-ca57e741.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16103537/s57647079/cda17740-b55c35b9-f6867fd9-cd8589f3-2188bd5d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15987251/s57781619/44704acb-ac56933e-aeb045cb-c070ce32-34b5c45d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15456778/s54926865/ddef55c7-63478352-d3db0338-5669a4a5-e4989167.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16130030/s59609895/a8a5b809-d22bffcc-c9e4c551-fb8fac06-3cb9d97c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11126801/s56178858/e16fb550-fa48254e-2b28af7c-d1cc7c47-fffde88a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17038950/s59940783/3547969b-bbcb3520-00ebc1cf-6e8ae600-ab9dd087.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14921607/s58123366/60630731-d660e96d-d5198cc0-4d8ddff0-a927f635.jpg

 69%|██████▉   | 3465/5000 [00:54<00:36, 41.84it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13057021/s51148453/e8244509-4a4d6b5f-e493cb5e-0bbda08f-06343565.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14150988/s50803154/25be2abd-f37d2013-0e53fa18-145deec4-1cf002dc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15389058/s55943374/8fd56e0c-c9334033-9f5347c9-9c84ba78-d799447e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15710868/s55137145/14122cb1-df668aee-0f5f7477-e87ec36b-37f5b8b2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16454913/s53775998/e3967333-87969815-5701ebf9-952c3de0-773421f0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17717614/s57326510/7a804008-57240561-cbe9bc70-8f6860f3-357dabb2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16346361/s52725592/63bd2720-171758b2-c1fa25eb-928ff263-6fdd361d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16437473/s51645025/562996c2-0ac1bd2d-31b39e4f-0bc6145e-54b04ede.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14838068/s52169528/756caee0-ea15b32e-4456b8fa-25b5331c-91109413.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16288809/s50932975/0baa1069-61e4695c-9c51fced-769d8bcd-1ce68248.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18202111/s54545030/0e9c9a32-437d8a0d-728284b5-db7d6449-50ed57c2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16514111/s53311031/c448f24d-f0e81e03-b571eeb7-8dde4581-998c008c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15853547/s55226809/2f30354f-da9ea332-7957fedc-ee723fef-18d06b20.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19076882/s58201888/78a0a60f-2688bace-bf65cac5-cb2068b1-8a725110.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18620180/s51423066/032bbeed-5f1923e3-8fbb8adf-6d3cd73c-4a4236fc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12627028/s57552388/8b3dcde3-167fc223-145a7bde-f8a24bdb-24fb8bfe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14102384/s52991440/ddeb1a84-094a614f-21b9f9f9-95f3d9bc-692df9e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17357689/s53251372/1a79f9b3-117ec560-66a7e17b-0887fe18-a0d6d7c2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18257244/s54428852/8360a3f5-fb003abc-ecc17797-2065a221-0e9fe9aa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13524796/s52420627/f1b116bf-d6e67344-cff86476-fc6dcbe0-6664a5d2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19757720/s54045154/d5cabbb7-94d369a5-63b100a0-ee367e8e-e320832b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15479539/s59548094/d4f9b6a8-ff666cc2-0fb3560c-aaa778c7-6ed79c7d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17076457/s57351498/af83fd1e-2fd152b5-4dbb2f21-a0176668-6cc92ceb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15925315/s59723249/20f4b2dd-3d054ee9-e75cd330-c566aa5e-9a3c8959.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16516267/s59781718/22f7184d-10a595e0-15bf5705-95d12dec-ad1ec2f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16223763/s55816518/23d285ef-dcd9f24d-53182fdc-552aa4f3-118e4eff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15697115/s50085145/74821e87-2d9bb8b0-31120a68-f6cabd1a-06ce0735.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17241424/s51144524/6e90ca23-b59194fd-7ba3ce0a-5b89cefa-58d3b1d6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16119588/s58121461/cb213765-e6b75e9f-02773e87-3cd49cf1-51ac602e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10012261/s52687681/9af1bc12-a2f79746-3bc4e986-f903d0c5-72d58c21.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12064183/s50732341/fdab9144-c1c3d79a-ba3d53ec-920a4414-f9e4d0c5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18798039/s56221433/f8eb5b4e-c305aa7a-5c8f404e-680c95d2-9d4bfa70.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10374990/s50367671/72393f58-3de64497-fa2b8f3c-8caf7e2a-45a8e745.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12579086/s59758823/61cb61a4-1326ebf0-5b45b66a-89dadd2f-891bf33d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16373688/s52756380/44011fb4-e481a4c1-3c16e53f-94427826-53653975.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16440784/s52503897/e70a7c22-9834ff52-40ae52e1-d8ad91fb-f0910b2e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16968616/s55062995/7e70a1ae-2616b769-bb777dc7-9729c55b-50282c90.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13224377/s59422168/1033d43e-725fb7b5-b41e88be-914ae186-79f1e995.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13647451/s52588756/bf5c000b-725ab1ff-a01b8e85-987c2f21-bf643645.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13536343/s55579765/4f43610f-1779f8d2-600e88ad-0891e6a6-15d19636.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15213209/s59705368/b0a8fc75-3b095fec-6a00a0d7-24d1dea8-3eca5f59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15267238/s56088651/92ddcd5b-eef385f8-1535332c-2636cbfe-5ca0e5dc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14689985/s53369153/ece32804-308f3848-94ec9bec-215de762-b5bc967c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14950396/s50456547/89e9433e-b5ed1fb0-1da03ef0-74c1f0ac-877ff457.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15362524/s54509087/ebabda24-d647ebc3-e761d163-b1c5adc4-ab02e70b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15035666/s54461338/bb114efa-0e50a8d1-b889e03d-eca51adb-73648024.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18377113/s57741629/e398aee0-2a2a5fe5-e82ea07c-5e53e40d-ab2e09f9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10598185/s58316118/f49bd099-410d7e18-0edac78f-50e394d8-02d6434f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17915051/s55155380/ab752db1-88bd2764-fc0c3e26-1487827f-469dda9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16780307/s54030898/97abc636-261379f3-982e7c04-d2ebfea2-c571576c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13135020/s53119963/204a9230-c6ea5499-ef7a0c19-1d92e463-e21289f3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10862893/s52960595/a18babb6-7e7ec715-94038431-259a8843-84a2db7e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15165563/s51659523/33d5c246-013637a0-cc2e2d16-f1faf168-bfb66110.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10702059/s53585164/49f05723-ae68b45d-03c7a5dc-63492bcf-2f4dcf63.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14191782/s59333443/49336084-7e4215f7-6fc189bf-d7120599-9fc0aa8c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14687805/s54717154/dd6c7013-208e11de-7a63614c-23294185-7a00b74b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10213338/s57416577/8bb0fdb7-130c502d-5ed801de-8af47fe6-cc0f67cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17051420/s55910335/a37359be-f86395c7-b0a006e5-4953950a-052925dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15475784/s59412867/cf127359-f73fbaef-37847782-fbccf3eb-91804928.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16542986/s56297775/977ce9fa-43106a05-0292950c-a92b51d5-d7afd5a2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15223781/s50415964/f3c98f85-4713e1c5-fabc0336-470d5cb5-4900e81a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10417421/s55565191/fca34755-904299ae-11d20b2c-14152848-d1b1cf4a.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12942909/s50993511/3ec7f136-ccd427f1-ae0d8126-eebadaad-91b8bd94.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18111204/s52434740/ef6eafb4-5c19d116-5faf413c-9bea2838-d748f48e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10934084/s55698860/632b00a5-cfed3ea4-5ac35232-7d00455f-4a9bff08.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12993962/s56162774/62b27919-acf68271-41fb50f8-0fe4b79d-fff1942f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11434374/s52916793/b30920ff-741d3a49-2becaf82-55365c74-fa420a2e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12767234/s50374638/13e54c81-cb9495b1-7e0d5e0e-60d8854e-63fff3c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18249179/s54300188/5c3662f7-82b4bb20-de8e8198-b1c626f3-a5154592.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15862493/s58229542/43b8a630-a9db9de9-7c3d66b4-52ce47ba-ab6a9696.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12328460/s57544557/86511d45-162bdd23-79a975e3-e88cb931-87215f4f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12945480/s51189489/4fb3e6f3-081847c4-0a812ce9-5d7e44ff-07eba988.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14937207/s51132267/9072274a-26255d17-66e24dc4-a4184d52-376de68e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19780451/s51879305/ac1c659f-73cf3e1e-3d01b2f6-634f9934-6670d584.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10145374/s52207654/46fc1b6b-2bd6be5a-b8680008-c27a898d-fb4b290b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11028216/s58665953/25d88b94-02f4467f-5a387fa0-57db1410-15ea7742.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16662316/s58927405/42f47044-6d5f5f23-e751939c-cbc9a4c9-242e5431.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15511388/s54547463/4abf6d6e-6663a336-c9354ba0-c3d61d95-41c8aec2.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12813733/s58662319/2f62d2ab-c32be343-071da369-b163287d-095259d8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12308349/s50996315/69ede4b2-e67f361d-0afa50fa-cb99cae6-4e314a1d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18727840/s51613498/5cd04fbd-3640b252-34b1efcd-9f278a4f-02856cc1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17123392/s53259652/f0664ad2-39c4f302-bb78c333-652110ad-0d92988d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11613361/s56191281/82d3010d-58c2a8c2-8ed320bb-561b84ec-319ee7ef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10655111/s52220516/6d70752f-aade8e66-2cae9266-a6cc5f58-754773f8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15065637/s56849787/1d0c4d67-96133114-439719a3-bfdc3b79-5ea962bd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13835462/s57897728/01ba039b-904e94ea-13d65cd3-3600af2b-a936c306.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18663142/s51714047/d4a181db-e59fde60-a8d719b7-e6293d0f-940b3639.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19305757/s59662395/019a3144-156f39d3-8e0d415a-ce99d845-da8423ea.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18936629/s50626263/470d14b4-34021db0-7d7fa36c-be56e051-aa3439cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18678622/s50997720/2bd00de8-3f3b4a7d-9f77fa6f-70025dc6-3d3e0b79.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10856095/s53043821/c8f38e56-15c24a1c-cc97f936-720d49e9-f9f2661f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10398333/s54879960/bbe9b4c2-5a196471-053d798c-84dfc479-ce8daac9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12408912/s53734003/cead150c-f7f523ef-92e0d5ed-1963b270-772a4d72.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11673731/s59992889/3a6c1b23-4136fc6e-c46fe8a6-187c3d9f-3c13718d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18933476/s51262714/77bca560-cf43281a-5054d498-f5785f20-2124a406.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14535212/s56313068/f4df41df-042e4cda-21184ecd-c014578e-cade5127.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11124859/s57088664/6569208d-8463df7a-9461a51f-1e3a7cd0-c7c5ea3e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12162956/s56528163/3ae98df5-88c01a44-bf3c5b71-230bcd4d-79ef661c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12591382/s59881599/b89f0911-2f9fcba8-cb87285d-305e3576-4b2836c0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19418764/s52731017/2380cd26-71d4af57-32bf45e3-5de3ebb0-b0f93234.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14657829/s50295143/bdd3bb70-829dac6a-7432c5e3-f1b2167b-0eb1d30f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18879223/s52812006/bdff6639-96ce55e3-36e78b51-97b83986-30f2dd52.jpg

 71%|███████   | 3544/5000 [00:58<00:53, 27.12it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15229604/s51209326/924354a4-cb556cb9-3d762df6-a36601e5-ebb4b6bc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15874847/s52582396/f16fe73c-287485a3-f9fa058b-302f57b1-7998cf00.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16826165/s56681179/92985545-b89b849c-99b976f3-093164b3-3a8c976b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10189939/s56993354/9d5d0427-5d2afea7-4f8dd080-1b17681f-55809063.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16747881/s59082887/ef1d078c-278f5bd0-d8a1177e-072ef2c7-7293a11d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17592232/s50371515/7ee6de2f-76e8112e-ee78b6a6-f86d05ab-1d5b73c8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13989970/s54782819/20f62933-3dbd0208-9423edb0-dcec5e84-0c785104.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11512695/s50040170/9c8cd0c1-4d2f391e-08322bbb-3727525b-9e046360.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15165563/s51659523/9d8a0546-a198f565-eb6fa847-e9b635af-c598f4b8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17517362/s50480046/19d605f6-adcab921-06687f2b-4264e7d3-0fc1a70f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17071904/s51762217/a4dabbee-338080d4-7a80fdc8-f5c19901-ede95392.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19349785/s59889869/7cfd2860-765785ca-7a0c3b66-c1f42b7b-94182f9c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12907811/s56470707/2ce0c575-ad9f44a9-100cf54f-e650980b-0f31ec85.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14703317/s59171447/196ce543-499caded-0b7e5d4c-86b193b8-aaa7a5ba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13282189/s58860429/a79d85fe-c9fb40ed-e2a0a5f4-3bb9f71e-8f742d57.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14437955/s58683770/452c0225-a58f6be7-55fc2be1-e5be6720-67ff4dd6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16113543/s58433008/3aa205a2-969a5b46-2a64788f-fdc5ddfc-33e8b5f7.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10191482/s57553180/d36671b1-33c0dd0b-9ca4abce-c573be38-5b079a7a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15259074/s59729411/f1f8b6ee-ea9bd6c6-0dbb33a9-c5691dea-27642375.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18908038/s53785145/d8b63715-d69aea55-ad8a44ce-083bc3f8-f69a54cc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18407215/s57020125/aece19d8-1679ac33-b2e41eb6-8ff2d043-68456ed4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13562117/s51496587/b9b99c70-99ef2cf8-e248be5c-0bbb62f0-6dde15e6.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11234592/s51545962/8a4e820c-97b55d09-c040a46a-d351cb15-fa153d4c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11928388/s59610618/8bcc303f-b5947926-f49c71ee-3f262413-8484277f.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19122984/s55157582/75c6844c-bef9ea12-14b9df52-580d80a3-89184c55.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13714286/s59779626/4461adde-d85d66a1-787d4beb-13a60b1d-eb7926bd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19740976/s55903287/40a315f7-f6bccb78-c6439ff6-b3752cc2-8d2d5f5e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12385109/s53691560/ea613e64-3c422c88-69772945-d60c1e39-55c5bf50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18110807/s56191180/2c61f76f-d6fa4b48-44779d41-392bcbae-e1443f17.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18362067/s55099818/72fe7e6f-f9a09662-8db93ade-e085c16f-193d8603.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18220139/s51592614/28acd130-5bebc023-5640f82c-aedb4a77-ed7722dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13688683/s51620787/257448c8-2c7f35cd-7d144213-be0b45a7-13e4ae7e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13648633/s53511466/7181b44b-149a4585-6606965b-7e8f9cb3-2bdbfbef.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14044629/s55462550/4840a269-1f8c6729-ffd76165-a9c9aa84-0c7bcb74.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14382318/s58394786/631d946e-37b7067e-a86edf8b-de2d0605-dac0b32f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12229726/s56397487/05078ecb-eafbf126-db68e0be-d3995fd3-7e208cb6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19895187/s55924190/63673d9a-c9aaa541-797831b0-3ec88ab0-3c0c6780.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17630935/s52836064/bd11d651-824d854d-d32b41fe-0e7e124c-95463a25.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19788382/s51073383/6309a63b-c4f4faae-1dbd7560-d39b5c55-94fd94b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16081944/s51602301/570bdafa-ed038b3c-12af819b-03ad2250-70a269b5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16113201/s50311857/f9105192-f65a6444-692d5aec-cf093c4e-461a0db9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10630310/s54642772/cab1708b-a4d73a60-9947b385-3ae5ab66-88e5c663.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17343150/s59424371/622849d7-cd348a3f-93f57cb8-3f5eb01e-ecfbb3bf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10449497/s54904259/e14d1d31-1286b8f3-d98dec30-e1a997ad-118c55a1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10572099/s54889793/8b971657-0a0e8d76-ec126574-4737b870-3e08c85a.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18991843/s58556115/ff59d0c0-418e9f18-af5af5e2-9acac8fc-1fdf1980.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17865089/s50982899/65f87543-87a03c42-d1fb2b73-97bb989f-b2a25788.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15656571/s58347550/f84f4d9b-6a0b4216-e1a52b22-48f895c5-43d20107.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10459005/s57083109/3810c9fd-459eb711-3c88095b-718cf51c-7cb14c3b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10377016/s51464989/760be072-7ca3aa0e-8489f820-a388ce19-69036e30.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10867166/s52151611/9489c140-dfcf8afd-88a9c33d-3248be76-fd6b555a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10149624/s51809279/6420f47b-3aba3bcd-8bf6100e-3ebcf0b3-f3cfba78.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15654175/s54922905/13f37ef1-6ab5180e-25550bdb-fc515b9d-6aa92727.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15165193/s59085184/d646869c-07a54ebb-590c4a37-78ac0242-c3e2985d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14281951/s55383171/6415c6bc-82ea44bb-15a82bec-5eb76048-61d7be4a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15420371/s57379664/e1c50d81-eea06142-f92ac21d-2f0d61d8-d48c5ef5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19630013/s54908438/8f13b302-d6aadea2-d46b67b3-43959aa1-6b5e3905.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10181023/s58357900/61e1b821-378d0cb5-9d2dcf96-6cb802f7-cb7a32c0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18150264/s55632456/a3192ac4-1197c37f-27aa0e5a-7d5c71bb-8f5f464f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19553666/s55797359/b7f35d18-640fd455-e24c80f7-b6d5ad7c-edd5f955.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19848478/s57936140/e66ec5b8-af82c170-75377c15-0fedace0-6f15d503.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14329446/s54994537/8db87fa4-08649768-5d05ba78-5b093483-d848db6e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15676084/s58262019/de28e20c-826a6fe0-fbb4d62e-88439880-51a428db.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18679547/s50495769/aabe5cf8-f4bdb7e5-df02962c-aa5ebe34-1d4816c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17439857/s54686900/46a6be20-d9c564f3-c5cda438-fa34efd3-1eca8cc3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11885477/s50524352/25f8bd5a-edb43c91-e3636e3e-494bc15e-b488a7cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13472364/s51531209/f4b1e370-174cec79-864c2de9-704619ca-2d863810.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12387217/s56095945/b66a8cf7-7807e73e-ee7fd011-d973ed84-632735aa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17288844/s51904170/cf6229c4-0dbb5dd3-64610954-17ed414a-c7d2837d.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16216649/s59795690/f486b982-652a63c4-ebf514a2-3edf77df-0ec0e345.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10838161/s50419958/95bfb7b3-65ca1302-c5107737-1823de3e-45929e1a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13302464/s54789289/94c3e8af-3ccc91d5-486ed2f4-fc099641-6e7edb5a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19030532/s55463289/be64b363-db3aacbd-28247559-3ea60655-4133c367.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19185280/s52245245/5b9b5080-d30a2451-341b49d8-d6d27ddf-502542a7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15164924/s59924176/87d47098-7bfb5a46-690d4303-886e1314-6a4d333d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17481139/s55116964/65c9c61d-266af259-9f549e6a-87285d10-475ea791.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19288911/s58763090/4ec44249-606007f2-187bfd84-deaea202-8970ebf7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15512494/s53671878/b965407e-61e274a4-345cfb7a-07774dfc-00e8377d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14376085/s55707112/38d9629b-3575bfed-be484083-e673a588-72936a93.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15479218/s59625046/7a24500c-56014d34-79ed8841-c75c3452-55a76bc6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10526322/s58793311/977d9206-4f8156aa-fd0a9f57-a0e5b984-c38aad69.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13040755/s57277611/71969706-c914b911-0fd23f86-cf4dc198-6d0a22bb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17425647/s50467128/7d3675ff-d57c79a9-130e92bd-97e07c72-7e26d1c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14045504/s52718436/91456c82-86e0f660-7a059257-6314aab1-d132843b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14754762/s51264828/971a86f4-01c9587a-74f464e4-d64ec3a4-73662ebe.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15524760/s52141331/65dfa87f-d808fe8b-e2c80e3c-f66ae4ff-ea264e9c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19323933/s57444303/77eea935-76df217f-c6984932-ebc84914-494818f0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16458801/s55187885/a29c482e-f1e3a5cf-2aa694f8-4fe59641-b1138120.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17961555/s59875634/23c0c180-11e2ae6c-2cd50fbd-607f007f-0104227f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13512648/s58323857/f67b4dbd-f692d543-da95bb94-cf7c9cfb-f7808e4d.jpg

 75%|███████▌  | 3755/5000 [01:00<00:25, 48.49it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11255133/s56454501/bd73e9ab-4b2f7118-a7484a2b-bab0778d-300ce9fb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11976099/s58083428/6980c04d-7f0eab04-d3853776-480e6e25-06b18236.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12153312/s50048936/4ded594f-67d45619-819a240b-79eeceaf-10638419.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11247570/s56323553/a6767f8d-05c83915-97d967ea-3a964bdc-c3ba7799.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11922236/s57289100/1b0ba692-4c635a6c-9e4cd0c7-76f46ca7-1b053c99.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17147147/s52567055/f7b96fb6-370b17fc-54eeee5c-4165d532-433b34cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18048805/s50808906/cc273ea7-5e04b95a-9ee75446-dadc4f16-23ac8b2c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10939051/s53096242/d222b4dd-d7923984-5c4e455e-846081cd-69255c33.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18610959/s56916748/91e9bfc0-785735e0-b2c3e603-95bc8b0e-bf96471a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13428362/s54709121/a34a1b95-163be742-af5f8021-e671c55a-56d215e8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13601656/s58320330/fe744b52-d90e73bc-ccaf5372-6365d95a-2bad6139.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10530041/s54402398/e5abdf1c-fb2d3fdd-73f6ec02-ab58cc17-2eb6629b.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15455517/s59435944/a07ff955-ea598d7d-7bab45c6-81b02fd4-ffbfa09a.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10171967/s57636479/65ae96c5-04f7fc0d-d42b43bf-9a3a40a7-91f5cb7a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12019744/s54372722/e9184747-c2aafb5e-01087454-f632c528-585882f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11660644/s54661789/637c7701-8bd15dbf-1016cfb1-71907062-73633ef9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11465141/s54426019/55b684a4-a25d4ee4-eeb1b7b0-13412fdc-3297991b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17470891/s58964642/86b21961-77c2cdd7-98433940-39924841-e58cbe0a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11116402/s51571085/a9e35f18-85c54b62-477450db-b25ec185-5c587fb7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18817171/s56209283/172858ca-5cbc198a-199cf125-c1eb54b4-617fd088.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19687661/s56136069/9c75e618-0731a407-4920618c-d907257f-39d23e58.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19075045/s58577683/28436719-d87f3ae5-9c69e639-adb91cdf-96771118.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11725969/s58008708/e5bc50a4-68a32a32-2089c166-9b057096-f205aecf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17459404/s56591364/26092bd9-25938fba-334dd7f7-823cf6bd-577d63ab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13637699/s52915995/e32801bc-6a4a575e-45ca268c-1be9814a-04262901.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11607177/s59695557/bd9e0147-8fff814f-a93f4208-77ba2b4c-e4255b97.jpg

 76%|███████▌  | 3810/5000 [01:01<00:21, 55.00it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11533366/s59909608/197d538e-892c79fd-9d6ee5ef-a56a1256-9a68bdae.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11479858/s50894799/c640893c-43c5cd08-1a9df177-fba56491-dc9c05c2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10335334/s56048989/b4c4480f-87470efc-9ca0cadf-a3d51437-45702749.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12126708/s59250141/35f8fe8f-5fe81c37-560d16f8-c1b9af00-d4a8addc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12868814/s51212670/3d1e1565-e1c7ecfc-3951e0fa-03698b87-eb381c44.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14715243/s50171878/765085c6-503e5019-dff6d673-35e58da2-f4f89068.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14147261/s56394841/44f07e88-cac9425a-70789c2f-9a7e2541-31e8c7d6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11492213/s56019485/2578b3f2-a1a80de9-2162e8fb-a0bfcb5e-cb040a8b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14603776/s58946336/5f9dd923-262a8997-f67ceb1e-0d83b891-0a7a83ec.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13188963/s50391324/c01bbfd9-b27fd1ee-a56e4116-6da1bb5d-09e88bb8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15106163/s58290017/6bdc46af-17aad841-074467d6-6d060827-48dc3860.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15963174/s53185915/12d7febb-73c3c29b-1fd2cde3-d5e2f0dd-da6dcf9c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15862014/s50892272/8b2bcafd-3feb79cf-07ca699a-c03aa917-1a0d0f76.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16732638/s50481139/5a5c1a97-a80c8ade-721b5730-da8af5e1-76515534.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19011082/s59091437/4f0164c4-a7354504-7551d6ee-c88d4de6-07642909.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11690358/s51001572/19383a67-e58c8abd-c1f710b5-3aa7b191-e651cbf7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18570563/s51674551/def2362e-1dea1b36-3122f1a3-c8dbb8e5-e7b9d506.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10804721/s51892076/5a6ddcda-4b78d4b4-39b71667-85f7e386-86748668.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14650506/s51252938/6ca36d76-c7bbbf13-81bfb03a-87512ae4-d236f734.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12996303/s59769316/809e47b8-1c0e910a-c439f479-6aee21a9-2f66239a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15545526/s59657808/fb559043-742e73ff-deab860d-939de3c0-b8327492.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16006840/s56291011/42cb079e-5f35c1f3-a59c9f55-75a1b818-79db64ac.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16337817/s57697955/4f806505-7d0e1c9a-fa30d3ed-48c2abb0-08bc5054.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13802468/s55536168/0abcdd85-ad4af15b-9c5ca08a-645f8469-c58c24af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17176962/s59431848/5d97cebe-76945dc2-cf57dd0a-b8ef7861-b1d741a5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15511388/s57084078/b32d87a2-bd306726-66f0b800-e93051ac-7b7a22b7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15205644/s58853560/5177ac0a-9d2c7065-50349a78-0a96d63a-c59ddc03.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15936063/s54775675/ac2ebc17-1be06fb9-760afc9d-12535828-0e98e762.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18426683/s53906284/88aac4f3-d7dc3810-6ffed23b-a6cafdb7-9d24f040.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18273833/s56043544/511f1f9b-b5ebb008-a61678df-c99a30ff-4aac06c7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18480730/s58498476/cfc74f6c-660fe91d-6bf6c673-089f26ab-1f68d88b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18091782/s55743513/8fb152a7-cefdfb50-4cc17c57-1423dcde-1c1cedff.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10011668/s56511682/d110191d-11ed1652-b1e795b9-3ee0f7c6-446f22ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19358609/s59002259/76d88971-1492bc74-4a00303b-111fa19f-a617a23b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10229323/s54781532/7f6a74e8-da45d895-54b3bfa5-3851e92e-e308bce3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19430776/s50007299/3a34210f-57dea3bb-f37dcca3-549c1610-93f5fe02.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19207802/s58199776/4324300e-1032b230-bfe2684a-d03ab3cb-ebc9e6d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18874543/s54945406/e77568e5-1543227c-0e904095-3bf67bc3-24979fab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14571729/s58064871/ece4091c-2965bf05-eabbc494-01cd723f-af82434e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10002131/s52823782/051b7911-cb00aec9-0b309188-89803662-303ec278.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14644914/s50376063/3f5d586f-dc674d57-86368d28-2128e80c-c80bfc61.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19830694/s52464736/84a17bbe-6ed28f62-53f93b21-cf84fd23-2f63b856.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13609561/s50375381/dd9f30ba-24d8de73-bc8b5b78-7c15f4e2-50d20b69.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10755736/s57172144/09c65ccd-67e40d96-9917aeaa-7df6d5b1-57bfb3e7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10336400/s54293020/b8322b10-1cb23642-83c80ce3-ebed8337-d51154ed.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10853018/s57197492/5b2a1850-a0e0e56f-344b0cf3-eafbafba-b9beb629.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16562665/s57252949/8c5e61d1-b7a2201b-21af3fca-4f5a278c-fe0f146c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17245999/s52862226/b45582ec-113363d3-bb4de73d-90af4eb2-0a20ee4e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11798500/s51217329/63b68a86-f90ebd3e-3c7eb706-3122f11f-1329cbbd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18614670/s51461691/81645d10-220e127d-b81276c0-c5e0a691-abdbcc50.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10661934/s52849261/d29e94d3-dfe02d69-c30826fb-56453654-e4e1bb3e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16391076/s58273615/7597bfc4-b3f2493d-5bc3c8c8-c61ffa99-9b67bffb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19344311/s55151020/430e561f-01fc8362-495bbbfb-625d0ccc-8e785827.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10354450/s57423477/bc6f8c9f-f5b40b8b-1c34e62a-fd2b5290-6bc171b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12850463/s57841962/91aeb34e-eeb27971-7e2026be-6b7874ba-a19284af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10314749/s55142934/1cae59e5-12d83948-b724ba07-4bceb9fb-e30dece4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14481284/s50596436/ed7298e4-ff1a5fa5-e98a32a9-8cbe3629-be3765b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12848856/s55829576/35683677-bc9c351b-e68f5b47-a1e3254b-646a6b1c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16949700/s59657922/1888e449-3203d9c2-5d87905a-71c2a2c7-4d6e6cc0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17585845/s57168298/242dd3a0-bbc3de9b-601e90e6-5c078737-86e8e1eb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16454913/s53284187/abbf48d2-f7395624-6b5db91e-3405162a-9b6025ab.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12294174/s53154860/cec6b5d6-670c7a52-6bb0dbce-0b941b2e-ef1005d7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12762405/s52878934/018166aa-ec54d385-4409f1b5-462638b7-9a7b75f8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12189285/s52939782/42c2c190-38498880-cb567499-34810fb4-46a63137.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15582954/s58244135/43beef2a-71235caa-0bf7cc71-19ac09a4-20271e9e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13537167/s55775659/1925839c-ee24c6f0-caa5d999-fc284954-0296e1f2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15028952/s58370497/f7ec844f-7f972159-5c0d22fa-e41a506e-cacb8c4e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12043836/s57999325/42153ba7-2a4e20dd-0955bd42-a7b47dbe-9a9fbc9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13011941/s59764222/7ef323d7-a39a33ab-4a4f8f0c-999d85f8-af56bfca.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15830739/s55965375/633429b2-beb3ea50-d47b21d1-fa152a4c-aae735bc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15989123/s56519698/7f2bd2a2-c0e04648-12d17569-dbd32655-01e2d498.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15886891/s57291466/108c5677-8e1c3306-e2de34ea-db04d932-2628e9e6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14470386/s54349507/8ca31abd-90989e99-84a2f550-35ee32ef-6518b7f7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19920625/s59321714/3edd3bfb-444333c9-850e071b-205932c6-0913611f.jpg

 78%|███████▊  | 3892/5000 [01:03<00:22, 50.08it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19623993/s59732891/1b2918e7-7299bc31-009a6db9-9ac44163-479cf007.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16932362/s51991723/65ee60cb-34320eb0-95ed4619-7ffc2093-ac6383b5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16196998/s59477586/d605db01-7480e701-5a3b2421-fd62be0a-ff963ea8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16472682/s55837143/2780e305-3d55dc31-55a3d876-96fac079-611c5db6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15892429/s54940979/4bdf4178-6fe10412-9f782f70-cad81d13-40200e8f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15998296/s59116062/3100e550-9a75c674-69529c87-2f7aef2f-44fc9446.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13798658/s54726555/785b84ee-3fadc0f3-fad1d196-13c5d4de-dc92cbc2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11292496/s53875708/d4e68896-e27d8d00-d254df18-ea66a0c9-ce9e5f22.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10556676/s55706849/5b077ea7-48c0d722-47cf5a3d-2f3450b7-2b9f2efa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18616550/s55273901/c93d0eed-d1cd7b9c-0da10b4f-7b83b3cf-ae76dafa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10723086/s58425386/66b1414a-c56c34aa-2b6aa119-4af2f241-72cbea1d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14930522/s54821272/d14665da-e06a5d6d-61f32161-d994d195-c71af0b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17477304/s51902388/98ad07e6-19056a63-204ed75a-622ed09e-28641ce9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10955604/s58560356/2346b82b-bedcb0f5-95a96ae0-5992e41f-fe37de26.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13340770/s52789306/f3aebb29-fbf17aa3-c9a4a4b7-e3aa015a-daf2612d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12248765/s58337278/1e07d813-3b853864-cf18fcca-86c271d5-2596d471.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12229623/s51862336/4c353cab-2ad1c59a-26926249-f9824952-edfb1a8f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12956624/s53200023/84725fce-b8b12b33-3387963c-a718b9c7-b1945438.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12542450/s56557285/83711845-a20b5408-f42ce5ee-6143f128-a53c140d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14719012/s52923985/712f66bc-99150698-e4e5a055-db0a79e7-f3bd81b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19509694/s56771164/b436401f-0dc8858d-a5dc71d0-f5e8e6d6-8823ead4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12351481/s54216109/795f2ba1-6debf7fd-0132fe8a-03f87042-6a990a80.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15110728/s51964910/f495b16a-34dd8c06-f07c5873-4b5bb66d-24559d35.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12183714/s55747099/82b465f7-737d9b3b-fec25575-e694087a-0422c1f0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19423061/s50829350/641c0bab-e8835ec0-a9953bda-359a9381-a8bc717a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10516278/s54368238/2dcc5505-f3562674-7db63307-4a369c54-2d6755eb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13364025/s55908390/98f45477-59ef2ebe-511ae436-0fbe05a6-4228acbb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12156923/s58831425/114739c9-a41fa109-a64ab4ae-c20bf374-56d0d1cc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18087960/s54756599/8666ecc5-be290923-4d575a3a-8aa66fbe-654782b9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17672026/s57300127/ca03268c-dd289385-ce1587c7-d10ff9ed-bee984d7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18460963/s53533814/5644d159-4aaded69-f82e8dde-dad29a2b-2f64e0fb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19355755/s52282988/cde614aa-ab4942dc-22f28904-4d5de9fa-9ed77549.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17361558/s56090323/5dcfeb2d-9e26c4cf-f8a4aa49-8008670b-8d6ac7e6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10124346/s53643077/82665dde-137dbbcd-ee49e2a2-cdfab695-af6a98c2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10699336/s54651023/8adacfcf-7aff38ae-c0526042-a207711a-41cc7a25.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17986879/s54391818/9a97b9ed-e9afd298-17c61ab0-279b83c1-49ff9c7c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17021161/s59659224/89c90e03-d1a66e47-06f48db5-c7ccaa0c-7ecb97a2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13566753/s55013271/77f2d1af-6256ce87-b89f0174-e96250f7-2c6a31a9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13300396/s53115659/f39099ab-1d72bc38-7f24e99e-89193a2d-36545dca.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13060009/s50912136/addb6b98-41931677-65584588-635eab30-4639b871.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10520955/s58439594/700be4d3-fa456b0a-659a0a37-10c9234b-c93d53cf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19692222/s52231761/abfa154d-85b838e3-3fe3f56c-d3cacdbc-303f9925.jpg

 79%|███████▊  | 3927/5000 [01:04<00:22, 47.53it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14485019/s57869776/28f7945a-999fd79e-6cf30623-b6e9b5ac-85aad13e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14546527/s53139633/6e9e3748-934411fd-d72d3f34-be1e5f6f-22e66869.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18967979/s55851535/22bf96ee-b9a2c775-20b77912-9b2437d1-7878ebd8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14687773/s58537711/c51683a5-c91c4709-feead9fd-015ab10a-c952c548.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19936782/s51320876/f94ab901-e326635a-6949c202-7fd75fe8-88fc0598.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19393028/s54637884/41165b2f-359c0260-2f651196-95c105c0-202480cb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14683400/s54626676/8175d6ee-2ee53d8f-682598b3-12a5b152-6ac95e19.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14781060/s54151502/0b8168e9-cf2cee7c-639f849c-dc88283f-ac091e0f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16274212/s56628883/2fb7f5d0-9d673da1-a8ef3d2f-d615b0a7-33080976.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16280495/s58322676/7597aa7c-8238d320-8cce4c92-73eb78ef-6cbb84ba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17672254/s53275822/f006dc43-e9a05333-9f5c1889-4f810820-c7697dbb.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10213338/s58087992/1ab9bcae-ebb389d3-03735dc5-16f90081-d2335912.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14786549/s51855911/3590f3e2-e6813e3a-9394c313-40afd101-d90bb7d6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13456784/s55505113/4531cbcf-25565efc-bac84ec9-394ef041-fa7bcd2d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10500801/s54115982/88582389-429823fb-85d72678-3a8ec20f-a2bff31c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10257709/s54496232/221518e7-b217bcc9-bc9d1d77-19786d4d-ef0f8a64.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14257710/s56513721/05c679ff-1a1ef005-cf29e635-6db0c074-46946173.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14048680/s57793406/0f03e085-23e7631c-4685fcf0-fa09e190-4884aea1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14187372/s52105305/e4ca5731-27333dee-81779505-527decfc-6b8518cd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19975898/s50219193/b84f8f69-0448c276-9d2ec888-2ba8f15a-d6e4dbaa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18551091/s59329610/352d13d4-e90bde63-d073c191-569e0096-75db02ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18388859/s57649668/a4da3766-542f79ac-814bc0e1-00e7303a-1c5628a5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15263884/s51926882/a84081ab-93320698-005f00fb-0e2e0dab-d19d2e29.jpg

 80%|███████▉  | 3993/5000 [01:05<00:18, 53.88it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14269990/s52857576/c2df1608-df701be9-2eeddd9f-2c8929a4-d1748d8b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16065369/s50084337/e2c00b12-3e9392a5-7f7612ba-63d81789-5b988248.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16201537/s56069280/b5766f0e-cb421f07-75d48ea6-7ab5947e-13d5cca2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16614887/s52969541/a5b583c2-9ba65caf-296bcd1b-4e2d23ce-7616264a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13410910/s54342802/f11219d3-f49e998a-17636cf0-9eed0af9-d6162eb5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11984732/s51762718/a68e33b1-d32848b0-d261a3df-7597a9b1-feb2aba5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12185775/s55494760/e6b4a152-bc73f001-84e7b150-4191779a-754f8459.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19941474/s52121507/f4d706fc-4b8633df-b0cdf406-93896960-9163b244.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17063025/s50991341/bc0edcfc-26caf8de-8b65bea0-b375fc93-fff08e48.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18864300/s52125684/2a31efdd-411d571d-0c620013-68e0e09f-873fa9d4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15592548/s57898581/d6b2792f-831ef3a6-a6b9b5d0-73cb3f20-1d4944f3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14650506/s52372543/95dc2eee-daa875d3-a197251a-7c97aec8-c7079fc8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16515452/s58465969/96610c51-0203b0b4-ada40d70-77c663a6-3ec15190.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15861255/s54887999/d657021b-82f00d76-376fa9b3-00f581a5-1de81f1c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16901713/s58107953/733cf8ca-2513d239-32610436-23b08fec-1ef7f23f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17057667/s58015625/e3986159-52b52155-db150f97-810cd8ed-69566e0c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18164811/s55537092/00950c8f-5137403b-0104480f-2beb3f91-d017993d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11528715/s56381584/dd9a1418-7695da57-f8a49c4f-edc256d8-fb85bbcf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17136424/s53613395/7f31ff87-0b2981af-21e1e7c7-c8a581bf-45af4fda.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10862893/s52946059/db571c1e-3babfd1a-15e30662-f9294fad-01738e8c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13677049/s50702814/e5bf1c52-5d6b651e-4e728f33-19916c62-d982101f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17135687/s57979945/836a98ff-47336fc4-5328e80c-7a0b29b5-f8ef52b6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15371486/s59141200/dcc5e074-381b66eb-11ca3061-a7cb5ac9-22bc33e4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18272067/s58978425/808aac18-cdd7ebbd-84ebeaa7-0ab31947-1d3c811e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13551252/s50318841/2cf1c7f0-555dd3bf-aa52f64d-1cd255c1-33c67987.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12462675/s59701101/7b04abb7-f8f82964-506564f5-66184a13-1a63f382.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18727840/s51996917/2f40e60a-695c23bc-f085e020-d17edfb8-c786276c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15097240/s58069187/a2510da8-ddf6aa2d-6923fb68-c6b1b434-4d29d8ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12138575/s54490096/82fa80e1-cce3798a-19a65ab7-2fb91180-84b23330.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16345504/s50884242/cbf1febd-f916d56b-f8f5c9a5-94e794a9-23e0508e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10973525/s52654636/b9159c42-a78a10ea-750e4d5b-56ca40d3-d3ba611a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10471469/s55539462/3f0b6ef8-54131e0c-75a2c330-685c01ed-f99ee29d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13939871/s50304076/9982af41-6a7afc8b-708c7b9e-18038c30-ba39686f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19243413/s50608653/f213b978-fa25fd12-53d7eed3-bbee193b-50663f4b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19066013/s53343662/7a3cc141-0b7d3a2b-48365a3c-52562c7a-93e2a8b3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10417530/s51045819/76743a57-1ad5118c-6be0a25f-6ad0d6e8-5b229984.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10944871/s52867995/b00d313d-cc27c194-1cce5712-a76fcb69-f8400be2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12780512/s51955339/7af52651-f875504f-dfe795e5-7f14c8c3-4a42f838.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12846283/s59467455/002962f9-b1f76192-37d45787-648ea0a6-5ec41e51.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15208561/s55596922/6538c435-28c4586f-c990dc86-95683e02-4b702d1d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17310670/s58497107/64e39f72-089f8d71-1419d832-76fdead0-94aab10a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12940177/s50910917/4c765078-f9909c94-d2498a48-d24ba746-05461622.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18872738/s55844107/85ab73d0-738a14e1-0aaf19b0-557cfd27-529bb3f5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17066959/s54489219/c7375f4b-8018c441-0cbc968f-f5625cd4-ca6b7d59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17854225/s59643989/c1862f65-dc9b5c9d-559e8b2f-4a4e424f-8478be2d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14415891/s55331790/b640b305-53233708-f12f4fdc-9e106d08-8ece5ecf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16350202/s55208515/d8ef74f3-07f995a4-f081e6cb-8addc9ae-60dfbc3c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16654740/s56559447/b1ae3ada-5f6f15ee-3a308c14-e71b95fd-c4b951f1.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16421543/s57308770/1e08bfd3-cec4118b-cb5161e9-31b9633d-00255420.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10702845/s54218400/e4898397-7d3559d0-49224c53-2c012cea-8bf15b91.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16257239/s58462596/272a04b0-a247e672-0af561fc-f19cd8a0-be39293f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10297948/s59571296/017972f9-be272b06-fdbb8041-d665a18e-e8edaa59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19509694/s55675964/47b90446-f1d4b738-66a23320-2867ee84-1be350bf.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11249665/s58773858/002a5b2d-f7ca0d7c-dda0c584-cbe528c4-002116af.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11775739/s57934737/d15df7a7-401e41ca-3c5c36b0-c8409f73-4d1ba552.jpg

 81%|████████  | 4057/5000 [01:06<00:18, 52.08it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10025268/s53208209/38527df3-730f55bc-dac829f3-e69d164c-3764de59.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13063188/s51082426/d0d63812-c29dc7ce-b2799a82-34a8e4c1-8bc94d9c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19015466/s53634494/a7603c80-8b261d6a-e8832982-76ec62c7-17f9fefd.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19217661/s54453123/d16b8a50-95277aa0-0f31f502-0a9e69f1-dd28cc19.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11154338/s51808709/918b6499-d6124530-b8064430-5f4aa028-1999f1e1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15682814/s54459256/e2c6e7f1-12475644-53f5cc71-50a49380-46449ad4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11877234/s52332731/25dea37e-75f47159-17f45e94-79a1d0e8-d89eb669.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11904362/s54421109/4924e888-4a2fcd44-5eb72617-86e988bc-18689aa5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11090206/s55166644/aa933266-743e66f4-8b3fbfd3-e325bad4-1493b54c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11114467/s50471641/d8e832d0-14900c84-8787d216-55993874-12f8ebd3.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11719852/s52642281/d255c119-fca8f3da-deb45c3d-9726abaf-d7ab9a9b.jpg


Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15772294/s58196108/a01aa46a-f5e04fc1-43f66a32-e8e73416-ab653d31.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11083509/s58547926/1fbaf8b3-a1dab8d7-8df6037c-1d2bf229-5c6a7498.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11982468/s55197844/a69b62ed-dfbcf0de-d944a2fe-361d5d3e-0392fef8.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11012243/s52028226/43b4f186-2e23e965-589805b5-c68f5891-447a1c3b.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10807985/s53584113/17a91470-5403d842-da742755-ef03491f-45f96d0e.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15705944/s56333616/39355e13-15d6f368-361f46ea-f5f3d21b-ac8c8226.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17798319/s54769793/a577220f-3a12d60b-d860893a-a437cc77-a161f3d2.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13423238/s55907448/195bfdb9-0b8befd6-b5d02dbd-6107efef-b84f8250.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14702876/s52563753/f44d1903-d1a4d2e3-8d7200ea-8fdf280e-4539ea87.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12388314/s53532701/e048375c-b032197e-12a4a16c-23963ae8-f16c794f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12006266/s59572801/8b7828dc-0c0025f0-7cb7c6b5-29b93e55-51e69741.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16500918/s51681444/413374c3-b328cfa4-fce3e31e-dd0c0f48-62cc84e2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16582727/s54390330/410819b2-858e3f44-baa83bd4-76d03f77-b1a6a49a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14921607/s57553307/6caecf6e-f03200a8-90d1dd74-d6960650-a2a3c37b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12972442/s55266799/0b71deb7-9f25bd6c-eb201740-fea5ff40-56907b14.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19149321/s52734968/925a62f2-70cc64fc-8cf29371-11412353-0f2ba553.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19338519/s50996974/65127f54-258a8941-d7eaa8c2-b7dc2f27-d856a6ce.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18835690/s51158704/9dc29840-09c85e54-a513a8b2-ad9d49c1-dd09500f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19860398/s55899782/e8df109f-ae4069f3-bbfca9b3-79bd07e9-f9510b14.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10659847/s57446766/6c53da06-214efd20-67f3d3f1-30a6e319-2c7ebae9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18152346/s52928825/5f67c911-c37e43d6-fe323fce-5d5ed580-d293cde4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15315888/s55391107/c4ed898c-5659dbc1-f9d52564-f8b1348d-9f9944aa.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17854152/s56360444/f6d65265-b21540ac-5893c1b4-a67ee035-1cfad6c2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16285590/s59121742/373a22f4-d891c4d4-faf8ce49-5cab32b1-5cb63428.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11968004/s59266094/a505c701-926d962b-2d6edc94-c7c58c5d-81783b4c.jpg

 82%|████████▏ | 4120/5000 [01:07<00:14, 61.12it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12816947/s52247690/543163a0-2c13f364-7362157b-12a98528-87884993.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12607853/s54860074/1772bfde-fe7f3463-d49be608-7d228363-cefc6c62.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12402539/s51717744/446d556b-acbf5183-4494ea1a-02801150-f94df04c.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12262277/s58367649/57befec6-3306da75-10ab27ce-d1a10281-887fce6c.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12219390/s50945724/f7b3c1f0-4788f5e2-ec3b1f2d-8eda336b-ba78e17a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11434374/s58448985/1ecb3bec-7f5e988f-66a8082b-43f05053-3d932aa8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12726753/s59995819/39367887-e28bee50-2a61e3e7-68ffca46-a3bde68c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18283050/s59585183/1783ebcd-0d6963aa-94aa7692-5edd0e91-e6aa0c57.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18148760/s50776093/404e1d68-2619531b-8a093899-7a72b804-ee681df8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18019825/s58940094/169dca39-8ae3c34f-e4afd99b-84063ac2-bb6ccb4f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14143731/s50295203/b5c0ac22-2162656c-effae2d3-d66416f0-d0a99da5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18461091/s58823651/3f3ed91d-60c7478d-e1a2a304-653f62ce-f2092730.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18377113/s55750927/504351b8-c686dbe0-7d9b183c-2b1a3fed-ea4adca1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18237734/s50567546/278792b7-2d61e267-8ecc6a59-a35f641f-7d6f13e3.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10020740/s59801677/84e2e8bf-5eef3074-26b068b0-58a6a947-8f033942.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15969841/s53008884/8467b733-97cf4cff-75b803b5-fbb7d5e8-ef4fc1b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15040313/s56172288/db761e5b-33f4e2f3-cd9e3b48-4f998a68-182c07ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15693812/s59212259/38b8e072-fa82c566-16dda428-93567d1a-cd86a596.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15564338/s55344259/f4429fcb-6fe08b38-f880057b-6f912d58-17385d28.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15835407/s53514856/2bc33562-fb294d27-2915587c-32ffbef4-baa9da48.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18416473/s52857526/0f59d68a-e931d42b-44cc6a1b-8b327661-efdceeb6.jpg

 83%|████████▎ | 4130/5000 [01:07<00:15, 57.23it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18512919/s53880358/78347b7d-8da93004-6f703ef9-5b78c39d-5c71a3c9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15075859/s50364864/0b388376-2270d94a-f49ba781-472f23bb-8c26e68d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19062760/s54660027/23907368-77c864e3-bb81f09d-aa90cc2a-a2f33370.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12820433/s58179523/ca41dd37-0d79b2a4-00909ee0-bf3c9fb1-9d182531.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12527778/s54233408/bc6af37e-5d3d94e6-a780df5a-bbd29bef-81c7d674.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10370700/s59531323/578fd402-94c7b360-7b085795-e395b394-d6ed74d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19966789/s56470911/38a5488d-75ca0559-080a1554-685a4c5e-1a551559.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15656571/s50771071/1e1eef93-e47c0a34-088d70e1-ff6029c3-3030b706.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10913472/s58842155/c09fd2f1-a8ce97fb-b75abd22-1ca73aff-93e35927.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18605997/s59622453/7394ca3e-a22fca20-c6f044fd-6fc5b227-1ccdb4d2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12773304/s58754524/6ef02774-cf122237-ab9dde61-4f8f709e-a0a64ac1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17689164/s58756972/811e42f7-7e055d7a-7032cb55-b165f8af-14988331.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14464018/s58350649/4b8871a2-fa8f1e2e-8f5ceea8-6bae5582-08cf54f1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10679652/s51102245/afbe55db-d092144f-5525e068-6359e74d-06f069b1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19431075/s59114744/9fcb75dd-5d039dc4-83cb6de7-0ebcdc22-1af9fcef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14858512/s58482167/b9ba6d6f-913a7639-86ddda2c-0330261c-1c6308a5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18746141/s53192075/748a0fb2-5b51b3e2-85bf78fc-778fc8c8-cd02dc4d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15710368/s51552644/702772f7-b4a6ac29-575993d2-ca020499-2b244687.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19607507/s59047269/1b39e5f8-c3314e87-08550a7e-88128c0a-d570c7e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15289580/s54178269/41253919-b5e5edf5-4314f4c3-f195dc93-a52b436f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11985034/s59466475/678ec5ac-eb344e03-faea226e-aa0a8cb8-29456544.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10332328/s58967133/dc6cb814-197f1a88-4d667eb8-41b0c223-f54c26ba.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17258978/s50594024/895f58f1-09f8a43b-001b27f8-e6dce87b-469473ee.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16796985/s58312499/fe6f3711-cae97abd-e1660e62-07e78953-a4baae99.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13848029/s52291632/fe6aef84-0d24bfc6-22975922-6f00b99d-5cc0951a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15783916/s55984479/4cba05e4-cc1cfde2-eb1c881f-d91361a9-721ae4da.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18673777/s51972361/a9f7b25c-125104db-c9317b3a-a22c87df-6430d64d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16524406/s54985612/cae34b8f-cef454bf-250bd88e-8bef265d-9a3f0172.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16428261/s53929960/589025cf-b3357e84-28cfdc63-acc2a095-c474e420.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15423372/s56706053/c86e24d7-26cc65fe-c4168f47-1e256907-c398cb24.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10677030/s53467096/172f1ae4-7f791ed0-26c6ba90-49aa9fef-c75c69e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16521649/s55896207/864d3896-dffaddbd-4b7c1510-79148eaf-eb945ec5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17486231/s58950429/3fbfe141-ff1a5eff-8d13cd67-d7213f2a-c633de22.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11395953/s57951975/03431fc4-e2c798de-c91fb309-d8a6737f-0a79bf1d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12405648/s54272101/630dbd71-92aa4ce7-9c422272-c61e4e19-daae8e01.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15290047/s54197950/fb3de891-dbfee15b-d85af6ad-5466b03c-56825cef.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15353133/s52954543/19e48f0a-a1932cb0-2c8bf746-b92c5eab-223ac1b7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12392480/s56376068/226d8b11-dfc31358-a2030e8f-5cec057f-2b2cc03d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16924675/s59380966/c259f6ab-5c38bd06-165d8fbf-ccce1bc4-f10a3934.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12877392/s59836592/3a6bec1b-a064369c-09aa6d7f-feac20c7-12c5fbbc.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13080738/s58894071/c9dc69ec-63c87684-a1436491-3dcfd7b6-cd658430.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13764666/s53083884/010e3350-dce5d947-e690512b-017d29b3-7eafce55.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13860103/s55438633/27810332-e9c0b0ad-9740d36c-c64faac9-032bd7e9.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10832658/s57715842/0d1dd737-f46510d5-c86ce38b-5c495500-2cdd24ea.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15075859/s56710241/62662474-86febc98-057c626e-286f61b4-bbd71cb1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17396346/s50633907/b0f9a796-1343bfa3-f91e6fef-a6104b58-cc565f0c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10452634/s54872393/d12fa1a5-3421bb57-e1cec1aa-a0b6b64a-64f81869.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19753029/s53759658/1e11bb44-6425a4cb-76dc2a16-217e2eb9-25d6af26.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12591656/s59734480/f543c42c-643c0f2b-5fc05ecf-4141cb03-59dced5f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19926992/s53302487/c9b79543-1c3c959b-1984d4e3-ddf3ea05-26a37c8c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16454913/s59345024/273d3805-5cd905c5-45bbcb50-d0769a4d-55f7fbec.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19174716/s54183879/f1693972-e5b8083f-b4e0d082-e523c499-24bea95b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12385857/s55876031/46318065-890f539c-0ecc7789-4e963be1-a2678b3f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15613151/s52035444/9da6c307-f1844edb-3e679b65-d8d73e06-da1ad717.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11614040/s52577959/3171e900-87eb21d0-8d960bcd-ae644198-073b1869.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17172702/s55452109/1b44e56b-c8688961-5ec155a8-17c0fab4-c79746f0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10318991/s56751359/bb7657a9-d79270b8-df199d95-7da0ab0e-c0a0b781.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14892655/s53861721/ef264c8f-07c02d8a-f14b4875-f65e2783-8b8bd349.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14795403/s58429665/0ebc12fa-ef82d832-1b5a546e-87c8b484-fdc9624b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19759491/s52929450/c5ba12eb-19b106cb-51fb3665-486c18e6-65a1a778.jpg

 84%|████████▎ | 4178/5000 [01:08<00:17, 46.26it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15452636/s52187725/ccd3c424-dd412a6c-654dc449-bc1aa2c0-43dd4d8c.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12930373/s54118629/687cd530-bce682bb-13494f15-59e7013b-cd7ab637.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14787496/s54366074/0f735fad-e5bd3454-a41bcaa0-bcdf5333-ac43b3c6.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15680945/s56006903/6e3df856-f1647684-cb4f3fe5-7cfeac5c-6f02f096.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12734486/s53804893/d5b0e546-0eacaa58-a6b39f23-547fb62c-f56a04d2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11098660/s56488390/5fd4cd7d-104d8fca-85247b79-f6698b42-9364fcd8.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13718304/s51979359/305cc658-f479b15f-8c17deb3-f94d16a2-2c014a85.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13037718/s52681176/2e0fd575-7a387e11-b264be46-c87e24a2-3d0570ef.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16665687/s56963009/459b3d8b-85538300-d25c3a5f-dc58ff4c-d96c2c08.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18687658/s50512554/7884fde9-eb9f3872-675b449d-8a81ae13-0e706e5d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13880645/s59739656/a7d91f91-0e5cb8e4-860b17a7-b67e089b-bdf4d228.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13736592/s53112042/862760d1-98b67926-8ddebfc9-d1542939-09c4408b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19855614/s59450003/66fc7fbe-dc8a0d49-aee3b9f4-91f411b2-f928533f.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14719865/s56034888/931028c3-c6d7c718-13077a2c-a04da85d-ee1554f6.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14403931/s59965674/8ec99d08-eb7068b4-dcb247e7-acb672ad-956f81be.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18693928/s54930398/07815841-1e396f89-130005cc-e5c64b19-e707ad3b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12137189/s53081233/3c8176f4-9cf95ad4-1fff2f5f-7109ad52-250caa1d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15485853/s59390977/8e116638-75080b94-5c3f4796-98b6cc3b-5637b9b4.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12279690/s50518877/b40422bd-706eac26-c21523db-6a3782fb-3d79f378.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11648387/s50060923/6e20207f-ef8df3be-04b7045c-18df871a-8b32d23f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17005364/s58600466/9e2d2f52-72c2fd55-64f4251f-278f15ce-ade79f57.jpg

 84%|████████▎ | 4186/5000 [01:09<00:19, 41.89it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19551627/s57376280/ca23708f-93914854-48087f02-b16daba9-a38b3ab5.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14388229/s52986480/1fce1360-e4f9da20-c614a7e8-97a4e8be-7d3b0f52.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14932641/s58374241/756eeb35-52f7eeb9-5b3ad870-2640423c-9627cb9a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10866763/s54986088/6c86603e-6c3d914b-f2478abf-302e52ef-03f25272.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17211008/s55849772/c241ec25-b8d4031e-274a8be3-b54efb12-fd2d1952.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19355229/s59100397/ad941242-b106fd69-f610109c-72af5fb8-c015c07b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16337794/s59232265/27e3a683-70ce9cdd-ad491361-cbde6ac9-d3c940a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p18/p18946719/s57247538/48311191-a41c9b84-82b37bbb-f31b7029-31895fe2.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17106724/s51707326/2a49793e-ece45a5c-60cba54c-7d1c44a3-ad7d491b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p14/p14304572/s54323122/b5a8b3cf-7857dc71-fca8ef50-f3eb8147-95d2e6d7.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13364829/s59342951/86ea9a5e-7f310285-195188f7-1ad76f2b-ddfa77a0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19654136/s56405857/28ad2798-a62c5c05-6825a375-c4e4f4fd-3fcd2832.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10508110/s55204609/e610c91d-863bb765-d6c655c2-2e759879-1c4c0c9d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17991372/s55395628/92f48ff1-ed18577c-7f94a394-bf242023-de50103f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17420936/s55091468/a23efea4-c6d8275a-82fe4266-4772c76c-4c66769e.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19721801/s55667262/f1b866fd-315d166e-ac36d086-c1cfb276-ee0e74b0.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12712344/s53383088/641be66c-7450c33e-5729fa55-0a3ccd0d-b128986d.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12581135/s53409176/ce702416-c597d57a-c47d87e6-676110aa-2717c26f.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p12/p12223080/s55981248/170646e9-b3203ee0-1912c284-8739fa0d-19acc199.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p19/p19385219/s51600986/db3afeaf-fb81e0ae-4042ba32-2f8c2ccb-c5331f66.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p16/p16876651/s58891331/a2c2148e-3303c48e-c7737d2d-c6344a3a-dfaf35dd.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17982428/s58848455/fa3f1ca5-ad6baba8-14c9a0dc-2eade31d-e22fd125.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17256511/s57327923/20b80b45-c552f1cf-eb2891ac-ac07dc11-0ebf0a68.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p17/p17375769/s54245350/a8612343-715e13b3-cba4fee2-30460f73-62a35cb5.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11234535/s56611705/f3f84cbe-49d7d20b-c72dddb0-d33c8f2d-ae8ffe5b.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13259676/s56115130/0651fe0a-ccbd8671-3af020f1-fe1b6a56-aeb8c4d1.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13543584/s55967440/b2c6d142-32dd7eb7-81de67e5-90083147-36d92700.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p13/p13279221/s53768646/87b7f242-4501df8a-18c6debb-689676b3-ee5f0e1a.jpg
Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p10/p10389768/s58394773/3e697905-5d17f979-4be2144f-dfe804d1-1e293666.jpg

 85%|████████▌ | 4257/5000 [01:10<00:16, 45.44it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11255297/s54279796/e3677c59-dc643b18-cb817365-f9577f2a-9d071519.jpgWarning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11017127/s59432181/75fff237-2e747701-736d7a94-b2a850e0-00d516f8.jpg

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p11/p11829192/s53054204/4ba789fe-76e7c3ec-be81b919-eba4abfe-40044bfd.jpg

 88%|████████▊ | 4404/5000 [01:11<00:06, 88.37it/s]

Warning: 新文件已存在并将被替换: /mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/files_256/p15/p15723530/s55067036/1b427421-22ff0f6b-b1f43dea-10306644-789cc74d.jpg

100%|██████████| 5000/5000 [01:17<00:00, 64.49it/s]

任务完成，所有图像已保存到新的路径！

In [7]:
import pandas as pd

# 读取 CSV 文件和 full.parquet 文件

for subset in ["1000", "5000", "10000", "20000"]:
    train_csv = f'/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold_data/fold0/fold0_train_subset_{subset}.csv'
    full_parquet = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/full.parquet'

    # 读取数据
    train_df = pd.read_csv(train_csv)
    full_df = pd.read_parquet(full_parquet)

    # 在 full.parquet 中查找与 train 数据中 path 对应的记录
    train_paths = train_df['path'].unique().tolist()
    print(f"在 train 数据中找到 {len(train_paths)} 个唯一的路径。")
    train_subset = full_df[full_df['img_original_path'].isin(train_paths)]

    print(f"找到 {len(train_subset)} 条记录与 train 数据中的路径匹配。")

    # 更新数据，替换 seed 和 parquet_path
    train_subset['data_source'] = 'cxr_crop'
    train_subset['parquet_path'] = 'data/cxr_all/full.parquet'
    train_subset['prompt'] = train_subset.apply(lambda row: [{"content": "", "role": "user"}], axis=1)
    train_subset['extra_info'] = train_subset.apply(lambda row: {
        "env_config": {"parquet_path": "data/cxr_all/full.parquet"},
        "env_name": "cxr_crop",
        "seed": row['seed'],  # 使用 full.parquet 中的 seed
        "split": "train"
    }, axis=1)

    # 创建最终需要的列格式
    final_df = train_subset[[
        'data_source', 'prompt', 'extra_info'
    ]]

    # 保存为新的 parquet 文件
    output_parquet = f'/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold_data/fold0/fold0_train_subset_{subset}_parquet.parquet'
    final_df.to_parquet(output_parquet, index=False)

    print("任务完成，train 数据已成功保存为新的 parquet 文件！")

在 train 数据中找到 1000 个唯一的路径。
找到 1786 条记录与 train 数据中的路径匹配。
任务完成，train 数据已成功保存为新的 parquet 文件！

/tmp/ipykernel_2216780/3851056925.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['data_source'] = 'cxr_crop'
/tmp/ipykernel_2216780/3851056925.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['parquet_path'] = 'data/cxr_all/full.parquet'
/tmp/ipykernel_2216780/3851056925.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['prompt'] = train_subset.apply(lambda row: [{"content": "", "role": "user"}], axis=1)
/tmp/ipykernel_2216780/3851056925.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['extra_info'] = train_subset.apply(lambda row: {

在 train 数据中找到 5000 个唯一的路径。
找到 9065 条记录与 train 数据中的路径匹配。
任务完成，train 数据已成功保存为新的 parquet 文件！

/tmp/ipykernel_2216780/3851056925.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['data_source'] = 'cxr_crop'
/tmp/ipykernel_2216780/3851056925.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['parquet_path'] = 'data/cxr_all/full.parquet'
/tmp/ipykernel_2216780/3851056925.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['prompt'] = train_subset.apply(lambda row: [{"content": "", "role": "user"}], axis=1)
/tmp/ipykernel_2216780/3851056925.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['extra_info'] = train_subset.apply(lambda row: {

在 train 数据中找到 10000 个唯一的路径。
找到 17777 条记录与 train 数据中的路径匹配。

/tmp/ipykernel_2216780/3851056925.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['data_source'] = 'cxr_crop'
/tmp/ipykernel_2216780/3851056925.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['parquet_path'] = 'data/cxr_all/full.parquet'
/tmp/ipykernel_2216780/3851056925.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['prompt'] = train_subset.apply(lambda row: [{"content": "", "role": "user"}], axis=1)
/tmp/ipykernel_2216780/3851056925.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['extra_info'] = train_subset.apply(lambda row: {

任务完成，train 数据已成功保存为新的 parquet 文件！
在 train 数据中找到 20000 个唯一的路径。
找到 35243 条记录与 train 数据中的路径匹配。

/tmp/ipykernel_2216780/3851056925.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['data_source'] = 'cxr_crop'
/tmp/ipykernel_2216780/3851056925.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['parquet_path'] = 'data/cxr_all/full.parquet'
/tmp/ipykernel_2216780/3851056925.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['prompt'] = train_subset.apply(lambda row: [{"content": "", "role": "user"}], axis=1)

任务完成，train 数据已成功保存为新的 parquet 文件！

/tmp/ipykernel_2216780/3851056925.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_subset['extra_info'] = train_subset.apply(lambda row: {

In [2]:
# import pandas as pd

# # 读取 CSV 文件和 full.parquet 文件
# train_csv = '/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold_data/fold0/fold0_train_subset_10000.csv'
# full_parquet = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/full_v2.parquet'

# # 读取数据
# train_df = pd.read_csv(train_csv)
# full_df = pd.read_parquet(full_parquet)

# # 获取 train 数据中所有的路径
# train_paths = train_df['path'].tolist()

# # 创建一个空列表来存储结果
# missing_records = []

# # 检查每个路径是否在 full_df 中存在
# for path in train_paths:
#     if path in full_df['img_original_path'].values:
#         missing_records.append({'path': path, 'found': 'Yes'})
#     else:
#         missing_records.append({'path': path, 'found': 'No'})

# # 将结果转换为 DataFrame
# missing_df = pd.DataFrame(missing_records)

# # 保存到一个新的 CSV 文件，以便查看
# missing_df.to_csv('/home/aiscuser/verl_new/cxr_data_process/mimic_cxr_jpg_data/fold_data/fold0/missing_paths.csv', index=False)

# # 打印前五条记录
# print(missing_df.head())

KeyboardInterrupt:

In [8]:
import os
import pandas as pd

# ===== 输入/输出路径配置 =====
ms_csv = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/MS_CXR_combined.csv'
full_parquet = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/full.parquet'
# MS_CXR_combined.csv 的 path 前要加的前缀（注意，这里不重复加 'files'；CSV 里的 path 已以 files/... 开头）
PREFIX = '/mnt/input/mimic_cxr_jpg/ori_dataset/mimic-cxr-jpg-2.1.0/mimic-cxr-jpg-2.1.0.physionet.org/'
# 产出 parquet 路径
out_parquet = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/ms_cxr_all.parquet'
# 未匹配路径导出
out_unmatched_csv = '/home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/ms_cxr_all_unmatched.csv'
# ===== 目标 extra_info 配置 =====
TARGET_PARQUET_PATH = 'data/cxr_all/full.parquet'
SPLIT = 'test'
# =================================

# 1) 读取 MS_CXR，并按 path 去重 -> 构造完整 img_original_path
ms_df = pd.read_csv(ms_csv, dtype=str)
ms_df['path'] = ms_df['path'].astype(str)
uniq_paths = ms_df['path'].dropna().drop_duplicates().reset_index(drop=True)
uniq_full_paths = PREFIX.rstrip('/') + '/' + uniq_paths.str.lstrip('/')
uniq_full_paths.name = 'img_original_path'  # 命名一下列

print(f'Unique paths from MS_CXR: {len(uniq_full_paths)}')

# 2) 读取 full.parquet，并构建：img_original_path -> seeds[]
full_df = pd.read_parquet(full_parquet)
# 防御：只取需要的两列，且去重
full_min = full_df[['img_original_path', 'seed']].dropna().drop_duplicates()
# 生成 mapping：路径 -> 多个 seed（去重）
seed_map = (full_min.groupby('img_original_path')['seed']
            .apply(lambda s: sorted(set(int(x) for x in s)))
            .to_dict())

# 3) 为每个唯一路径生成多条记录（每个 seed 一条）
records = []
unmatched = []

for p in uniq_full_paths:
    seeds = seed_map.get(p)
    if not seeds:
        unmatched.append(p)
        continue
    for sd in seeds:
        records.append({
            'data_source': 'cxr_crop',
            'prompt': [{"content": "", "role": "user"}],
            'extra_info': {
                'env_config': {'parquet_path': TARGET_PARQUET_PATH},
                'env_name': 'cxr_crop',
                'seed': int(sd),
                'split': SPLIT
            }
        })

# 4) 写出结果
out_df = pd.DataFrame.from_records(records)
out_df.to_parquet(out_parquet, index=False)
print(f'Wrote parquet: {out_parquet}  | rows: {len(out_df)}')

# 5) 导出未匹配路径，便于排查
if unmatched:
    pd.DataFrame({'img_original_path': unmatched}).to_csv(out_unmatched_csv, index=False)
    print(f'Unmatched paths: {len(unmatched)} -> {out_unmatched_csv}')
else:
    print('All unique paths matched seeds in full.parquet.')

Unique paths from MS_CXR: 1047

Wrote parquet: /home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/ms_cxr_all.parquet  | rows: 2645
Unmatched paths: 59 -> /home/aiscuser/verl_new/cxr_data_process/ms_cxr_data/ms_cxr_all_unmatched.csv